### ISSUE TITLE
ornate stones recipe gives 1 ornate stone for 8 normal ones

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1000]
see recipe:
![ornate8to1](https://cloud.githubusercontent.com/assets/7753414/20108800/984892b2-a5dd-11e6-8e10-923956edec5e.png)

it's the same for all ornate stone recipes added by railcraft

rc 10.0.0.0
forge x2122
mc 1.10.2

**Comment by liach** [comment]
You want 8?

**Comment by MalkContent** [comment]
yea. the other stone transformations are all 1 for 1. i'm not insisting though, but i asked in chat if this was meant this way and got told to make a ticket.

**Comment by CovertJaguar** [comment]
Hmm... not sure why its wrong actually.
