### ISSUE TITLE
Dumping Track dumps mobs into the ground

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1004]
And then they suffocate.
 rc 10.0.0.0
forge x2122

**Comment by liach** [comment]
A proper fix would be only enabling this track kit on abandoned tracks.

**Comment by MalkContent** [comment]
And when they are over air, yea.

**Comment by CovertJaguar** [comment]
Hmm... well it turns any track into suspendable track. You just need to remove the blocks under it.

But yes, maybe the dumping logic needs some tweaking.

**Comment by MalkContent** [comment]
on a side note: you can also throw mobs into the wall with the help of disembarking tracks

**Comment by liach** [comment]
@CovertJaguar Can you define a desired behavior in this case?

**Comment by CovertJaguar** [comment]
If there is a block under the track, don't dump the mob.
