### ISSUE TITLE
Game Crashes When Viewing Item Detector In Creative Tab

### ISSUE THREAD

**Issue by MariaTheDinkus** [Railcraft/Railcraft#1005]
First off, before giving the crash report I want to let you know, this crash only occurs with Optifine.

The crash report is found at http://puu.sh/scUdj/206cb72010.txt

Looking at the report it's a divide by zero error, and it only seems to occur whenever I put the Item Detector in view on the Transportation creative tab. It may occur with the other detectors as well, but whenever I scroll down, the report always always says the Item Detector and none of the other detectors.

Hope you're able to find the cause :P

- Zundrel

**Comment by liach** [comment]
Waiting for the fix on TextureAtlasSheet first. See #924

**Comment by liach** [comment]
@Zundrel Can it be reproduced with latest Optifine?

**Comment by MariaTheDinkus** [comment]
I can confirm, as of Optifine 1.10.2_HD_U_D4, that Railcraft **no longer** crashes with Optifine when scrolling down to the detectors.
