### ISSUE TITLE
Metal.COPPER missing definition in BlockOre.java

### ISSUE THREAD

**Issue by SirChamomile** [Railcraft/Railcraft#1006]
Railcraft Copper Ore won't Smelt. It just won't. You can't even place it into an IC2 electric furnace. In the vanilla furnace it just sits there. I'm on the newest version of Railcraft. I haven't changed any of the configs. As a way to provide information as to my setup and mod list, I'm attaching an unrelated recent crash report. 

[crash-2016-11-08_22.35.46-client.txt](https://github.com/CovertJaguar/Railcraft/files/582215/crash-2016-11-08_22.35.46-client.txt)

EDIT: Removed all mods except for Railcraft, still does not smelt in the furnace. The Smeltery from Tinker's Construct will handle it as well as the Macerator, Crusher, etc. however.

**Comment by SirChamomile** [comment]
I don't know anything about Java or coding, but there isn't any recipe listed for Copper in the BlockOre.java. I believe it should be listed somewhere shortly after line 60 but it isn't:

```
@Override
public void defineRecipes() {
    registerOreRecipe(Metal.IRON);
    registerOreRecipe(Metal.TIN);
    registerOreRecipe(Metal.LEAD);
    registerOreRecipe(Metal.SILVER);

    registerPoorOreRecipe(Metal.COPPER);
    registerPoorOreRecipe(Metal.GOLD);
    registerPoorOreRecipe(Metal.IRON);
    registerPoorOreRecipe(Metal.TIN);
    registerPoorOreRecipe(Metal.LEAD);
    registerPoorOreRecipe(Metal.SILVER);
}
```

https://github.com/CovertJaguar/Railcraft/blob/325f34d43c70a5ec1cfd5ec526640cbf3d03f4fd/src/main/java/mods/railcraft/common/blocks/ore/BlockOre.java

Can someone confirm this? Perhaps it's a very easy fix. I'd suggest it if I knew anything about how GitHub works, but I don't :\

**Comment by liach** [comment]
@SirChamomile Does other poor ores like poor iron or poor tin burn in furnace? You can try in a creative world and report.

**Comment by liach** [comment]
Yes, a line of `registerOreRecipe(Metal.COPPER);` is needed.

**Comment by SirChamomile** [comment]
Okay that's what I thought. Everything else worked but this. It's the copper ore that I use for world gen on my server so it was very dismaying that it wasn't processing in the furnace.
