### ISSUE TITLE
Remove MinecartRiderAIDisabler as it is a failed attempt.

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1008]
https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/carts/MinecartRiderAIDisabler.java#L27

Such an approach was proved to be ineffective in #316 and may cause a major performance decrease. A better approach is to adjust the drag of carts according to observations from #1003.

**Comment by CovertJaguar** [comment]
Why would it be a performance issue? And what does #1003 have to do with anything?

**Comment by liach** [comment]
Cuz they are both related to drag. Drag should be easily done since all minecarts in vanilla are replaced by Railcraft ones.

**Comment by CovertJaguar** [comment]
How is any of this related to drag?
