### ISSUE TITLE
10.0.0 Release , coke oven bricks and water tank siding not craft-able. 

### ISSUE THREAD

**Issue by schmidtyrulz** [Railcraft/Railcraft#1010]

**Comment by liach** [comment]
That is intended.

**Comment by CovertJaguar** [comment]
Will return in 10.2.0

**Comment by Sellec** [comment]
And when the 10.2.0 would be released?

**Comment by liach** [comment]
Well, CovertJaguar is pretty inactive in the recent month, so it is not sure now.

**Comment by Twisted-Code** [comment]
Good thing immersive engineering is a thing, as it appears I can't get creosote otherwise... that is, unless I'm overlooking something

**Comment by liach** [comment]
@macks2008 Cook coal in furnace.

**Comment by Twisted-Code** [comment]
@liach 
first of all, whatever recipe is supposed to be there is being overridden by Extreme Reactors' graphite bar recipe (and I'm not sure removing the recipe for graphite bars via Crafttweaker would cause the other recipe to come back)
secondly, that sounds more like a recipe to make coal coke, not creosote, though I am just guessing seeing as I can't test it for myself

**Comment by CovertJaguar** [comment]
That is the correct recipe.

**Comment by Generalcamo** [comment]
Coal Coke is intentionally not craftable without the factory module. Smelting Coal for Coal Coke is blatantly overpowered due to how good Coke is.

**Comment by liach** [comment]
See #1235 for extreme reactors recipe conflict.

**Comment by VsUK** [comment]
Anyone know when anchors are put back? Using 13th May 2017 release 1.10.2 for MC 1.10.2 & still no anchors. Makes the whole reason of wanting this mod pointless without anchors!

**Comment by liach** [comment]
Will be in release 10.2.0

**Comment by Philosyang** [comment]
Still can't craft raw firestones with 10.2.0.
![image](https://user-images.githubusercontent.com/24841393/32600962-2d68562a-c57c-11e7-8f5a-e36c7203b215.png)
