### ISSUE TITLE
Optifine cannot be compatible with RailCraft.

### ISSUE THREAD

**Issue by JDiTian** [Railcraft/Railcraft#1011]
![2016-11-12_13 18 21](https://cloud.githubusercontent.com/assets/16774285/20235889/43b30ed4-a8db-11e6-8ce9-d7e718160178.png)
![2016-11-12_13 19 29](https://cloud.githubusercontent.com/assets/16774285/20235888/43b2710e-a8db-11e6-99f7-518bc8761623.png)

Like the picture above, the blocks are orange.
If you use the BetterFPS car will become transparent.

**Comment by CyanideCarrot** [comment]
Optifine is known to break thousands of mods. Go bug the OF developer.

**Comment by KnightMiner** [comment]
Likely #924.
