### ISSUE TITLE
1.10.2 Infinity Lite Creosote Duplication

### ISSUE THREAD

**Issue by ProsperCraft** [Railcraft/Railcraft#1012]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1674

We are having the same issue with FTB Infinity Lite

Player says - "So, if you have a stack of 16 Cresote oil bottles and go into a crafting grid with wood to make treated planks. When you have the full stack of planks the cresote will dupe 5 times in your inventory."

**Comment by CovertJaguar** [comment]
I'm not really sure what the issue is here. It doesn't have a container item or anything. Usage in a recipe should consume it.

**Comment by ProsperCraft** [comment]
FTB Infinity Lite 1.0.1(I see there is a non recommended update, I wonder if it updates railcraft, or the recipe)

Railcraft_1.10.2-10.0.0

P.S are personal anchors implemented in 1.10?

**Comment by liach** [comment]
@ProsperCraft Factory machines are not available yet at this point.

**Comment by liach** [comment]
@prospercraft Can you still replicate this issue?

**Comment by liach** [comment]
@ProsperCraft Does this happen in railcraft 10.1.1?

**Comment by ProsperCraft** [comment]
Sorry we quit hosting this pack.
