### ISSUE TITLE
[1.10.2] Iron Plate recipe conflict

### ISSUE THREAD

**Issue by Biochao** [Railcraft/Railcraft#1013]
Currently the Iron plate recipe conflicts with the vanilla Iron Trapdoor.

![2016-11-14_21 27 29](https://cloud.githubusercontent.com/assets/6515654/20291012/b763c4fe-aab1-11e6-99f1-2c92b0636755.png)
![2016-11-14_21 27 39](https://cloud.githubusercontent.com/assets/6515654/20291013/b768e45c-aab1-11e6-97f0-b821306f7cc6.png)

**Comment by liach** [comment]
Great catch... It was originally supposed to be produced by rolling machines, but they are not available yet.

**Comment by Forecaster** [comment]
I'm not sure how to fix this. It might require turning it into a 3x3 recipe

**Comment by liach** [comment]
@Forecaster This is priority medium.

**Comment by Forecaster** [comment]
If it prevents crafting a component I'd call it high, unless it's not used for anything outside of the factory module

**Comment by tomelfring** [comment]
This conflict currently prevents making the feeder unit and the electric locomotive. Which are, as far as I know, not part of the factory module.

**Comment by CovertJaguar** [comment]
I may just need to make the Rolling Machine a priority.

**Comment by Forecaster** [comment]
This is still an alt-recipe though right? It'll need to not conflict with a vanilla recipe even when the rolling machine is back

**Comment by CovertJaguar** [comment]
Its not so much an alt recipe really. Its more just dumping all the Rolling Machine recipes onto the Workbench wholesale.

**Comment by Forecaster** [comment]
Ah

**Comment by CovertJaguar** [comment]
Closed because Rolling Machine is back.

**Comment by Blargenth** [comment]
This issue wasn't resolved. There is only one rolling machine in Beyond right now, the TechReborn rolling machine. And its recipe does not include the railcraft iron plate

**Comment by Ristellise** [comment]
fixed in dev.. not available in current release...

**Comment by twitchyliquid64** [comment]
Is there any workaround?

**Comment by liach** [comment]
@twitchyliquid64 The rolling machine is back in 10.1.0 and later versions.
