### ISSUE TITLE
Railcraft & Immersive Engineering Creosate Conflict

### ISSUE THREAD

**Issue by Frinckles** [Railcraft/Railcraft#1016]
Creosote Oil from Railcraft & Immersive Engineering are conflicting. 

Railcraft_1.10.2-10.0.0
ImmersiveEngineering-0.10-48

In the Immersive Engineering Coke Oven, creosate is missing it's texture (Pink/black checkered pattern) and it's referencing creosote from "Minecraft Forge." 

This issue was brought up on the Immersive Engineering Github so I wanted to make you folks aware of it too. Has something to do with the fluid registry I'm guessing.  

If you need any more information, let me know.

**Comment by Frinckles** [comment]
Update: I'm testing both mods together & with something else that I think maybe the culprit in order to figure out what's causing it. 

Will post back results soon.

**Comment by Giovanni-NL** [comment]
We are experiencing the same issue on our server.  Railcraft version 10.0.0 and Immersive Engineering version 0.10-48.  It is impossible to create Creosote Bottles or Creosote Buckets from the creosote that the IE Coke Oven produces.  

We found a workaround using Forestry machines.  Use a Forestry Bottler to create Creosote Oil Cans, which can be used to craft IE's Treated Wood Planks, or use a Forestry Carpenter to create Railcraft Wooden Ties.  Pump the creosote directly from the Coke Oven into the Forestry machines.

**Comment by liach** [comment]
Dupe with #934. Moved to BluSunrize/ImmersiveEngineering#1659 as it is an IE bug.
