### ISSUE TITLE
World Anchors gone?

### ISSUE THREAD

**Issue by Kehaan** [Railcraft/Railcraft#1017]
Hello

I may be derping, but using Railcraft_1.10.2-10.0.0 i cant find World Anchors or other chunkloaders in the mod ? :S Have they been removed?

Thanks

- Kehaan

**Comment by Ristellise** [comment]
![screenshot 2016-11-18 20 42 32](https://cloud.githubusercontent.com/assets/7894419/20430501/961c0bd2-adcf-11e6-9bec-d5c423473011.png)
TLDR Added in later.

**Comment by Forecaster** [comment]
What Josh said, they have not been ported yet. They will arrive in time.
