### ISSUE TITLE
Some ideas I came up with:

### ISSUE THREAD

**Issue by brisingraerowing** [Railcraft/Railcraft#1018]
Tracks:

 * Comparator Track - Acts like a comparator next to a detector rail
 * Teleporting Track - Teleports carts to another track with the same frequency.

Carts:

 * Tesla Cart - Like the RF cart, but for Tesla energy
 * Anvil Cart - An anvil in a cart.

That's all I have right now.

**Comment by liach** [comment]
@BrisingrAerowing Teleporting tracks for the same world might not be a good idea, but can be used for cross-dimensional transportation. Tesla cart should be done with another mod at best.

**Comment by Ristellise** [comment]
> Teleporting tracks for the same world might not be a good idea, but can be used for cross-dimensional transportation.
> They should use RC Power too.

**Comment by MalkContent** [comment]
I'd love if trains could just travel into netherportals and continue on a rail there

**Comment by liach** [comment]
@MalkContent Although I have not tested yet, I believe the current mechanics for carts through the nether portal is erroneous.

**Comment by MalkContent** [comment]
did that even work at any point? ^^
not being able to drive through portals was one of my biggest vanilla disappointments

**Comment by abculatter2** [comment]
Sending unmanned, unlinked carts through nether portals has been possible for awhile. It requires some tinkering and figuring things out, but it's quite doable.

It would indeed be neat to send trains and manned carts through them, though. I remember there being a suggestion for a portal tunnel before...

**Comment by liach** [comment]
In fact, only anvil cart is feasible here.

**Comment by liach** [comment]
ok i will open another one for anvil carts
