### ISSUE TITLE
[1.10.2] detector tracks metadata do not persist across chunk unloading/loading

### ISSUE THREAD

**Issue by Skully71** [Railcraft/Railcraft#1019]
When you leave the chunk in which a detector is present and come back to it. The detector has reset to the default state (metadata 0)

**Comment by liach** [comment]
Video or other proof? Needs verification.

**Comment by Forecaster** [comment]
Do you mean it resets to an any-detector?

**Comment by Skully71** [comment]
Before: https://cdn.discordapp.com/attachments/225184360049934336/249873194079617026/unknown.png

TP-ing away and back.

After: https://cdn.discordapp.com/attachments/225184360049934336/251247647321620480/unknown.png

**Comment by Forecaster** [comment]
Oh. That's a detector *track*.

So the directional detector track turns into a regular detector track on chunk reload.

Does this also happen when the world loads?
