### ISSUE TITLE
[1.10.2] World Gen Config Feature Request

### ISSUE THREAD

**Issue by SpartanSamuel** [Railcraft/Railcraft#1025]
I'd like to use the configs to disable redundant ores so that I'm not working with 3x different kinds of copper across my various mods but the only place I see that disables RC ore generation is simply disabling the World module entirely. There's no options to disable specific ores, or even quality of ores (looking at you poor ores), not to mention adjusting the spawn chance, height, or density of clusters.

Are these features currently planned to be added at some point?

**Comment by CovertJaguar** [comment]
Its added, but the config issue is getting in the way.
