### ISSUE TITLE
Blocks not rendering

### ISSUE THREAD

**Issue by coryhiller** [Railcraft/Railcraft#1026]
I am having an issue with certain blocks not rendering on the screen.  They show as blank on the recipes list from the JEI mod.  And when crafted they show as blank spots in the inventory as well.  When placed in the world the appear as generic gray bricks.
This appears to be affecting the railcraft decorative blocks (Bloodstained, Frostbound, Infernal, etc.)
I've included two screenshots for the Bloodstained bricks.
I have checked the Mod Options to make sure all blocks are set to true.  I am currently running the Railcraft_1.10.2-10.0.0 version and can provide a list of other mods I'm running if needed.

Thanks for your help.
![2016-11-27_15 58 36](https://cloud.githubusercontent.com/assets/24213058/20652300/453771fe-b4bc-11e6-95f2-a18d7daf653c.png)
![2016-11-27_15 59 31](https://cloud.githubusercontent.com/assets/24213058/20652301/453a4c30-b4bc-11e6-86a3-a6e32d29a957.png)

**Comment by liach** [comment]
If you have Optifine, please update to versions later than OptiFine 1.10.2 HD U D4.

If you do not or the issue persists, a mod list with versions would help. You can generate one by pressing F3+H in game for 8 seconds to generate a crash report containing all these information.

**Comment by coryhiller** [comment]
Upgrading OptiFine did indeed fix the issue!! Thank you very much!!
