### ISSUE TITLE
[10.0.0] Creosote Oil is not ore dictionaried and the Railroad Tie recipie eats bottles when used.

### ISSUE THREAD

**Issue by DaemosDaen** [Railcraft/Railcraft#1027]
When using Immersive Engineering with Railcraft, the Creosote buckets given by that IE's Coke Oven does not work with Railcraft's Railroad Tie recipe, my workaround ended up being a Forestry Carpenter. I tried bottles, but they got eaten by the recipe (probably due to the currently recipes. in place for Railcraft to get Creosote).

**Comment by liach** [comment]
Does this happen without Immersive Engineering?

**Comment by DaemosDaen** [comment]
There are no other mods that add Creosote that I know of. As for the eating of the bottles, yes, but as Railcraft gives the bottle  (i.e. does not use one to actually make the creosote) with the recipe, that makes sense.

I'm not really worried about the bottle thing as that will probably work it's self out once machines are added back in. it's that the Creosote buckets are not in the "ore dictionary"

Updating the title to include the version I'm working with.

**Comment by CovertJaguar** [comment]
My solution: https://github.com/MinecraftForge/MinecraftForge/pull/3332

**Comment by liach** [comment]
Well, bottle eating is intentional. Although I do not like this feature, this is how Railcraft had been.

**Comment by liach** [comment]
Moving into #1207
