### ISSUE TITLE
Minecraft crashes when scrolling down Railcraft tab in creative inventory

### ISSUE THREAD

**Issue by ghost** [Railcraft/Railcraft#1029]
I'm using Railcraft 10.0.0 and I have been experiencing crashes ever since I installed Railcraft.

The crash report is attached here:
[crash-2016-11-30_22.31.11-client.txt](https://github.com/CovertJaguar/Railcraft/files/622050/crash-2016-11-30_22.31.11-client.txt)

I'm using OptiFine as well, forgot which version it was. I believe it is the latest version as of 30th November. I remember seeing another similar report filed by Zundrel (see #1005) but his has been resolved I think?

EDIT:
I removed OptiFine from my mods folder. Seems like Forge has it by default? But it still crashes.

**Comment by Zundrel** [comment]
Update Optifine to the latest which is D4.

**Comment by Zundrel** [comment]
Assuming you haven't already

**Comment by liach** [comment]
remove coremods first and try.

**Comment by ghost** [comment]
Which coremods?

**Comment by liach** [comment]
CXLibraryCore (cxlibrary 1.10.2.jar)
  EnderCorePlugin (EnderCore 1.10.2.jar)
  MalisisCorePlugin (MalisisCore 1.10.2.jar)
  MalisisSwitchesPlugin (Malisis Switches 1.10.2.jar)

**Comment by Project579** [comment]
It's Optifine one of the settings is not compatible with railcraft (tested only with railcraft and optifine installed, with optifine set on max quality AA x16 etc.).

I will test and see if I find the setting that causes the crash.

Found it Anti-aliasing causes the game to crash.

**Comment by liach** [comment]
@Forecaster Please close this.
