### ISSUE TITLE
link issue 2

### ISSUE THREAD

**Issue by changemenemo** [Railcraft/Railcraft#1031]
new version of railcraft 10.0.1, still link issue with carts after loading, unloading chunk

**Comment by liach** [comment]
Ref #882. You do not need to open a new issue but just comment on the old one. Currently, we do not know what caused the loss of NBT data.

**Comment by Forecaster** [comment]
Another duplicate... please stop doing this

**Comment by liach** [comment]
@boistordu Does you game lag when Minecarts get unlinked?
