### ISSUE TITLE
Crash on next page of recipes in JEI

### ISSUE THREAD

**Issue by Mxater** [Railcraft/Railcraft#1032]
I see the recipes usage for cooper of industrial, on pass to page 2, this crash.

This is using in a server, if use this in SP, dont crash.

Iam use version Railcraft_1.10.2-10.0.1

https://gist.github.com/Mxater/af4693a93fa063f3d3a961c18348f62d

Sorry for my english...

**Comment by Ristellise** [comment]
paging @mezz

**Comment by mezz** [comment]
This looks like a normal rendering issue, it shouldn't be specific to JEI.

**Comment by liach** [comment]
@Mxater Does this happen only with Railcraft on dedicated servers?

**Comment by Mxater** [comment]
@liach, yes, only in dedicated servers.

El 21-12-2016 12:07 a. m., "liach" <notifications@github.com> escribió:

@Mxater <https://github.com/Mxater> Does this happen only with Railcraft on
dedicated servers?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CovertJaguar/Railcraft/issues/1032#issuecomment-268423072>,
or mute the thread

**Comment by CovertJaguar** [comment]
Duplicate of #1063
