### ISSUE TITLE
About half of the blocks are missing a texture

### ISSUE THREAD

**Issue by alexandercool123** [Railcraft/Railcraft#1033]
I'm missing half of the textures in railcraft. There are no coke oven blocks as well as blast furnace blocks. I really need to make coal coke. Did i mention the missing textures to the blocks being black. 
All bricks, cart detectors, cobble variants, strengthened glass and types of stone added by the mod are just black blocks. Am I missing something? 
I'm using version 10.0.1, tried with 10.0.0, didn't work either. Doesn't work on servers, nor singleplayer.

Please help, looking forward to using the coke oven and the whole railcraft mod in the future.

**Comment by AEnterprise** [comment]
do you have optifine installed? if so that's most likely your cause, updating or using another variant could fix it, if not you'll have to wait for railcraft and optifine to addapt to recent forge changes to fix this

**Comment by alexandercool123** [comment]
I deleted optifine, not too much lag, however, there still are no coke oven blocks :/

**Comment by alexandercool123** [comment]
The textures loaded btw, everything has a texture now.

**Comment by AEnterprise** [comment]
yes optifine is just the textures, the rest is normal, not everything is implemented in railcraft atm

**Comment by Forecaster** [comment]
Please search for similar issues before posting.

Update optifine, the problem has been fixed on their end.

No multiblocks have been ported yet amongst other things.
