### ISSUE TITLE
Different accepted MC versions in @Mod and mcmod.info

### ISSUE THREAD

**Issue by NitroxydeX** [Railcraft/Railcraft#1034]
In @Mod Minecraft 1.10.2 and 1.11 are defined to work with Railcraft while mcmod.info only references 1.10.2. 

This causes a wrong MC-Version detection when Railcraft is inside an 1.11 environment. We noticed this during our workspace upgrade to 1.11.

https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/core/Railcraft.java#L64

https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/version/gradle.properties#L2

**Comment by liach** [comment]
That is right. It means to exclude 1.11

**Comment by NitroxydeX** [comment]
@liach But on the other side 1.11 is defined in the @Mod method to work with Railcraft.

**Comment by KnightMiner** [comment]
That is a mathematic domain in which 1.10.2 is included (square bracket) and 1.11 is excluded (round bracket). It's the same as saying 1.10.2 <= version < 1.11.

**Comment by NitroxydeX** [comment]
Ah well because the comma is missing after 1.11. But you just could make the closing ] to only accept 1.10.2.

**Comment by liach** [comment]
@NitroxydeX I now ported Railcraft to 1.11. Feel free to use it #1042 but do not distribute.
