### ISSUE TITLE
[10.0.1]Multiple missing localized names

### ISSUE THREAD

**Issue by The-Fireplace** [Railcraft/Railcraft#1035]
tile.railcraft.manipulator.loader.ic2.name and tile.railcraft.manipulator.unloader.ic2.name need to be localized.
Also, when viewing the tooltip for the Steam Locomotive in JEI, it says Primary Color is railcraft.color.silver
EDIT: Also, in the Cart Detector GUIs, the titles aren't translated.

**Comment by liach** [comment]
1. It should be `tile.railcraft.manipulator.unloader.energy.name` tag.
2. There is no silver color. How did you get that?

**Comment by The-Fireplace** [comment]
liach: just what I saw in JEI. It will be a bit before I can provide full details about Forge version, loaded mods, etc. Finals week is busy.

Note that IC2 is loaded, and these loaders were separate from the RF loader and unloader.

**Comment by The-Fireplace** [comment]
![2016-12-10_16 32 58](https://cloud.githubusercontent.com/assets/5914284/21076647/89fe21ea-bef6-11e6-9f85-c417ec41d7f9.png)
![2016-12-10_16 33 00](https://cloud.githubusercontent.com/assets/5914284/21076645/89fdcc22-bef6-11e6-8918-5b8de3730ba8.png)
![2016-12-10_16 33 10](https://cloud.githubusercontent.com/assets/5914284/21076646/89fe0df4-bef6-11e6-94f7-fbd14013e786.png)
![2016-12-10_21 06 31](https://cloud.githubusercontent.com/assets/5914284/21077808/07a0afac-bf1d-11e6-9239-169c5d7e6cc2.png)

**Comment by Generalcamo** [comment]
@liach Silver = Light Gray in Minecraft

**Comment by liach** [comment]
I know that, and Covert already told me that this is on his todo list

**Comment by CovertJaguar** [comment]
I suspect "Light Blue" is broken as well.
