### ISSUE TITLE
[1.10.2] Move Charge Interfaces into Railcraft-API

### ISSUE THREAD

**Issue by primetoxinz** [Railcraft/Railcraft#1036]
Moving the interfaces required to make blocks capable of using charge to allow addons to add blocks that accept or create new forms of energy.

it would be greatly appreciated if this happened, thanks :)

**Comment by liach** [comment]
😒 The charge system is not in api at all...

**Comment by CovertJaguar** [comment]
The plan was always to do so, once some practical testing of the system of was available.

The lack of any related bug reports is a good sign.

**Comment by liach** [comment]
Fixed by 401a34747260c078b573e740e19e64c6941e54fb

**Comment by CovertJaguar** [comment]
> Fixed by 401a347

Haha.... no. I wish.

I tried to move interfaces for the block API (different from the cart API) and it just broken everything so horribly I couldn't even figure out how to fix it.

And this isn't really complete either, there is no reference implementation for ICartBattery.

**Comment by liach** [comment]
moving it to rc api. btw @CovertJaguar consider setting up the github bot in discord for api and localization repos.

**Comment by CovertJaguar** [comment]
Closed by:
https://github.com/Railcraft/Railcraft-API/commit/d54ca4bcc3ec9402df87e4aba7715b12573990cd
https://github.com/Railcraft/Railcraft-API/commit/0004943c1e76184bfd45615c40f24328054ce035
https://github.com/Railcraft/Railcraft-API/commit/ab32a4b31347313d0bff3301a952c6b8f240fde2
