### ISSUE TITLE
[3rd party?] Entity Render Crash

### ISSUE THREAD

**Issue by Discomanco** [Railcraft/Railcraft#1038]
So first off, I need to say that this is not a problem with Railcraft itself, but it is affected, and we cannot find the root of this problem.

We are on a 1.10.2 server, with a lot of mods, on Forge 12.18.2.2151.
Whenever an entity with an AI (seems to be the only ones affected) such as Railcraft Locomotives, Mekanism Robits and OpenComputers Drones are placed, the client instantly hardcrashes.
We have not tried to try mods one by one, since we have over 150 mods active on the server, and don't have the time for it, due to RL commitments.
The crash occurs for anyone within its render range. Luckily the entities can be killed with some commands, but does require another mod to be on to do so.
This does not happen in SinglePlayer, where everything functions as it should.

Crashlog: http://pastebin.com/Zt2HXkv4

I am writing this for some help, maybe a lead/solution on how to fix this, or where to report this.
I have not been able to find any reports of anyone with the same issue.

**Comment by liach** [comment]
`at net.minecraft.client.renderer.entity.RenderManager.redirect$onRenderEntity$0(RenderManager.java:41)`
My best guess is that conflicts in different versions of mixins caused this, since LiteLoader and Davinci's Vessels both use SpongePowered Mixin. Try to make sure all mods are up to date, and you should post a full log to provide more information.

**Comment by Discomanco** [comment]
Only I use LiteLoader. The rest don't, but still have the crash issues.
The OpenComputers drone seems not to be affected anymore, and I'm trying to fetch an older crashlog from one of our members.
Everything is pretty much up-to-date as it can be, with the exception of maybe 1-2 versions behind (update + possible hotfix(es) to the update) - Server is getting updated about every week with new mod versions

**Comment by liach** [comment]
I want a full log, like one fml-client-latest.log from logs folder instead of crash reports from crash-reports folder.

**Comment by Discomanco** [comment]
I'll get one

**Comment by Discomanco** [comment]
Full log as fresh as it can be
http://pastebin.com/0KCTBNvf
This is just the Latest log - Can't upload the full log on Pastebin, as it's too big.
Instead I have attached it here
[fml-client-latest.zip](https://github.com/CovertJaguar/Railcraft/files/648192/fml-client-latest.zip)

**Comment by liach** [comment]
You should try to remove coremods one by one. Now I guess some coremod transfromed Railcraft code accidentally, because LiteLoader code is all right.

**Comment by Discomanco** [comment]
Update: Managed to get a copy of our server, and find the time to start looking for the cause.
The mod affecting the render (or whatever it does) is [Custom Mob Spawner](https://mods.curse.com/mc-mods/minecraft/229261-custom-mob-spawner), which is a coremod for Mo' Creatures (sorta). We are at the latest (3.10.1) version of it.
Trains are placeable and interactable without Custom Mob Spawner

Edit: The 2 mods alone (or 3 with Mo' Creatures too) does not cause any issues by themselves, but in the modpack as a whole, it works without Custom Mob Spawner

**Comment by liach** [comment]
Then it becomes a complex issue. You need to try all coremods one by one.

**Comment by Discomanco** [comment]
It would appear there are multiple core mods causing this.
I used a base mod set (JEI + Mo' Creatures + Custom Mob Spawner + Railcraft + Journey Map + Mekanism), and then added different batches of mods at a time, just to reduce startup/load times to test it out.
Could not get the crash to occur, so seems there is Custom Mod Spawner + at least 2 more Core Mods.
I may look into pinpointing it, but with more than 4 mods involved, it will be very time consuming.
But for now, our issue is resolved by removing Custom Mob Spawner.

**Comment by liach** [comment]
shrugs

**Comment by CovertJaguar** [comment]
Just a comment, the Locomotives don't interface with the AI code.
