### ISSUE TITLE
Consider un-nerfing CESU cart drag

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1039]
An electric locomotive pulling a CESU cart looks to be 4 times as slow as an electric locomotive pulling a full chest cart. Nobody's gonna be riding a CESU train any time soon. 2 times as slow seems like a more reasonable maximum. Using CESU carts is a way of cheesing out of laying electric rail, but making them slow also makes using them for energy transfer less reasonable.

**Comment by CyanideCarrot** [comment]
Same thing happens with all locomotives and all energy carts. It's not just electric loco with CESU.

**Comment by liach** [comment]
@CovertJaguar The electric locomotive is too mad right now. It is now both slow and electricity-consuming.
On the loop shown here, a batbox cannot even power an electric locomotive to go along the loop once. http://srv1.almuramc.com:8123/?worldname=dakara&mapname=flat&zoom=5&x=4263&y=64&z=2155

**Comment by CovertJaguar** [comment]
This is an intentional balance decision. The alternative is banning battery carts from powering locomotives entirely.

Adding more locomotives negates some of the slowdown.

The Battery carts are intended for moving energy, not powering trains.

**Comment by CyanideCarrot** [comment]
But then why does it affect steam and creative locos?

**Comment by CovertJaguar** [comment]
Consistency. They are intended to be extremely heavy, as batteries generally are.

**Comment by liach** [comment]
@Generalcamo Can you work on this?

**Comment by Generalcamo** [comment]
Rejected
