### ISSUE TITLE
Stairs are immovable by pistons

### ISSUE THREAD

**Issue by unpairedbracket** [Railcraft/Railcraft#104]
All of the decorative stair blocks added by Railcraft refuse to be moved by pistons. This seems odd because all the vanilla stairs, as well as the full-block decorative blocks the stairs come from, can be moved by pistons.

I'm guessing Railcraft's stairs have a a TileEntity, in which case would it be feasible to implement them without it?

**Comment by CovertJaguar** [comment]
This will be resolved when stairs return after the flattening.
