### ISSUE TITLE
Compatibility with TC Rails

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#1040]
Since Railcraft is not going to have slopes and curves anytime soon. May I suggest you guys make Railcraft routing systems compatible with Traincraft tracks? Thanks.

**Comment by liach** [comment]
Doesn't traincraft have a routing system themselves?

**Comment by liach** [comment]
@kylesy20 Any update?

**Comment by liach** [comment]
Merged into #787
