### ISSUE TITLE
Breaking Minecart Hopper bug

### ISSUE THREAD

**Issue by Squaredude** [Railcraft/Railcraft#1041]
Minecraft 1.10.2
Railcraft 10.0.1

Broke a Minecart Hopper and it visibly generated Hopper and Minecart entities (one of each), but the first time I did not get the Hopper back. Both times gave me the Minecart back.

However, the Minecart seems to have gotten a "Name Tag" that says "Minecart with Hopper". It's impossible to push, but it can be used as a regular Minecart (you can ride it).

If I destroy it, it gives a Minecart named "Minecart with Hopper". When I joined it with another Hopper, placing it on a rail gave me "Minecart Hopper".

Desired effect would be getting a "Minecart Hopper" with just one entity that doesn't split, correct?

**Comment by snurre0** [comment]
Having the exact same bug here, same versions.

**Comment by liach** [comment]
Should get closed now @CovertJaguar
