### ISSUE TITLE
[Feature] tunnel bore addected by randomTickSpeed

### ISSUE THREAD

**Issue by xbjfk** [Railcraft/Railcraft#1044]
for example when you type `/gamerule randomTickSpeed 1000000` the tunnel bore will take less time to bore a 3x3 area

EDIT: found tweaks > carts > bore > mine speed in config.

**Comment by Vexatos** [comment]
But the action is not related to random ticks at all...

**Comment by liach** [comment]
@Vexatos Since you are a collaborator, can you work on fixing some bugs and managing issues?
