### ISSUE TITLE
[Suggestion] Factory module alternative via Immersive Engineering integration

### ISSUE THREAD

**Issue by KyeoftheSea** [Railcraft/Railcraft#1045]
I know that Railcraft 1.10.2 is largely unfinished, with whole feature sets missing, such as the factory and steam modules. This suggestion pertains to the factory module specifically because if you look, there is pretty much a 100% content overlap between the ~~increasingly popular~~ **more than twice as popular as IndustrialCraft** Immersive Engineering mod and Railcraft's Factory module, including the coke oven, blast furnace, rock crusher, and even the rolling machine, which has a similar counterpart in the form of the metal press.

My suggestion would be to have Railcraft utilize those existing blocks when IE is present, rather than enabling its own blocks (when they're completed) to serve the same functions. Rails can use the iron/steel rods in place of rebar, or perhaps as a component of rebar, and the plates of IE can be used in place of the Railcraft plates.

While Railcraft should be useable standalone, and the Factory module DOES need to be finished eventually, I think having a mod integration like this would be really nice, and reduce the priority of the factory module some until other things, like the steam module, get updated. 

EDIT: I'm done. So done. Why do people have to be so closed-minded and short-sighted? I'm just going to start using freakin' teleporters.

**Comment by liach** [comment]
Immersive engineering... It is more realistic to integrate with IC2.

**Comment by KyeoftheSea** [comment]
There is already a ton of IC2 support for Railcraft, and not nearly as much perfect feature overlap. My suggestion probably wouldn't be too difficult to implement, either. Simply detect the existence of IE, disable the factory module, and use recipes tailored to IE.

**Comment by liach** [comment]
Recipes from IE? IE is a mod that needs very good set up, but Railcraft is a simple mod that "everyone can play". You can disable the factory module on your own.

**Comment by KyeoftheSea** [comment]
I don't think you understand what I'm suggesting here. For one, I said recipes tailored TO IE, as in using IE materials that are analogous to the ones that Railcraft uses, such as iron or steel rods in place of rebar, which normally requires a railcraft rolling machine. Railcraft's plates don't even appear to be in the ore dictionary right now.  And your argument makes no sense whatsoever, nor does it have any bearing on the suggestion. Railcraft's factory module doesn't need much less in the way of setup than IE. The coke oven and blast furnace are functionally identical, with the IE furnace actually being cheaper, and the RC coke oven and furnace use an old style of multiblock structure detection, which is harder on servers and makes the blocks unsafe for decoration. The rolling machine and rock crusher both require power, which requires power generation, which is actually simpler to provide in IE than it is in Railcraft, and the machines generally use less. Oh, and with IE, you can craft some things by hand that require a rolling machine in Railcraft, like iron plates. But Railcraft is simpler, right?

Also, disabling the factory module currently _completely breaks_ Railcraft Many things, stone ties as an example, become completely uncraftable, because there are no fallback recipes for several components, such as rebar. That means that _half the tracks are completely uncraftable_.

What I am suggesting is that, _when present_, Railcraft utilizes the functionality of IE in place of the currently absent factory module, which both adds functionality Railcraft currently lacks, and prevents extreme content overlap when the factory module is complete.

**Comment by bookerthegeek** [comment]
@KyeoftheSea or you know, use minetweaker to modify the recipes to to do as you are suggesting, and then hide the now non-useful blocks from NEI. Also, asking a mod author to basically turn off a part of their mod because, in your opinion, that other mod does it better, is almost a sure fire way to not get what you are after.

A better way to ask would be to ask for more mod integration, or the ability to turn off specific blocks in the mod without having to disable the entire module. That is much more likely to be considered.

As it is, your post basically reads "Your mod sucks because they do it better, you need to turn your shitty things off and let that other mod do it for you." 

Also, go fuck yourself, ok? I love RailCraft as it is, along with the updates that have been comming out, and would choose it over IE any day of the week.

**Comment by liach** [comment]
Railcraft is not an IE addon. This topic is invalid.

**Comment by KyeoftheSea** [comment]
@bookerthegeek That is _exactly_ what I was asking for. Better integration. I love railcraft, I've been using it since 1.2. I love the way the factory module is set up as a standalone. BUT... It has 100% content overlap with Immersive engineering. That's my point here, they do the exact same things. Not similar things a little differently, like say, Ender IO conduits vs Extra Utilities conduits, which function differently, they do the _same things_. There are other mod authors, Vakzii is one I can think of off the top of my head (Botania, Quark, etc.), that will self-disable parts of their mod to avoid content overlap in the presence of other mods that do the same thing. It's a practice I think should be more common. How many umpteen bajillion BUDs do you need in one modpack?

I have never once said that Railcraft is bad, and in hindsight I went a little too far in my attempted rebuke of liach, who has contributed no real argument against my point, insisting on twisting my words, setting up straw men, and outright making false statements the whole time.

I've attempted to use CraftTweaker to set up alternate recipes for Railcraft objects, but it's an inelegant solution, and doesn't allow for some things that could be allowed through in-mod integration. I think a lot of people would be happy if Railcraft did so automatically.

Also, you both seem to be missing the point that I'm asking for this specifically for the 1.10.2 version, which currently doesn't even _have_ a proper factory module. At present, IE integration like I'm suggesting would remove _nothing_ from Railcraft.

**Comment by liach** [comment]
Then, the best solution is implementing Factory module as fast as possible.

**Comment by bookerthegeek** [comment]
If their is so much overlap, why not ask IE to disable the parts of their mod that overlap? Nobody is making you use specific machines.

**Comment by liach** [comment]
Most of the tile entities themselves are functional already; the only issues are with block textures right now.
