### ISSUE TITLE
[Bug] Interacting with tunnel bore in spectator crashes the game

### ISSUE THREAD

**Issue by xbjfk** [Railcraft/Railcraft#1046]
Steps to reproduce:
1: place tracks
2: place tunnel bore
3: change to spectator
4: right-click tunnel bore
5: wait

Crash Report (Railcraft is the only mod):
[crash-2016-12-23_04.35.29-server.txt](https://github.com/CovertJaguar/Railcraft/files/670278/crash-2016-12-23_04.35.29-server.txt)

**Comment by liach** [comment]
Give the crash report!

**Comment by liach** [comment]
How long do I need to wait? Things goes just fine:
![2017-01-01_09 56 30](https://cloud.githubusercontent.com/assets/7806504/21582356/b352dba8-d008-11e6-8299-1bf0ed36c65e.png)

**Comment by AEnterprise** [comment]
@liach the crash report is original comment, he probably edited it in

**Comment by liach** [comment]
Should be fixed. I tested in that pull request.
