### ISSUE TITLE
Forge Launcher slows down to a crawl and crashes, never happened with other mods

### ISSUE THREAD

**Issue by Scooterman1542** [Railcraft/Railcraft#1047]
Last night I had taken all my mods off Minecraft to test Railcraft, booted it up normally, and when it reaches what I assume is the last thing it has to load, it starts loading less and less, until it crashes.

VIDEO:

https://www.youtube.com/watch?v=n5E9-ZiDz6Y&feature=youtu.be (it ends abruptly because the game crashes)

The most interesting thing, however, is that it seems it had loaded all those last files before, without a problem, even.

CRASH REPORT:

http://pastebin.com/4yB6VnU2

I hope this gets solved soon.

**Comment by liach** [comment]
You should never play minecraft with only 499 MB of memory. At least use 1024 MB!

**Comment by Scooterman1542** [comment]
How do I use 1024, though? I have no idea how the MB thing works in Minecraft.

**Comment by liach** [comment]
You change the memory in Minecraft launcher. Add argument `-Xmx1G -Xms1G` in launch argument if you are using Mojang launcher.

**Comment by Forecaster** [comment]
The stacktrace clearly says out of memory error. If you require more assistance with increasing memory or similar please visit the railcraft irc or discord server, someone may help you there after a while.
