### ISSUE TITLE
Locomotive unlinks when using elevator rails

### ISSUE THREAD

**Issue by 0xCyberFortress** [Railcraft/Railcraft#1048]
When using elevator rails, locomotives unlink carts when going up or down an elevator track. I am currently using minecraft 1.7.10 with railcraft Railcraft_1.7.10-9.12.2.0

**Comment by liach** [comment]
They are not supposed to link on elevator at all.

**Comment by Forecaster** [comment]
This is known, but it's not something that would be trivial to fix. Trains just don't like travelling vertically. You'll either have to unlink the carts before, and relink them after the elevator, or use a different method to get them up/down.
