### ISSUE TITLE
[1.10.2] Worldgeneration is limited to dimension 0.

### ISSUE THREAD

**Issue by Aroma1997** [Railcraft/Railcraft#1050]
The worldGeneration in Railcraft is limited to only generate in dimension 0. (See https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen/GeneratorMine.java#L164 ) This creates problems with other mods, that add their own dimension, because then, RC ores won't spawn there.
It would be better to check if the biome at the specified coordinates is registered as hell or end biome in the biome dictionary to solve the problem.

**Comment by liach** [comment]
@Forecaster Please add tag [bug] and set milestone to next release.

**Comment by CovertJaguar** [comment]
This was an intentional decision after much internal debate as I have no idea whether it should spawn in those dimensions.

**Comment by liach** [comment]
For a dimension like twilight forest, I think Railcraft should generate ores like all other mods.

**Comment by Aroma1997** [comment]
Most dimension mods set their Biomes to something reasonable and register their Bimes to the BiomeDict, so using biomes still gives you the result that you want in 99% of all cases.

**Comment by liach** [comment]
@Aroma1997 Would you mind taking a look at my pull to see if it is a correct solution?

**Comment by Aroma1997** [comment]
@liach Your solution would work in many cases, however I think, it's a better idea to go for biome detection and not for isSurfaceWorld(), because the biome corresponds with the intentional usage of the current place, where the isSurfaceWorld is a bit unspecific. For example the Deep Dark (ExtraUtils) has isSurfaceWorld() to set to false, but since it's a mining dimension, you would expect ores to be generated there.

**Comment by CovertJaguar** [comment]
Fixed by 74b9110b1988e51b7539ac45875a8371dccd56d4
