### ISSUE TITLE
[1.10.2] Item Loader and Adv. Item Loader ignore redstone settings.

### ISSUE THREAD

**Issue by threehams** [Railcraft/Railcraft#1053]
Verison: 1.10.2 (Minecraft 10.0.2, Forge 12.18.3.2185)
OS: all (singleplayer + multiplayer)
Other mods: None

The Item Loader and Adv. Loader ignore the Manual, Partial, and Complete redstone settings, and emit a redstone signal as soon as there is no more work to be done.

Steps to reproduce:
- Place a Loader about a Locking Track (any type of track).
- Set the Loader to Manual mode.
- Create a cargo cart, do not apply a filter, and send it toward the Loader.

Result: The cart reaches the Loader, and it applies a redstone signal immediately. If there is cargo available (and the cart has a filter set - separate bug) it will load the cart, then apply a redstone signal.

Screenshots:
![manual-loader-bug](https://cloud.githubusercontent.com/assets/1399894/21573121/b90ba314-ce95-11e6-897d-5969956ed317.gif)

Other Details:
I'm completely new to using Railcraft, so I'm a little unsure of expected, but the redstone signal seems to be applied when there is no more work for the Loader to do, regardless of any settings. For example, adding 64 cobble, setting a filter to 127 cobble, and using the "Transfer" and "Complete" settings will emit redstone after transferring 64, instead of waiting for the other 63 to arrive and be transferred.

**Comment by AWPgodkiller** [comment]
I have exact same problem too.

**Comment by TomSmith27** [comment]
Same problem aswell

**Comment by raymondbh** [comment]
Kind of same problem. Trying to set the loader to immedite and the unloader to complete, settings will always end up as the loader is set. But even then it's not working as it should, the unloader just sends the cart away even its not finnished (in complete mode).
