### ISSUE TITLE
Elecitric Locomotives dead

### ISSUE THREAD

**Issue by shivachirr** [Railcraft/Railcraft#1055]
So i wanted to upgrade to the elctric trian evry block seems to be there it just did want want to transfer power to the energy feeder from other mods also im wondering if i can use rf to do this

**Comment by liach** [comment]
Electric locomotive is, in fact, only usable in creative.

**Comment by Forecaster** [comment]
Because the flux transformer (aka the RF-converter)  being one of the machines that have yet to be ported to 1.10 the only way to power the tracks is with EUs. I'd perhaps look into immersive engineering which can output EUs, at least in 1.7 it could.

**Comment by Silvrus** [comment]
@Forecaster, can you confirm the EU implementation actually works at the moment? I've been trying to get this working for a bit now and cannot get the IC2 Feeder Unit to actually take in any charge. Used Energy Converters -> Feeder, and Energy Converters -> Batbox (which filled) -> Feeder Unit. Tried track directly on Feeder Unit, adjacent to Feeder unit and with Shunting Wire. No configuration gets charge into the locomotive.

**Comment by shivachirr** [comment]
yeah that's what i got when testing

**Comment by Silvrus** [comment]
@shivachirr Check #964, I forgot about the redstone signal. Test it out if you can.
