### ISSUE TITLE
[1.10.2] Tunnle wall replacer/builder and torch placer

### ISSUE THREAD

**Issue by shivachirr** [Railcraft/Railcraft#1058]
im suggesting a cart or something to replace the walls of a tunnel or just a open air area with blocks you want in a good pattern so you could make them look better as you travel. kinda like how Buildcrafts builder can do paths over distances this would be a simmialr thing and you could take like a patteren so lets say every 3 blocks the pattern changes a bit and you add a torch or glowstone and maybe every 10 add something like a Immersive engineering wire link relay of some kind. because right now im building a massive rail line that has like 5000 blocks long to go and i kinda want it to look a bit nice and have a cover of some kind when it is open air. while building it i kinda thought of this. if anything its and advanced version of the undercutter that dose more then under the tracks

**Comment by Forecaster** [comment]
See #649 
If you have additional ideas that are not mentioned there add them to that thread

**Comment by shivachirr** [comment]
yeah but thats for the tunnel bore im talking like a independent cart but ok
