### ISSUE TITLE
Iron tank and steel tank load only 4000 mb

### ISSUE THREAD

**Issue by Pilad** [Railcraft/Railcraft#1062]
Railcraft_1.7.10-9.12.2.0
Iron tank and steel tank load only 4000 mb at once , but tank or cell have capacity 16000mb or more.

**Comment by liach** [comment]
How do you input?

**Comment by liach** [comment]
@Pilad Any update?

**Comment by Pilad** [comment]
> How do you input?
I put cell in to tank.
Cell from GT and Extra Cells
http://imgur.com/HpseAQF
http://imgur.com/HTVxhx8
http://imgur.com/p0xNolU
Tanks from Ender Io not load same fluids. Such us Hydrogen. Water is load.
http://imgur.com/BjJxChA
http://imgur.com/7VeJfyO

**Comment by Ristellise** [comment]
Oh...tanks can only hold liquids that registered in the dictionary.. thats why you can't put hydrogen in. but it still doesn't explain why GT refuses to export all its fuids...

**Comment by Pilad** [comment]
> Oh...tanks can only hold liquids that registered in the dictionary..
Tanks railcraft or ender Io or Extra Cells?
The bug is also manifested with water. It also downloads only 4 liters

**Comment by CovertJaguar** [comment]
Fluid handling in 1.7 is utterly broken and should be mostly fixed in 1.10.
