### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SpartanSamuel** [Railcraft/Railcraft#1063]
When viewing Alloy Smelter recipes in JEI, I crash. Not quite sure what page I was on, somewhere past 30. I just got through the dead bushes. Anyways, I'm reporting it here because the crash log is claiming it was rendering a Railcraft block that threw the error. If I need to be redirected to another GitHub, just let me know.

MC: 1.10.2
Forge: 12.18.3.2202
Railcraft: 10.0.1
Ender IO: 3.1.157
JEI: 3.14.2.401

http://pastebin.com/YrkyscAC

**Comment by Ristellise** [comment]
@mezz

**Comment by AEnterprise** [comment]
can you try again without optifine?

**Comment by SpartanSamuel** [comment]
Dead on. Running without optifine doesn't cause the crash given the parameters. I'll submit a bug over there, thanks for the assist!

**Comment by sp614x** [comment]
The crash only happens when Anisotropic Filtering or Antialiasing is enabled.
Most probably related to the sprites with custom loader, looking for a bugfix.
