### ISSUE TITLE
Cannot make Tin Plates

### ISSUE THREAD

**Issue by ranger135xp** [Railcraft/Railcraft#1065]
Hello Covert,

I noticed a bug in the latest 9.12.2.0 for 1.7.10. The rolling machine will not make tin plates even with different tin ingots. The recipe in NEI shows the exact recipe that is in the rolling machine. Here's the image: 
![2017-01-10_11 54 42](https://cloud.githubusercontent.com/assets/15115164/21815805/ebeec8b2-d72b-11e6-9d8e-867698ffe09b.png)
I removed the one ingot to show you the tool-tip without it blocking the machine GUI.

If you need a mod-list, it is Bevo's Tech Pack.
Thank you.

**Comment by liach** [comment]
It needs iron and tin ingots instead of all tin ingots. Invalid

**Comment by ranger135xp** [comment]
Ah shit you're right! I'm sorry for missing such an obvious thing. A user brought it up to me and I was distracted while trying to scurry them along. I'm closing this.
