### ISSUE TITLE
Feed station and some other items not accessible in 1.10.2

### ISSUE THREAD

**Issue by Sellec** [Railcraft/Railcraft#1067]
New clear installation of Minecraft (remove all old files specialy for testing)
Minecraft forge 12.18.3.2209, 2202, 2185 with mercurius
Have installed:
Railcraft 10.0.1

Create new world with creative mode.
Entering inventory, searching for feed station and furnace block and see nothing.

fml-client-latest.txt attached into issue.
cannot attach zipped client becouse of upload limitation size (10mb).

[fml-client-latest.txt](https://github.com/CovertJaguar/Railcraft/files/703560/fml-client-latest.txt)

**Comment by tomelfring** [comment]
See issue #1010 
They will return in 10.2.0
