### ISSUE TITLE
[Request] Fuel support for xu2 Red Coal

### ISSUE THREAD

**Issue by xenoflot** [Railcraft/Railcraft#1068]
Please!

**Comment by Forecaster** [comment]
Fuel values? Production method? etc?

**Comment by xenoflot** [comment]
ExtraUtilities2 adds an item called Red Coal that's processed by putting regular coal into a Resonator which is the first machine in the tech tree of that mod so it's pretty early game. Process requires about a minute per piece of coal to process. The Red Coal is enriched and has a burn time of 12800. Works as normal solid fuel for furnaces and several other mods that use coal-like substances.

It could (probably would) be argued that it's substantially OP compared to RC's native X-minutes for Coke with a burn time of 3200. Balance is a personal thing. It's still trivial to set up a wall of coke ovens, just potentially more lag.

**Comment by liach** [comment]
What device do you use this for? Blast furnace? Furnace cart?

**Comment by xenoflot** [comment]
In general, Red Coal is a solid fuel and works where coal works, just with a longer burn time. Vanilla furnaces, most mods' coal generators, etc. I haven't personally tested with vanilla Furnace Carts but I expect it would work.

Given free reign with RC... I'd have it work wherever solid fuel would work and add a section in the config where support can be toggled as desired with everything set to false by default. Pack devs can enable depending on the flavour they want.

Support 3rd party mod fuels
-----------------------------
SteamEngine3rdPartyModSolidFuels = <boolean> [false]
BlastFurnace3rdPartyModSolidFuels = <boolean> [false]
etc.

If getting it that granular is prohibitively tedious, then a single value for 3rdPartyModSolidFuels = <bool> would do, and have it work in RC wherever you'd use Coke or Coal (except in a Coke Oven).

Cheers!

**Comment by Generalcamo** [comment]
As a question: Is there any other information requested for this fuel type? I can give any if needed.

**Comment by CovertJaguar** [comment]
Seems too OP.
