### ISSUE TITLE
Light addon for loccmotives

### ISSUE THREAD

**Issue by shivachirr** [Railcraft/Railcraft#1069]
so im running hardcord darkness and i was riding my long range HV rail and ive thought of something why no be able to add lights to locomotives like torches on the side of the carts or the standard nose light on the engins

**Comment by Forecaster** [comment]
Railcraft should support the DynamicLights mod #992 at least for the electric locomotive which has a light on the model, but we're not going to add dynamic lights to Railcraft itself because it's not a trivial thing to do as far as I'm aware.

**Comment by shivachirr** [comment]
im not saying anything about the dynamic lights mod what im sauing is that you can mod the cart and trains to have working lights on them

**Comment by liach** [comment]
It is not likely that Railcraft will include a dynamic lights within.

**Comment by liach** [comment]
Moreover, dynamic lights need coremods, and Railcraft is NEVER intended to be a coremod. Find dynamic lights here: http://www.atomicstryker.net/dynamiclights.php

**Comment by shivachirr** [comment]
why is everyone tailing about dynamice lights im talking about puting a torch on a cart when did dynamic lights come it and im thinking more 1.10.2+

**Comment by KnightMiner** [comment]
By dynamic lights, they mean entities (such as carts) that produce light. It is really hard to do as Minecraft only expects actual blocks to produce light, so apart from placing fake light blocks (very messy) or rewriting the lighting system, Railcraft cannot do this.

**Comment by shivachirr** [comment]
ok then also i think it would be easier since optifine dose dynamic lights
how it could be only enabled when the requried mod is present

**Comment by liach** [comment]
Optifine? As I can see in sp614x/optifine#182, mods cannot add custom dynamic light source for now. Pinging @sp614x for help in integration.

**Comment by Ristellise** [comment]
@liach optifine's dynamic light afaik is fake dynamic light. it means that it lights up on the clientside by not on serverside and does not prevent any mob spawns.

**Comment by liach** [comment]
Optifine ones are also fake, since Optifine is a client only tweaker. What are you talking about then @Joshwoo70?

**Comment by Forecaster** [comment]
@liach he said optifine. What are you on about.

Both optifine and dynamic lights only do client-side lighting. Railcraft is not going to have this feature. If you want this @shivachirr you need to get either author of those mods to support railcrafts locomotive(s).

Edit: Right, DL is already supported with the electric locomotive thanks to liach

**Comment by liach** [comment]
> @lunch

Do you mean @liach?

In fact, all dynamic lights are fake. That's all.

**Comment by dj3520** [comment]
I believe what @shivachirr wants is not for Railcraft to put in it's own dynamic lighting system, but instead to add lights to trains so that when a dynamic lighting system is used, the train has multiple sources of light that travel with it. As @Forecaster pointed out the electric locomotive already has this feature, but possibly @shivachirr is looking to add this to all locos and to carts, despite them not having a light source on them.

**Comment by shivachirr** [comment]
Finally someone gets whats what i want to do 

> I believe what @shivachirr wants is not for Railcraft to put in it's own dynamic lighting system, but instead to add lights to trains so that when a dynamic lighting system is used, the train has multiple sources of light that travel with it. As @Forecaster pointed out the electric locomotive already has this feature, but possibly @shivachirr is looking to add this to all locos and to carts, despite them not having a light source on them.

**Comment by dj3520** [comment]
@shivachirr I know how irritating it can be to not have your idea come across. The real issue is that minecarts and the steam loco don't have lights on them. I'm about 50/50  for my opinion of the steam locomotive getting a headlamp, but the minecarts being in the dark is realistic.

**Comment by shivachirr** [comment]
yeah but i was thinking of it like an optional addon via crafting to add
like torches or a band glowstone to the cart and thx

**Comment by dj3520** [comment]
The optional addon would have to be separate from the main mod. There's also the issue of making the lighted minecart but not having a dynamic light mod (crafting cost for nothing in that case.)

**Comment by shivachirr** [comment]
i guess but i would of be nice if it was as easy as putting a torch on the cart then it works maybe later version it might be possible once the 1.10.2 version of the mod is fully flushed out

**Comment by dj3520** [comment]
Again, the issue with that would be that there wouldn't be a purpose if you don't have a dynamic lighting mod.

**Comment by liach** [comment]
Will close since we cannot really do much.
