### ISSUE TITLE
Cross-mod inventory access

### ISSUE THREAD

**Issue by xenoflot** [Railcraft/Railcraft#1070]
Hi,

I'm playing with 1.10.2-10.0.1 and trying to use it to get my quarry output back to my base. I've noticed that I'm unable to input or output from loaders/unloaders with extrautil2's transfer nodes nor Steve's Factory Manager. SFM simply doesn't even know there's an inventory there. It does work with vanilla hoppers but they're painfully slow in the modded game.

Is this intentional?

Cheers!

**Comment by Forecaster** [comment]
Loaders and unloaders can respectively take and put items into an adjacent vanilla chest. I'd suggest using that as a proxy.

**Comment by xenoflot** [comment]
Hah! I tried underneath. I didn't think to put one on the side! Seems to be working, thanks!
