### ISSUE TITLE
[RC 10.0.1] Rolling Machine's rail recipes not working on crafting table

### ISSUE THREAD

**Issue by ghost** [Railcraft/Railcraft#1071]
Railcraft 10.0.1
Forge 2185
MC 1.10.2

Given that the factory module is not yet ready in this version, I tried making advanced rails in the crafting table. I am unable to get the recipe to work.  The configuration files are all bone-stock with 10.0.1. Do these work out-of-box, or am I supposed to modify them to allow for the factory module situation?

Screenshot attached.
![screenshot 2017-01-19 11 08 08](https://cloud.githubusercontent.com/assets/21157174/22092403/53155d0e-de38-11e6-8836-803c8bbfbd16.png)

**Comment by ghost** [comment]
I tried disabling the factory module and enabling alt recipes separately with no results.

**Comment by liach** [comment]
How did you get normal rail then? From village chests?

**Comment by ghost** [comment]
No. I was able to make it via the standard RC formula in the crafting table (before even touching config files). This is why I'm so perplexed.

**Comment by liach** [comment]
Does this recipe show up on JEI?

**Comment by ghost** [comment]
I don't have JEI installed and have never used it.

**Comment by ghost** [comment]
Is there perhaps a different recipe for difficulty: 2? For example, EnderIO changes some of the recipes depending on map difficulty, though I didn't see anything indicating this in the files so I didn't think to ask until now. Sorry for the lack of information, though I'm at a loss here. I'm no developer, though my years of running a few private servers have allowed me to usually troubleshoot things like this.

**Comment by liach** [comment]
JEI: http://minecraft.curseforge.com/projects/just-enough-items-jei

**Comment by ghost** [comment]
@liach you are awesome. I would have never thought to install an additional mod to have access to the temp recipes. Here's a screenshot of everything. The standard rails recipe still works (in a crafting table), but it's not even used in the temp recipe for advanced rails. Very strange. Thank you again for your suggestion.

![screenshot 2017-01-22 15 42 13](https://cloud.githubusercontent.com/assets/21157174/22180933/86f6c5ac-e0ba-11e6-9e86-2ddab82d08ff.png)
![screenshot 2017-01-22 15 42 48](https://cloud.githubusercontent.com/assets/21157174/22180932/86f364e8-e0ba-11e6-8fb9-2aac465ed4a0.png)
