### ISSUE TITLE
1.10.2 Crash

### ISSUE THREAD

**Issue by Realever** [Railcraft/Railcraft#1072]
Hi,
I played with a friend and suddenly his game has crashed. Could you please help me? Crashreport:
here the pastebin : http://pastebin.com/f5w3jgBU

 I would be glad to hear from you.

**Comment by liach** [comment]
It is caused by some coremod with a super bad coding style. It does not have a package, so I cannot really help. Try remove them one by one.

**Comment by liach** [comment]
Ohh it's optifine... @sp614x

**Comment by sp614x** [comment]
The OutfittedTrackModel$CompositeModel.getQuads() crashes with NullPointerException.
Does not seem related to OptiFine.

**Comment by liach** [comment]
Well, no such report exists without optifine.

**Comment by Realever** [comment]
i think i have found the crash.my friend uses faithful and spahx bdcraft at the same time.And when i look in to the folder from Faithful this is for the vanilla texture and bdcraft maybe too.I must wait when he comes home for checking this.

**Comment by liach** [comment]
https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/client/render/models/resource/OutfittedTrackModel.java#L160

I think a wrong state gets passed in as an argument, causing the crash.

**Comment by sp614x** [comment]
A wrong state should throw ClassCastException, not NullPointerException.
In fact the NPE is not possible at this line, there is a null check 2 lines above.
Either the source does not match the running JAR or some core mod has patched it incorrectly.

**Comment by liach** [comment]
On the crash report, there is a part:
```
-- Block model being tesselated --
Details:
    Block: minecraft:brick_block
    Block location: World: (8,65,-237), Chunk: (at 8,4,3 in 0,-15; contains blocks 0,0,-240 to 15,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Using AO: true
```
This makes things look more complicated.

**Comment by sp614x** [comment]
This is OK, the call comes from ConnectedTextures.
The block being rendered is "minecraft:brick_block" and CTM checks the neighbour blocks in order to find if the block is connected or not.
The CTM rule most probably uses "matchTiles=xxx" so CTM has to check the neighbour block model textures. One of the neighbour blocks is from Railcraft and the call to CompositeModel.getQuads() crashes.

**Comment by liach** [comment]
@Realever Please give steps to reproduce.

**Comment by Realever** [comment]
As he used the wirless crafting grid from refined storage at the Village,which is near at our Base the crash happened

**Comment by liach** [comment]
@Realever Any update?

**Comment by CovertJaguar** [comment]
I don't know why it throws a NullPointerException, but it could be that the state they pass in isn't an ExtendedState maybe.

**Comment by Realever** [comment]
Ups sorry i forgot to write it.Yes the problem is solved.I don´t know, if the error solved through changing the ressource pack or an mod update, but it solved

**Comment by liach** [comment]
Thanks!
