### ISSUE TITLE
[1.10.2] Forge 221 - Mod is asking forestry mod for bad commands. - Feature not added yet?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Railcraft/Railcraft#1074]
https://gist.github.com/P3rf3ctXZer0/4f85461055b0cba5ed6d7107ef36ee15

**Comment by liach** [comment]
Well, those items are simply not yet added back.

**Comment by P3rf3ctXZer0** [comment]
Aw; it just said to report it.

**Comment by CovertJaguar** [comment]
I think the Forestry syntax changed or something. I haven't looked at it.

It seems to be referencing a missing backpack? Maybe it got renamed.

**Comment by liach** [comment]
Might be fixed by updating Forestry API and fixing compile errors.

**Comment by CovertJaguar** [comment]
I doubt it, its an IMC error. Either something is wrong in how I'm defining my backpacks (highly possible) or something is wrong with the message itself.

**Comment by liach** [comment]
Dupe of #981, closing
