### ISSUE TITLE
Admin charge feeder not working

### ISSUE THREAD

**Issue by VsUK** [Railcraft/Railcraft#1077]
Just decided to give this mod a try to give a little more oomph to my server. Kinda disappointed at the furst hurdle. I wanted to create a constant rail network that allowed players to wait for trains to board & the right trains to the right place. However the admin charge feeder doesn't work at all. No power from it what so ever. `The charge meter shows all supply, draw & so on as 0. The only thing that does work is the loss rate which is 0.84 c/t

Using 1.10.2 version!

**Comment by Forecaster** [comment]
It won't do anything unless you apply a redstone signal to it

**Comment by Vectrobe** [comment]
If redstone is already being applied, break the redstone source and re-place it. I've noticed the feeders tend to bug out when you change the track and simply breaking the feeder wont fix it most of the time, it's to do with how they handle redstone signals.

(confirmed a bug)

**Comment by VsUK** [comment]
Right ok. I've just tested it & I wasn't using redstoneI was using blocks. I would have thought placing the admin charge feeder on top of redstone blocks would do it. 

Just double checked this & this is the case. Charge is 0 on the admin feeder & the tracks if the admin feeder is connected to a redstone block. It only works if you link the feeder & the redstone block with redstone!

**Comment by Vectrobe** [comment]
It will work with a redstone block right next to it, but you have to place the redstone block last or the feeder will not know it's there.

Where is the block relative to the feeder however?

**Comment by VsUK** [comment]
Tested what you said & if placing the block before the admin feeder. It doesn't provide power. Only by placing the admin feeder before redstone block does it work. The only places placing the redstone block before the admin feeder that doesn't work is on the sides or above it. Doing so below does work. it's just on top & down the sides that doesn't if done after placing admin feeder!

________________________________

**Comment by Vectrobe** [comment]
It will work with a redstone block right next to it, but you have to place the redstone block last or the feeder will not know it's there.

Where is the block relative to the feeder however?

**Comment by Vectrobe** [comment]
Why did github only just decide to submit that comment...

**Comment by CovertJaguar** [comment]
Sounds like a neighbor block update issue or something. hmm.
