### ISSUE TITLE
[RC 10+] Switch, Wye and junction tracks

### ISSUE THREAD

**Issue by Vectrobe** [Railcraft/Railcraft#1078]
Progressing in my local world I discovered that said tracks haven't been implemented yet, so I decided to make it into an "issue" for notification etc...

I presume these pieces will be re-implemented via kits? because it makes sense to do it that way, otherwise you have the problem of the copper rails on the new electric tracks...

**Comment by CovertJaguar** [comment]
We were actually tossing around the idea of using the Crowbar (or another tool) to switch tracks between normal, junction, turnout, and wye.

Making them into Track Kits ran into issues with what the recipe should look like.

**Comment by bookerthegeek** [comment]
Using the crowbar, with an item use from your inventory ( Think bow and arrow) would be pretty cool.

**Comment by Vectrobe** [comment]
Using the crowbar is a pretty good idea, however maby making a dedicated tool might be better? a blowtorch makes sense for cutting and welding the rails, however I'm not sure about fuel for it...

A problem I see with using the crowbar will be track orientation, unless you just let it cycle through for each click. The steel crowbar also currently seems a little soft so you may need to increase its durability...

**Comment by liach** [comment]
This way of dealing with junction tracks can make tracks less a pain :smile:

**Comment by Natesky9** [comment]
How about a "toolbox" that stores track parts (just basic bits) and a tool that can use the items from the toolbox to change track types? Would allow for more customization with only a few inventory slots

That would allow you to keep the crafting costs for each rail independent of each other, but still swap tracks on the fly

**Comment by CovertJaguar** [comment]
We'll its mostly implemented now, but I'll just keep it simple and just make the tool fairly costly. Don't want to make it even more confusing for new players.

**Comment by Ristellise** [comment]
close this?

**Comment by liach** [comment]
Well, switch is not done yet.

**Comment by Vectrobe** [comment]
Technically you shouldn't close these things until you at least have a commit to attach...
