### ISSUE TITLE
[1.10.2] Client crashes after placing steam locomotive to the world

### ISSUE THREAD

**Issue by zTorden** [Railcraft/Railcraft#1080]
I've placed my newly created steam loco on a track, and the client crashed, and keeps crashing on entering the world. Happens on separate client only: both standalone server and integrated server-client don't crash.

The client crashes only when ALL of these mods are present (there is no crash with any three of them):
Railcraft
Forestry
CustomMobSpawner
ImmersiveEngineering
more info here: https://openeye.openmods.info/crashes/671e9feeea39161e2a1f5a17415e4f52

re-creating the world makes no influence on the bug

**Comment by liach** [comment]
I believe this is caused by a coremod.

**Comment by zTorden** [comment]
If I am not mistaken, the only coremod present is OpenEye, and the client crashes without it just the same.

**Comment by KnightMiner** [comment]
Can you add the full crash report then? a single error does not help debug the issue.

**Comment by zTorden** [comment]
Here you are, but don't expect too much: http://pastebin.com/SQTyXGdQ

**Comment by liach** [comment]
Looks like an id conflict...

**Comment by Discomanco** [comment]
We had this issue on our server as well.
We fixed it by removing CustomMobSpawner (DrZhark's).
Railcraft + CustomMobSpawner + Something else that I haven't managed to locate, makes stuff like Locomotives and Robits (Mekanism) instacrash the clients.
I say "+ something else" because Railcraft and CustomMobSpawner works fine alone.

Mods in common with our pack though, is:
Immersive Engineering
Forestry
Railcraft

**Comment by zTorden** [comment]
I think Forestry is to blame: 
public abstract class EntityMinecartBeeHousingBase extends EntityMinecartContainerForestry implements IBeeHousing, IOwnedTile, IGuiBeeHousingInventory, IClimatised, IStreamableGui {
	private static final DataParameter<Optional<GameProfile>> OWNER = EntityDataManager.func_187226_a(EntityMinecart.class, GameProfileDataSerializer.INSTANCE);


1) it uses EntityMinecart.class instead of it's own class
2) this initialization happens before Railcraft on server side, but after Railcraft on client side, which leads to all Railcraft ids being shifted, as they are basing on different EntityMinecart.class topmost id value

**Comment by mezz** [comment]
Should be fixed in the latest Forestry, please confirm.

**Comment by zTorden** [comment]
I confirm, there's no crash anymore with the latest Forestry build,
