### ISSUE TITLE
I can't see the switch rail in Minecraft 1.10.2 with Rc 10.0.0.1

### ISSUE THREAD

**Issue by Ostrichbeta** [Railcraft/Railcraft#1083]
Some days ago,I saw an update on rc on 1.10 and i download it,but when i open the game,i can't any switch rails and any switch motor.But i see the name of the switch rail in the lang file.it's that a bug??

**Comment by liach** [comment]
Use normal rails and levers for now. They are unfortunately, not yet implemented.
