### ISSUE TITLE
No 1.8.9 update

### ISSUE THREAD

**Issue by Akame-Zero** [Railcraft/Railcraft#1084]

**Comment by Ristellise** [comment]
No why do you need 1.8 anyways?

**Comment by CovertJaguar** [comment]
1.8.9 was too broken to support Railcraft.

**Comment by Akame-Zero** [comment]
1.8.9 is the most recent version of the game I will use, I hate 1.9 because in my opinion the changes to the combat system were(and still are) completely unnecessary and don't make the game better, if anything I think the update made the game worse.

**Comment by Generalcamo** [comment]
Irrelevant. There are major issues with 1.8.9 that make modding in general difficult. 1.7.10 is still available for your use.

**Comment by Akame-Zero** [comment]
The 1.7.10 version of one of the mods I use no longer exists.

**Comment by dj3520** [comment]
It's expected that eventually everyone will use the newest version of Minecraft. So it makes sense to develop for the newest version. Going backwards just to please people who don't like the new versions is usually seen as more work than it's worth.
