### ISSUE TITLE
Survivalist Integration

### ISSUE THREAD

**Issue by WolfieWaffle** [Railcraft/Railcraft#1085]
This is a suggestion to add compatibility for the ore rocks in Survivalist. It has ore rock items for each of the ores that Railcraft provides, so it would be easy to add a config that makes the poor ores drop ore rock instead of the block if Survivalist is installed.

**Comment by liach** [comment]
Can you provide a link to survivalist mod?

**Comment by liach** [comment]
https://github.com/gigaherz/Survivalist

**Comment by liach** [comment]
@gigaherz It seems you might need to support oredict from your side.

**Comment by liach** [comment]
@CovertJaguar I think we can close this one, since this is not really Railcraft's issue.

**Comment by WolfieWaffle** [comment]
Should I ask the Survivalist dev about it? not exactly sure what side needs to implement it.

**Comment by gigaherz** [comment]
Already done: https://github.com/gigaherz/Survivalist/issues/33
