### ISSUE TITLE
Unable to play unknown soundEvent:  railcraft:locomotive.steam.whistle

### ISSUE THREAD

**Issue by MKindy** [Railcraft/Railcraft#1087]
Train whistles are not playing. Not sure why. Running 10.0.1 on Forge build 2107, Java 1.8.0_121 on Windows 7. Error in log from debug is in the title. No other mods are running -- this is a fresh install.

**Comment by MKindy** [comment]
[Forge 12.18.3.2221 and Railcraft.log.txt](https://github.com/CovertJaguar/Railcraft/files/809473/Forge.12.18.3.2221.and.Railcraft.log.txt)
Here's a follow-up attempt where I ran it on my Windows 10 machine, same Java ver, Forge build 2221; same issue presents itself.

**Comment by liach** [comment]
@MKindy Give fml-client-latest.log

**Comment by MKindy** [comment]
Thanks for reminding me about that, 'cause this is weird -- fml-client-latest.log isn't being generated.  I've done fresh installs of Forge 2107, 2221, and 2239 and none of them are creating fml-client-latest.log.  Weirdly, though, 2252 (1.11.2) is.

I will be doing more troubleshooting, but do you have any thoughts?

**Comment by AEnterprise** [comment]
@MKindy what MC launcher version are you using? if you heapen to be using the new MC launchert revert to the old one for the logs, there are issues with the logging in the new one for mods

**Comment by CovertJaguar** [comment]
Sounds are in the other repo sorry. I haven't had a chance to fix the code over there yet, so sounds are missing at the moment.

**Comment by MKindy** [comment]
Thanks for the info, @CovertJaguar -- and thanks for the info, @AEnterprise , I didn't know the latest MC launcher was having those problems, and that's the launcher I was using.

**Comment by liach** [comment]
@CovertJaguar Should I close this?

**Comment by CovertJaguar** [comment]
No, if you do someone will just make a new one.

**Comment by liach** [comment]
@GeneralCamo See the comment above.

**Comment by Generalcamo** [comment]
@liach See dev chat comments

**Comment by Generalcamo** [comment]
FYI: This has been fixed in the next version. Compiling the code base from this Repo won't work, but trust me in that it will be in the release build (and is in the Patreon Alphas)
