### ISSUE TITLE
The mod is has some problems

### ISSUE THREAD

**Issue by ming514** [Railcraft/Railcraft#1088]
I am sorry that your mod has some problems. The problem is: I cannot make tracks on the Rolling Machine, and the NEI is not able to investigate the recipe list. Could you please fix it?

my minecraft version is 1.7.10.

User,ming514

**Comment by CovertJaguar** [comment]
Yes.

**Comment by liach** [comment]
?
Use NEIAddon and NEIPlugin.

**Comment by ming514** [comment]
the problems still not fix.

2017-03-02 3:56 GMT+08:00 liach <notifications@github.com>:

**Comment by ming514** [comment]
I cannot make tracks on the Rolling Machine, and the NEI is not able to investigate the recipe list.

**Comment by liach** [comment]
Wait for next official release. Rolling machine will be back.
