### ISSUE TITLE
Any hopes for 1.11?

### ISSUE THREAD

**Issue by HoldYourWaffle** [Railcraft/Railcraft#1089]
So is this mod gonna be updated to 1.11 anytime soon?
It is possible as shown by @liach in PR #1042, although he _deleted_ it for being a mess...

Of course some compatibility code would have to be (temporarily) removed because of unupdated mods (as shown in #1042 😄 )

**Comment by Ristellise** [comment]
once 1.10 is ported fully.

**Comment by HoldYourWaffle** [comment]
Any time indication?

**Comment by liach** [comment]
Well, Jaguar wil port himself as he said.

**Comment by CovertJaguar** [comment]
Yeah, I'd like to at least mostly finish the 1.10 port first. I don't think the 1.11 port will be too bad from there.

**Comment by bookerthegeek** [comment]
@HoldYourWaffle Usually you also can add a week to the release date every time somebody asks for a release date.

**Comment by liach** [comment]
Just wait, it's going to be okay.

**Comment by HoldYourWaffle** [comment]
@CovertJaguar I understand that of course, it's really weird to half-finish a port and just move on, but since I don't know the full potential and/or what's done and what's not so I can't judge myself how long this is is gonna take and if I'm gonna wait for that :)

@bookerthegeek Luckily I didn't ask for a release date, just an indication of how long it's gonna take 😄  I'm a coder/"modder" myself so I know it's really frustrating to get pressurized by this kind of questions

**Comment by HoldYourWaffle** [comment]
Dammit you were faster than me....

**Comment by liach** [comment]
Moved to #1232
