### ISSUE TITLE
Only allow liquid destroying tracks when...

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1090]
I propose only to allow fluid to destroy track when the track is right next to a source block or when the fluid is right above.

**Comment by CovertJaguar** [comment]
This is all determined by the Block Material type. I have no control over it beyond whether it does or does not happen. And I have no means to change the Material type on vanilla Iron Tracks. As annoying as it is, I wiped out half my test track earlier.

**Comment by liach** [comment]
@CovertJaguar After a recent look, I found I could change it in fluid class directly.

**Comment by CovertJaguar** [comment]
Maybe, but I'd prefer to leave it as is.
