### ISSUE TITLE
[1.10.2] [Decoration] Some Railcraft stones have errored or no textures.

### ISSUE THREAD

**Issue by Notawallplan** [Railcraft/Railcraft#1096]
Title.
Here's a pic of the block and fitted versions of Abyssal Stone. The fitted version is surrounded by the block version.
![2017-03-05_09 31 25](https://cloud.githubusercontent.com/assets/13065770/23588120/b1c24314-0186-11e7-87a7-a73cc9d8c440.png)
I am unsure if this is just a simple model bug that can be fixed vita resource pack or something far worse.

**Comment by CovertJaguar** [comment]
Outdated Optifine?

**Comment by Ristellise** [comment]
probably.. optifine can be seen on the top right as FPS,Chunk updates overlay text... you don't usually get that in games without optifine.

**Comment by Notawallplan** [comment]
Will update immediately. Thanks.
