### ISSUE TITLE
Convert from Redstone Flux to Forge Energy

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1097]
Just a generic project to convert Railcraft's energy system from RF to FE, maintaining TeamCoFH's RF as a pure compatibility layer if detected. This removes the need to keep the API in Railcraft, and should ease the transition to 1.11 as well when that comes.

Note there is ongoing discussion to switch to Railcraft Charge entirely. If this is the case, then FE should be maintained in its own separate module like the RF module is for compatibility with other mods.

**Comment by CovertJaguar** [comment]
Ugh...keep me out of the energy wars please.
