### ISSUE TITLE
Console spam after placing Charge Feeder Unit

### ISSUE THREAD

**Issue by bassomarko** [Railcraft/Railcraft#1098]
Railcraft 10.0.1, Forge 12.18.3.2234, Infinity Lite 1.10 pack version 1.7.0.

I have a small electric track loop, and after I placed the IC2 charge feeder unit next to the track and supplied power and redstone, the server console is now full of "[Server thread/INFO] [railcraft]: Saving Charge Battery data..." about once every 45 seconds.  Not sure if it's intentional to have that message displayed in console or if I'm missing something obvious to filter it out, but I haven't seen any other mentions of this issue.

**Comment by liach** [comment]
Does it happen with admin charge feeder?

**Comment by bassomarko** [comment]
After replacing the IC2 feeder with the admin feeder, the messages stopped.  I then went back to the IC2 feeder and the messages returned like before.  This happens even when the net retains a constant 20k charge.

**Comment by liach** [comment]
Related lines: https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/blocks/charge/BatterySaveData.java#L53-L54

https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/util/misc/Game.java#L31

Should be an issue. Easy fix.
