### ISSUE TITLE
Incorporate Bone Block into Bleached Bone Recipe

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1100]
Currently the Bleached Bone Block requires Bleached Clay for its creation. 1.10 however introduces Bone Blocks, which could be used in the crafting recipe instead, like how Nether Bricks were incorporated into the old recipes back in the day.

I would recommend a recipe like so:
BB*
BB*  --> 4x Bleached Bone Block
***

Where "B" is Bone Block

**Comment by CovertJaguar** [comment]
Clay was added because Bones are hard to properly balance. You either don't build a skeleton farm and never have enough, or you build a skeleton farm and they become basically free.

**Comment by CovertJaguar** [comment]
The current recipe is 1xClay+3xBoneMeal -> Bleached Clay -> Bone Brick.

1xBoneBlock -> 4xBoneBrick would be a significant cost decrease.

I'm not necessarily against that, just pointing it out.
