### ISSUE TITLE
Creosote and arthropods

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1106]
Since creosote is intended to prevent bugs biting away rails, they should be able to damage arthropods. I suggest the addition of splash creosote to damage arthropods and make arthropods slowly lose health when in creosote.

**Comment by Natesky9** [comment]
There are alot of improvements that could be made to the brewing system. This seems like a neat idea, but it would be a novelty item.

If there were more to this, then definitely

**Comment by liach** [comment]
This will probably wait until the addition of creosote back as a fluid.
