### ISSUE TITLE
Error after Building from Source

### ISSUE THREAD

**Issue by JackTerok** [Railcraft/Railcraft#1107]
Hi.

So I was trying to Build Railcraft from Source and after a bit of trial and error that finally worked.
But then when I tried to launch it minecraft crashed.
Here is the crash log:  http://pastebin.com/a3dtTCvz
THX

**Comment by liach** [comment]
This aims to prevent redistribution. More questions welcome.

**Comment by JackTerok** [comment]
If it's for preventing redistribution whats the point in having a guide to build it yourself.

And in addition is there any way to get something like daily builds so i am not stuck with the version from last year. THX

**Comment by liach** [comment]
Good point. To play, add mods to `/run/mods` directory and run `./gradlew setupDevWorkspace runClient` in (git) bash.

**Comment by liach** [comment]
This will be left open for other people.

**Comment by JackTerok** [comment]
Sorry to ask again. With your additions, a client pops up to test. But that still doesn't give me the jar to put in my modpack. Am I doing something wrong here?

**Comment by liach** [comment]
You are doing it right. What are you going to do with the modpack? Do you just play or you want to give it to some other people? Ask other people to do the same in order to play.

**Comment by JackTerok** [comment]
I have a Modpack and a Server on which I play with some friends.

**Comment by liach** [comment]
Unfortunately, you need to ask all your friends to do so. For the server, you can launch in almost the same steps as the client, but change `runClient` to `runServer`.

**Comment by JackTerok** [comment]
That's not really an option. Isn't there any way to get an version that is newer than the one on the official website. I don't need to build it myself. just want an newer version.

**Comment by liach** [comment]
https://www.patreon.com/CovertJaguar See beta access

**Comment by Joshwoo70** [comment]
liach there is an easier solution is to change the code at L#151 of Railcraft.java. quite simple.. just change it to a FMLLog.bigwarning. but i am not sure if CJ would like it... in my opinion this is a very bad way to do so... just in code wise to tell the use he is running a unofficial build. instead of just crashing the whole thing... 

If you do the following and it gets out... we might cause a lot of drama.

**Comment by JackTerok** [comment]
Joshwoo70 Thank you for your help.

**Comment by CovertJaguar** [comment]
The instructions for building are intended for people in development environments.
