### ISSUE TITLE
 [Suggestion] Creative Steam Locomotives

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#1108]
I like the Perpetuum Loco which is a creative version of Electric Locomotive. So I guess to add a creative version of Steam Locomotive.

**Idea:**
When user putting creative Steam Locomotive, it has already full-filled water and fuel, so user just only select _Running_ to start the steam or _Idle_ to just burning to eliminate steam only. If user click _Shutdown_, steam locomotive will stop burning **but** still full-filled water and fuel.

**Comment by Ristellise** [comment]
but why?

**Comment by CovertJaguar** [comment]
The Perpetuum locomotive is not an Electric Locomotive. It just never had a new model created for it.
