### ISSUE TITLE
Cart /w chest name bug.

### ISSUE THREAD

**Issue by adegarimore** [Railcraft/Railcraft#1110]
Railcraft: 1.10.2-10.0.1
Minecraft: 1.10.2
Forge: 2254

We're skipping to the "steps to reproduce" section
1. Place a vanilla cart on a track.
2. Place a chest in the cart.
3. break the cart with by hand or with a tool.
4. Observe that the chest fall out of the minecrart (we're doing good so far)
4. Pickup cart
5. Observe that the cart is called "Minecrart with Chest" (uhh.. what)
6 Place the empty minecart on the tracks
7. Observe  that the (empty) minecart has a big "Minecart with Chest" nameplate over it.

http://i.imgur.com/eY8LO7A.png

**Comment by liach** [comment]
"Place a chest in the cart"
Well, you cannot do this in either vanilla minecraft or Railcraft. This sounds impossible.

**Comment by adegarimore** [comment]
hmm ... okay. what's the railcraft way of making a minecrart with a chest? Maybe it's a different mod's bug.

**Comment by liach** [comment]
It is to craft a "chest cart" item. You should provide a mod list so we can investigate.

**Comment by adegarimore** [comment]
will do. I will also do a little testing to see if there is any more information I can provide

**Comment by Ristellise** [comment]
Thats quark... probably best @vazkii

**Comment by adegarimore** [comment]
Modlist: https://minecraft.curseforge.com/projects/unabridged
Will remove quark and see is issue still exists

**Comment by adegarimore** [comment]
After removing quark, this is no longer an issue. Sorry for taking up your time.

**Comment by liach** [comment]
https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/tweaks/feature/MinecartInteraction.java

**Comment by CovertJaguar** [comment]
Railcraft intersects the ItemMinecart usage to replace the vanilla cart with the Railcraft one. If you placed it some other way, it will not get replaced with the Railcraft version. I don't know about the naming though. I don't think that can be Railcraft related since the Railcraft cart never gets placed.

**Comment by liach** [comment]
@CovertJaguar Can replacement be done in a way similar to Forge replacing EntityItem with custom item entities?

**Comment by CovertJaguar** [comment]
Not that I'm aware. I used to replace the Item object with my own version but that stopped working in 1.7.
