### ISSUE TITLE
Command issues with Vanilla Command Blocks

### ISSUE THREAD

**Issue by Phonavis** [Railcraft/Railcraft#1111]
Was attempting to use pre-generator in FTB Beyond, Found this - https://www.youtube.com/watch?v=7WSMgOVsnCU, According to comments it has issues with railcraft. Someone thinks it's do to tweaks with the cart item, said person is in the comments section of the video

I was curious if there was a way to have a work-around for this, as I imagine this same issue may be had with other command blocks considering command blocks are commonly used.

**Comment by CovertJaguar** [comment]
I intercept cart item usage and have it spawn my version of the minecart. I don't really understand the script enough to say how that affects it, it may be as simple as replacing the entity id with my cart version.

**Comment by liach** [comment]
Referring #1110, we need to replace carts in a way similar to this: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java#L36-L60

**Comment by liach** [comment]
Related link: https://www.reddit.com/r/feedthebeast/comments/5dpf1g/8000_x_8000_pregen_save_dw20_1102/da6k8du/

**Comment by liach** [comment]
@CovertJaguar I will try to write another replacement like that of forge item entity replacement. This should fix the bugs.

**Comment by liach** [comment]
So the issue is on command block minecarts. The video comments say so.

**Comment by liach** [comment]
@UnstableCodeScarlet Please provide a crash report.

**Comment by liach** [comment]
The biggest issue is that why do you still use command blocks when you can use mods at a lower cost of memory and with a higher efficiency?

**Comment by liach** [comment]
Anyways I will try to reproduce it in the dev env.

**Comment by liach** [comment]
@CovertJaguar After testing, I found that the issue is that minecarts explode when there are too many. The command generates a lot of command block minecarts riding one command block minecart.

**Comment by liach** [comment]
Turned out that this explosion is to prevent glitches that too many minecarts are stacking each other, so this behavior will be kept and such commands will not work for now. You should never use command blocks in a modpack (such a stupid idea!) but use mods instead. That's why it explodes and drop a lot of carts.

**Comment by CovertJaguar** [comment]
We will make the explosion code ignore command minecarts. Since players can't normally acquire them there is no danger of them using them to crash to the server.
