### ISSUE TITLE
New Track Kit: Delay Track

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#1112]
The Delay Track is a track that holds a cart/train for period of time, say five seconds, before releasing it. This would make it simple to add spacing between carts/trains for sorting purposes and other things.

**Comment by Generalcamo** [comment]
Couldn't this just be achieved with a holding track connected to a redstone circuit containing a clock? That could also be influenced with routing detectors.

**Comment by Forecaster** [comment]
That requires an external timing mechanism though, and you might not always have access to a convenient compact clock

**Comment by liach** [comment]
@Forecaster Just use ticks. And this can be non-ticking.

**Comment by Forecaster** [comment]
...what

@liach I'm not talking about code. I have no idea what you're talking about.

**Comment by liach** [comment]
So the textures are done, right?

**Comment by Generalcamo** [comment]
Nearly. Here is the current WIP:
![delay_preview](https://cloud.githubusercontent.com/assets/1779662/24168730/a2546f92-0e51-11e7-8ca4-7df9d0886485.png)

**Comment by Generalcamo** [comment]
Some Specifics:

- Current discussed implementation has a GUI, similar to the Priming Track, that would allow for a setting of the Delay time.
- Currently assuming that the Delay Track will -IGNORE- Locomotives and Trains, and only touch Single Cars that are not engines.
- Track will require a Redstone Signal to operate, but will automatically handle the delay and launching of cars.

**Comment by CovertJaguar** [comment]
Rather than ignore trains, it should probably only apply to trains. All carts are considered to be part of a train, so you get single cart handling for free. When it releases a train, it lets the entire train pass before resetting.

The rest sounds good.

**Comment by liach** [comment]
Uh, my opinion on better interlocking is to introduce linked signal blocks instead.

**Comment by liach** [comment]
Closing as I implemented this. Its default delay time is 5 seconds.
