### ISSUE TITLE
Minecraft random just stop deciding to launch

### ISSUE THREAD

**Issue by Dwarfy-Dwarftins** [Railcraft/Railcraft#1113]
https://github.com/MinecraftForge/MinecraftForge/issues/3791
Can someone help tell me whats wrong just all of a sudden stoped working and dont know why.

**Comment by Ristellise** [comment]
sorry tehnut has alreadr replied to your comment.. it is not railcraft fault... chdck over at that link

**Comment by adrwa** [comment]
Why are you asking in railcraft? the mod thats erroring is clearly [this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2157350-1-7-2-1-7-10-v1-0-2-myths-and-monsters-mod-check) mod, dont spam random mods that have nothing to do with the error

**Comment by Ristellise** [comment]
thanks Coded :)

**Comment by Dwarfy-Dwarftins** [comment]
hey im sorry im asking on railcraft i really just dont know who to ask and cant get help. can you guys please tell me where i should go. i dont know what the problem is or how to fix it and i just really need help

**Comment by Dwarfy-Dwarftins** [comment]
im not trying to spam random mods or anything i really dont know what mod or whats causing the problem and im just hoping someone would be nice enough to help someone in need im sorry if ive annoyed anyone but thats not my intention

**Comment by Daomephsta** [comment]
@Dwarfy-Dwarftins 
com.hoopawolf.mam.**MythsAndMonstersMod**

**Comment by Dwarfy-Dwarftins** [comment]
thank you. much appreciated
