### ISSUE TITLE
Infinite XP from Firestone Ore

### ISSUE THREAD

**Issue by phit** [Railcraft/Railcraft#1114]
Mining the firestone ore gives you the ore and experience, you can just keep placing it down to get more experience. I know the whole firestone thing isn't really done yet, but I would be great if it wouldn't drop experience.

Railcraft_1.10.2-10.0.1
Modpack: FTB Beyond 1.1.0

**Comment by Generalcamo** [comment]
Checked the code, this is confirmed. This is due to an oversight in how it was coded.
