### ISSUE TITLE
Implement Red Sand Coke Oven variant

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1121]
As the title says, implement a Coke Oven that uses Red Sand instead of normal Sand.

There are two ideas I have for this:

1. Make it purely cosmetic. A coke oven with a different texture.
2. Give it slightly different properties. Assuming the Red Sand contains Iron to cause the Redness, we could say that the Kiln made from Red Sand could handle higher temperatures than a Kiln made from Normal Sand. This would cause Coke and Charcoal to be created faster, but at the cost of some Creosote.

One is simple but boring. Two is more complicated, but since Mesa Biomes are relatively rare compared to Beaches, Rivers, Oceans, and Deserts, it would bring an incentive to explore to find some if its properties are desired.

**Comment by Ristellise** [comment]
I vote for the second... a faster coke over is nice

**Comment by Vexatos** [comment]
There is no reason to make it any faster. Just build a second one. Wouldn't make sense, either.

**Comment by Generalcamo** [comment]
Besides space efficiency, right? Otherwise there would be no reason to build a High Pressure Boiler when you can just build more Low Pressure Boilers.

**Comment by transcondriver** [comment]
Opinion: I'm okay with a simple cosmetic variant.

**Comment by liach** [comment]
The second one needs a recipe overhaul, so I support the first one.

**Comment by liach** [comment]
Added. It can mix and match with regular coke oven bricks.
