### ISSUE TITLE
Manual Rolling Machine

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1125]
The Manual Rolling Machine is planned to be a primitive machine that can perform all the tasks that the RF-powered Rolling Machine can do. However, there are some restrictions:

- Sided input/output will not be supported (No easy automation)
- Will be slower
- Will require some sort of manual power

This will allow players to independently tech up in Railcraft without reliance on other RF mods like TeamCoFH's mods. Later this will allow for machinery to move off RF in favor of Railcraft Charge.

**Comment by CovertJaguar** [comment]
Closed by a408da1f967e2994b6f159e9bd3e7b7a5595c97c
