### ISSUE TITLE
Add Bronze (Copper + Tin Alloy)

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1126]
Railcraft currently has Tin and Copper, adding Bronze Alloy will be trivial to do as a result.

This could be used in some crafting recipes. I'm thinking definitely a component for the Manual Rolling Machine ( #1125 ).

**Comment by Ristellise** [comment]
but crafting.. how to do so? Forestry way or we have to have a grinder to grind then down?

**Comment by liach** [comment]
probably 1/5 tin to copper ratio or some different ratios.

**Comment by Ristellise** [comment]
usuall ratio is 1 tin to 3 copper for forestry.

**Comment by Generalcamo** [comment]
1 Tin + 3 Copper is the current plan, yes. This is for consistency within other mods like Forestry, IC2, GregTech, and Thermal Expansion.

As for grinding requirements: That is being discussed currently. Very likely the Forestry Method will be the alternative recipe if you do not have machines for example if there is going to be crushing or smelting involved.

**Comment by Generalcamo** [comment]
I'll be working on the implementation of this.
