### ISSUE TITLE
Implement Nickel (Ore)

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1130]
Will be necessary for our plans with electricity and machinery. Look into providing Nickel Ore and its derivatives.

**Comment by Generalcamo** [comment]
Moved to 10.1, since we want most of the WorldGen in 10.1

**Comment by abculatter2** [comment]
Why not make nickel be a by-product of another ore, such as iron?

It's annoying how every mod adds a ton of its own ores simply because 'it's cool' or 'it's realistic'...

**Comment by Generalcamo** [comment]
Actually, making Nickel a by-product of Iron Ore is more realistic. Problem is though that this can cause issues with other mods. One of the ideas I had (for user intuitiveness and compatibility with other mods) was to have Nickel generate within Iron Ore Mines, so you would collect a lot of iron and some nickel.
