### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by Moobien** [Railcraft/Railcraft#1134]
No idea if any of these have been picked up on yet but in the last couple of versions for 1.10.2 I am noticing a few things not working/interacting or outright MIA.

Using latest RC version on curse.

1) Coke Oven and Blast Furnace, Iron and Steel Tanks: MIA
2) EnderIO Tank not transferring Creosote Oil into jars - no jars consumed
3) Creosote Oil missing texture.

Here is my Mods List.

ArchitectureCraft-1.7.0-mc1.10.2.jar
Auto-Sapling-Mod-1.10.2.jar
bdlib-1.12.2.14-mc1.10.2.jar
Bookshelf-1.10.2-1.3.0.282.jar
buildcraft-8.0.0-alpha-85.jar
ChunkAnimator-MC1.9.4-1.2 (1).jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.7.241-universal.jar
compactstorage-2.1-1.9.4.jar
CreativeCore v1.6.11 mc1.10.2.jar
damage-indicators-mod-by-torocraft-1.10.2.jar
dooglamoocitiesmod-1.10.2-1.1.2.jar
DoomlikeDungeons-1.8.13-MC1.10.jar
EnderCompass-1.9.x-1.2.3.2.jar
EnderCore-1.10.2-0.4.1.61-beta.jar
EnderIO-1.10.2-3.0.1.145_beta.jar
ExtraRails-1.10.2-1.1.1.jar
extrautils2-1.10.2-alpha-1.2.2.jar
ExtremeReactors-1.10.2-0.4.5.27.jar
FTBLib-1.10.2-3.4.5.jar
Futurepack-1.10.2-24.2.118.jar
GiacomosFoundry1.10.2-1.3.5.jar
hopperducts-mc1.9.4-1.4.8.jar
IDT-Beta2.0-16w44a.jar
ImmersiveEngineering-0.10-57.jar
industrialcraft-2-2.6.118-ex110.jar
Iron-Chests-Mod-1.10.2.jar
ItemPhysic Full 1.3.4 mc1.10.2.jar
jei_1.10.2-3.14.7.414.jar
malisiscore-1.10.2-4.2.10.jar
malisisdoors-1.10.2-5.1.8.jar
MCA-1.10.2-5.2.3-universal.jar
mcjtylib-1.10-1.9.9.jar
MCMultiPart-1.3.0-universal.jar
Mekanism-1.10.2.jar
Mo' Glowstone-1.1.0.jar
modnametooltip_1.10.2-1.6.0.jar
Norzeteus-Spaceextended-MC vers1.10.2(Forge)2.nd updt.jar
NotEnoughItems-1.10.2-2.1.2.175-universal.jar
omlib-1.10.2-3.0.0-61.jar
openmodularturrets-1.10.2-3.0.0-100.jar
Ore-Dictionary-Converter-Mod-1.10.2.jar
Pixelmon-1.10.2-5.0.1-universal.jar
platforms-1.10.0-1.2.9.jar
pressure-1.3.1.22-mc1.10.2.jar
quantumflux-1.9.4-2.0.7.jar
QuantumStorage-1.10.2-3.2.12.jar
RadixCore-1.10.2-2.1.3-universal.jar
Railcraft_1.10.2-10.0.1.jar
rapidform-1.10.2-1.4.jar
RebornCore-1.10.2-2.13.5.136-universal.jar
rftools-1.10-5.11.jar
RoguelikeDungeons-1.10.2-1.5.5.jar
RTG-1.10.2-4.1.2.2.jar
sentries-1.1.jar
ShadowMC-1.10.2-3.6.0.jar
shetiphiancore-1.10.0-3.3.8.jar
SimplyConveyors-1.4.2.jar
StevesCarts-1.10.2-2.1.0.45.jar
SuperCircuitMaker-1.0.4.jar
TechReborn-1.10.2-2.1.10.207-universal.jar
Tesla-1.10.2-1.2.1.42.jar
ThutCore-1.10.2.jar
Thuts-Elevator-1.10.2.jar
TreeChopper-1.10.2.jar
VeinMiner-0.33.2-1.9r561+335ca99.jar
Xaeros_Minimap_1.12.5_Forge_1.10.2.jar
YABBA-1.10.2-0.4.0.jar
zerocore-1.10.2-0.1.0.4.jar

**Comment by liach** [comment]
1. Multiblocks: Not ported yet. See #1017 
2. Creosote is not added back as a liquid yet. It is just an item.
3. So that creosote is not from Railcraft, thus "not railcraft".

**Comment by liach** [comment]
And check #1132 out.

**Comment by Moobien** [comment]
Ahhhh. With RC installed rails are uncraftable because the recipe wants creosote

**Comment by liach** [comment]
Cook coal in furnace to get 2 creosotes. Any more issue?

**Comment by Moobien** [comment]
Thanks for all the info :)
