### ISSUE TITLE
IC2 module issues

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1136]
Multiple issues with the IC2 module that should be fixed before the release:

- [x] IC2 Upgrades (Energy Storage, Transformer, Overclocker, etc.) cannot be added to the Energy Loader and Unloader (There is also no button showing which ones can be added, likely related)
- [x] Macerating Obsidian --> Crushed Obsidian doesn't work in default configs (requires outside modifications to support. Caused by a recipe conflict)
- [x] Look into adding an ore production line for poor ore
- [x] #993

**Comment by liach** [comment]
Related: #993

**Comment by Generalcamo** [comment]
A note here:
Lapotron Upgrade is getting replaced by an Energy Crystal Upgrade to match the current IC2 tiering. It will behave exactly the same though, just look different and have a different recipe. If IC2 classic is loaded, it will use the old Lapotron Upgrade.

**Comment by liach** [comment]
#1353

**Comment by liach** [comment]
Is this still the case? will investigate in 1.12.

**Comment by liach** [comment]
Fixed the last point.
