### ISSUE TITLE
Minecart Hopper Issues

### ISSUE THREAD

**Issue by Ristellise** [Railcraft/Railcraft#1137]
1. when you open the inventory of the hopper minecart, it displays its unlocalised names
2. Hopper carts do not pull items froma block above.. though this might be a vanilla bug, if would be nice if wd could reimplement it back.

**Comment by liach** [comment]
Probably I need to write it a little bit.

**Comment by liach** [comment]
Number one is fixed by CovertJaguar/Railcraft-Localization#327, right?

> Hopper carts do not pull items froma block above.. 

Do you mean picking items through a block or picking items through an inventory right overhead?

**Comment by Ristellise** [comment]
picking through a block. this is probably a oversigh by mojang but it is quite useful for hiddeb piston doors.

**Comment by Natesky9** [comment]
iirc, this was changed in 1.11 where hopper minecarts could now pick up from more than a block away. They can pick up through soul sand and tilled soil and anything less than a full block

**Comment by Ristellise** [comment]
it has all along been in the game since they were introduced in the redstone update.
