### ISSUE TITLE
[1.10.2] IC2 Feeder Crash (and suggestions)

### ISSUE THREAD

**Issue by LawsOfScience** [Railcraft/Railcraft#1142]
*[MC 1.10.2, Ver 10.0.1]
Hey, I'm sure this has already been brought up before, but I'm bringing it up again.

Whenever I place down an IC2 Feeder, my game instantly crashes and I cannot re-enter that world. However, installing IC2 fixes this. If this crash was intended, then leave this alone I guess. Also, I would like to see the routing and signaling stuff put back in, that was one of my favorite parts in the older versions.

Thanks :)

**Comment by Generalcamo** [comment]
How are you placing an IC2 Feeder without IC2 installed? That recipe shouldn't be registered in the first place.

Of course it crashes since it relies on the IC2 API to work properly.

**Comment by liach** [comment]
routing and signals will be in next version, 10.2

**Comment by CovertJaguar** [comment]
I may have derped a bit on the Feeders. I cut a few corners with them. Like not disabling the recipe.
