### ISSUE TITLE
Colorable laser track

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1143]
www.railcraft.info/forum/?mingleforumaction=viewtopic&t=823.0#postid-3086

**Comment by CovertJaguar** [comment]
That is not a simple thing to implement.

**Comment by liach** [comment]
You mean new textures?

**Comment by CovertJaguar** [comment]
No, I mean I had planned to make the Force track a Block without a tile entity. You'd need to have a Tile Entity to store the color data.

**Comment by liach** [comment]
why?

**Comment by CovertJaguar** [comment]
Because tracks use the metadata for shape information.

**Comment by liach** [comment]
oh. non-ticking tes should not be too bad, I guess.

**Comment by abculatter2** [comment]
Is it a significant concern to simply use 16 block IDs?

**Comment by CovertJaguar** [comment]
Yes, we only have 4k, some big packs hit that.

**Comment by liach** [comment]
Hmm, recently vanilla Minecraft team said that they encourage to use more block ids for different block types, instead of using metadata for different colors, etc.

**Comment by CovertJaguar** [comment]
Yes, well Mojang still only officially supports 256 block ids, so they are not a reliable source.

**Comment by liach** [comment]
@CovertJaguar Don't we have a tile for laser tracks already?

**Comment by CovertJaguar** [comment]
It's not the big of a deal I guess. I just have to factor it into the update.

**Comment by mainrs** [comment]
Wouldn't 1.13 solve this issue since there won't be any block id limitations and metadata usage isn't encouraged anymore?

**Comment by liach** [comment]
@SirWindfield No. We still need to save block state onto disk in forms of meta. If they really allows storing any block state, then it may help.

**Comment by liach** [comment]
Fixed in 517f3d0cef8bd1b77287eb4777e61c09b949a52e. It actually supports full rgb color.
