### ISSUE TITLE
Look into adding mod support for Ore Mines

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1147]
Currently, our ore mines generate using Railcraft and Vanilla ores. There are however some other mods that include their own metals that could benefit from this type of generation. These include things like:

- Uranium Ore (IC2)
- Alumin(i)um Ore (Various)
- Quick Silver (Thaumcraft)
- Zinc Ore (Various)

We should look into things like this in the future.

**Comment by bookerthegeek** [comment]
God thank you. A simple config line for mine name, and th ore to spawn (optionally also somehow to include other sort of poor ore or dense ore versions or said ore), along with the y level would be amazing.

**Comment by MauveCloud** [comment]
> Aluminu(i)m Ore (Various)

I've seen it spelled "aluminum" or "aluminium", but I don't think I had seen it spelled "aluminuim" before, as this would suggest. 😆

**Comment by bookerthegeek** [comment]
As most mods (honestly all mods other then GregTech) spell it ```Aluminum``` I would suggest going with the traditional North American spelling.

**Comment by Generalcamo** [comment]
...without going into a major argument about something like that, most mods actually use Aluminium in non-NA localization. So we will just do that.

**Comment by liach** [comment]
hey, since CJ lives in the US, so US localization. Change only in language file.

**Comment by CovertJaguar** [comment]
There are no plans to add Aluminium, Aluminum, or any other Alums to Railcraft. The point was to be able to generate mines for other mod's blocks.

**Comment by liach** [comment]
@CovertJaguar Isn't this done yet?

**Comment by CovertJaguar** [comment]
Yes
