### ISSUE TITLE
Quarried Cobblestone into Quarried Stone instead of Quarried Block.

### ISSUE THREAD

**Issue by TCloudGaming** [Railcraft/Railcraft#1151]
This is obviously a very small thing, but it would be nice if the Quarried Cobblestone would be smelted into Quarried Stone to make it more easily obtainable.

**Comment by CovertJaguar** [comment]
@liach marking something as an open project is my prerogative, please stop. -.-

@Generalcamo I'll let you sort this out.

**Comment by Generalcamo** [comment]
Duplicate of #1103
