### ISSUE TITLE
Trackman villagers harvest farmland like farmers do

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1152]
![2017-04-18_00 01 20](https://cloud.githubusercontent.com/assets/7806504/25118291/76ca79aa-23ca-11e7-95dd-3379e8a29e86.png)

**Comment by CovertJaguar** [comment]
I don't think we have control over this atm. @cpw was talking about adding some AI support to the API, but I don't know if it ever went anywhere.

**Comment by liach** [comment]
Then it is a forge bug: Villagers are supposed to check their profession before farming.
