### ISSUE TITLE
Add a real recipe for the Charge Trap

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1155]
The Charge Trap is currently using a temporary recipe. It needs a better recipe.

**Comment by CovertJaguar** [comment]
Eventually it will require a battery I think.

**Comment by liach** [comment]
@CovertJaguar I think you can solve this with your newly added items, right?

**Comment by CovertJaguar** [comment]
I guess a terminal works, I was kind of assuming battery still though, but maybe that's too expensive?
