### ISSUE TITLE
Question: Sulfur/Saltpeter generation

### ISSUE THREAD

**Issue by ReTeYeZ** [Railcraft/Railcraft#1157]
I've enabled the wolrd module and the generation of the ores in the config but after some testing I couldn't find neither of those. JER doesn't show any generation statistics aswell.
So are they actually supposed to generate, event tho they dont show up in JER?
Just wanna be sure before I start a new world.

**Comment by CovertJaguar** [comment]
They both have very specific generation rules, so you aren't like to find them unless you know where to look.

Saltpeter spawns in dry sandy biomes, a layer under the surface, with some sprinkled on the surface for easy identification.

Sulfur spawns in mountainous biomes around y-level 10, but only next to lava.
