### ISSUE TITLE
10.1.0 Conflict with Mod: BlockDrops v1.1.1

### ISSUE THREAD

**Issue by Y0ungSandwich** [Railcraft/Railcraft#1162]
https://pastebin.com/S2hvzdkK

**Comment by liach** [comment]
Does this crash only happen when Railcraft is installed?

**Comment by Y0ungSandwich** [comment]
Only when this version is installed.  Previous versions work fine.

**Comment by liach** [comment]
ignore my last comment. So this happens when both mods are installed in a fresh environment, right?

**Comment by Y0ungSandwich** [comment]
This is happening during a pack update of Mech &  Magic on ATLauncher.  I'm willing to bet JEI is a middle man culprit here.

**Comment by liach** [comment]
This is related to Railcraft's creative tab handling by blocks, which add null entries to the list... That is my best guess. @CovertJaguar Please take a look.

**Comment by CovertJaguar** [comment]
I've run a test over all my blocks, and none added a null with default settings. Are you running any config changes?

**Comment by D3nnis3n** [comment]
I use this mod with railcraft 10.1.1 and 120 other mods and got no crash.

**Comment by liach** [comment]
Removing "mod compatibility" since it's reported to happen in pure Railcraft.

**Comment by Y0ungSandwich** [comment]
I can't reproduce without block drops. Only things I have disabled are poor ores.
