### ISSUE TITLE
Railcraft crash: TileCokeOven cannot be cast to Reika.DragonAPI.Base.TileEntityBase

### ISSUE THREAD

**Issue by UltraVolta425** [Railcraft/Railcraft#1163]
Hey

I recently built Reika's Reactorcraft's Fusion Reactor, and as soon as everything was set up properly and the plasma was running, I continued working in my singleplayer map. But then I got a crash, and since then I can't start up the game anymore. As soon as I select my singleplayer map (so the game does start up, but the crash starts when I load my map) it crashes with the following crash report:

`https://pastebin.com/j7UEWGz3`

Would you please be so kind as to look at it please?
I am indeed running 1.7.10, thanks for pointing that out, GeneralCamo

**Comment by Generalcamo** [comment]
You are running 1.7.10, correct?

**Comment by UltraVolta425** [comment]
How silly of me not to mention this.
Yes, I am running 1.7.10. I'll update the post at once. :)

2017-04-21 23:56 GMT+02:00 Cody Brittain <notifications@github.com>:

**Comment by CovertJaguar** [comment]
This is because of bad instance checking on tile entities in Dragon API, nothing I can do from my end.
