### ISSUE TITLE
Anchor and Anchor cart ?  RF ？ that is a very useful?

### ISSUE THREAD

**Issue by m1696309** [Railcraft/Railcraft#1164]
10.1.1 Very good！！！

which version will add Anchor and Anchor cart ?   that is a very useful?

whether consider make a block for  RF energy to RC power conversion？

**Comment by CovertJaguar** [comment]
Look at the milestones under issues.

**Comment by liach** [comment]
呃呵... 有问题你用中文问好了。各种机器因为渲染比较困难，暂时没有加回来，虽然其机制还在源码中。单方块机器会更早加入，比如锚、辊压机和饲育站。

**Comment by liach** [comment]
By the way, another point of concern is that CoFH might make some overpowered power converter, destroying the modding community further.

**Comment by m1696309** [comment]
Liach 谢谢,我英文不好，我也是做软件的,不知道能不能帮上什么忙，以前做过简单的插件！

**Comment by liach** [comment]
推荐你耐心等，反正不会弃坑的

**Comment by m1696309** [comment]
OK
