### ISSUE TITLE
(CRASH) "Ticking Entity" after trading with Railcraft Villager

### ISSUE THREAD

**Issue by Vaygrim** [Railcraft/Railcraft#1167]
Minecraft 1.10.2 / Railcraft 10,1.1 / Forge 2281

User was performing a trade with a Railcraft villager. Mid-trade, server crashes due to a "Ticking Entity" error. [https://github.com/Vaygrim/CoopLife/issues/7](https://github.com/Vaygrim/CoopLife/issues/7)

First time it has happened, doesn't _seem_ common?

**Comment by liach** [comment]
What items did you disable?

**Comment by Vaygrim** [comment]
Only two things disabled are "Bottle of Creosote" and "Bucket of Creosote". Had to disable those as we were getting a crash when users right clicked either item, to dump them out into the world. (A bug that I saw previously reported here.)

**Comment by Vaygrim** [comment]
Oh actually that's not true.. I've also got the Signals module disabled, but that's the whole module. We weren't sure how long it was going to take for those to be re-added to Railcraft, and opt'ed to include another mod that added those same blocks. So .. disabled to prevent redundancy.

**Comment by liach** [comment]
They are currently available. You can use the signal boxes as signal lights; the routing system already works. However, keep this open because this is an issue with handling other things.
