### ISSUE TITLE
About the repost of RC

### ISSUE THREAD

**Issue by forestbat** [Railcraft/Railcraft#1168]
I'm an editor of an encyclopedia website www.mcmod.cn of Minecraft in China,because of the different between languages,and many people have trouble to use curse becuase of Google API--too slow in China,so we want to repost your mod to there for spreading RC better,and we still will direct players to curse as possible,do you agree to give us the authority?

**Comment by CovertJaguar** [comment]
@liach remind me what I said for you about this topic.

**Comment by liach** [comment]
@forestbat See #928: Download must be from curseforge as CovertJaguar would like. However, you can still link to the download page (the exact jar file, not the list), the download is always going to start in 3 seconds no matter whether the whole page is loaded (the page will appear in loading progress, but it will be fine)

为方便起见可以说中文。
吐槽一句，mcmod百科说电力伤害是药水效果，只是和原版水伤害一样的一个伤害来源而已

**Comment by CovertJaguar** [comment]
And there you have it.
