### ISSUE TITLE
About  recycle station.

### ISSUE THREAD

**Issue by m1696309** [Railcraft/Railcraft#1169]
关于列车回收站的建议：

既然有列车发车站，应该也有列车回收车站，有红石信号的列车回收车站把当前轨道上的列车回收进回收车站，如果是装了物品的拒绝回收。

Since there are train station, should also have a recycling station on the train, the train has a redstone signal recycling station in orbit in the current recovery into the recycling station, if it is installed items refused to recycling.

**Comment by CovertJaguar** [comment]
I don't even know what this means.

**Comment by liach** [comment]
He says train dispenser does not recycle trains. There should be a recycling station that only recycles empty container carts.

**Comment by CovertJaguar** [comment]
You mean the Cart Dispenser?
