### ISSUE TITLE
Creative Mode crash with certain blocks disabled

### ISSUE THREAD

**Issue by WesCook** [Railcraft/Railcraft#1171]
Railcraft will crash using the Creative Search tab (not the Railcraft tab) with certain blocks disabled.  From the testing I did, these blocks were the ones at fault:

    B:ore_dark_diamond=false
    B:ore_dark_emerald=false
    B:ore_dark_lapis=false
    B:ore_saltpeter=false
    B:ore_sulfur=false

Other ores can still be disabled safely.

May be related to #1162.

edit: Ah, almost forgot a crash log: https://pastebin.com/su0dktz2

**Comment by liach** [comment]
Merged into #1162. Thanks for the report!
