### ISSUE TITLE
Split Railcraft villager up into careers

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1180]
Currently, the Railcraft Villager's trades are contained in a single villager. This is inconsistent with the Vanilla behavior introduced in 1.8 (See: http://minecraft.gamepedia.com/Villager#Professions_and_careers and http://minecraft.gamepedia.com/Trading), and makes that single villager blatently overpowered compared to others.

We should look into splitting this up so we don't have a single villager with a long list of trades to grant. Some ideas:

- Trackman: Blue Overalls (Railworker)
  Sells Tracks, and Overalls at higher levels
- Cartman: Blue Overalls (Railworker)
  Sells Carts, and Locomotives at higher levels
- Alloyer: Black Robes (Blacksmith)
  Sells Bronze, Invar, and various parts made from them (gears)
- Steel Forger: Black Robes (Blacksmith)
  Sells Coke, Steel, and Steel Tools

Just some of the ideas that came to my mind so far. We could possibly do far more with this.

**Comment by liach** [comment]
#851 is why I moved the milestone.

**Comment by liach** [comment]
Done.
