### ISSUE TITLE
[Feature Request] Buffer Stop Tracks and Booster Tracks interaction

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1183]
If Booster Tracks have full, opaque blockside on one end, they apply a directed boost to halted cars.
I don't know if it's doable, but I think it would be pretty neat, if that also worked when there was a Buffer Stop Track instead of a full, opaque blockside on the end :)

**Comment by liach** [comment]
We'd make another track kit for this.

**Comment by MalkContent** [comment]
That seems excessive. If it doesn't work/is too unintuitive with the booster track, couldn't you make the buffer stop track apply the boost to the cart in front of it?

**Comment by liach** [comment]
The concepts are different.

**Comment by MalkContent** [comment]
What concepts?
Bottom line is that I didn't want this request to result in new items as long as it doesn't have to.

**Comment by liach** [comment]
booster track is not going to have a new model.

**Comment by MalkContent** [comment]
i am just confused now :/ my bad. not having a super smart day today

**Comment by CovertJaguar** [comment]
Changing the vanilla track behavior isn't possible. But we could certainly add it to the Booster Track Kit. I'm just not entirely sure why you'd want that though since the Locking Track does the exact same thing, without the buffer requirement.

**Comment by liach** [comment]
Another mode in booster track?

**Comment by MalkContent** [comment]
The Locking Track only stops as far as i managed with it.
I want to be able to send the cart away again at some point.
For that I currently have a booster track in front of a cobble block.
I just wanted to replace the cobble block with the buffer stop track, because it looks fancy.

**Comment by CovertJaguar** [comment]
Hit the Locking Track with a crowbar a few times.

**Comment by MalkContent** [comment]
oh, awesome, thanks! this makes this a non-issue, i guess.
close at will :)
