### ISSUE TITLE
Cart Uncrafting is bugged

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#1184]
Cannot uncraft Chest Cart, per @Neptunepink

**Comment by liach** [comment]
This affects many users IMO.

**Comment by liach** [comment]
Confirmed.

**Comment by liach** [comment]
![2017-04-30_00 32 10](https://cloud.githubusercontent.com/assets/7806504/25562571/24f98508-2d3e-11e7-90ae-8fe38ef0b893.png)
