### ISSUE TITLE
Crowbar-only enchants are applied to other tools

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1187]
Crowbar-only enchantments (Wrecking, Destruction, Implosion) are being applied to tools other than the Crowbar. This can be done through a Book + Anvil, or through an enchantment table.

As a Sidenote: I don't mind if Implosion could be applied to Swords (and Axes secondarily), but the others being applied to pickaxes is too much.

**Comment by liach** [comment]
Are you testing in creative or survival?

**Comment by liach** [comment]
Lowered priority because it affects only a minority of users, and it does not crash, etc.

**Comment by Generalcamo** [comment]
Survival Multiplayer, reported by several people on the official server.

**Comment by CovertJaguar** [comment]
Book + Anvil should not have been possible, unless something else is wrong. But that should fix the enchanting table issue.

I'd also be fine with allowing Implosion on other things, but I didn't do that here.
