### ISSUE TITLE
[1.10.2-10.1.1] Whistle of locomotive playing vanilla sound on server

### ISSUE THREAD

**Issue by Cassiobsk8** [Railcraft/Railcraft#1189]
In singleplayer everything works as it should, but when I'm playing on the server all the sounds of the whistles have been changed by these:
[https://www.youtube.com/watch?v=ICThDrUhe5A](url)
mod list: https://pastebin.com/k1PZdrRQ
I tried removing all the render mods like optifine and dynamicsurround but the problem continues

**Comment by Generalcamo** [comment]
I don't get a sound at all on SSP, haven't tried SMP.

**Comment by Generalcamo** [comment]
Confirmed working (on SSP) in 10.1.0, classifying this as a regression.

**Comment by liach** [comment]
That seems to be a forge bug caused by registry

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/3613

**Comment by liach** [comment]
Let's take a look again. We might fix it.

**Comment by CovertJaguar** [comment]
I triple checked that I build 10.1.2 correctly.

**Comment by liach** [comment]
So it's fixed and included in 10.1.2?

**Comment by CovertJaguar** [comment]
I didn't say it was fixed. I said I made sure I constructed the jar correctly. I could be an entirely different issue.

**Comment by liach** [comment]
@CovertJaguar Fixed by moving sounds.
