### ISSUE TITLE
[1.10.2-10.1.1] Immersive Engineering Conveyors can't insert into Railcraft Inventories

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1190]
Railcraft Inventories tested are the Powered Rolling Machine and the Item Loader.
I suspect this is because Railcraft is not using the ItemHandler capability, but this is purely because iirc IE only uses that one to interact with other inventories. I might be completely wrong about this.
The Item Unloader IS capable of emptying its items into/into the conveyors and i think it fits with the suspicion above.

**Comment by liach** [comment]
We use IInventory, the vanilla function.

**Comment by CovertJaguar** [comment]
And until Forge fixes the API properly, we will continue to use IInventory.

**Comment by mezz** [comment]
What needs to be fixed with the API?
Edit: nevermind, found it: https://github.com/MinecraftForge/MinecraftForge/issues/3344

**Comment by CovertJaguar** [comment]
Here is an example of a simplex noise cloud being used to generate saltpeter deposits:
https://github.com/CovertJaguar/Railcraft/blob/0280b6013ae6ba553a0729e7daad05e7a9a041dc/src/main/java/mods/railcraft/common/worldgen/WorldGenSaltpeter.java#L53-L53

**Comment by Generalcamo** [comment]
This isn't going to happen until 1.12 at the very least from the looks of it. Don't ask when Railcraft will be released for that version, it's looking like there will be another long wait for Forge like there was in the interim of 1.6 and 1.7.
