### ISSUE TITLE
[1.7.10] Tank carts + IC2 Universal Fluid Cells = Void Cart

### ISSUE THREAD

**Issue by Ghostlyr** [Railcraft/Railcraft#1191]
![noname](https://cloud.githubusercontent.com/assets/8511068/25664135/8693ac8a-303b-11e7-8eff-0354afc504d8.gif)
Steps to reproduce:
1. Place tank cart
2. Putin any universal fluid cell from ic2
3. Wait for the full filling and cry

MC: 1.7.10
Forge: 1644
Railcraft: 9.12.2.0
IC2exp: build 827

**Comment by liach** [comment]
Not anymore in 1.10. We've decided to drop 1.7 support.
