### ISSUE TITLE
[Request] Add support for crafttweaker

### ISSUE THREAD

**Issue by Skillotic0703** [Railcraft/Railcraft#1193]
It would be cool if we could change rolling machine recipes so I would like you to add support for crafttweaker please!

**Comment by liach** [comment]
Use modtweaker mod instead.

**Comment by Ommina** [comment]
Except ModTweaker doesn't have Railcraft support, so the request still stands.

**Comment by liach** [comment]
@Ommina https://github.com/jaredlll08/ModTweaker#supported-mods It claims to support Railcraft, so please move to jaredlll08/ModTweaker#478. Thank you!

**Comment by bookerthegeek** [comment]
@liach I should probably update that page...

Afaik, http://minetweaker3.powerofbytes.com/wiki/ModTweaker is the list broken down between minecraft version.

**Comment by TheDeviantCrafter** [comment]
ModTweaker does not support Railcraft in 1.12. A feature request has been made [here](https://github.com/jaredlll08/ModTweaker/issues/704).

**Comment by liach** [comment]
Uh.. Take a look at issue #1610 as well.

**Comment by Draskh** [comment]
Are the machine recipes also registered in post?

**Comment by liach** [comment]
we will gradually move them to init.

**Comment by CovertJaguar** [comment]
Generally only recipes that use items from other mods are in POST. Everything else should already be INIT.
