### ISSUE TITLE
Strange syncing issues with Widgets

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1195]
I've been doing some testing locally with Electric Locomotives. However, when I disconnect the power going to the Locomotive and open its GUI, it stops long before it appears to run out of charge (Around 24% charge). Closing and reopening the GUI shows the energy correctly at 0%.

I've noticed the same with the Powered Rolling Machine, except with RF instead of Charge.

ADDENDUM: This appear to affect all widgets, judging from #1194. This happens locally and over servers.

**Comment by liach** [comment]
#1194 ?

**Comment by CovertJaguar** [comment]
@liach very likely the same issue

**Comment by Generalcamo** [comment]
Thinking all the widgets are broken then?

**Comment by liach** [comment]
@CovertJaguar I suggest raising priority to medium because this is rather often and disturbing.

**Comment by CovertJaguar** [comment]
I believe the widgets generally use the same code for net sync, and I recall I did have to rewrite it for 1.10.
