### ISSUE TITLE
high-speed track totally same as vanilla boost track in speed[1.10.2]

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [Railcraft/Railcraft#1202]
I used railcraft few years.
when it been 1.7.10 version.
its high speed track much more faster than vanilla redstone boost track.

but now,i'm using 1.10.2,tried so many forge version.
from Railcraft 10.0.0 to Railcraft 10.1.2 - MC 1.10.2
I have try them all
and still get a slow speed track same as vanilla boost track

and trust me i'm very good as rail worker(at least 1.7.10)
I'm think should be a bug?

**Comment by liach** [comment]
能不能提供一个gif?
Can you provide a gif for this issue?
Ref #973

**Comment by xiaoxufeiji1a** [comment]
can i use Utube?
I'm going to make it
我可以使用Utube 视频吗？

**Comment by liach** [comment]
当然可以用Youtube
Of course you can use Youtube

**Comment by xiaoxufeiji1a** [comment]
好的 请给我几分钟时间

**Comment by xiaoxufeiji1a** [comment]
https://youtu.be/B0P-r_skFJk
你可以看到  原版轨道和高速轨道完全相同
there are all the same speed between RCmod and vanilla track
****
and here is 1.7.10 highspeed: https://youtu.be/jD8rjwYrKAU
1.7.10 is so fast and normal

**Comment by liach** [comment]
第一个视频里面高速轨道方向好像反了

**Comment by liach** [comment]
然而是我看错了

**Comment by xiaoxufeiji1a** [comment]
哈哈 ....那这应该是个BUG吧...
希望能尽快修复

**Comment by CovertJaguar** [comment]
Sure seemed to work in my testing. hmm.

**Comment by xiaoxufeiji1a** [comment]
hope that could be release early

**Comment by liach** [comment]
已经修复，将在10.2中放出

**Comment by xiaoxufeiji1a** [comment]
效率很高，点赞！

**Comment by edisonkendrick** [comment]
@liach This issue has not been solved for me!! I've tried the new version already...

**Comment by liach** [comment]
The new version will be 10.2.0 instead of 10.1.2. It is not completed yet.
