### ISSUE TITLE
Trains locking/idle not serialized?

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1204]
Locomotives have a "one of my carts is being held by a locking track, so I'll idle even though my button says I'm running" variable, right? It's probably not being serialized.

1. Locomotive at lava refill station, one of the tank carts being held. Locomotive is chill.
2. Visit nether for cart to grab more lava
3. Return, locomotive is not chill & is all sproinged out.

**Comment by CovertJaguar** [comment]
"sproinged out" that's a new one.

**Comment by CovertJaguar** [comment]
I think the issue is that I'm not telling the train that it is locked in this case.

**Comment by CovertJaguar** [comment]
However, the code looks like it should be handling this correctly. I may need to use the debugger.

**Comment by purpleposeidon** [comment]
I may also be wrong! We'll see if I can get it happening again.

**Comment by liach** [comment]
@purpleposeidon Is it still happening?

**Comment by purpleposeidon** [comment]
I haven't noticed it recently.

**Comment by liach** [comment]
#1195?

**Comment by liach** [comment]
I think it exists, since no track kit calls `TileEntity#markDirty` at all!

**Comment by liach** [comment]
I've opened a pull to debug. Hope it works!

**Comment by liach** [comment]
This one is actually more similar to #657.

**Comment by liach** [comment]
I have confirmed that train states are indeed not serialized.
