### ISSUE TITLE
[1.10.2-10.1.2] Recipes containing creosote containers don't allow buckets of creosote

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1207]
I glanced at the code a bit and I assume that the recipes are intended to accept them. Tried to find why the don't, but didn't find the end of that rabbithole.
Best guess: Bucket gets added only after the recipes are set up.

**Comment by liach** [comment]
That is intentional. CJ opened a pull request to forge but was not accepted because he failed to maintain it.

**Comment by MalkContent** [comment]
oh. strange. okay then :) i mean i tried this in a vanilla + railcraft only setting with the universal creosote bucket that was added by rc so i'm genuinely curious as to what the issue is.

**Comment by liach** [comment]
The issue is with fluid containers not recognized in crafting recipe.

**Comment by Generalcamo** [comment]
There are some plans to "fix" this with our own implementation of the prior pull request. I'm sure CovertJaguar can explain more though.

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3332

**Comment by Generalcamo** [comment]
Affects Railcraft recipes as well. This is a bit more important than I thought.

**Comment by liach** [comment]
We can create a custom recipes class for this for now.

**Comment by liach** [comment]
Fixed in that commit above.
