### ISSUE TITLE
Destruction not picky enough

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1223]
Breaking a tall grass block w/ a destruction crowbar probably shouldn't break tracks.

Also it'd be nice if it only broke like connected tracks of the same type. Maybe don't go through junctions or kits.

**Comment by liach** [comment]
@CovertJaguar Should we add a key binding for that careful check (like a mode switch key)?

**Comment by CovertJaguar** [comment]
Naw, I'd just only break _like_ blocks.

**Comment by liach** [comment]
How about add modes that have block state check?

**Comment by CovertJaguar** [comment]
I don't really see why we need a mode at all.
