### ISSUE TITLE
Feeder unit stops accepting EU even when it should be

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1224]

**Comment by purpleposeidon** [comment]
Cycling redstone does not make it start converting power again.

**Comment by sparhawk765** [comment]
Not sure if this is related but I have the same problem in FTB Beyond, I have my base chunkloaded via FTBUtilities but when I logout or move dimensions the feeder seems to stop, and turning it off and on again (lever) does nothing. Breaking it and putting it back down on the other hand seems to get it working again. Other machines at the base seems to work fine so the chunks seems to be loaded at least. FTB Beyond 1.8.0 (Railcraft_1.10.2-10.1.2.jar, FTBUtilities-1.1x-3.6.5.jar)

**Comment by CovertJaguar** [comment]
I've added some debug information to the next build, but have to wait for it get on the server to use it.

**Comment by liach** [comment]
I will try to test it on the patron server.

**Comment by CovertJaguar** [comment]
This fix is incomplete. Nodes that already exist are also rejected in registerNode and that needs to be modify somehow too.
