### ISSUE TITLE
Messenger Track Kit Question

### ISSUE THREAD

**Issue by jjc54** [Railcraft/Railcraft#1225]
Hi, I was just wondering if there is a specific parameter that I need to enter to get the messenger track kit to display text. I'm not a coder so I'm unsure exactly what "raw json message" means and I've tried a bit of text from online but I cannot get it to work. Could you just post an example of what saying hello would look like using the track kit? Thanks for any help!

**Comment by CovertJaguar** [comment]
It uses the same format as the Minecraft /title and /tellraw commands, there are plenty of example online.
Let me know if you need more.

```
/rc track msg ["Hello World!"]
/rc track msg [{"text":"Hello World!","color":"gold"}]
```

Some helpful links:
http://minecraft.gamepedia.com/Commands#Raw_JSON_text
https://www.minecraftjson.com/

**Comment by Generalcamo** [comment]
Should get a wiki page up for this in the near future. Keeping this issue open until that's done.

**Comment by liach** [comment]
Well, the dokuwiki is not very convenient to edit compared to the ftb one (ftb wiki looks fine but the modpack is horrible)

**Comment by brisingraerowing** [comment]
There's also [this](http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-9-json-text-component-for-tellraw-title-books), which has a lot of good info.

**Comment by jjc54** [comment]
eh I'll check that out. This is a lot to learn just to type welcome to x station though.

**Comment by jjc54** [comment]
I do really appreciate the example above though, it's exactly what I needed!

**Comment by liach** [comment]
Guess this is fine then.

**Comment by CovertJaguar** [comment]
Dokuwiki is fine.
