### ISSUE TITLE
[petition]Could U build a little version for fixed TrackSpeed?

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [Railcraft/Railcraft#1230]
sorry for ask.that's a petition
I really like Railcraft,and I really need high speed ASAP
but I guess that new version might be release in long time.
I really want to build a high speed railway 😄

**Comment by liach** [comment]
Unfortunately not... Railcraft is like Harvestcraft which pre-releases (betas) are only available to patrons. We will try to release as soon as possible.

**Comment by xiaoxufeiji1a** [comment]
em I got it,thanks

**Comment by xiaoxufeiji1a** [comment]
I got it thanks

**Comment by CovertJaguar** [comment]
Due to the breakThings->fixThings->breakThings nature of the dev cycle, Railcraft is in not state to be released publicly at the moment.
