### ISSUE TITLE
EU Loader/Unloader can only be crafted with charged batteries.

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#1233]
See title.

**Comment by Generalcamo** [comment]
As far as I can tell nothing fundamental has changed about how Railcraft handles batteries for a long while now. All I did was correct the name.

I'll investigate this though. I think a wildcard is needed somewhere.

**Comment by liach** [comment]
For ic2, they only accept uncharged items.

**Comment by liach** [comment]
Crafting recipe is inventory not machines.

**Comment by Generalcamo** [comment]
It's both since the maniupulators are classified as machines internally.
