### ISSUE TITLE
Disembarking track puts entities between two blocks

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1236]
![image](https://cloud.githubusercontent.com/assets/150333/26666683/0e45e0d2-4656-11e7-94c0-a6d86aeaf4e9.png)
![image](https://cloud.githubusercontent.com/assets/150333/26666553/6f0b9a7a-4655-11e7-8e3f-a8d5607ff674.png)
![image](https://cloud.githubusercontent.com/assets/150333/26666555/72bb44b8-4655-11e7-89ae-998c70a21aa4.png)
(For each image, I ran the cart, flipped the disembarking side, and ran the cart again.)

It'd be nicer if they landed on the center of a block rather than between them.

**Comment by liach** [comment]
This is actually a bug: when you use `/tp @p 0 64 0` you go to (0.5, 64.0, 0.5) instead. The tracks should work like the command.
