### ISSUE TITLE
Unattended train on a looped track not possible?

### ISSUE THREAD

**Issue by sparhawk765** [Railcraft/Railcraft#1237]
Hi there. This is just a question since I can't find any good answer googling or searching the forum and I didn't really know where to put it.

I have built a 2000 or so blocks long track that goes in a circle between a few of my friends on a private server. I tried to put a electric train on said track and have it go round and round but it seems it only goes a few hundred blocks and then stops. From what I can gather it's due to the entity getting unloaded or something if noone is near.

I have tried to chuckload the entire track and also tried loading the adjecent chunks to see it that made a difference. Didn't work.

I don't know enough of minecrafts internal mechanics to know if this is intended or if there's any way around it. I have also tried with a steam locomotive just to be sure it wasn't a power-issue but still no luck.

If I ride the train or stay somewhere near it, it works perfectly. Sorry if this question is terribly misplaced.

// Regards Mattias

**Comment by liach** [comment]
Will be fixed in 10.2, and you'd attach train with a spike cart (chunkloader) at that time.
