### ISSUE TITLE
[mod compat] actually additions Jam Guy villager gets trackman trades assigned to it

### ISSUE THREAD

**Issue by Twisted-Code** [Railcraft/Railcraft#1239]
I'm currently standing next to a "profession: Jam Guy" villager that has both trades involving jam and completely uncharacteristic trades involving railcraft tracks and such. The villager initially spawned with trades from the right group, but when I unlocked tier II, the new trades were.... different, and not in a good way. I've also encountered a jam villager who has ONLY railcraft trades (for which he earned the nickname & name tag "traveling jam merchant"). If you guys (addressing both development teams) could work this one out, I would GREATLY appreciate it, as I want jams :-/

![2017-06-02_22 51 36](https://cloud.githubusercontent.com/assets/7110033/26750012/4a4d5a1a-47e6-11e7-8c87-7cdfb3281021.png)
![2017-06-02_22 51 22](https://cloud.githubusercontent.com/assets/7110033/26750009/4a173610-47e6-11e7-8a2e-9c0b60a148e3.png)
![2017-06-02_22 51 26](https://cloud.githubusercontent.com/assets/7110033/26750011/4a1dc782-47e6-11e7-8a39-b63b50852a0f.png)
![2017-06-02_22 51 31](https://cloud.githubusercontent.com/assets/7110033/26750010/4a1c57b2-47e6-11e7-8393-8836a0d6b2db.png)

By nature of this issue, it's hard to tell which side of the fence the problem lies on, so I've taken the liberty of posting a nearly-identical issue on both mods' issue trackers. You can find the sister issued to this one [HERE](https://github.com/Ellpeck/ActuallyAdditions/issues/797)

**Comment by liach** [comment]
Does it happen only with these 2 mods? I think it is caused by coremods.

**Comment by Twisted-Code** [comment]
That very well could be, especially since one of the mods in play is SpongeForge. I'll do some experimentation and let you know.

**Comment by liach** [comment]
I don't think SpongeForge is the criminal though. Can you provide a list of mods for your server?

**Comment by liach** [comment]
And by the way, does it happen with any other mod's villagers?

**Comment by Twisted-Code** [comment]
Okay, it appears to not be limited to villagers from either mod, and it only seems to happen on my spongeforge server, so I'm opening an issue SF's github. I guess you guys should close your respective issues for now. See Spongeforge [\#1562](https://github.com/SpongePowered/SpongeForge/issues/1562)
