### ISSUE TITLE
[Suggestion] 3-Way Rail Switch

### ISSUE THREAD

**Issue by brisingraerowing** [Railcraft/Railcraft#1242]
How about a 3-Way rail switch ([example](http://s145079212.onlinehome.us/rr/howto/faq/faq_turnouts.htm#lapturnout))?

I mostly want one for a mineshaft I am repairing, as there are several sections where one would be useful.

**Comment by liach** [comment]
Please tell us where do you plan to place the actuator.

**Comment by brisingraerowing** [comment]
```
   A | A
---------
   A | A
```

The lines are tracks, the As are where the actuator can go (only one is needed, of course)

Basically, in a corner next to the tracks.

**Comment by liach** [comment]
Ping @CovertJaguar for opinions

**Comment by Generalcamo** [comment]
There are several issues with such a thing:

- The fact that this would need to function completely differently from other switches (Analog Redstone Signal, Placement, etc) means this would be unintuitive to users and difficult to code and maintain.
- The usability of it would be limited, as a Redstone circuit would need to be primed for the handling of analog signals. This type of switch is usually intended to be placed in areas where space is an issue, so there is obviously no room for such a complicated circuit.
- Real-World Installations are noted to be complex and rare--often having significant speed reductions--and only used in lesser-used spur ends like Maintenance Depots; they would certainly not be found on a mainline.

For these and other reasons, this will not be done.
