### ISSUE TITLE
Firestone extremely rare with Natura installed.

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1247]
I'd say about 98% of the underside of the magma sea is tainted soil, but firestone only generates on netherrack.

![image](https://user-images.githubusercontent.com/150333/26962368-90b89b28-4c9a-11e7-9198-5db5c9343b8a.png)

Relevant code:

https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen/WorldGenFirestone.java#L53

https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen/GenTools.java#L28

**Comment by purpleposeidon** [comment]
Staring at things some more it looks like natura basically only allows netherrack underneath gravel & soulsand patches.

**Comment by Generalcamo** [comment]
Actually, Firestone generates in patches of isReplaceableOreGen. This is on the other mods to set their block to be replaceable.

**Comment by purpleposeidon** [comment]
Fixed in Natura.
