### ISSUE TITLE
Forestry water capsules are infinite in the steam locomotive.

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1248]
Put a wax capsule of water in the input slot --> goes into the processing slot --> water goes into the loco --> capsule still containing water goes in the output slot.

**Comment by CovertJaguar** [comment]
Did I mention I hate fluid containers?

**Comment by liach** [comment]
I think this is forestry bug because they did not define their container item for water wax capsules correctly.

**Comment by CovertJaguar** [comment]
I need to check if I even fixed the GUI for the locomotive.

**Comment by purpleposeidon** [comment]
IC2's fluid/solid canning machine treats wax capsules properly.

**Comment by liach** [comment]
I think the train treats buckets, ic2 universal fluid cells, and foundry capsules properly, right?

**Comment by Generalcamo** [comment]
Does the train handle lossy containers properly? Ones that are destroyed upon use?

**Comment by CovertJaguar** [comment]
If the GUI only has two slots, then the Locomotive needs a GUI redesign to handle these properly. If it has three slots, then there is a bug in the container handling code.

**Comment by liach** [comment]
@CovertJaguar It has three slots. I know what is the fix already.
