### ISSUE TITLE
Fluid unloader can drain water from steam locomotives

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1254]
Let me tell you, this is really obnoxious.

**Comment by Generalcamo** [comment]
Best way I can think of to fix this is to disallow unloading from all Locomotives, unless the filter is set to a Locomotive. Basically an opt-in feature.

**Comment by liach** [comment]
Or to allow carts to decide.

**Comment by CovertJaguar** [comment]
The PR just disables draining, but I'm pretty sure draining was enabled at some point because people playing with finite water wanted it.

**Comment by liach** [comment]
So @purpleposeidon, Adding a filter to the unloader is the ultimate solution.
