### ISSUE TITLE
[1.10.2] Crash when placing peat engine from forestry against rolling machine

### ISSUE THREAD

**Issue by 3TUSK** [Railcraft/Railcraft#1255]
[Crash report](http://paste.ubuntu.com/24854983/). Initially reported by @Glease. Can be reproduced with given mod list (found in crash report).

The issue is most likely due to Forestry removed their method regarding Redstone Flux compatibility  as there is no API packages provide [`cofhapi|energy`](https://github.com/CoFH/RedstoneFlux-API/commit/11e351808ed0cbd181205a61f25f7732a696ce52#diff-e9098f736e4da525a4036c61bc295954R5); whereas, in this case, Railcraft is the only mod shipping with RedstoneFlux API in this modpack, but is still using the old modid (i.e. `provides = "CoFHAPI|energy"` in `@API` annotation). As such, Forestry thinks RF is present but still removes their methods for compatibility.
Therefore, I believe it should be reported on Railcraft's side, rather than Forestry.

**Comment by 3TUSK** [comment]
Regarding #1203: while it is planned to get rid of Redstone Flux, before that happens, this issue is still a real bug for those who don't install CoFHLib (or CoFHCore? can't remember exactly) for whatever reason. Please consider about it.

**Comment by liach** [comment]
We will indeed remove that api in 10.2, the very next version released. So there is no need to keep that API-we once kept it as a submodule but it simply does not update on time.

**Comment by liach** [comment]
And by that time, the machines will no longer use rf. They will switch to Railcraft charge or some similar power source.

**Comment by 3TUSK** [comment]
But this doesn't sound like a "rejection" - but, another approach of fixing problem, I will say.

**Comment by liach** [comment]
"rejected" means we reject to update the RF api.

**Comment by 3TUSK** [comment]
I guess the only possible workaround is adding CoFHLib?

**Comment by CovertJaguar** [comment]
Just disable the Powered Rolling Machine and use the Manual one for now.

**Comment by CovertJaguar** [comment]
The bigger question....does this affect the @API id for our API. Or do we worry about that for 1.11?

**Comment by 3TUSK** [comment]
Since powered rolling machine uses charges now, question: will there be means to get charge in next released version?

**Comment by liach** [comment]
Yes, you should read that commit.

**Comment by 3TUSK** [comment]
... I saw nothing but #1203 ? Either way I will wait for next release.

**Comment by liach** [comment]
@3TUSK Read this: https://github.com/Railcraft/Railcraft/commit/7321d7064c0bda5456cde45ce311a010202696ff#diff-cde1bad81f8d19c277f72a919cdec65fR46

**Comment by 3TUSK** [comment]
... `TileChargeFeeder` is abstract. I mean the actual method(s) (in terms of actual gameplay) to get Railcraft charge.

**Comment by liach** [comment]
Don't worry, more things will come up as of the release.

**Comment by CovertJaguar** [comment]
The next release will for sure include craftable, pre-charged single use charge batteries.

Beyond that, the Steam Turbine is still a way off, but there have been some discussion of a lower tech solution, though admittedly not much has come of the conversation so far. I'm open to suggestions.
