### ISSUE TITLE
Routing table issue

### ISSUE THREAD

**Issue by CyanideCarrot** [Railcraft/Railcraft#1256]
It requires the full string rather than the beginning of it. For example:
My locomotive's name is BBL/01/Buildworld
I typed in the string Name=BBL/01 and it didn't work
I then typed Name=BBL/01/Buildworld and it worked

**Comment by liach** [comment]
You should check the destination of the locomotive instead. Use tickets.

**Comment by CyanideCarrot** [comment]
That wont work with my setup

**Comment by liach** [comment]
Why? Talk on discord.

**Comment by CyanideCarrot** [comment]
In order to route them to the correct location, I would need a routing detector to detect the name so that the correct routing track activates, which defeats the whole purpose

**Comment by liach** [comment]
@bballboy2002 Then just keep the ticket always in the loco inventory instead of naming the carts.

**Comment by CyanideCarrot** [comment]
no i need destinations for other things

**Comment by CyanideCarrot** [comment]
just fix the problem

**Comment by liach** [comment]
> just fix the problem

This is not going to fix any problems. Tell me the exact use case and I will derive a resolution.

**Comment by CyanideCarrot** [comment]
I am trying to build a depot for the railcraft server, and each train is designated to a specific parking spot. For this I need to use the locomotive name, dest won't work, nothing else will work.

**Comment by liach** [comment]
Can you put routing tracks on the parking spots? If you put the routing tracks there you don't need to reroute them by name and then set tickets.

**Comment by CyanideCarrot** [comment]
> In order to route them to the correct location, I would need a routing detector to detect the name so that the correct routing track activates, which defeats the whole purpose

**Comment by liach** [comment]
So the solution is that we may add origin tags to tickets so trains may be sorted in that way.

**Comment by CovertJaguar** [comment]
Name does not support partial matching. It does however support the regex operator.

```
Name?=BBL/01.*
```

You can ignore whatever liach is babbling about. 

@liach be less combative please. -.-
