### ISSUE TITLE
Worldspike Point xrays

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1258]
![image](https://user-images.githubusercontent.com/150333/27310076-a335934e-550c-11e7-9011-bc04b70e1df0.png)

**Comment by liach** [comment]
@purpleposeidon Only with spike points?

**Comment by CovertJaguar** [comment]
Oh, that's an easy fix, if only I can remember what it is.

**Comment by CovertJaguar** [comment]
Probably isOpaqueBlock() is wrong.

**Comment by liach** [comment]
Will try to fix this.
