### ISSUE TITLE
steel sheers 

### ISSUE THREAD

**Issue by bear989** [Railcraft/Railcraft#1264]
I found an issue in 1.7.10 so I thought i would bring it to your attention so you can make sure it isnt an issue in 1.10
steel shears do not deactivate trip wires like regular sheers

**Comment by CovertJaguar** [comment]
Code probably needs updating. I seem to recall that I had to duplicate most of the code for the shears because it wasn't easily extended.

**Comment by liach** [comment]
Although this is indeed a bug, this should happen to all modded shears. This is, in fact, a forge bug.

**Comment by bear989** [comment]
well scissors from Gregtech 6 seem to perform this function without any
issue.

**Comment by liach** [comment]
Is GT6 a coremod? This can only be fixed with coremods IMO.

**Comment by CovertJaguar** [comment]
The only solution I see is to listen for BlockEvent.BreakEvent and do the state change ourselves.
