### ISSUE TITLE
Derail stops locomotives even when not actually derailed

### ISSUE THREAD

**Issue by Natesky9** [Railcraft/Railcraft#1272]
This one is difficult to explain. It's also not that critical, though it would help prevent issues later.

Whenever a cart derails but is prevented from leaving the track, it will act as if it is no longer on a track. Locomotives will not move, and even when re-linked, will cause any carts to immediately derail

also, locomotives tend to just reverse when being pulled by another locomotive, halting both.

**Comment by liach** [comment]
Derail in fact is that locomotives consider track direction to be east-west instead of north-south.

**Comment by CovertJaguar** [comment]
Not sure about derailing, but we should probably look at the multi-head situation.

**Comment by CovertJaguar** [comment]
See #1460 for rotation issues.

"Derailment" as a game mechanic only happens on Abandoned Tracks over a certain speed of travel. At which point the cart sees the track as having rotated 90 degrees. This kicks it off the tracks, but never marks it as being unable to use rails.

There are some other cases involving elevators and launcher tracks that might be able to result in carts that can't use tracks, but again without more info I can't comment.
