### ISSUE TITLE
"Train" detector

### ISSUE THREAD

**Issue by Natesky9** [Railcraft/Railcraft#1274]
While testing with Forecaster, we found that there was no good way of detecting a "train" with a detector without using a locomotive detector. Usually, there would always be a locomotive powering a train, but that might not always be the case

In the case of some trains, you only want one signal if a detector finds a match, and keep that signal until the entire train has departed, other times you want a pulse for each.

So what about an option in their gui to change this behavior?

**Comment by CovertJaguar** [comment]
What's wrong with the Train Detector set to size 2?
