### ISSUE TITLE
MC 1.10.2 Not able to find tin ore [not solved!]

### ISSUE THREAD

**Issue by winnetrie83** [Railcraft/Railcraft#1290]
I have been unable to find any tin ore.
I am flying in spectator mode with nightvision.
It is very very very rare or it doesn't generate at all.

**Comment by liach** [comment]
It generates in mines in different chunks. I suggest using ore finding methods like OV/OD scanner for finding poor ores and ore mines

**Comment by winnetrie83** [comment]
After more then 1 hours searching for tin ore in spectator mode, nothing to be found. If people have to find this in normal survival mode, that will be nearly imposseble. For now i will use an other tin ore generation mod. Closing this issue won't solve it by itself.

**Comment by liach** [comment]
You can change the configuration for more frequent tin ore generation. Or turn on skygen in the configuration.
