### ISSUE TITLE
Exception with loot table lookup

### ISSUE THREAD

**Issue by andrewminer** [Railcraft/Railcraft#1291]
I've included Railcraft in a custom modpack, and when I start up my server, I see the following error:
```
[08:33:04] [Server thread/ERROR]: Couldn't load loot table railcraft:chests/village_workshop from jar:file:/Users/andrew/Documents/Minecraft/quiet-countryside/mods/Railcraft_1.10.2-10.1.2.jar!/assets/railcraft/loot_tables/chests/village_workshop.json
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'railcraft:ingot'
```

It doesn't prevent the server from starting up correctly, and everything seems to be working okay except that the chests in the railcraft houses in villages are always empty.

Minecraft 1.10.2
Railcraft 10.1.2

**Comment by CovertJaguar** [comment]
Unfortunately the loot system doesn't handle missing items very well. I've reported this to Forge people, but I don't know if they plan to do anything about it.

The solution is to provide your own versions of the loot table with the disabled items removed.

**Comment by andrewminer** [comment]
Ah!  Thanks for the explanation!

**Comment by forresthopkinsa** [comment]
> The solution is to provide your own versions of the loot table with the disabled items removed.

@CovertJaguar How can this be accomplished with fingerprinted jars?
