### ISSUE TITLE
Suggestion Change electricity to RF

### ISSUE THREAD

**Issue by winnetrie83** [Railcraft/Railcraft#1293]
Since electric locomotives and their tracks can't be used anymore in survival. Because we can't make electricity with railcraft. It would be a good idea to change it to redstone flux as it is the universal power in minecraft.

**Comment by liach** [comment]
You should convince @sfPlayer1 to switch ic2 to RF. :trollface:

**Comment by liach** [comment]
fyi railcraft will provide means to generate charge in 10.2

**Comment by winnetrie83** [comment]
I have no idea what ic2 has to do with this issue? I don't even play ic2..... You say railcraft provides means to generate charge in 1.10.2? How ? I haven't found a way yet. Can't find any information about it! The only way i know is the admin charge feeder block. Wich is not what i want ofc!

**Comment by winnetrie83** [comment]
Nvm, I just realized you were talking about the railcraft version (10.2) not minecraft.
In that case, good to know it will be added! Do you have much work to do untill that version is ready?

**Comment by liach** [comment]
https://github.com/Railcraft/Railcraft/milestone/19
