### ISSUE TITLE
Track kits registryname [SOLVED]

### ISSUE THREAD

**Issue by winnetrie83** [Railcraft/Railcraft#1295]
If you craft the track kits, all is fine.
When you do the /give player railcraft:track_kit 1 0
it gives you a purple/black block called invalid track kit.
I tried 0,1,2,3,4,etc etc. They all give an invalid track kit.

Edit: Crafttweaker also can't find the proper item.
Edit2: Tested it with only forge and railcraft installed. Same results.

**Comment by CovertJaguar** [comment]
That's because they use NBT data for differentiation.

**Comment by winnetrie83** [comment]
Yeah i saw that in the code last night. Is there a way to spawn them in anyway? Sorry to ask btw.
I'm making a modpack that has multiple plates and those of railcraft are not registered in the ore dictionary nor do your recipes use it. So i wanted to change some recipe that require the railcraft steelplate, but i can't change that recipe with crafttweaker for the dumping track because they return an invalid track. 1 way to fix this on your part is the use the ore:plateSteel in your recipe. Easy fix in my opinion, but i won't push ofcourse. It's just a suggestion. Otherwise you can also tell me if there is an other way.

**Comment by winnetrie83** [comment]
I have googled alot and found a solution. Basicly i have leared how to use the nbt tags. So i was able to use this in crafttweaker and to customize the recipes. The downside is the way to retrieve that nbt data. Is there a list anywhere or a way to retrieve that nbt tag data more easily? For now i'm using the command:
/entitydata @e[type=Item,r=3] {}

I bet you already knew this, but refused to help. Finding information about all this is very diffecult and you close a thread and answer with a very short sentence with no additional information.
I was hoping for more kindness on your part. Don't expect that everyone knows everything about minecraft/railcraft/forge. Besides that your mod is still awesome!

**Comment by MauveCloud** [comment]
Have you tried using /mt hand after crafting them?  That should get you the nbt data.

**Comment by winnetrie83** [comment]
@MauveCloud
Oh damn, i didn't know that command does exactly that! Thank you very much!

**Comment by CovertJaguar** [comment]
It should be noted that plates will be ore dict'd in 10.2.
