### ISSUE TITLE
1.10.2 Hoppercarts not working as expected

### ISSUE THREAD

**Issue by Sora-Canstavia** [Railcraft/Railcraft#1299]
Hi there,

I Don't know if this is a bug or not, but when using hoppercarts, they will not pick up items from the block above them as they are supposed to normally, according to the minecraft wiki: "It will also pick up items that are lying on a block directly above the track." https://minecraft.gamepedia.com/Minecart_with_Hopper#Usage%5C 
again, I Don't know if this is intended with Railcraft installed or if it is indeed a bug. But I Felt I Should at least ask, in case it is a bug, if it isn't I Apologize for wasting your time.

**Comment by CovertJaguar** [comment]
Oh its most certainly Railcraft's fault.

**Comment by liach** [comment]
See #1212
