### ISSUE TITLE
Tunnel Bore Infinite loop stalling server

### ISSUE THREAD

**Issue by Ashonee75** [Railcraft/Railcraft#1300]
something something infinite loop when tunnel bore is empty of balast.

Liach and Covert you know more about the specifics than i do.

Stalling our server when ever the chunk the tunnel bore is in loads.

Gravel dropping on mud breaks into an entity, the tunnel bore then empties itself of gravel setting up some sort of infinite loop that stalls the server.

**Comment by liach** [comment]
@Ashonee75 Fixed #1296
