### ISSUE TITLE
Item Unloader doesn't unload into storage drawers

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#1303]

**Comment by liach** [comment]
Guess they use the capability instead of the iinventory

**Comment by purpleposeidon** [comment]
https://github.com/jaquadro/StorageDrawers/blob/1.11.2/src/com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityDrawers.java Somewhere 'round here...

**Comment by liach** [comment]
Yeah it has a dummy iinventory, that is very sick...

**Comment by purpleposeidon** [comment]
https://github.com/jaquadro/StorageDrawers/blob/1.11.2/src/com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityDrawers.java#L691 better link, but that method doesn't have `@Override`...

**Comment by purpleposeidon** [comment]
https://github.com/jaquadro/StorageDrawers/blob/1.11.2/src/com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityDrawers.java#L1003-L1022 Capabilities. https://github.com/jaquadro/StorageDrawers/blob/1.11.2/src/com/jaquadro/minecraft/storagedrawers/inventory/DrawerItemHandler.java

**Comment by purpleposeidon** [comment]
Just check Capabilities before IInventory?

**Comment by liach** [comment]
I disagree. Capabilities has some issues. https://github.com/MinecraftForge/MinecraftForge/issues/3344
Will close since this is not really Railcraft's fault.
