### ISSUE TITLE
Add anvil cart

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1306]
An anvil in a minecart. From #1018

**Comment by liach** [comment]
Rejected as suggested by Generalcamo.

**Comment by liach** [comment]
Actually I'd keep it. It is not that problematic.

**Comment by CovertJaguar** [comment]
Well other than the anvil code being super annoying and needing to be updated every Minecraft version since they are _always_ changing it.

And being slightly pointless.
