### ISSUE TITLE
Anchors missing? Version 1.10.2 for mc 1.10.2

### ISSUE THREAD

**Issue by VsUK** [Railcraft/Railcraft#1311]
Using the last update for 1.10.2 as of 13th May 2017. Looked in the cfg file & anchors are set to true, but I cant find them in creative mode, nor craft them. 

Bit of help here. Never used anchors before, didn't know they existed until I asked for help on why my long distance train network kept stopping when i logged off or if they got to far away. 

So, bit of help would be great. I am a noob when it comes to anchors so be kind lol

**Comment by abculatter2** [comment]
The 1.10 update is very much WIP, and most machines have not been ported yet, the world anchor included.

**Comment by Forecaster** [comment]
World anchors (now called World Spikes) have been ported and are being tested in the beta versions right now. They will most likely be in the next release (barring anyone finding any significant issues). When the next release will be I don't know yet.

**Comment by liach** [comment]
However, you can see the new features here: https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/resources/change_log.txt

You can play beta versions once you support CovertJaguar on patreon, $5 or more per month: https://www.patreon.com/bePatron?c=81136&rid=1556762
