### ISSUE TITLE
Can't see to enchant the bore head.

### ISSUE THREAD

**Issue by coryhiller** [Railcraft/Railcraft#1314]
I noticed it said the 10.1.2 version now supports enchanting the bore heads.  How do you go about enchanting them?  I've tried the Anvil, the standard Table, and the Advanced Enchanting Mod but none of them seem to allow me to place an enchantment on the bore head.

**Comment by liach** [comment]
That version is actually bugged. You need to add enchantment with custom NBT tags.

**Comment by coryhiller** [comment]
Gotcha! Thank you for the fast response!

**Comment by liach** [comment]
I will make it implement `ItemTool` for better functionalities.
