### ISSUE TITLE
[Suggestion] Adding bees for Forestry

### ISSUE THREAD

**Issue by 3TUSK** [Railcraft/Railcraft#1317]
Imagine a new kind of bee that is capable to help you deploy the tracks (randomly, hopefully). With the help of apiary cart from Forestry, one can imagine that those ~~trackbees~~ "trackmans" will make some ... well, not something really imaginable. 

Just a very weird idea while chatting and brainstorming with my friends. I can even imagine that this can cause balance issue. Still, without speaking it loud, who knows what will happen next.

**Comment by forestbat** [comment]
I don't think it's a good idea——bees can't represent everything，do you want to come to every mod which have resources to get bees for it？

**Comment by liach** [comment]
Hmm there are nine :+1:s, but I cannot implement it.

**Comment by liach** [comment]
去，curseforge 推广群有毒啊！

**Comment by 3TUSK** [comment]
@forestbat 
1. ~~Beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeees iiiiiiiiis eeeeeeeeeeeevveeeerryyyyyythhhhhhing.~~
2. Not all bees are designed to give you raw material. Heroic bees kill mobs. Edenic bees give you experiences points. Phantasmal bees ~~resurrect~~ summon the ender dragons. ~~And there are also easter eggs - Merry bees, Tispy bees and Leporine bees.~~
3. For your question: I won't. If resource bees are what you only want, try Binnie/Magic Bees/More Bees/Genedustry.

Also, @liach if there will be some railcraft bees, they can be something other than "trackbees". Though I only have come out with the idea of trackbees so far.

**Comment by liach** [comment]
看了代码后发现实现不会很难。只是实现了我不会测试而已。

**Comment by liach** [comment]
However, CovertJaguar needs to decide if he likes it.

**Comment by forestbat** [comment]
@3TUSK We shouldn‘t and can't let a mod do everything——that's modpack。

**Comment by 3TUSK** [comment]
*You need Groovy or Kotlin runtime compiler to achieve such a weird goal*

**Comment by CovertJaguar** [comment]
Either magic bees or extra bees, added a ton of Railcraft specific bees in the past.

**Comment by 3TUSK** [comment]
>  in the past

Cannot verify...?

**Comment by CovertJaguar** [comment]
I don't know what the current state of those mods are. There were bees for Quarried Stone, Abyssal Stone, and Creosote for sure.

**Comment by 3TUSK** [comment]
Closing - see if I can find time to make a new railcraft addon, or pull request some one.
