### ISSUE TITLE
"gradlew eclipse" not creating an "eclipse" folder

### ISSUE THREAD

**Issue by MrAnima** [Railcraft/Railcraft#1319]
I have followed the [build instructions](https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/README.md#building) written in the _README.md_, and even though Gradle tells me that the build was successful, no "eclipse" folder appears in the root of the project. Does this folder have a different location ? I had previously built a few other mods, and nothing wrong occurred.
Thanks !

**Comment by liach** [comment]
@MrAnima You don't need that folder. Just import the gradle project in idea or in eclipse after running `gradlew.bat setupDecompWorkspace`.

**Comment by MrAnima** [comment]
Okay, thanks a lot, I was used to the classic way of doing things. I'll try that tomorrow.

**Comment by liach** [comment]
@MrAnima Is this fine now?

**Comment by MrAnima** [comment]
Oh, sorry, everything's fine, I was busy exploring the code and completely forgot, a big thank you for your help, have a great day!

**Comment by liach** [comment]
😄
