### ISSUE TITLE
Am I the only one who can't find anywhere a block signal? [1.10.2]

### ISSUE THREAD

**Issue by jsmetana** [Railcraft/Railcraft#1320]
# I can't find anywhere a block signal.
(not signal box, I mean the block lamp) (I can't find the double, too)

I look in all categories, even from other mods and it wasn't there: (only railcraft categories at photos)
![2017-08-27_12 40 29](https://user-images.githubusercontent.com/29602127/29749178-7da19c54-8b26-11e7-8740-08600c0c838d.png)
![2017-08-27_12 40 40](https://user-images.githubusercontent.com/29602127/29749180-858452f4-8b26-11e7-917b-015f42fcbfa1.png)
![2017-08-27_12 40 51](https://user-images.githubusercontent.com/29602127/29749182-8cf318ea-8b26-11e7-8f31-c99bdd3542d6.png)
![2017-08-27_12 40 56](https://user-images.githubusercontent.com/29602127/29749184-8f4c7afa-8b26-11e7-839b-6e2adc13bd84.png)
![2017-08-27_12 41 04](https://user-images.githubusercontent.com/29602127/29749185-9157f9b4-8b26-11e7-9b60-62e90d8a2cab.png)
![2017-08-27_12 41 08](https://user-images.githubusercontent.com/29602127/29749186-93622108-8b26-11e7-9c42-7efa8a467494.png)
![2017-08-27_12 41 18](https://user-images.githubusercontent.com/29602127/29749187-96b365d8-8b26-11e7-9dca-cefe1b18627d.png)
![2017-08-27_12 41 25](https://user-images.githubusercontent.com/29602127/29749189-9a4423cc-8b26-11e7-8a1d-bd027b2315f9.png)
![2017-08-27_12 41 36](https://user-images.githubusercontent.com/29602127/29749191-9dd81c78-8b26-11e7-8dfc-7a328de3e94b.png)
[some weird glitch with more pages than is needed (happens in other versions of Minecraft with forge, and the Railcraft isn't causing that) ]

I tried to craft it with all types of circuits:
![2017-08-27_12 43 19](https://user-images.githubusercontent.com/29602127/29749388-5a1c5900-8b2a-11e7-9bc8-36eb23868e4b.png)
![2017-08-27_12 43 24](https://user-images.githubusercontent.com/29602127/29749389-5cda6682-8b2a-11e7-897c-6f80ec85a0ca.png)
![2017-08-27_12 43 28](https://user-images.githubusercontent.com/29602127/29749390-5f2607a2-8b2a-11e7-81ae-00e951a7ef3d.png)

I checked all settings in configs and every thing what has to be set to "true", was and I tried to find it through give command.

I also checked hash (MD5):
![hash](https://user-images.githubusercontent.com/29602127/29749266-d5da6972-8b27-11e7-9cdf-030e591f6b98.PNG)
![goodprogram](https://user-images.githubusercontent.com/29602127/29749295-73fbac74-8b28-11e7-92dd-5bed3caf4a39.PNG)

List of mods:
AutoRegLib 1.0-2
CodeChickenCore 2.4.1.102
CodeChickenLib 2.5.9.283
ForgeMultipart 2.0.0.38
FullscreenWindowed 1.5.1 (Have 2 monitors)
ChickenChunksMod 2.2.052 (Until the anchors get back)
MoarSigns 4.2.3.9
MrTJPCore 2.0.1.20
Optifine HD U E3 (I haven't the fastest computer)
ProjectRed 4.8.4.49 (All modules available 1.10.2)
Quark r1.1-70
Railcraft 10.1.2
XaerosMinimap 1.13.6

_Thanks for help_

**Comment by liach** [comment]
Thanks for various information provided. Signals are available in the beta versions only for now. Once 10.2.0 is released, you will have access to them.
