### ISSUE TITLE
1.10 Locomotive stops when out of range.

### ISSUE THREAD

**Issue by Magi1053** [Railcraft/Railcraft#1324]
When I move away from my locomotive it just stops moving. I found this related issue #1237 mentioning a spike cart or chunk loader, but I am not able to find that item ingame or in any railcraft configs.

**Comment by liach** [comment]
You need to learn how minecraft works. When you are away, furnaces will stop cooking, too. Use chunk loaders.

**Comment by liach** [comment]
chunk loaders are available from different mods, but in the patron only betas, there are worldspikes (or world anchors in 1.7.10) they will be released in next major release.
