### ISSUE TITLE
consider speeding up the update by reducing railcraft to smallest viable product

### ISSUE THREAD

**Issue by EnderiumSmith** [Railcraft/Railcraft#1327]
railcraft has the problem that its too big to keep up with minecraft updates. shaving off some features could help catching up to 1.12. 

the most important feature are the tracks themselves. the tracks, carts and (un)loaders are all its needed for the mod to exist. electric tracks are not essential.

second of importance are locomotive and cart linking.

third are electric tracks. a simple RF transformer would suffice at first

the different brick varieties could be their own mod, and some of then are in quark anyway.

the ore gen could also be its own mod

the machines can also wait. by the time the steam boiler is ported an independent mod will add its own.

**Comment by EnderiumSmith** [comment]
forgot about signals. probably more important than electric tracks

**Comment by liach** [comment]
Not at all. We are just adding back multiblocks which are hampered by 1.8 rendering update. We are ready for all changes like item stack wrapping. Recipe jsons are not bad, too. We have a utility class that can be easily modified to generate jsons.

**Comment by liach** [comment]
If you really want to make railcraft up to date, we can port to 1.12 in one day, but we'd rather get new features in first. Some other mods, such as Aether 2 and carpenterblocks, are still on 1.10.2.

**Comment by liach** [comment]
> railcraft has the problem that its too big to keep up with minecraft updates. shaving off some features could help catching up to 1.12.

Uh eh, features are not ones that prevent railcraft from keeping up to date. It is caused by bad codebase (minecraft has a trashy codebase in which they find a furnace recipe entry by iterating over a hash set instead of actually using the features of a set)

And most of those "non-essential" features are already ported because they are easy to port. They are, in fact, essential.

**Comment by EnderiumSmith** [comment]
why is multiblock rendering a problem? forge added extra features to json and blocks could change state depending on whats around them like fences. immersive engineering has more complicated multiblocks and didnt have much trouble porting.

**Comment by LuigiHutch** [comment]
People only have so much time, splitting stuff up will only be more work. 

If you want development to speed up, the project will need more contributors or someway to speed up time.

All rendering has changed in 1.8+ and multi block rendering just hasn't been touched yet and will be done when CJ has time and the current milestone is done.

**Comment by liach** [comment]
Again, I can almost make sure that once 10.3 is out, we are ready to jump. 10.2 includes too many fixes (100 issues!) and 10.3 will come faster (for posts, etc. in 10.4, CJ has already been working on them) At that time, we might go to 1.12 or higher, releasing for mc versions in between depending on the situation.

**Comment by CovertJaguar** [comment]
All that stuff is already done for the most part. Just some small tweaks needed. Doing what you suggest would increase the effort required, not reduce it, since that is essentially what I had to do for 1.10 and why we are so far behind atm.
