### ISSUE TITLE
Game crashes on startup after installing Railcraft

### ISSUE THREAD

**Issue by pcking99** [Railcraft/Railcraft#1331]
Hello. My game crashes in loading mods after installation of Railcraft. It crashes on step 3 of 7 when loading minecraft engine.
MC: 1.10.2
Railcraft: 10.2.0
Log: https://www.dropbox.com/s/60ebwnv6l58s2mm/crash-2017-09-07_14.44.25-client.txt?dl=0

**Comment by pcking99** [comment]
When its doing modelmanaging.

**Comment by liach** [comment]
Thanks for speedy reports!
Will ask @covertjaguar to find a fix for his post renderings.

**Comment by liach** [comment]
does it crash when only rc is installed?

**Comment by pcking99** [comment]
let me test. Any core mods requierd?

**Comment by pcking99** [comment]
It works when its only that mod.

**Comment by liach** [comment]
I doubt it might be caused by CoFH mods or NEI.

**Comment by pcking99** [comment]
i tryed to remove NEI but did not work. Then i removed CoFH + mods and then i works. Does this mean i need to start a ticket to the creator of CoFH core?

**Comment by liach** [comment]
Yes, @KingLemming might know how to fix it.

**Comment by pcking99** [comment]
Solved! Looked like Thermal Expansion made the problem.
Solution: Updated Thermal Expansion from 5.1.9.23 to 5.1.10.25.
