### ISSUE TITLE
Is coke oven missing in 10.2.0?

### ISSUE THREAD

**Issue by pcking99** [Railcraft/Railcraft#1334]
Hello. I cant find a way to make coke coal and creosote oil.
I have looked in NEI to find an oven or smelter in railcraft but i cant find it.
What am i doing wrong?

**Comment by liach** [comment]
Yes. It is scheduled for [10.3.0](https://github.com/Railcraft/Railcraft/milestone/14).

**Comment by 054545641** [comment]
Err...is coke oven also missing in 10.3.0 and 10.3.1?
I cant find it in these two versions on curseforge.
Thanks.

**Comment by Generalcamo** [comment]
Yes it is, it's implemented in the source however and will be released for 10.4 on 1.10 and 1.12 eventually.
