### ISSUE TITLE
Tunnel Bore Destroys blocks

### ISSUE THREAD

**Issue by coryhiller** [Railcraft/Railcraft#1335]
Just started using version 10.2.0 and seem to be having an issue with the tunnel bore destroying blocks instead of mining them.  It appears I have the correct settings in the config file.  Hoping you can look into this. 

        bore {
            # 
            # change to 'destroyBlocks=true' to cause the Bore to destroy the blocks it mines instead of dropping them
            # 
            B:destroyBlocks=false

            # 
            # change to 'mineAllBlocks=false' to enable mining checks, use true setting with caution, especially on servers
            # 
            B:mineAllBlocks=true

            # 
            # add block ids to 'mineableBlocks' in a common separated list to define non-vanilla blocks mineable by the tunnel bore 
            # ignored if 'tweaks.carts.bore.mineAllBlocks=true' 
            # metadata sensitive entries can be defined in the form 'modid:blockname#metadata' 
            # Example:mineableBlocks= { minecraft:stone, minecraft:stonebrick#3 }
            # 
            S:mineableBlocks={}

            # 
            # adjust the speed at which the Bore mines blocks, min=0.1, default=1.0, max=50.0
            # 
            D:miningSpeed=1.0
        }

**Comment by liach** [comment]
How about the `doTileDrops` game rule?

**Comment by coryhiller** [comment]
I can check that. Which cfg file is that located in?

**Comment by liach** [comment]
https://minecraft.gamepedia.com/Commands#gamerule

**Comment by coryhiller** [comment]
Sorry for the confusion. That is set to true as well.

**Comment by PDelta41** [comment]
On a hunch, I tried changing " B:destroyBlocks=false" to " B:destroyBlocks=true". 
After reloading the game, the bore spit out the blocks it was mining. The behavior is inverted. Should be an easy fix (or just reword the tooltip).

**Comment by liach** [comment]
Already fixed in the commit above, waiting to get merged.
