### ISSUE TITLE
Minecarts in unloaded chunks causing server to crash

### ISSUE THREAD

**Issue by dn96** [Railcraft/Railcraft#1336]
Hi, minecarts on high speed rails are causing server crashes when they are loaded with a chunk. Now this has caused a player to crash the server every time they join, due to loading this chunk giving an error of ".testHighSpeedCollision" and a lot of others

Crash report included
[crash-2017-09-18_01.57.17-server.txt](https://github.com/Railcraft/Railcraft/files/1309194/crash-2017-09-18_01.57.17-server.txt)

**Comment by liach** [comment]
Does this happen with only railcraft in 1.7.10?

**Comment by dn96** [comment]
My server is currently on 1.7.10 so I'm currently unsure if this happens on the newer Minecraft versions

**Comment by liach** [comment]
1. Use MCEdit to remove those errored minecarts
2. Try to get this on 1.7.10 with only railcraft with no other mods (the latest version is 9.12.2.1 on curseforge, I suggest an update)
3. If you can get it, write down steps here.

**Comment by liach** [comment]
@dn96 any updates?
