### ISSUE TITLE
Cart linking depends on two modules

### ISSUE THREAD

**Issue by t0suj4** [Railcraft/Railcraft#1338]
I've recently installed Railcraft into my Age of Engineering modpack and disabled all modules except for railcraft:train so I could use the furnace minecart in my mine. But it turned out that I also need railcraft:tracks in order to make links with crowbar. It doesn't work without having *both* modules enabled.

**Comment by liach** [comment]
fyi there's a config to reenable furnace carts. for the module one, I will look into it. Is there any error message?

**Comment by t0suj4** [comment]
It just fails silently. Nothing in logs. RC is installed as single mod when I test it. AoE can't initialize with railcraft:tracks btw.

It would be great if there was an option to restore pre-1.8 furnace cart behaviour.

**Comment by liach** [comment]
@t0suj4 Verified. Module dependencies are borked.

Edit: Soft dependencies.
