### ISSUE TITLE
Railcraft crashes on Minecraft 1.10.2

### ISSUE THREAD

**Issue by Kiritow** [Railcraft/Railcraft#1340]
I am using Railcraft 10.2.0 on Minecraft 1.10.2. The game starts successfully. But when I put a signal lamp on the ground, the game crashes. 
Here is my crash report:

[crash-2017-10-01_18.19.14-client.txt](https://github.com/Railcraft/Railcraft/files/1347063/crash-2017-10-01_18.19.14-client.txt)

**Comment by brisingraerowing** [comment]
This is caused by Optifine breaking API stuff.

**Comment by Kiritow** [comment]
I removed the Optifine and everything is ok now. Thanks!

**Comment by liach** [comment]
建议升级optifine，如果继续崩溃到 https://github.com/sp614x/optifine/issues/new 汇报

**Comment by Kiritow** [comment]
升级了Optifine之后也没有问题了，谢谢！@liach
