### ISSUE TITLE
crash on minecraft version 1.10.2 on both 10.1.2 railcraft and 10.2.0

### ISSUE THREAD

**Issue by jayyyin** [Railcraft/Railcraft#1342]
almost the identical error for both versions of railcraft

https://pastebin.com/k5V06wY0

**Comment by liach** [comment]
1. This is caused by other mods that add items with incorrect capabilities. Remove half by half to test.
2. Will be fixed once version containing #1321 is released.

**Comment by liach** [comment]
@jayyyin Any updates?

**Comment by jayyyin** [comment]
@liach discovered it was a bug in forge 12.18.3.2488 for minecraft 1.10.2 caused a conflict between Tinker's construct and railcraft so, unrelated it wasn't directly related to railcraft

**Comment by liach** [comment]
thanks!
