### ISSUE TITLE
Single-head signals crash game

### ISSUE THREAD

**Issue by kehkou** [Railcraft/Railcraft#1343]
Railcraft 10.2.0 release - Win 7 64-bit
Placing a single-block signal causes the game to crash without error message or logs. Reloading the game causes crash on world render; backup saves without block signal in place load fine.

Let me know what other info I need to provide.

Thank you!

**Comment by liach** [comment]
is there any hs_err_pid files?

**Comment by kehkou** [comment]
I believe this one is correct (time stamp matches):
G-Drive link: [https://drive.google.com/open?id=0Bw381QoZQ2jFV1NPTXhPZDlwVG8](hs-err-pid.log)

**Comment by liach** [comment]
Can you try with VBOs and Vsync? If you can, you should try with and without Optifine and compare the results.

**Comment by liach** [comment]
@kehkou Any updates?

**Comment by kehkou** [comment]
Sorry, been busy. Without Optifine, the signals seem to work as intended. It was an older version: OptiFine_1.10.2_HD_U_D6.

**Comment by liach** [comment]
Thanks. Closing then.
