### ISSUE TITLE
Carts become transparent

### ISSUE THREAD

**Issue by Kiritow** [Railcraft/Railcraft#1344]
Hi, I am using Railcraft 10.2.0 on Minecraft 1.10.2 Server. After running 4 days, we suddenly found all carts become transparent, just like the following picture:
![rc_report_pic1](https://user-images.githubusercontent.com/13619158/31850281-1224e68e-b682-11e7-89df-58b11b578f43.png)
After checking server log, we found an error:
`[16:47:16] [Server thread/ERROR] [Sponge/]: No entity type is registered for class mods.railcraft.common.carts.EntityTunnelBorePart`
I have restarted my client and my server. And nothing changes. Please help!

**Comment by Ommina** [comment]
It's not Halloween already, is it?

Oh my.  It is.

Edit in case I sounded glib:  It's a season effect.  You can turn it off in _client.cfg_.

**Comment by Kiritow** [comment]
Well... I just forgot it~ Thanks ~!

**Comment by liach** [comment]
#1346 for that error

**Comment by amelia-bartlett** [comment]
had the same problem, just realised how stupid i am lol!
