### ISSUE TITLE
Worldspike eats 48 fuels

### ISSUE THREAD

**Issue by 1696309** [Railcraft/Railcraft#1347]
在往锚钉里添加燃料时，如果按住shift键，64个的燃料变成了16个

**Comment by liach** [comment]
Anchor fuel shift filling. It's been reported on discord, but this is the first issue opened.

**Comment by 3TUSK** [comment]
> English please.

**Comment by 1696309** [comment]
when add fuel to the anchor,Hold shift key,64 fuel become 16.

**Comment by liach** [comment]
Fix found, pushing soon. It is a really silly bug... You can just place a stack of 64 in without using shift, and the items will still go away.

**Comment by Amelia-** [comment]
When I had this happen the fuel you put in isn't actually lost. It only shows 16 fuel in the world spike but the spike stays online for days on end without reducing the fuel count.

I'm pretty sure the fuel is just there but not displayed properly.

**Comment by liach** [comment]
@amelia- this bug is alread fixed. I am waiting for @CovertJaguar
