### ISSUE TITLE
Cart Model issue

### ISSUE THREAD

**Issue by ptrstourac** [Railcraft/Railcraft#1350]
Hi, I´ve got an issue with all railcraft carts. They look like game spawns two carts at once, each with different size.

https://imgur.com/a/DLUBU

**Comment by ptrstourac** [comment]
As you can see here: https://imgur.com/a/DLUBU This happens to me with all entities from this mod

**Comment by DDLPYT** [comment]
Well its an effect that appears at Halloween ;D
I had the same problem until I found out that you can turn the "ghost trains" off in your configs:
.minecraft/config/railcraft/client

Happy Halloween ;)

**Comment by 3TUSK** [comment]
#977 #1344 - Guess there should be some pop-up message to remind people Halloween is coming?
