### ISSUE TITLE
Switch Actuator Motor does not always work

### ISSUE THREAD

**Issue by Kiritow** [Railcraft/Railcraft#1351]
Hi! I am using Railcraft 10.2.0 on Minecraft 1.10.2. I am writing lua programs (like [this](https://github.com/Kiritow/OpenComputerScripts/blob/master/station_2_6.lua) and schedule trains through my programs with OpenComputers Mod. I found the switch actuator motor does not always work.

For example, in this station, I use 15 signal receiver boxes as input and 14 signal controller boxes as output.
![rc_issuepic_1](https://user-images.githubusercontent.com/13619158/32106818-5bd54f62-bb5f-11e7-8036-1385e0911dde.jpg)
And I set allcontroller boxes to this state:
![rc_issuepic_2](https://user-images.githubusercontent.com/13619158/32106861-7e4e1790-bb5f-11e7-9605-ba129c2d3f12.jpg)
I set all motors to this state:
![rc_issuepic_3](https://user-images.githubusercontent.com/13619158/32106955-c233c432-bb5f-11e7-9b42-c7980d209462.jpg)
Then I use tuner to connect them.
![rc_issuepic_4](https://user-images.githubusercontent.com/13619158/32107453-33827196-bb61-11e7-82c1-3686cf50106f.jpg)

The schedule program uses Redstone API from OpenComputer to change the output of a specific side of the Redstone IO block. And now I am sure that the program has the right judgement and the Redstone IO block did change the output and the Signal Controller Box did change its signal. But, the motor does not change its state and that just cause railway crashes.
Is this a bug? Or it is because of too much signal boxes ? Or something else? Please help...

**Comment by liach** [comment]
@Kiritow 话说最后一张图三个转辙马达里面最右边一个没有控制任何铁轨。是这个问题吗？
The setup for the rightmost switch actuator is wrong. It is not attached to any wye or switch track.

**Comment by Kiritow** [comment]
存档丢了... 没法重现这个问题了. 
I'm sorry that the world is lost and problems can not be reproduced for now.
