### ISSUE TITLE
Unseen cart blocks railway

### ISSUE THREAD

**Issue by Kiritow** [Railcraft/Railcraft#1352]
Hi, I am using Railcraft 10.2.0 on Minecraft 1.10.2. My train system is blocked by an unseen cart.
As you can see, there's a stopped train.
![rc_report_1](https://user-images.githubusercontent.com/13619158/32330111-0e305044-c01a-11e7-8f5f-6673a3ba12a9.png)
After I started it, it moved and then just stopped there.
![rc_report_2](https://user-images.githubusercontent.com/13619158/32330175-483c25b0-c01a-11e7-90ec-f686e68cd8bb.png)
As you can see, the train is still working and trying to move forward. (Its light is on)
![rc_report_3](https://user-images.githubusercontent.com/13619158/32330194-5b7d96cc-c01a-11e7-83f7-5c2e8bf54bdc.png)
If players in survival mode go through that place, they will die.
![rc_report_4](https://user-images.githubusercontent.com/13619158/32330238-79279416-c01a-11e7-8ce4-6596aadd9e7f.png)
![rc_report_5](https://user-images.githubusercontent.com/13619158/32330250-7ed5b6ea-c01a-11e7-9ac4-ce76852ebb2e.png)
As the game says, I was hit by a train.
This problem has occured twice on my server. It really affects our game experience. Please Help ~!

**Comment by Forecaster** [comment]
Have you tried using a command to destroy entities in a small radius near there?

**Comment by Kiritow** [comment]
We tried it when the problem occurred first time. But it didn't seem to work. So we just built walls and change lines.

**Comment by Forecaster** [comment]
something like `/kill @e[r=5]`?

**Comment by Kiritow** [comment]
Yes.

**Comment by Forecaster** [comment]
Inspect the world in mcedit and see if there's an entity there? then delete it?

**Comment by Kiritow** [comment]
I am sorry but I can't find any entity there.
![rc_report_6](https://user-images.githubusercontent.com/13619158/32333380-b61af68a-c022-11e7-9e8d-a72c967244e8.png)

**Comment by Forecaster** [comment]
That's strange

**Comment by Kiritow** [comment]
I restarted the server and when I logged in, I saw a creative locomotive appeared and disappeared immediately. Now everything goes well again...
Another strange thing is that sometimes the locomotive just disappears, leaving all other carts there.

**Comment by liach** [comment]
What other mods are on the server?

**Comment by Kiritow** [comment]
Sponge, IC2, OpenComputers, InfernalMobs, TConstruct
CodeChickenLib, StatusProtocol, ServerListPlus, ProjectPortals, WorldEdit, twentyticks, Nucleus, ProjectWorlds, TitleMOTD, PermissionManager, Inspector, Stackban, Keys

**Comment by liach** [comment]
try with only sponge and railcraft and see the results.

**Comment by liach** [comment]
@Kiritow Any updates?

**Comment by Kiritow** [comment]
Sorry for such a long delay. I tried it a few days ago and everything was normal.

**Comment by liach** [comment]
thanks! i will mark it as resolved. feel free to conment if it happens again and i will reopen.

**Comment by traincrisis** [comment]
What creative locomotive looked like? Like the perpetuum locomotive? Also why the train on screenshots is transparent? And why the carts of it is black and locomotive grey? Steam locomotive is grey but on screenshots it has shape of electric locomotive while electric loco is always yellow

**Comment by Forecaster** [comment]
> What creative locomotive looked like? Like the perpetuum locomotive? Also why the train on screenshots is transparent? And why the carts of it is black and locomotive grey? Steam locomotive is grey but on screenshots it has shape of electric locomotive while electric loco is always yellow

The perpetuum locomotive is the creative locomotive.

The carts in the screenshot are transparent because it was taken around halloween.

Locomotives are colorable. They don't have to be the default colors.

**Comment by traincrisis** [comment]
> > What creative locomotive looked like? Like the perpetuum locomotive? Also why the train on screenshots is transparent? And why the carts of it is black and locomotive grey? Steam locomotive is grey but on screenshots it has shape of electric locomotive while electric loco is always yellow
> 
> The perpetuum locomotive is the creative locomotive.
> 
> The carts in the screenshot are transparent because it was taken around halloween.
> 
> Locomotives are colorable. They don't have to be the default colors.

How did the user recolored the carts (Not locos)?

**Comment by Forecaster** [comment]
Carts are not recolorable in Railcraft.

**Comment by traincrisis** [comment]
> Carts are not recolorable in Railcraft.

How are carts of other color on images?

**Comment by Forecaster** [comment]
Transparent use not a colour. I said before that is because it was around Halloween at the time the screenshots were taken.
