### ISSUE TITLE
10.2.0 Release unsolved problems.

### ISSUE THREAD

**Issue by Philosyang** [Railcraft/Railcraft#1354]
Can't craft **raw firestone** from **firestone ore**.
Refer to #1010 for more information.

10.2.0 has been released on curseforge as a stable, even though there isn't in the github releases section.
https://minecraft.curseforge.com/projects/railcraft/files
https://github.com/Railcraft/Railcraft/releases

**Comment by liach** [comment]
Can you try with IC2 installed? Try macerator recipes.
试试安装工业2有可能有用（打粉机）

**Comment by Philosyang** [comment]
Will try asap, but btw I believe the ultimate goal should be something that can be pulverized in any mods’ macerator instead of single compatibility with IC2 machines.

**Comment by liach** [comment]
When rock crusher is ported back, the recipe will be in rock crushers.

**Comment by liach** [comment]
Ref #1373.

**Comment by liach** [comment]
Done in 1.12.
