### ISSUE TITLE
Can't sell kits to trackman villagers

### ISSUE THREAD

**Issue by GiovanH** [Railcraft/Railcraft#1356]
Working version: Railcraft 10.1.2 for minecraft 1.10.2

Noticed with Whistle Track Kit. Villager requests (#7428/22), but crafting produces item (#7428/0) 7428:22. The trade is not compatible. I assume this issue extends to other kits. 

I have only used this version of railcraft, but as this issue has not been reported on the issue tracker, I assume it has not been fixed.

**Comment by liach** [comment]
Confirmed. It should be an issue with track kit recipes.
