### ISSUE TITLE
All locomotives are extremely slow on activated High Speed booster tracks

### ISSUE THREAD

**Issue by SL-RU** [Railcraft/Railcraft#1357]
Why electric locomotive is slow on H.S.E. tracks with boosters? I know that in prev. versions was transformer, but where is it now? I've tried with normal I2C charge feeder and with admin charge feeder - the same. 
Steam locomotive and admin locomotive is waaaaaaay much faster.

Railcraft 10.2.0 - MC 1.10.2

**Comment by liach** [comment]
I will try this one.

**Comment by awesomeguy6661** [comment]
1.10.2 version 10.3.1 still same

**Comment by liach** [comment]
In fact this is for all types of locomotives.

**Comment by liach** [comment]
Fixed in dev.
