### ISSUE TITLE
[Request] New mode for locomotive track 1.10.2

### ISSUE THREAD

**Issue by caine717** [Railcraft/Railcraft#1360]
Hi, can you please add a mode for the locomotive track that allows us to change the mode of the locomotive. So then there is a locomotive on the the which is in shutdown mode, the track starts the loco and if there is a running locomotive then it stops it. So that I just need one track for running AND stopping? It would be extremly useful
Sincerly Caine717

**Comment by liach** [comment]
Then what happens if the loco shuts down on the track after it ran? Does it resume immediately after since it has already stopped?

**Comment by caine717** [comment]
I think you misunderstood me, sorry my English is not the best^^
I mean it would be cool if the track piece for starting the loco and shutting it down would be the same. So you activate the track piece with redstone and the loco stops. Maybe you can start the loco with another impulse of redstone. Or another idea, with a redstone signal you stop the loco and if you shutdown the redstone signal it the loco starts again.

**Comment by liach** [comment]
In this case, you may use a lockdown track kit instead.
