### ISSUE TITLE
Switch tracks

### ISSUE THREAD

**Issue by Raven2911b** [Railcraft/Railcraft#1363]
I have used the spike maul to create the switch tracks, but they only seem to turn right. What is the procedure to flip the track and have it turn left? I tried to make a siding off my main line, but the train turns the wrong direction after the second switch and head back on the main line the way it came in.

Thanks

**Comment by Forecaster** [comment]
Crowbar. Same as it's always been. If you need additional help go to IRC/Discord.

**Comment by Raven2911b** [comment]
Doh!
Sorry... still in learning mode.
