### ISSUE TITLE
Switch tracks do not appear in 10.2.0

### ISSUE THREAD

**Issue by ex0planetary** [Railcraft/Railcraft#1364]
I've been looking into routing, and it seems that the switch tracks have disappeared from both the creative inventory and NEI. The switch actuators are still there, but not the actual tracks. The only other mod I have installed that has anything to do with rails is Steve's Carts Reborn. Does anybody know what is happening?

**Comment by CyanideCarrot** [comment]
They aren't accessible in creative inventory, you get them by right-clicking with a spike maul.

**Comment by ex0planetary** [comment]
Ah, okay. I'm too used to old versions of Railcraft, apparently...
