### ISSUE TITLE
The question that probably tired everyone :)

### ISSUE THREAD

**Issue by ghost** [Railcraft/Railcraft#1365]
Is the mod update planned for 1.12.2, eh? And then the normal assembly of mods is not done, because on some versions of the maincraft there are updated modes, but for others there is (well, not including 1.7.10). For example, say as with BuildCraft on 1.12.2 version is, but on 1.10.2 there is no ... and such examples still exist and not a few. I also want to note that without BuildCraft and playing RailCraft is not interesting :(
And it stays at 1.7.10 boring, as some modders stopped supporting this version.
ps - I know that it is quite possible that you are already tired of such questions, since they are likely to be asked every day, but English is not my native language, so I can not read it fluently on it and therefore can not understand what they say about this in your forums or not ... And yes I apologize for my English, as I said it can not be my native language.
Thank you for your attention and good mood.

**Comment by bookerthegeek** [comment]
Well they were going to release it on new years day but now that you asked it will be at least another month.

**Comment by ghost** [comment]
Well, you must have understood me =D
Otherwise, I did not understand what I said. Thanks for the answer .

**Comment by liach** [comment]
Account deleted? Please don't do that next time!
