### ISSUE TITLE
Crash on local and multiplayer with Bees as the culprit.

### ISSUE THREAD

**Issue by seeker2921** [Railcraft/Railcraft#1366]
All,

I encountered an issue involving Bees and the crafting table. While these apparently have some random connection with zero obvious connection it caused me some headaches.

To reproduce: On forestry, disable bees, all of them, and any bee related thing (config below.) In railcraft, leave default config.

Open a crafting table, Doesn't matter if your local or on a server. Add recipe. Now take your crafted item and initiate a crash.

The problem was rectified by changing railcraft's config to disable forestry integration. (Config below)

Setup:
MC 1.10.2
Forge 12.18.3.2488
Forestry 5.2.17.388
RailCraft 10.2.0

While it makes sense that this causes issues since I had Bees disabled in forestry, It seems like there should be a check on init to prevent loading the full API if part of the functionality was disabled in another mod. without looking at the code, I think that Railcraft just checks of forestry rather than subparts.

Let me know if other information is needed, or if I'm off my rocker and is entirely my fault.

Configs:
[Modified_MC_Config_Bees.zip](https://github.com/Railcraft/Railcraft/files/1588273/Modified_MC_Config_Bees.zip)

Logs:
[crash-2017-12-26_21.26.21-client.txt](https://github.com/Railcraft/Railcraft/files/1588275/crash-2017-12-26_21.26.21-client.txt)

**Comment by liach** [comment]
@nedelosk Is the bee manager null or dummy when bees are disabled?

**Comment by liach** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1919#issuecomment-355872532
