### ISSUE TITLE
[1.7.10] Chisel mod broke the texture of steam in Railcraft

### ISSUE THREAD

**Issue by demycat** [Railcraft/Railcraft#1367]
After installing the version of chisel mod 2.9.5.11 for minecraft 1.7.10(railcraft 9.12.2.1), the texture steam became such (screenshot)! How to fix?
On the last screenshot, the answer from the developers Chisel mod.
![2017-12-25_12 46 23](https://user-images.githubusercontent.com/34833284/34404818-88ed32d8-ebb8-11e7-892d-1f18174d8454.png)
![2017-12-25_12 46 27](https://user-images.githubusercontent.com/34833284/34404819-89ada48c-ebb8-11e7-8bc9-a128fb7fc4b6.png)
![bandicam 2017-12-28 10-20-16-956](https://user-images.githubusercontent.com/34833284/34404864-c1b65784-ebb8-11e7-8ab0-4120c5a82166.jpg)

**Comment by liach** [comment]
@demycat Try in 1.10.2 with latest railcraft on curseforge.

**Comment by demycat** [comment]
@liach I need exactly for 1.7.10, and not for 1.10.2

**Comment by MyNameIsKodos** [comment]
I am using the same versions of both of these mods, and do not have this issue. Can you replicate it with JUST Railcraft and Chisel installed?

**Comment by AEnterprise** [comment]
it isn't realy eighter mod, during startup the first steam to be registered becomes dominant (so only that one texture gets registered)

when you make a world that dominant fluid is saved to the world to preserve it with mod changes, problem in your world is that the dominant fluid saved to the world and picked at startup do not match so it uses the old dominant fluid but it's texture isn't loaded

you wana grab nbtedit to edit the world metadata and remove that dominant fluid tag

**Comment by demycat** [comment]
@MyNameIsKodos i'm all download from curseforge

**Comment by demycat** [comment]
@AEnterprise How to do it?

**Comment by liach** [comment]
@demycat Do you have Minefactory reloaded?

Edit: Just give me a mod list.

**Comment by demycat** [comment]
@liach I'm not install Minefactory reloaded.
![bandicam 2017-12-28 20-12-10-245](https://user-images.githubusercontent.com/34833284/34419286-9b172470-ec0b-11e7-8b63-78d5fa43f1b3.jpg)
![bandicam 2017-12-28 20-12-30-847](https://user-images.githubusercontent.com/34833284/34419287-9b357c0e-ec0b-11e7-8036-323513700b34.jpg)
![bandicam 2017-12-28 20-12-38-769](https://user-images.githubusercontent.com/34833284/34419288-9b4e3ef6-ec0b-11e7-9cf3-ec3780254dfa.jpg)

**Comment by liach** [comment]
Unfortunately, I don't know what mods add steam

**Comment by demycat** [comment]
@liach only Railcraft(in my build)

**Comment by liach** [comment]
@demycat Remove mods except railcraft and chisel until the texture is fine

**Comment by demycat** [comment]
@liach I've already tried it, and the results with textures give it a Railcraft + chisel

**Comment by liach** [comment]
redownload each mod and try in a clean copy of minecraft, latest forge, with a new world

**Comment by demycat** [comment]
@liach just noticed this

**Comment by demycat** [comment]
Guys I noticed that the problem with the textures was on version 9.12.2.0, but after the update(to 9.12.2.1) I need to create a new world then the textures of the couple will work fine (I only have 1 world out of 2, now with normal texture pair, but the second one is not)

**Comment by demycat** [comment]
Thank you very much for your help, good luck to all!
