### ISSUE TITLE
LoaderExceptionModCrash

### ISSUE THREAD

**Issue by janagyjr** [Railcraft/Railcraft#1368]
MC: 1.10.2
Forge: 2511
Railcraft: 10.3.1

Gist: https://gist.github.com/janagyjr/f777b52ea209d19bf9ec6d85f1094899

Crashes during load and is fine when disabled.

**Comment by liach** [comment]
it looks like coremod hacks. the fluid field is always initialized by that point in code. can you produce the crash with only ie and rc?

**Comment by janagyjr** [comment]
I've disabled IE and IC2 and enabled RC but it still crashes during load. I cannot get the pack to load with RC. I was about to go and see if I could disable creosote in RC and just use the IE one (even if I have to adjust recipes to make it work).

**Comment by janagyjr** [comment]
I'll disable everything but RC and see what that gets me

**Comment by janagyjr** [comment]
Same
https://gist.github.com/janagyjr/1db33c6fc52bccac21dab0cd662f6dd7

**Comment by liach** [comment]
This should not error. I don't know what causes the error exactly.

**Comment by liach** [comment]
I cannot reproduced this bug @janagyjr. It is most likely your launcher's fault.
