### ISSUE TITLE
can't craft rails

### ISSUE THREAD

**Issue by caine717** [Railcraft/Railcraft#1369]
Hi, I'm using RC 10.3.1 on MC 1.10.2 and I cannot craft rails with the correct recipe. The output of the crafting table shows me the correct item I want to craft, but every time I click it the rails show up on my cursor like normal, but the disappear immediately and no ressources were used. The server log shows no errors when I'm doing this.

**Comment by liach** [comment]
@caine717 It is caused by railcraft only installed on the client but not on the server in general. Or your server has modified the recipes so that the old recipe does not work. Can you provide more information about your server?

**Comment by caine717** [comment]
Thanks, I had altrecipes active on the serverside. I changed it back to normal, now everything works fine.

Thank you!
