### ISSUE TITLE
can't place down any cart

### ISSUE THREAD

**Issue by tonimark** [Railcraft/Railcraft#1370]
I tried to place down any type of railcraft train and it won't be placed 
here the log
[notes.txt](https://github.com/Railcraft/Railcraft/files/1648910/notes.txt)

if you ask me to remove foam fix I can't because my game won't longer initializing then
for more information contact the modpack that I use:https://forum.resonantri.se/

**Comment by liach** [comment]
Please update foamfix to 0.7.2 first.

**Comment by asiekierka** [comment]
Update to the latest version, not just 0.7.2. For 1.10.2, that's actually 0.7.3.

For more information, a lot of the mods in that modpack seem to be outdated, so you are likely to encounter further issues. You might want to consider changing modpacks.

**Comment by liach** [comment]
oh. I just saw 0.7.2 on the github repo.

**Comment by asiekierka** [comment]
Yes, I already linked them to the download page in the previous issue.

**Comment by liach** [comment]
Pretty sure I can close this now.
