### ISSUE TITLE
Steam Locomotive doesn't draw water from tank cart

### ISSUE THREAD

**Issue by Shandoo94** [Railcraft/Railcraft#1372]
I haver Railcraft 10.3.1 and my setup is a steam locomotive with fuel and a connected tank cart. When i fill up the tank cart with water the locomotive doesn't draw the water into its own tank. I have tested this in running, shutdown and idle mode. 
Is this feature not added to the current version of railcraft or am I missing some config options?

**Comment by liach** [comment]
This has been confirmed by @xfl03.

**Comment by liach** [comment]
Addressed in 1.12.2.
