### ISSUE TITLE
The way Railcraft takes over vanilla ore gen seems wrong to me

### ISSUE THREAD

**Issue by Skullywag** [Railcraft/Railcraft#1375]
Ill try and surmise my issue:

So Railcraft has multiple config files, 1 for each ore, including vanilla oregen (iron and gold) as you wish to change how it generates, great

So lets say you have multiple mods and you dont want to use Railcrafts generation, you go into each of the railcraft files and set them to 0 blocks to generate.

Now my other mods will handle generating their ores. Great.

Except, none of the other mods generate iron and gold as they are fine with the vanilla generation and simply want to generate their own ores. Now I set iron and gold to 0 (both of the vanilla ores present in railcrafts config) so now I have no iron and no gold in my world because nothing is generating them.

So question 1:

Am i blind and theres an option to simply stop the ore generation override so as to let vanilla take back over generation?

Question 2:

Is the expectation that someone wouldnt do what I proposed above? (hint I already did it lol) and that the iron and gold generation is part of the mod balance or something.

Question 3:

I simply thought I could retrogen them as per the config files hint but this mentions the railcraft retrogen mod which I cannot find anywhere, the mod is on github but isnt built, is the expectation that I build the mod from source myself? I tried simpleretrogen but as expected it isnt compatible with railcrafts ore generator as per the railcraft retrogen github readme.

So yeah, it seems weird to me that there isnt a "let vanilla take back control of this ores generation" config option (unless the answer to question 1 is that there is an option).

**Comment by liach** [comment]
I think you can disable the whole thing somewhere in the config... like disabling the worldgen module or something of that sort.

**Comment by Skullywag** [comment]
ok turns out my issue was actually caused by:

tweak {
        # 
        # chance that vanilla ore gen (Iron, Gold) will spawn ore uniformly throughout the world, set to zero to disable, min=0, default=100, max=100
        # 
        I:vanillaOreGenChance=0
    }

I dont even....very confusing config. :(

**Comment by liach** [comment]
Set it back to 100.

**Comment by Skullywag** [comment]
Yeah I have done. Regenning my world as I type this. I still feel there could be a "turn off all word generation overrides" option, I mean I know how this is setup now so wont make the same mistake again, but still feels like an easy mistake to make.

**Comment by Dockter** [comment]
Ok, RC doesn't change how Vanilla does its ore generation, it simply adds to it.  These additional gold and iron ores are intended to be ore veins something Vanilla doesn't do.  Reference this ticket for an example of how it does its ore generation:  

https://github.com/Railcraft/Railcraft/issues/1400

**Comment by liach** [comment]
So now the bug should be fixed by dockter. thanks!

**Comment by CovertJaguar** [comment]
You know you can just delete the config files right?
