### ISSUE TITLE
Railcraft not loading in dev. enviro [1.7.10]

### ISSUE THREAD

**Issue by draknyte1** [Railcraft/Railcraft#1376]
So, whenever I try load Railcraft_1.7.10-9.12.2.1 or a deobf version of such, Eclipse fails to load.

[Obf] - https://pastebin.com/f6wJ9NWN
[Deobf] - https://pastebin.com/wHVg1J5H
[Deobf-No Chisel2] - https://pastebin.com/0F8y2FyU

Any thoughts on the matter mate?

**Comment by liach** [comment]
@draknyte1
1. For obf, the `printSignalDebug` field exists here: https://github.com/Railcraft/Railcraft-API/blob/master/mods/railcraft/api/signals/SignalTools.java#L17
(this is 1.7.10)
My conclusion is that one of your mods ships a broken railcraft api.

2. For deobf, how can you make us responsible for codechicken's coremod hacks?
```
    at net.minecraft.launchwrapper.LaunchClassLoader.getClassBytes(LaunchClassLoader.java:370) ~[launchwrapper-1.12.jar:?]
    at codechicken.core.asm.MCPDeobfuscationTransformer.getParents(MCPDeobfuscationTransformer.java:209) ~[CodeChickenCore-1.7.10-1.0.7.47-dev.jar:?]
    at codechicken.obfuscator.ObfuscationMap.evaluateHeirachy(ObfuscationMap.java:219) ~[CodeChickenCore-1.7.10-1.0.7.47-dev.jar:?]
    at codechicken.obfuscator.ObfuscationMap.lookupObfMethod(ObfuscationMap.java:187) ~[CodeChickenCore-1.7.10-1.0.7.47-dev.jar:?]
    at codechicken.obfuscator.ObfRemapper.mapMethodName(ObfRemapper.java:64) ~[CodeChickenCore-1.7.10-1.0.7.47-dev.jar:?]
```

**Comment by draknyte1** [comment]
@liach, I was just posting both logs for reference. :)

Hmm, I'll see what else ships a RC API. Probably GT.

**Comment by liach** [comment]
Or the api may be transformed by some transfromer (coremod)

**Comment by draknyte1** [comment]
hrnng, neither links here work.
http://www.railcraft.info/releases/9-12-2-0

And I can't see anything else in my modlist for dev declaring RC API, nor anything outside GT that touches RC.

I would prefer not to use a Bon2'd copy of RC, lol.

**Comment by liach** [comment]
So @CovertJaguar should fix the link to stupid dropbox which changed all its link formats, breaking all dev/api downloads and emblems.

**Comment by draknyte1** [comment]
Well, It seems GT grabs 9.4.0.0 from Maven.. so, the issue is probably from GT (Which I obviously can't remove from Dev, lol) 

Might have to see about fixing that then, since 9.4.0.0 loads as expected.

**Comment by liach** [comment]
Ah. Hope the api/dev and dropbox drama may end soon.

**Comment by draknyte1** [comment]
I already had a copy of 9.4.0 dev from my GT workspace, just annoying that I'd like to use 9.12.x in my personal workspace but GT isn't liking it in Dev.

Outside of Dev GT seems to load as expected. *shrug*
Doesn't seem to be an issue on RC though :)
