### ISSUE TITLE
[1.7.10]Error in compilation

### ISSUE THREAD

**Issue by Pilad** [Railcraft/Railcraft#1378]
Install JDK7 , and i create a gradle.properties file in the project root with the following properties:

mcUsername=Steve
mcPassword=ILoveNotch

And error : 

****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************

FAILURE: Build failed with an exception.

* Where:
Build file 'Y:\Railcraft-mc-1.7.10\build.gradle' line: 248

* What went wrong:
Could not resolve all dependencies for configuration ':api'.
> Could not resolve :buildcraft:7.1.13.
  Required by:
      mods.railcraft:Railcraft-mc-1.7.10:9.12.3.0-unofficial
   > Could not resolve :buildcraft:7.1.13.
      > Could not get resource 'http://www.mod-buildcraft.com/releases/BuildCraf
t/7.1.13/buildcraft-7.1.13-[classifier].xml'.
         > Could not GET 'http://www.mod-buildcraft.com/releases/BuildCraft/7.1.
13/buildcraft-7.1.13-%5Bclassifier%5D.xml'.
            > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 10.57 secs

y:\Railcraft-mc-1.7.10>

**Comment by liach** [comment]
@alexiil

**Comment by AlexIIL** [comment]
I think this is an issue with how the BC server is configured to handle https vs http connections. Can you retry but change the ````http://*```` dependency to ````https://*````?

**Comment by Pilad** [comment]
Not work. 

y:\Railcraft-mc-1.7.10>cmd /k gradlew clean build
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************

FAILURE: Build failed with an exception.

* Where:
Build file 'Y:\Railcraft-mc-1.7.10\build.gradle' line: 241

* What went wrong:
Could not resolve all dependencies for configuration ':api'.
> Could not resolve :buildcraft:7.1.13.
  Required by:
      mods.railcraft:Railcraft-mc-1.7.10:9.12.3.0-unofficial
   > Could not resolve :buildcraft:7.1.13.
      > Could not get resource 'https://www.mod-buildcraft.com/releases/BuildCra
ft/7.1.13/buildcraft-7.1.13-[classifier].xml'.
         > Could not GET 'https://www.mod-buildcraft.com/releases/BuildCraft/7.1
.13/buildcraft-7.1.13-%5Bclassifier%5D.xml'.
            > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 10.566 secs

y:\Railcraft-mc-1.7.10>

**Comment by Pilad** [comment]
May be login and password wrong ? ---> > peer not authenticated

**Comment by AlexIIL** [comment]
No, you don't need a password to access the buildcraft downloads. Perhaps try updating Java to the latest 8 version? I know that added support for newer ssl protocols, perhaps that's it? (Oh, and can you try accessing [http://www.mod-buildcraft.com/releases/BuildCraft/7.1.23/buildcraft-7.1.23.jar](http://www.mod-buildcraft.com/releases/BuildCraft/7.1.23/buildcraft-7.1.23.jar) in a browser?

**Comment by Pilad** [comment]
Yes, I can download the file.

**Comment by liach** [comment]
@Pilad Any more issues?

**Comment by Pilad** [comment]
No. I do not think
