### ISSUE TITLE
[Suggestion] Mechanically powered rails

### ISSUE THREAD

**Issue by primis** [Railcraft/Railcraft#1379]
Railcraft has a bunch of cool rail types, but one thing it doesn't have is a trolleycar style rail.
Basic idea would be to have a single large motor drive the entire track at the head end, and would be used to chain drive un-powered carts along the route. This would work best realistically for straight line tracks, and have the ability to switch to non-mechanical rails to switch between lines (like a real trolley during a turn).
To craft, I was thinking a standard rail plus an iron "chain" crafted together, and have a cart that could catch them. The drive end could be two block solution: mechanical receptor, and a motor. The mechanical receptor could accept IC2's kinetic energy (for use with steam turbines), Immersive engineering's rotational energy (For watermills and windmills), and a railcraft based motor or two (RF or IC2 powered electrical, and steam powered). The motor that accepts RF/IC2 power would also act as a lossy method of power transfer between the two standards of electricity if plugged into the mod's respective kinectic generators.

**Comment by liach** [comment]
I am asking @CovertJaguar here if he likes this.

**Comment by Forecaster** [comment]
How is this going to be balanced against booster tracks?

**Comment by liach** [comment]
fore, boosters do not even use power...

**Comment by Forecaster** [comment]
...yes, I know. That was kind of the point.

**Comment by primis** [comment]
We could make cool trolly carts that only work on these lines, just a suggestion

**Comment by Forecaster** [comment]
Right, then the next question becomes, what would the motivation be for using those?

**Comment by liach** [comment]
i support this type of track for slopes

**Comment by Forecaster** [comment]
Right, but, again, why not just use booster tracks?

**Comment by liach** [comment]
Railcraft is customizable. If a server wants to make the game harder, they can remove the booster because it is free. Mechanical tracks then can fulfill this gap and advance the technological theme of the server.

**Comment by Ommina** [comment]
OK, but how is this, really, different than powered (RF / Charge / Whatever) tracks?

On one you apply energy to some location on the track, the track powers the locomotive, train moves, life is good.  The other... energy is applied to some location on the track, the track powers the locomotive, and the train moves.

This seems, to me (and I'm just an interested third party) to be the same mechanics of the electric track, but with a different name.

**Comment by Forecaster** [comment]
It's different from electric tracks and locomotives because with electric tracks you need the locomotive, which itself doesn't do anything, you need that plus carts that do things, like carry items for example. It is a bit similar to that too though.

But it's more similar to booster tracks, except with power use, which is why I'm asking for more mechanical distinction. But so far I've heard nothing that makes it sound useful or interesting and worth the time it'd take to implement.

**Comment by abculatter2** [comment]
It can be made with just a bit of iron or steel, making it cheaper then boosters?

This could be further enhanced by making it work with wooden rails, for very cheap but energy-consuming and kinda slow rail lines.

Could also make it so normal boosters either don't work with wooden rails, or the chain link doesn't work with normal rails or above. Also, do wooden tracks have the ability to be electrified? If not, this could be a good alternative.

**Comment by bookerthegeek** [comment]
This could be super nice to add integration with. 

Imagine powering it with any of the following:
- pneumaticcraft air pressure
- Better with mod rotational energy
- Botania mana beams (More manna faster climb)
- Buildcraft MJ
- COFH RF
- IC2 EU (higher tiers give a faster clone)

And most likely others I can't think of off the top of my head.

Basically I imagine a block under the first mechanical track and the continue placement up the hill. It can only be placed on a slope though and gives a very slight boost when coming off of the mechanical track.

**Comment by Generalcamo** [comment]
I'm going to unfortunately agree with @Forecaster here. I do not see any reason to implement this when Booster tracks are in the game. Not to mention the complexity of adding this feature: We would need to add a new type of power (pneumatic energy) just for this one thing, and that is not a trivial task.

**Comment by liach** [comment]
I'd say a track preventing carts from sliding on slopes would be a good alternative.

**Comment by Generalcamo** [comment]
But that's not for this issue.
