### ISSUE TITLE
Switch track can direct carts travelling only west->east

### ISSUE THREAD

**Issue by JJablon** [Railcraft/Railcraft#1383]
Hi! I am using the steel spike maul to change the type of junction to a switch track. 
And no matter which direction is Steve (or my character in MP) looking when I click on a track with spike maul, there is always only possible to configure the junction to send carts right or straight. I'd like to be able to send cards travelling from east to west to the left or straight. 
I assume there is a bug or missing feature, or I wasn't able to find the information on a project page (the spike maul page does not even exist).
Also, the wye track does not solve my problem, as well as vanilla solution.
Minecraft 1.10.2, Forge 12.18.2.2107, RC 10.3.1.  installed both client and server-side.

**Comment by Forecaster** [comment]
You can switch the direction with a crowbar. Just like you've always been able to since before the spike maul.

**Comment by JJablon** [comment]
omg i can't believe I haven't figured it out. Thanks a lot!!!
