### ISSUE TITLE
Feed Station & Modded animals compatibility

### ISSUE THREAD

**Issue by Ghostlyr** [Railcraft/Railcraft#1384]
I have encountered a problem with breeding modified animals from [ImprovingMinecraft](https://minecraft.curseforge.com/projects/improving-minecraft) modification (with enabled `animals_genetic_evolution` option): all newborn entities lose their information about the generation and go wild (aggressive and unprofitable).  This is an important point of the mechanics of modification and this behavior creates difficulties.

Having little experience in programming, I decided to understand what was happening and to examine the Feed station code, after which I came to the conclusion that all processes are only simulated and no vanilla reproduction actually takes place. Spawns a completely new entity with standard values, just from the same instance. Consequently, is not on the IMC side therefore I am writing here.

IMC 1.12.1
Railcraft 10.2.0

Manually:
![2018-03-14_02 42 55](https://user-images.githubusercontent.com/8511068/37368802-762beef0-2731-11e8-86a1-6d7df262d296.png)
From feed station:
![2018-03-14_02 42 49](https://user-images.githubusercontent.com/8511068/37368801-75fe1aca-2731-11e8-9c43-ea08f175224e.png)

**Comment by liach** [comment]
I do not know how exactly is this thing handled in IMC after looking at decompiled code. We might need to fire events.

**Comment by liach** [comment]
Unfortunately this mod is not in 1.12, so we cannot support it very well in the future.
