### ISSUE TITLE
[1.10.2] Tunnel Bore doesnt drop into Chestcarts?!

### ISSUE THREAD

**Issue by Marcel40625** [Railcraft/Railcraft#1385]
Hey there, tried today the Tunnel Bore and it seems not dropping his items into linked Chestcarts

any idea?

Running: Railcraft 10.3.1 - MC 1.10.2

Edit: Pulling out of Chestcarts seems to work (Tracks and Coal) bot not dropping.

**Comment by liach** [comment]
Sorry for the late response, but I believe this is a duplicate issue. Duplicate of #1335.

**Comment by Marcel40625** [comment]
ohh okay ... any idea how close to the next update you guys are? (dont want to push, only interested)

**Comment by liach** [comment]
one month or more, but you can fix it via config.
