### ISSUE TITLE
Suggestion for Railcraft 1.12.2

### ISSUE THREAD

**Issue by border999** [Railcraft/Railcraft#1386]
I would suggest using the ender IO method to appease the insane gamers that desire your mod for 1.12.2.
http://ci.tterrag.com/job/EnderIO-Modules/
Put it up on jenkins or someplace and let people play with the incomplete port. People get their mod, (And see a disclaimer in chat about it being heavily incomplete), and you, the devs, get a dedicated workforce to hunt down bugs in what does function in the mod.

**Comment by liach** [comment]
Hmm, you mean to break rc modules into jars?

**Comment by border999** [comment]
That seems to be what Ender IO has been doing and it's working for them by all appearances. So yes, I would recommend that. If it is at all possible to do that without much inconvenience. Also I am one of the people that would love to have the firestone back, because that little stone is amazing.

**Comment by border999** [comment]
If it is at all possible to do that without much inconvenience.

**Comment by AEnterprise** [comment]
BC has also been doing it for quite a while, it can sometimes be a little confusing to new users that they are not additional modules but for more advanced players who only want parts of the mod it is much easier then using configs to dissable things, also for modpack makers possibly in the future

**Comment by LuigiHutch** [comment]
You do know RC is already modular right? Just not in seperate jars but in the module config. Also seperating the modules into seperate jars just means more time and work when porting.

Also a jenkins is not always useful, especially when it means that even more people to be using random outdated builds. Releasing more builds with known very WIP content can be quite a pain when dealing with bug reports resulting in more outdated and duplicate bug reports can be really demotivating.

CJ already distributes dev builds which are **only available for patreons** when he feels the mod is ready to be tested and bugs need to be found so I doubt a jenkins will be happening any time soon.

**Comment by liach** [comment]
@border999 Fyi porting is done. build from source if you wanna play.

**Comment by border999** [comment]
How would I go about doing that?

**Comment by liach** [comment]
Do `git submodule update --init --recursive` and then `./gradlew runClient`.

**Comment by border999** [comment]
not a sufficient answer for me, I have no experience when it comes to building from a source. I don't even know where that command would go, if there's some software I require.

**Comment by liach** [comment]
install git for windows/mac, open git bash, do git clone command to clone railcraft and run that 2 things. btw do you have a discord?

**Comment by LuigiHutch** [comment]
Well wait for the betas to be released, no need to reopen the issue as your questions have already be answered. Building source is not be recommended for normal users

**Comment by liach** [comment]
Well, this is the only mean allowed by the license

**Comment by border999** [comment]
@liach yep

**Comment by liach** [comment]
@border999 join https://discord.gg/VyaUt2r to talk more easily
