### ISSUE TITLE
[1.7.10 (All versions of RC)] Cannot place wye tracks back-to-back.

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#1387]
Everytime I would place the bottom-side of a wye track to a bottom-side of another wye track, either wye track would change orientation. I've tried rotating it with a crowbar but to no avail.

**Comment by Forecaster** [comment]
So rotate them with a crowbar after placing?

**Comment by kylesy20** [comment]
I forgot to mention that rotating with a crowbar doesn't work.

**Comment by liach** [comment]
You can do it. 
![2018-06-07_08 55 43](https://user-images.githubusercontent.com/7806504/41111370-9fc312d8-6a30-11e8-988e-c61e6e4e5f3c.png)

**Comment by kylesy20** [comment]
Okay, I'll try it again. Thanks
    On Thursday, 7 June 2018, 11:56:19 PM GMT+8, liach <notifications@github.com> wrote:  
 
 
You can do it.

**Comment by CovertJaguar** [comment]
Does this actually work? I expect the switch logic to fail as badly here as it does when you place corners next to switches.
