### ISSUE TITLE
Add back MJ-producing engines

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1388]
Edits by liach: This issue will, from now on, dedicate on tracking the progress of engines, instead of tracking in #1373. The Railcraft team has decided that when three steam engines are back, they will be producing microjoules. However, we are awaiting on BuildCraft's stablization.

Original issue:
Since BC has gone back to using MJ instead of RF, would it be possible to add an engine of some sort to output MJ as we will already have one for EU & FU/FE?

Thank you for taking the time to consider this request.

**Comment by 3TUSK** [comment]
#1232 ?

**Comment by bookerthegeek** [comment]
Almost. The previous versions of BC used the COFH api for power, but no longer.

Also they do not use the FU/FE either to my knowledge.

**Comment by liach** [comment]
this is likely only for 1.12

**Comment by AlexIIL** [comment]
Just FYI the BC MJ API isn't finalised yet, so I don't recommend adding anything *yet*.

**Comment by liach** [comment]
@AlexIIL Adding bc api as submodule is safe, right?

**Comment by AlexIIL** [comment]
Sort of. I'd recommend using our maven instead though (see https://www.mod-buildcraft.com/pages/maven.html for details) although the api will change in the future, so you would need to ensure you only use safe bits (as far as I know railcraft only uses the trigger and action API, which should be basically final - please check before using anything else, as it might change if I don't think anybody's using it).

**Comment by bookerthegeek** [comment]
As a small request in addition, would it be possible to make it a 2x3 multiblock similar to the EU turbine instead of a single block?

**Comment by Generalcamo** [comment]
Working on it now. Going to reimplement the engines first, then we can see about an MJ to Charge multiblock.

**Comment by liach** [comment]
FYI you should make a buildcraft module.

**Comment by Generalcamo** [comment]
Just to clarify: I'm not adding support for MJ just yet. The API is too unstable for that. I will however work on the engines as the MJ API is worthless without them.

Also this is no confirmation on that multiblock. I myself am not too keen on converting pneumatic power directly to charge; at the very least it should be pretty lossy.

**Comment by liach** [comment]
We are now sure that when the steam-powered engines are back, they will be producing MJ. Generalcamo is doing the most model design work.

**Comment by tungstonminer** [comment]
FWIW, while you're thinking about this, the [modpack](https://github.com/tungstonminer/brunel-3) I'm currently working on is based upon the combination of Immersive Engineering and Railcraft.  No Buildcraft.  No IC2.  I would love to have these engines in this modpack outputting RF power (or IF power) to be compatible with Immersive Engineering.
