### ISSUE TITLE
Add shield disabling ability to certain tools

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1390]
Currently, it is decided that spike mauls will be able to disable shields. Should we add it to crowbars (or crowbars with good enchantments)? Open for public discussion.

This can only be in 1.12.2 versions because of forge limitations.

**Comment by Forecaster** [comment]
Do you mean "bypass shields"?

**Comment by liach** [comment]
no, they give shields a delay so the defender cannot block for a few seconds.

**Comment by liach** [comment]
like what axes do.

**Comment by liach** [comment]
2f900abc20886a91347977fdee9fec23092b4834

**Comment by liach** [comment]
Closing for now since spike mauls should do.
