### ISSUE TITLE
1.12 Correct collision bounding boxes

### ISSUE THREAD

**Issue by vos6434** [Railcraft/Railcraft#1391]
you can walk through any block on 1.12
![2018-04-04_14 21 52](https://user-images.githubusercontent.com/21976486/38314924-42337204-381f-11e8-8c8f-7e1dc0403fb4.png)

**Comment by Player3324** [comment]
Most(?) of the AABBs lost their position offset, the port likely didn't account for this yet.

**Comment by liach** [comment]
Ah thanks @sfPlayer1. Luckily the mod uses an interface to account for aabbs for tile entities, that would not be very hard. Do you mean those ones which have their World parameters changed to IBlockAccess?

**Comment by liach** [comment]
Cannot reproduce after fixing some code style. Guess was a code style issue.
