### ISSUE TITLE
Dynamic light for optifine

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1392]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L472

**Comment by liach** [comment]
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/dynamic_lights.properties

**Comment by liach** [comment]
@luigihutch why is this bad? it will be a simple json file.

**Comment by LuigiHutch** [comment]
Because then that states that you 'officially' support optifine which I dont think is a great idea.

**Comment by liach** [comment]
Will close this for now since optifine does not yet support data-aware entity lights.
