### ISSUE TITLE
Update cofh api for 1.12

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1397]

**Comment by ZEROX7** [comment]
the crash log that was missing


---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.5.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/4/18 6:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.EnergyStorage, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.TileEnergyHandler, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyConnection, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyProvider, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyHandler, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyStorage, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyContainerItem, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar
    cofh.api.energy.IEnergyReceiver, loaded from: Railcraft_1.12.2-10.3.1-unofficial%20(1).jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.

	at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:64)
	at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:637)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1083350968 bytes (1033 MB) / 2229796864 bytes (2126 MB) up to 10498867200 bytes (10012 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11264m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                      | Source                                          | Signature                                |
	|:----- |:-------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCH   | mcp                  | 9.42                         | minecraft.jar                                   | None                                     |
	| UCH   | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.3.2678.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.3.2678                 | forge-1.12.2-14.23.3.2678.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | appliedenergistics2  | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar           | None                                     |
	| UCH   | bdlib                | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| UCH   | ae2stuff             | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
	| UCH   | morphtool            | 1.2-16                       | Morph-o-Tool-1.2-16.jar                         | None                                     |
	| UCH   | quark                | r1.4-123                     | Quark-r1.4-123.jar                              | None                                     |
	| UCH   | autoreglib           | 1.3-17                       | AutoRegLib-1.3-17.jar                           | None                                     |
	| UCH   | miscrails            | 1.0.0                        | Better-Railroads-1.0.0.jar                      | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | betterfoliage        | 2.1.10                       | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | codechickenlib       | 3.1.7.340                    | CodeChickenLib-1.12.2-3.1.7.340-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCE   | redstoneflux         | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCE   | cofhcore             | 4.4.1                        | CoFHCore-1.12.2-4.4.1.12-universal.jar          | None                                     |
	| UCH   | cofhworld            | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cookingforblockheads | 6.3.26                       | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCH   | dimdoors             | 3.0.8+271                    | DimensionalDoors-3.0.8-271.jar                  | None                                     |
	| UCE   | thermalfoundation    | 2.4.1                        | ThermalFoundation-1.12.2-2.4.1.15-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCE   | thermalexpansion     | 5.4.2                        | ThermalExpansion-1.12.2-5.4.2.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCE   | dyndyn               | 1.12.2-1.8                   | DynamicDynamos-1.12.2-1.8.jar                   | None                                     |
	| UCH   | dynamictrees         | 1.12.2-0.7.6                 | DynamicTrees-1.12.2-0.7.6.jar                   | None                                     |
	| UCH   | enderstorage         | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | exchangers           | 1.12.2-2.7.2                 | Exchangers-1.12.2-2.7.2.jar                     | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCH   | extracells           | 2.5.13                       | ExtraCells-1.12.2-2.5.13a56.jar                 | None                                     |
	| UCH   | shadowmc             | 3.8.0                        | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCH   | extrarails           | 1.3.0                        | ExtraRails-1.12-1.3.0.jar                       | None                                     |
	| UCH   | farmingforblockheads | 3.1.12                       | FarmingForBlockheads_1.12.2-3.1.12.jar          | None                                     |
	| UCH   | fastleafdecay        | v14                          | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | forgelin             | 1.6.0                        | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | ichunutil            | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | jei                  | 4.9.1.175                    | jei_1.12.2-4.9.1.175.jar                        | None                                     |
	| UCH   | ftblib               | 5.0.2.10                     | FTBLib-5.0.2.10.jar                             | None                                     |
	| UCH   | ftbutilities         | 5.0.2.10                     | FTBUtilities-5.0.2.10.jar                       | None                                     |
	| UCH   | gravestone           | 1.10.1                       | gravestone-1.10.1.jar                           | None                                     |
	| UCH   | hammercore           | 1.9.9.5.8                    | HammerCore-1.12.2-1.9.9.5.8.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | inventorytweaks      | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks        | 1.12.2-3.0.7-10              | IronBackpacks-1.12.2-3.0.7-10.jar               | None                                     |
	| UCH   | ironchest            | 1.12.2-7.0.42.827            | ironchest-1.12.2-7.0.42.827.jar                 | None                                     |
	| UCH   | jepb                 | 1.2.1                        | jepb-1.12-1.2.1.jar                             | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | justenoughbuttons    | 1.12-1.2                     | justenoughbuttons-1.12.2-1.2.2-5.jar            | None                                     |
	| UCH   | jeresources          | 0.8.7.41                     | JustEnoughResources-1.12.2-0.8.7.41.jar         | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCH   | malisisblocks        | 1.12.2-6.1.0                 | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCH   | malisisswitches      | 1.12.2-5.1.0                 | malisisswitches-1.12.2-5.1.0.jar                | None                                     |
	| UCH   | mcjtylib_ng          | 2.6.7                        | mcjtylib-1.12-2.6.7.jar                         | None                                     |
	| UCH   | moreoverlays         | 1.13                         | moreoverlays-1.13-mc1.12.1.jar                  | None                                     |
	| UCH   | oreexcavation        | 1.4.118                      | OreExcavation-1.4.118.jar                       | None                                     |
	| UCH   | p455w0rdslib         | 2.0.29                       | p455w0rdslib-1.12-2.0.29.jar                    | None                                     |
	| UCH   | railcraft            | 10.3.1-unofficial            | Railcraft_1.12.2-10.3.1-unofficial (1).jar      | None                                     |
	| UCH   | rangedpumps          | 0.5                          | rangedpumps-0.5.jar                             | None                                     |
	| UCE   | redstonearsenal      | 2.4.2                        | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | rftools              | 7.33                         | rftools-1.12-7.33.jar                           | None                                     |
	| UCH   | rftoolscontrol       | 1.8.1                        | rftoolsctrl-1.12-1.8.1.jar                      | None                                     |
	| UCH   | rftoolsdim           | 5.53                         | rftoolsdim-1.12-5.53.jar                        | None                                     |
	| UCH   | rftoolspower         | 1.0.0                        | rftoolspower-1.12-1.0.0.jar                     | None                                     |
	| UCH   | scannable            | 1.6.3.17                     | Scannable-MC1.12-1.6.3.17.jar                   | None                                     |
	| UCH   | shulkertooltip       | 1.3                          | ShulkerTooltip-1.3.jar                          | None                                     |
	| UCH   | signals              | 1.3.2-11                     | Signals-1.12.2-1.3.2-11-universal.jar           | None                                     |
	| UCE   | simplyjetpacks       | 2.2.3.33                     | SimplyJetpacks2-1.12.2-2.2.3.33.jar             | None                                     |
	| UCE   | solarfluxreborn      | 3.50r                        | SolarFluxReborn_1.12.2-3.50r.jar                | None                                     |
	| UCH   | spartanshields       | 1.4.1                        | SpartanShields-1.12.2-1.4.1.jar                 | None                                     |
	| UCH   | storagedrawers       | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCH   | sync                 | 7.0.2                        | Sync-1.12.2-7.0.2.jar                           | None                                     |
	| UCH   | theoneprobe          | 1.4.22                       | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCE   | thermalcultivation   | 0.2.0                        | ThermalCultivation-1.12.2-0.2.0.6-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCE   | thermaldynamics      | 2.4.1                        | ThermalDynamics-1.12.2-2.4.1.10-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCE   | thermalinnovation    | 0.2.1                        | ThermalInnovation-1.12.2-0.2.1.6-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | wanionlib            | 1.12.2-1.5                   | WanionLib-1.12.2-1.5.jar                        | None                                     |
	| UCH   | wct                  | 3.9.64                       | WirelessCraftingTerminal-1.12.2-3.9.64.jar      | None                                     |
	| UCH   | unidict              | 1.12.2-2.5b                  | UniDict-1.12.2-2.5b.jar                         | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.9.5.8.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.65' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 225 names; 278 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgQ2h1bmsgTG9hZGVyIGJsb2NrPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOkNodW5rTG9hZGVyPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBUZXNzZXJhY3QgYmxvY2s/IFtkZWZhdWx0OiBmYWxzZV0NCiAgICBCOlRlc3NlcmFjdD1mYWxzZQ0KfQ0KDQoNCmNsaWVudCB7DQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcmVwbGFjZSBlbmNoYW50bWVudCBnbGludCBjb2xvciB3aXRoIG1vcmUgbWF0Y2hpbmcgY29sb3JzIGZvciBzb21lIHZhbmlsbGEgaXRlbXM/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IkN1c3RvbSBFbmNoYW50bWVudCBDb2xvcnMgZm9yIFZhbmlsbGEgSXRlbXMiPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIHBvcnRmb3J3YXJkIHlvdXIgbG9jYWwgd29ybGQgd2hlbiB5b3Ugc2hhcmUgd2l0aCBpdCB0byBMQU4/DQogICAgIyBUaGlzIGZlYXR1cmUgZG9lc24ndCB3b3JrIG9uIGFsbCBjbGllbnRzLCB5b3UgYXJlIGdvaW5nIHRvIGdldCBhIG1lc3NhZ2UgaW4gY2hhdCBpZiBpdCB3YXMgc3VjY2Vzc2Z1bC91bnN1Y2Nlc3NmdWwgW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiTEFOIFVQblAiPXRydWUNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBNb2QgQnJvd3NlciBmZWF0dXJlIHRvIG1haW4gbWVudT8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiTW9kIEJyb3dzZXIiPXRydWUNCg0KICAgICMgUmVwbGFjZSB2YW5pbGxhIGZ1cm5hY2UgYW5kIGJyZXdpbmcgc3RhbmQgcHJvZ3Jlc3MgYmFycyB0byB1c2Ugc21vb3RoIHJlbmRlcmluZz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQ0KfQ0KDQoNCmRlYnVnIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgZGVidWcgcmF5IHRyYWNlciBpdGVtPyBbZGVmYXVsdDogZmFsc2VdDQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBkZWJ1ZyB6YXBwZXIgaXRlbT8gW2RlZmF1bHQ6IGZhbHNlXQ0KICAgIEI6WmFwcGVyPWZhbHNlDQp9DQoNCg0KaXRlbXMgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBBY2N1bXVsYXRvciBpdGVtPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOkFjY3VtdWxhdG9yPXRydWUNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgIyBTaG91bGQgSGFtbWVyQ29yZSB1c2Ugb2xkIG5ldHdvcmtpbmcgaW5zdGVhZCBvZiB0aGUgbmV3IChldmVudC1kcml2ZW4pIG9uZT8gW2RlZmF1bHQ6IGZhbHNlXQ0KICAgIEI6Ik9sZCBOZXR3b3JrIj1mYWxzZQ0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
	List of loaded APIs: 
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.64.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.4-123.jar
		* CoFHAPI (1.8.9R1.2.0B1) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* cofhapi (2.4.1) from CoFHCore-1.12.2-4.4.1.12-universal.jar
		* cofhapi|energy (1.8.9R1.2.0B1) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* farmingforblockheads|api (1.0) from FarmingForBlockheads_1.12.2-3.1.12.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* jeresources|API (0.8.7.41) from JustEnoughResources-1.12.2-0.8.7.41.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.9.1.175.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
		* QuarkAPI (2) from Quark-r1.4-123.jar
		* railcraft:API|core (3.2.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|carts (2.1.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|charge (3.2.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|items (2.4.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|signals (4.0.0) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* RailcraftAPI|tracks (5.1.1) from Railcraft_1.12.2-10.3.1-unofficial (1).jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.22.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.64.jar

**Comment by liach** [comment]
#1401
