### ISSUE TITLE
Locking tracks catch high-speed trains without explosions

### ISSUE THREAD

**Issue by Forecaster** [Railcraft/Railcraft#1399]
If a train going at high speed is caught by a locking track it should explode unless slowed down first.

This was not an issue before because locking tracks did not go on high-speed tracks, and high-speed trains would explode when going onto locking tracks because they were always a regular track.

When a high-speed train goes over a powered high-speed locking track nothing should happen.

I'm not sure if this can be classified as a bug or not. Probably can.

**Comment by liach** [comment]
Should we just disable such a combination @Forecaster?

**Comment by Forecaster** [comment]
...no?

Why would we do that? It should be made to work properly.

**Comment by Lilithvia** [comment]
To be honest, I think the train should explode, or derail or something if it is traveling at high speed on a high speed rail, and hits an unpowered locking rail.

Same if it hits a switch, wye, or vanilla junction.

**Comment by liach** [comment]
Fixed.
