### ISSUE TITLE
Server doesn`t start

### ISSUE THREAD

**Issue by korxal** [Railcraft/Railcraft#1403]
Hello,
Did some testing with server side:
1) Compile branch liach-1.12.2
2) Install clean forge-1.12.2-14.23.3.2691
3) Put Railcraft_1.12.2-10.3.1-unofficial-dev.jar to mods folder
4) Run server 
Crashed with: NoClassDefFoundError: Lmods/railcraft/common/util/effects/IEffectManager

Thanks for attention...

**Comment by liach** [comment]
1. dev jar is not for mod usages. it is for modders to add as a dependency.
2.the normal jar would crash to stop illegal distributions. 

if you need more help, ask me on discord.
