### ISSUE TITLE
Client Classes being loaded on server

### ISSUE THREAD

**Issue by Dockter** [Railcraft/Railcraft#1404]
It appears we are attempting to load client classes on the server.  This needs to be isolated out.

Caused by:  Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag

Link:  https://gist.github.com/Dockter/c9853339825b58451b5ca2512a1f91ab

**Comment by Dockter** [comment]
This commit fixes this however my branch is behind the current liach-1.12.2 due to the compilation errors stated on a different issue.

https://github.com/AlmuraDev/Railcraft/commit/d1e56bc8f4ea7cb28b9c86bd48cd1a799f594fbc

**Comment by liach** [comment]
Yep, that event bus loading method is funky indeed.

**Comment by Dockter** [comment]
Fixed.

**Comment by liach** [comment]
Thanks mike!
