### ISSUE TITLE
[1.12.2] Duplicate recipes registered

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1410]
## Heyo
Looking through recipes, I notice that many show up twice, or three times. For example the Cart Detector.
![Recipe45](https://i.imgur.com/0klOMZD.png)
![Recipe526](https://i.imgur.com/F01qAOK.png)

### List of items with Double recipes
- [ ] Cart Detector - Item
- [ ] Cart Detector - Any
- [ ] Cart Detector - Empty
- [ ] Cart Detector - Player
- [ ] Cart Detector - Animal
- [ ] Cart Detector - Tank
- [ ] Cart Detector - Advanced
- [ ] Cart Detector - Age
- [ ] Cart Detector - Sheep
- [ ] Cart Detector - Villager
- [ ] Cart Detector - Locomotive

### List of Items with Triple Recipes
- [ ] Cart Detector - Mob
- [ ] Manual Rolling Machine
- [ ] Powered Rolling Machine
- [ ] Feed Station
- [ ] Smoker

**Comment by xfl03** [comment]
`BlockDetector` which contains all detectors has been defined in two modules `AutoMation` and `Routing`.
`BlockMachineEquipment` which contains other blocks mentioned has been defined in three modules `AutoMation`, `Factory` and `Steam`.
It may be the reason of this issue.

**Comment by liach** [comment]
Resoved by #1437
