### ISSUE TITLE
[1.12.2] Missing recipes in JEI

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1411]
## Heyo
Here are some recipe related issues;
- Rock Crusher Recipes not showing up in JEI
- Rolling Machine recipes not Showing up in JEI
- Powered Rolling Machine crafts Small Charge Wire Spools for Free ([Image](https://i.imgur.com/gIaMXaa.png))

Working but not in JEI;
- Wooden Tie
- Creosote Wood Block
- Refined Firestone
- Metal Posts

Can not find recipes for the following;
- Force Track Emitter
- Trade Station
- Large Charge Wire Spool
- Any Electrode
- Charge Shunting Wire
- Track Parts
- Blank Tickets

**Comment by liach** [comment]
machines recipes are temporarily removed from jei because i don't understand jei that well yet. a few working recipes do not show up because they are of custom types.

**Comment by liach** [comment]
Now everything except JEI conpat is fixed.

**Comment by xfl03** [comment]
The third problem may has been fixed in https://github.com/Railcraft/Railcraft/commit/101b6cde9c48d1ea717e624020ab99fa144694c8

**Comment by liach** [comment]
Yep. Actually before your commit, it already stops giving free items (or stops giving any output) :trollface:

**Comment by liach** [comment]
This should be totally fixed by #1487. I will test.

**Comment by liach** [comment]
According to the picture in #1494, the jei integration should be complete now. Closing.

**Comment by TimGoll** [comment]
Can confirm, the JEI integration seemed complete to me

**Comment by Carnaxus** [comment]
A quick addendum: Adding Just Enough Resources at least partially reintroduces this bug; I couldn't get the rolling machine recipes for the charge wire coils to show up until I removed JER.

**Comment by kappa-maintainer** [comment]
@Carnaxus Could you post your whole mod list? I have this problem too, but can't fix it by removing JER

**Comment by Carnaxus** [comment]
> @Carnaxus Could you post your whole mod list? I have this problem too, but can't fix it by removing JER

@kappa-maintainer

Advanced Machines 61.0.0 (IC2 addon)
Advanced Machines Patcher 1.0
Advanced Solar Panels 4.3.0 (IC2 addon)
AdvSolarPatch 1.2.1
BetterFPS 1.4.8
Buildcraft 7.99.24.8
Chameleon 4.1.3
ChickenChunks 2.4.2.74
Chisel 1.0.2.45
CodeChickenLib 3.2.3.358
Connected Textures Mod 1.0.2.31
EnderStoarge 2.4.6.137
FoamFix 0.10.14 (disabled, game refused to launch)
ForgeMultipartCBE 2.6.2.83
IC2 2.8.221 experimental
JourneyMap 5.7.1
JEI 4.16.1.302
JER 0.9.2 (disabled)
Logistics Pipes 0.10.3.114
MrTJPCore 2.1.4.43
NEI 2.4.3.245
OpenBlocks 1.8.1
OpenModsLib 0.12.2
OreExcavation 1.4.150
Project Red 4.9.4.120 (all parts)
Railcraft 12.0.0
Storage Drawers 5.4.2
WAILA 1.8.26 B41 (HWYLA)
WAILA Harvestability 1.1.12
