### ISSUE TITLE
[1.12.2] GUI item tooltip issue

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1412]
## Heyo
When you are in the Rolling Machine Interface, items do not show there name when you hover over them.
![Image](https://i.imgur.com/uAhXcHc.png)
![Image](https://i.imgur.com/xpW6itj.png)

**Comment by liach** [comment]
this is the case for all railcraft guis

**Comment by tomelfring** [comment]
I remember fixing something like this.
You need to add the following to the gui classes:

	@Override
	public void drawScreen(int mouseX, int mouseY, float partialTicks) {
		this.drawDefaultBackground();
		super.drawScreen(mouseX, mouseY, partialTicks);
		this.renderHoveredToolTip(mouseX, mouseY);
}

**Comment by liach** [comment]
Fixed in one of the recent commits.
