### ISSUE TITLE
Charge system/ Tile entities reset after world reload

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1413]
That when you click with a charge meter, it no longer works. The rendering changes fine, though

**Comment by liach** [comment]
This is actually confirmed again. Just put it with a force track emitter and observe the track emitter draw the track back after the world has been reopened.

**Comment by liach** [comment]
Fixed by 7316d4d

**Comment by liach** [comment]
8743eee9892b5d6fafbf7ad77f4305ea3c145fc0

**Comment by liach** [comment]
uh camo, leave a comment at least

**Comment by liach** [comment]
Uh, not fixed per camo's comment.

**Comment by CovertJaguar** [comment]
I don't even know what this is about, closing unless further details provided.

Is this different from #1505?

**Comment by liach** [comment]
it was fixed as emitters now behave correctly after a reload.
