### ISSUE TITLE
Client loading error - API class not found

### ISSUE THREAD

**Issue by Dockter** [Railcraft/Railcraft#1414]
Error:  https://gist.github.com/Dockter/c599ea19c2618aab2f647b0adc8a8782

Branch: Liach-1.12 - as of 5/21/2018

**Comment by Dockter** [comment]
Disabling:      B:manipulator_loader_rf=false  within blocks.cfg did not help the matter.

**Comment by liach** [comment]
Can you try build 2cbefd885cfe7197c62edbce06be79c196ff8a7f?
