### ISSUE TITLE
ColorPlugin (ColorProxy instance) always null

### ISSUE THREAD

**Issue by Dockter** [Railcraft/Railcraft#1415]
Class:  https://github.com/Railcraft/Railcraft/blob/liach-1.12.2/src/main/java/mods/railcraft/common/plugins/color/ColorPlugin.java#L26

Any Item or Block Class that calls:  

ColorPlugin.instance.register(this, this);

will fail because "instance" is null.  Verified with debug.  

Confirmed in Production mode with Railcraft ONLY, no other mods.

**Comment by Dockter** [comment]
Stumbled upon fix, pushing PR shortly.

**Comment by liach** [comment]
Fixed in #1416. Thanks doc! btw the blast furnace is fixed in the last commit.
