### ISSUE TITLE
Cargo Cart Visual Glitch and Cargo Cart Loader freezing bug

### ISSUE THREAD

**Issue by Ang3lOfD3ath** [Railcraft/Railcraft#1420]
https://www.youtube.com/watch?v=A5oOFBnrrI4

**Comment by liach** [comment]
so it's loading and content render

**Comment by Ang3lOfD3ath** [comment]
the loader freezing seems to only happen to the cargo cart and i have to open the cart and click an empty slot for it to start loading again........ i also closed my game and relaunched it and all the Cargo carts that have cobble in them did not render any thing in them till i opened the carts

**Comment by liach** [comment]
hmm, same as that tank issue

**Comment by liach** [comment]
Didn't investigate loader freezing, but rendering bug will be fixed in next commit on 1.12.2 branch.

**Comment by liach** [comment]
@Ang3lOfD3ath What happens before you discover the loader freezing? did you quit and reload the world? I tried to quit and reload but was unsuccessful at reproducing the loader freezing.

P.M. I edited so many times because I write so many typos today.

**Comment by Ang3lOfD3ath** [comment]
i think the chunks unloaded then i came back to the chunks

i cant get the twitch client to open i also cant upload at the moment ....

**Comment by liach** [comment]
Since I cannot replicate loader issue and that the loader issue is fixed, I am closing this. Feel free to request reopen with more evidence.
