### ISSUE TITLE
[1.12.2] Uncrafting carts crash the game

### ISSUE THREAD

**Issue by Stantrien** [Railcraft/Railcraft#1422]
Placing a chest cart or any other block-in-cart in a crafting table and taking the item out crashes to desktop.

**Comment by liach** [comment]
@Stantrien Please give a crash report.

**Comment by Stantrien** [comment]
[crash-2018-05-29_20.12.10-client.txt](https://github.com/Railcraft/Railcraft/files/2052092/crash-2018-05-29_20.12.10-client.txt)

This was with a tank cart.

**Comment by liach** [comment]
https://gist.github.com/liach/b9b113220e5cf51de1b7a4d9887ca612
