### ISSUE TITLE
[1.12.2] Exiting Manual Rolling Machine gui mid-craft crashes to desktop

### ISSUE THREAD

**Issue by Stantrien** [Railcraft/Railcraft#1423]
[crash-2018-05-29_20.16.57-client.txt](https://github.com/Railcraft/Railcraft/files/2052102/crash-2018-05-29_20.16.57-client.txt)

**Comment by liach** [comment]
https://gist.github.com/liach/6ecfbdfc6b81103beec1c60549fdec24

**Comment by liach** [comment]
Will push a fix shortly.
