### ISSUE TITLE
Railcraft 1.7.10 Copper Ingots messing up Traincraft counter-parts

### ISSUE THREAD

**Issue by 777Gaming** [Railcraft/Railcraft#1424]
Hi, I use multiple mods such as Traincraft and Railcraft. I use the 1.7.10 versions and I have a problem. Ever since I installed Railcraft, I haven't been able to make TC copper ingots and only the RC ones. So maybe a patch could be released adding RC  Copper ore to the 1.7.10 version? Because I want to be able to make the TC Ingots a lot more than the RC ones because I use TC a lot more. Thanks!

**Comment by liach** [comment]
Aren't they interchangeable? You can use minetweaker to add them to the same ore dictionary `ingotCopper` and see if that helps.

**Comment by liach** [comment]
Closing as this is relatively obsolete.
