### ISSUE TITLE
bc transformer

### ISSUE THREAD

**Issue by vos6434** [Railcraft/Railcraft#1428]
![bc transformer](https://user-images.githubusercontent.com/21976486/40814041-f7eb0b14-6535-11e8-9542-301af27def90.png)

**Comment by Generalcamo** [comment]
What exactly is this for? Some sort of conversion from MJ to Railcraft Charge?

**Comment by Generalcamo** [comment]
Vague issues like this are neither needed nor warranted. We cannot implement something that is not explained. Please open a new issue describing exactly what you mean.
