### ISSUE TITLE
add coal gas (coke oven gas)

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1434]
(This is one of the ways Railcraft can attract users)
Coal gas is something like natural gas. It was used to light things in history. It can also be a component of ChemLab. Comments are welcome!

**Comment by liach** [comment]
First, the coal gas will be produced in coke oven. It then can be used as fluid fuel, or as some equivalent of steam (another power system)

**Comment by Generalcamo** [comment]
Definitely not an equivalent of steam. It doesn't have the pressure capable of handling that.

**Comment by liach** [comment]
I mean it is a type of power unit, just like how steam is considered as eu/rf/charge

**Comment by ReiDaTecnologia** [comment]
Guys i really liking this idea! i hope be added because look good!

**Comment by Generalcamo** [comment]
It's not even close to steam @liach. The closest equivalent is raw coal.

**Comment by Natesky9** [comment]
Maybe as an internal unit, but I can't see this working anywhere except as a side-by-side multiblock for passive charge. I just don't think it has the potential. Coal coke, and even charcoal, are treated as products and not always produced to create power. They're consumed, yes, but trying to build a system around the production of something leads to logistical nightmares

**Comment by liach** [comment]
it's a fluid for fuel and chemlab.

**Comment by Generalcamo** [comment]
If this is for the chemlab, then let's wait on the implementation until we have actual uses. We have enough fuel sources as-is being quite honest.

**Comment by liach** [comment]
Rejected per private discussion.

**Comment by CovertJaguar** [comment]
SynGas was always planned.... Coke + Steam in the ChemLab.
