### ISSUE TITLE
Cargo Carts 1.7.10

### ISSUE THREAD

**Issue by Hakameda** [Railcraft/Railcraft#1435]
Cargo Carts seem to refill the Locomotive while it's attached. Is that intended or anyway to disable. Great for charcoal i'm emptying from the ovens, but it also takes wood and uses it as fuel for Locomotive instead of fuel to coke ovens

**Comment by liach** [comment]
taking wood is intentional right now. however, it's a good suggestion to remove this annoying feature or to add a filter.

**Comment by Hakameda** [comment]
It would be okay to pull charcoal or something. But even if i can just smack a cargo cart to tell it not to refill

**Comment by Forecaster** [comment]
It's not an "annoying feature". You can prevent it pulling from a cart by putting a cart of a different type, like a tank cart, between the cargo cart and the locomotive.

Adding a filter to the locomotive for fuel is a good idea though.

**Comment by Hakameda** [comment]
I have it set pulling 3 charcoal carts then wood. Pulls wood but not
charcoal

**Comment by liach** [comment]
Hmm, this behavior is not very acceptable. Should have that one fixed. (in 1.10.2+ though)

**Comment by Hakameda** [comment]
=(

**Comment by Lilithvia** [comment]
1.12.2 release is a farther ways off then a build to add fuel filters to locomotives.

**Comment by liach** [comment]
Just fill one of the desired fuel in each slot of the locomotive fuel slots instead.
