### ISSUE TITLE
[1.10.2] Flux Transformer requires reopening of world.

### ISSUE THREAD

**Issue by coolnickname** [Railcraft/Railcraft#1440]
After first building the transformer it doesn't do anything. As you can see in the screenshot below it has an efficiency of 100%. After closing and re-opening the world this drops to 80%, loss to 0.5 c/tick and it starts working.

Before the restart the magnifying glass says it's a valid multiblock but it doesn't draw any power from connected Immersive Engineering capacitors (RF batboxes basically).

https://i.imgur.com/vRuCWoJ.png
(screenshot from before reopening the world)

Other multiblocks seem to not be affected (tested with the water tank and coke oven).

This was tested with the main branch for 1.10.2 and a few hours ago [this commit](https://github.com/Railcraft/Railcraft/commit/fa786e1dc43e2a56c4fe2a14455dc9f3a875dbad) was pushed on the main 1.10.2 branch but I'm not sure if it will fix the issue.

EDIT: I was using the normal 1.10.2 branch not @Liach's branch.

**Comment by liach** [comment]
@coolnickname Can you test with my 1.12.2 branch, too?

**Comment by coolnickname** [comment]
Maybe later today. I have stuff to do but if I find some time I'll try it out.

**Comment by liach** [comment]
Fixed on 1.12.2.
