### ISSUE TITLE
Old recipes missing

### ISSUE THREAD

**Issue by MCTian-mi** [Railcraft/Railcraft#1443]
![unknown](https://user-images.githubusercontent.com/35869948/41533199-8c3de1f2-732c-11e8-8849-e11714f71028.png)
Cannot use tank.

**Comment by liach** [comment]
fixed by generalcamo on 1.12.2.

**Comment by Generalcamo** [comment]
Well I didn't add support for using a Buildcraft Tank yet, but I'm certain once the compatibility module is completed there then I can add support for it.
