### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1445]
Look into replacing our old achievements with advancements, and adding a clear tech tree with recipes throughout the system.

Blast Furnace, Coke Oven, Rock Crusher, and Rolling Machine recipes will also need to be added to the system.

**Comment by liach** [comment]
Really? No comments? Ah. I suggest advancements for firestones too

**Comment by liach** [comment]
A few thoughts
1. coke oven -> blast furnace -> steel -> rock crusher
2. find copper, tin, and zinc-> bronze and brass -> brushing -> bronze rolling machine -> rail -> track
3. rock crusher -> firestone
4. boxes (should we make a signal casing. etc. that can be made of various metals?) and signals
5. worldspikes
6. find metals -> fllux transformer/battery/charge feeder
7. steel -> powered rolling machine
8. iron tank -> steel tank
9. steel -> metals chest
10. steel -> trade station
11. steel -> steam/electric loco
12. crowbar/spike maul
13. magnifying glass/goggles
14. loot workshop
15. carts?
16. track kits?

These are the major themes I can think of.

**Comment by liach** [comment]
Currenly as I've implemented:
- carts
  - bed
  - jukebox
  - linking
  - seasonal (pumpkin/gift)
    - season crowbar

- Tracks
  - coke oven
    - strap iron track
    - spike maul
    - manual rolling machine
      - regular track
      - kits
    - blast furnace
      - high speed track
      - rock crusher
        - firestone

**Comment by AlexJ6301** [comment]
Advancement for using signals, and maybe for having, say, two trains waiting on signals at once (that then change). 

Advancement for using routing tables.

**Comment by liach** [comment]
This issue is blocked by the addition of a stirling generator. #1482

**Comment by liach** [comment]
For signals and routing, I would suggest leaving them out. We need to add improved signal blocks. The routing table is not clear enough, too.

**Comment by LuigiHutch** [comment]
An RC advancement spreadsheet @liach asked me to setup: https://docs.google.com/spreadsheets/d/1Vyz0Ou92INNBlzAUzGLQVN0e4_c9LKVLlMzZv4lqRr8/edit?usp=sharing

**Comment by liach** [comment]
I think the current structure is fine; people did not bring up more ideas in discord either.
