### ISSUE TITLE
[1.12.2] Mod build failed

### ISSUE THREAD

**Issue by BinaryVigilante** [Railcraft/Railcraft#1448]
Hi,

I wanted to build Railcraft for Minecraft 1.12.2. So I downloaded the code, unziped, and ran gradlew.
Immediately I get this error:

------------------
FAILURE: Build failed with an exception.

* Where:
Build file '/home/someguy/Downloads/Railcraft/Railcraft-mc-1.12.2/version/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':version'.
> Cannot get property 'version_minecraft' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

------------------

Just let me know if there are any more information that you need :)
I'm using Kubuntu 18.04 btw.

Have a great day!
Kind regards!

**Comment by Generalcamo** [comment]
Import submodules and reload Gradle. See what happens then. If it still fails redo setuoDecompWorkdpace

**Comment by Kreatifchk** [comment]
How to do this?

**Comment by BpArCuCTeMbI** [comment]
Read a "Building" section in a README.
```
git submodule init
git submodule update
```

**Comment by Generalcamo** [comment]
Get on discord if you need additional help.

**Comment by liach** [comment]
never download zip in the future
