### ISSUE TITLE
Request: Update Curseforge mod page

### ISSUE THREAD

**Issue by BinaryVigilante** [Railcraft/Railcraft#1451]
Hi!

Would it be possible to update the curseforge page for railcraft by uploading a 1.12.2 version of the mod? I know it's here on Github for MC 1.12.2, but I think it would be nice to have the curseforge updated as well.

Speaking of updated, the railcraft website should be updated as well :)

Just suggesting ;)

Kind regards!

**Comment by liach** [comment]
Duplicate of #1448. See https://github.com/Railcraft/Railcraft/issues/1448#issuecomment-400718836

**Comment by BinaryVigilante** [comment]
How is this a duplicate? In that one I had problems building the mod. Here I'm simply asking if it's possible to update curseforge and the railcraft website with a 1.12.2 version of the mod...

**Comment by liach** [comment]
your best bet is pinging covertjaguar for a public alpha

**Comment by liach** [comment]
(on discord)

**Comment by liach** [comment]
Curseforge releases are only made by CovertJaguar. In general, requests like this would never work, and such requests are not related to Railcraft itself. If you are really a noob, look at #1454
