### ISSUE TITLE
Replace the sorting of railcraft modules with topological sort

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1453]
The current sorting mechanism is a funky one. A toposort is easy to write and helpful for fast sorting of modules (like how forge sort mods) Just a reminder. If someone wants to write one, it's welcome, too.

**Comment by liach** [comment]
Oh by the way I might write a tarjan's scc to detect cycles, too.

**Comment by CovertJaguar** [comment]
It's not "funky", its just a depth first search topological algorithm.
https://en.wikipedia.org/wiki/Topological_sorting#Depth-first_search

**Comment by liach** [comment]
The issue is the construction of load order that is inefficient. https://github.com/Railcraft/Railcraft/blob/6e91f36a963d34e48cd4dacf1a24691ba077e232/src/main/java/mods/railcraft/common/modules/RailcraftModuleManager.java#L172 Linked lists handle `contains` methods at `O(n)`, which is somewhat a big hit.

**Comment by liach** [comment]
In my opinion, we should pull dependency information to local variables to speed up the process instead of looking up in the annotation repeatedly at the same time.

**Comment by CovertJaguar** [comment]
Never said it was efficient, just that it wasn't funky or unusual. =P

Are annotations actually that slow?
