### ISSUE TITLE
Running instructions for Minecraft 1.12.2

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1454]
For many of you who anticipate Railcraft for Minecraft 1.12.2, I hereby create a ticket listing instructions for running. (Yeah, markdown is a great tool for making posts)

### Before you begin everything
- **Review the [License](https://github.com/Railcraft/Railcraft/blob/indev-1.12.2/LICENSE.md#source) of Railcraft: You cannot distribute jars!**
- **When you have questions, go to [Railcraft's official Discord server](https://discord.gg/xRk8MnD) instead of opening issues here! (Comments are already disabled here)**
### How to test run
- Make sure you have ***[JDK 8u100+](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)*** (JDK 9+ will break Minecraft, old JDK 8 will break BuildCraft dependency) and [**Git**](https://git-scm.com)
- Find a directory where you desire to put Railcraft folder in. I will call this directory *root* in the later parts of the guide.
- Open Git Bash in *root*. (For Windows users, you can right click the folder and find `open Git Bash` option)
- In the Git Bash, execute 
```
git clone --branch=indev-1.12.2 --recurse-submodules https://github.com/Railcraft/Railcraft
```
- If you wish to run other mods with Railcraft, put mods in `Railcraft\run\mods` folder.
- If you wish to play in online mode, create a file `gradle.properties` in `Railcraft\` directory with the following content (replace `<username>` with your Mojang login email and `<password>` with you Mojang account password)
```
mcUsername=<username>
mcPassword=<password>
```
- In the Git Bash, execute
```
cd Railcraft
./gradlew runClient
```
After a while, the Minecraft UI will appear. You will be able to play Minecraft 1.12 with Railcraft.

If and only if you find a bug ***in game*** can you [report an issue to Railcraft](https://github.com/Railcraft/Railcraft/issues/new). Otherwise, the issue created will be immediately locked, closed, and marked as invalid and duplicate. If you found a bug with this post, go to [Railcraft's official Discord server](https://discord.gg/xRk8MnD) and ping `@liach` on the server.

**Comment by Forecaster** [comment]
Check here instead:
https://github.com/Railcraft/Railcraft/wiki/Running-instructions-for-Minecraft-1.12.2
