### ISSUE TITLE
After building the mod, minecraft crashes

### ISSUE THREAD

**Issue by BinaryVigilante** [Railcraft/Railcraft#1459]
Hi,

I finally figured out how to build the mod. After I build it, I put it in my mods folder, and launched Minecraft where thereafter I get a crash. here is the log:

https://pastebin.com/it7FWS6w

If you need any additional information I will do what I can :)

**Comment by thedustboy** [comment]
The crash is intentional. You're only allowed to use the mod in a dev environment, not build a jar file. Read the log, the jar is unsigned and will not run.

**Comment by Generalcamo** [comment]
This is specifically to prevent unauthorized distribution in modpacks and throughout the community of a potentially buggy build, and definitely unfinished build. If you want to run it, you must run it in the dev environment.

**Comment by BinaryVigilante** [comment]
I can't believe why there aren't any 1.12.2 versions available for download...

**Comment by Dockter** [comment]
You are welcome to help contribute code to getting this mod updated to 1.12.2

**Comment by liach** [comment]
see #1454 for some help

**Comment by BinaryVigilante** [comment]
I mean a mod doesn't have to not have errors to be released. There are many mods that are alpha or beta, and they have files ready for you to install and play.

**Comment by liach** [comment]
but only covertjaguar can release the mod and patreons and conttibutors are supposed to test it first

**Comment by BinaryVigilante** [comment]
I don't use discord.. so I can't get in contact :( Does he have twitter?

And also, by making an alpha or beta version available for people, issues might be found much faster than if it's just a group of people. (Not saying you are ineffective, just saying with more people, more can be done on that part ;))

**Comment by liach** [comment]
@BinaryVigilante https://twitter.com/CovertJaguar 
You can go onto IRC if you refuse using discord, see https://github.com/Railcraft/Railcraft#official-links

**Comment by liach** [comment]
FYI some insider info: there is debugging by enthusiasts going on 
![image](https://user-images.githubusercontent.com/7806504/42353487-80efe556-8075-11e8-962c-85e46d37b59b.png)

**Comment by BinaryVigilante** [comment]
Thanks for the link!
And thanks for the info! I did not know that part :) Thanks!

Don't get me wrong, I love this mod! I just really wanted it on my server where I play with some friends, but I guess I'll wait till the next full release ;) Keep up the good work! :D
