### ISSUE TITLE
Allow ability for locos to pull from multiple cart types

### ISSUE THREAD

**Issue by Lilithvia** [Railcraft/Railcraft#1461]
I think it would be an asset if carts such as locomotives could pull resources from a cargo or chest cart, then a tank cart if that tank cart is attached to the chest or cargo cart.

This would especially be useful when using locomotives to create longer railway stretches without being able to supply water readily at such distances.

**Comment by Forecaster** [comment]
The biggest bottleneck to travel distance is water, fuel is very dense. If you want to extend range focus on tank carts.

**Comment by liach** [comment]
Duplicate of #1372

**Comment by Lilithvia** [comment]
While I get that is the current strategy to overcome this, the user should be able to automatically resupply via carts.

**Comment by Lilithvia** [comment]
This isn't a duplicate of #1372 as it assumes that bug is fixed, but rather suggests the locomotive should be able to pull from two different carts at the same time.

**Comment by liach** [comment]
Then it is a duplicate of #635

**Comment by Lilithvia** [comment]
Not really.
#635 ended up with CovJ fixing the behavior mentioned so locomotives couldn't pull from multiple types of carts at once.

**Comment by Lilithvia** [comment]
A single locomotive should be able to pull from tank and cargo carts attached to each other

**Comment by Lilithvia** [comment]
Currently that behavior doesn't exist, and the behavior mentioned in #635 relies on the use of a oversight to work.

**Comment by liach** [comment]
@Lilithvia That issue is not fixed. The behavior is not yet determined. As you requested, I will increase the priority of #635, but leave no more comment here. Go to #635 instead.

**Comment by Lilithvia** [comment]
Will do
