### ISSUE TITLE
Copper ingot compatibility

### ISSUE THREAD

**Issue by AnxQ** [Railcraft/Railcraft#1463]
The copper ingot (railcraft:ingot) does not compatible with the one in Industrial Craft 2 (ic2:ingot)
In fact, the map does not generate a single copper ore (railcraft:ingot) in the entire world...
Is there something wrong with my config?
Running Minecraft Server on Ubuntu with JDK8.
Minecraft Version: 1.10.2
Railcraft Version: 10.3.1
IC2 Version: 2.6.254-ex110
Forge Version: 12.18.3.2185

**Comment by liach** [comment]
What does "compatible" mean here?

具体是没法用工业铜锭代替铁路铜锭合成还是什么别的问题？

**Comment by AnxQ** [comment]
对 ic2的铜锭不能代替rc的铜锭

**Comment by liach** [comment]
I can fix this in the 1.12 branch. However, the fix won't be released in a while, so you can install CraftTweaker mod and change the current recipes 
with it.
我可以在 1.12 中修复，但是修复后需要很久才能放出，可以临时使用 CraftTweaker 调整配方。

**Comment by liach** [comment]
Fixed in 1.12 already.
