### ISSUE TITLE
Tracks don't emit redstone the same way as vanilla

### ISSUE THREAD

**Issue by ZodiacTrinity** [Railcraft/Railcraft#1465]
The directional detector track should work like vanilla detector track but it emit a signal redstone only next to the block and not under the block of track like vanilla.

![dectetor_track_vanilla](https://user-images.githubusercontent.com/41287065/42754336-6948fd02-88f4-11e8-8fbd-a30535e100cc.jpg)

![detector_track](https://user-images.githubusercontent.com/41287065/42754343-6cee1c8a-88f4-11e8-8d2d-872ca3d84b00.jpg)

Railcraft 9.12.2.0
Forge 10.13.4.1614

**Comment by liach** [comment]
As far as I can see the track is not emitting strong power but it should. Unfortunately I am not able to make a fix for Minecraft 1.7 versions; I can try to get this in for the Minecraft 1.12 version instead.
