### ISSUE TITLE
Migrate to IItemHandler

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1468]
Migrate to IItemHandler when MinecraftForge/MinecraftForge#5033 is merged. Should fix mod interaction with mods that fully implemented it (see #1190).

**Comment by liach** [comment]
Well, we will just accept item handler capabilities before the vanilla interfaces. This should be easy enough (the capabilities can be added to our base classes and is easy to implement: just use forge's sidedwrapper)

**Comment by liach** [comment]
camo, I think we can bump forge now.

**Comment by liach** [comment]
Patched the root classes.

**Comment by Generalcamo** [comment]
That isn't a full migration, especially for the manipulators. I'm assigning @CovertJaguar to handle them, as he already partially started on it.

**Comment by liach** [comment]
manipulators are already covered in item tiles.

**Comment by liach** [comment]
Now our invs appear as item handlers to other mods, but we yet need use item handlers.

**Comment by liach** [comment]
We exposed our invs as handlers but do not yet use others' handlers.

**Comment by liach** [comment]
Cj recently refactored inventories again. as i see, now adaptors favor handlers over vanilla interfaces. good.
