### ISSUE TITLE
About .jar file

### ISSUE THREAD

**Issue by DLumina** [Railcraft/Railcraft#1469]
I have waited long for an Railcraft release for 1.12.2, and I tried to follow the instructions on the Internet to compile the source code but failed(since I do not know about Java), so...do you have any plans for an beta version .jar file on curseforge or github?

Thanks a lot for your contributions to my second favorite mod(well, the first one may be botania).

**Comment by 3TUSK** [comment]
1. No compiled version available.
  2. Be patient.
  3. Wanna try new version? Run `gradlew runClient` directly. No extra tools needed.
