### ISSUE TITLE
What to do please help

### ISSUE THREAD

**Issue by ObsidianFury** [Railcraft/Railcraft#1472]
A mod has attempted to assign Block mods.railcraft.common.fluids.BlockRailcraftFluidFinite@5571554
f to the Fluid 'steam' but this Fluid has already been linked to the Block cofh.thermalfoundation.fluid.BlockFluidSteam@46a0e967. You may
 have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.

**Comment by liach** [comment]
It does not crash the game. Come on, no railcraft steam would be placed because Railcraft ask for fluid blocks from forge, which reports the first fluid block registered (in this case, CoFH steam). You will always get CoFH steam which will not hurt.

**Comment by CovertJaguar** [comment]
Unless your server and client have different mod load orders, then all bets are off.
