### ISSUE TITLE
Electric Locomotive can't dyeing（1.12.2）

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Railcraft/Railcraft#1473]
https://upload.cc/i1/2018/08/06/6ni2Lq.png

**Comment by liach** [comment]
@1a2s3d4f1 试试看在机车头上放一格，底下也放一格染料(看wiki)

**Comment by 1a2s3d4f1** [comment]
@liach https://upload.cc/i1/2018/08/06/97bGqn.png
也不行

**Comment by liach** [comment]
@1a2s3d4f1 截图看看

**Comment by 1a2s3d4f1** [comment]
@liach  https://upload.cc/i1/2018/08/06/AmILtj.png
蒸汽机车也不能染色
所有染色合成失效了
