### ISSUE TITLE
[1.12.2] Request for permission regarding modpacks

### ISSUE THREAD

**Issue by MainFreak** [Railcraft/Railcraft#1476]
Hello. 

I know that this is probably an annoying question to a lot of mod developers by now, but I wanted to ask for permission to use the 1.12.2 Beta version of RailCraft in a 1.12 port of my 1.10 modpack. 

Since this version is not on CurseForge I am positive that the FTB team will want this from me in order to publish it on their Launcher/Curse. The pack will stay closed beta for about 2-3 weeks before I actually publish it anywhere but I would still like permission to distribute the version to a closed circle right now.

**Comment by MainFreak** [comment]
Oops just saw something regarding this being done via discord. Sorry!

**Comment by CovertJaguar** [comment]
Or you could have just read the license...
