### ISSUE TITLE
Auto "unstick" of carts on unpowered coupler track kit

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1477]
Currently, there are two modes for the couploer track kit: sticky mode and unlink mode. An unstick mode would help in case of shunting.

**Comment by Generalcamo** [comment]
I don't understand: Exactly what do you want here and how should it differ from the existing unlink mode? Don't make a vague issue and then label it as a "good first issue" as it will create incentives for messy PRs as the issue wasn't defined well in the first place.

**Comment by liach** [comment]
you know rc adds a cart ability to allow carts to link when they collide. the new mode means to remove that ability.

**Comment by Lilithvia** [comment]
Basically what Liach was saying in a somewhat more easily understandable form (no offense Liach) was unstick mode wouldn't function like unlink, but rather remove the ability from carts to link together when colliding via sticky mode.

**Comment by Generalcamo** [comment]
This should be handled already by an unpowered auto-coupler. If it isn't, then it's an oversight and should be looked into.

**Comment by Lilithvia** [comment]
Isn't that the same as unlink?

I'm guessing what Liach wants is something that won't unlink, but will unsticky carts.

**Comment by Lilithvia** [comment]
I'm guessing what Liach wants is something that won't unlink, but will unsticky carts.

**Comment by liach** [comment]
This is extremely easy to work on.

**Comment by liach** [comment]
Resolved in c7487b5707039e4e478b3d560818fadb4a799e53
