### ISSUE TITLE
Multiplayer safety

### ISSUE THREAD

**Issue by Hugoland** [Railcraft/Railcraft#1480]
Hello, 
before I install this mod on my server, I need to know if, when a train is placed by an OP, all linked carts will be protected so other players can't break them, in the 1.7.10 version.
Thanks.

**Comment by liach** [comment]
unfortunately you need a protection plugin to achieve that function plugin if you are on cauldron. Or you can try forgeessentials.

**Comment by Hugoland** [comment]
Thanks for your answer.
So all new carts in this mod can be protected using WorldGuard "vehicle-destroy" flag, right ?

**Comment by liach** [comment]
I think it should.
http://wiki.sk89q.com/wiki/WorldGuard/Regions/Flags
https://worldguard.enginehub.org/en/latest/regions/flags/?highlight=vehicle

**Comment by Hugoland** [comment]
Thanks !
