### ISSUE TITLE
[Rendering] Tanks have a rendering issue

### ISSUE THREAD

**Issue by TimGoll** [Railcraft/Railcraft#1493]
![image](https://user-images.githubusercontent.com/13639408/45472113-7d684280-b733-11e8-807b-e6cfda1f2178.png)

West and east side have their texture on the north (or south) side and are therefore in the wrong orientation

**Comment by liach** [comment]
Fixed in code, will push soon.

**Comment by liach** [comment]
See that commit above. It is a change in the blockstate jsons.

**Comment by TimGoll** [comment]
nice! 
If there's anything to do I can help with this project probably in a few days. I'm a noob at rendering, but the rest is okay. Or I'll just pick an issue and try fixing it :)
