### ISSUE TITLE
[recipe] crusher has strange recipe

### ISSUE THREAD

**Issue by TimGoll** [Railcraft/Railcraft#1494]
latest in dev: birch wood stairs result in bricks:

![2018-09-13_19 32 12](https://user-images.githubusercontent.com/13639408/45505499-08295b80-b78d-11e8-84cb-6be6bdbc6c9f.png)

**Comment by liach** [comment]
Same as #771

**Comment by TimGoll** [comment]
I think you replied to the wrong issue. ^^

**Comment by liach** [comment]
Oh, I intended to put brick stairs but birch's spelling is too close to that of brick.

**Comment by TimGoll** [comment]
I expected something like this :D
