### ISSUE TITLE
[crusher] items on top of the crusher do not get destroyed

### ISSUE THREAD

**Issue by TimGoll** [Railcraft/Railcraft#1495]
latest indev, basically the title. The player does die as intended:

![2018-09-13_19 33 54](https://user-images.githubusercontent.com/13639408/45505559-2d1dce80-b78d-11e8-876e-33fae685ad0a.png)

**Comment by TimGoll** [comment]
It's the same as #771

**Comment by liach** [comment]
I'd actually leave this open because these two issues have overlaps but having both can better remind me
