### ISSUE TITLE
[feature request] Waila support

### ISSUE THREAD

**Issue by TimGoll** [Railcraft/Railcraft#1497]
show some basic information for the use in waila

![2018-09-13_19 35 58](https://user-images.githubusercontent.com/13639408/45505654-69e9c580-b78d-11e8-9a8d-d8e482503a5f.png)

**Comment by liach** [comment]
I don't think we will support that natively. Waila depends on NEI, which railcraft does not really like. Moreover, waila users will make up a very tiny fraction, and magnifying class covers the most information you need.
