### ISSUE TITLE
lang file entries are different from the MFSu cart's unlocalized name.

### ISSUE THREAD

**Issue by Trinsdar** [Railcraft/Railcraft#1501]
In the lang files entries are like this: entity.railcraft.cart_ic2_mfsu.name and this: item.railcraft.entity.cart.ic2.mfsu.name while the unlocalized names are this: entity.railcraft.cart_ic2_MFSU.name and this: item.railcraft.entity.cart.ic2.MFSU.name. It would probably be easier to just change the unlocalized name.

**Comment by liach** [comment]
@Trinsdar Please look at the indev 1.12.2 branch instead. It has been long fixed.
