### ISSUE TITLE
Recipes do not work on 9.12.2.0 [1.7.10]

### ISSUE THREAD

**Issue by UQuark** [Railcraft/Railcraft#1503]
If I want to craft standart track I need to craft a rail but it crafts from... 8 standart tracks! I can't disable new recipes in railcraft.cfg as it said on mc wiki, there is no such property as useOldRecipes. I can't craft steam locomotive because steel plates are not-craftable. I play with ic2, tinker's construct and buildcraft.

**Comment by liach** [comment]
look up rolling machine.
