### ISSUE TITLE
indev-1.12.2 Locomotive Will Not Reverse when Clicking R inside the locomotive Gui

### ISSUE THREAD

**Issue by Ang3lOfD3ath** [Railcraft/Railcraft#1506]
indev-1.12.2 Locomotive Will Not Reverse when Clicking R inside the locomotive Gui

https://www.youtube.com/watch?v=YEP1rWlII5o

**Comment by liach** [comment]
Looks like a facing desync when the cart is placed. Considering adding a custom spawn handler for the locomotives.

**Comment by CovertJaguar** [comment]
Can confirm the issue, though I doubt it has anything to do with placement since the facing is calculated when the cart starts moving if it doesn't already know. Probably a GUI issue or something. It used to work.

**Comment by liach** [comment]
Hmm, when I test now, it works. After clicking R, the lamp is on the opposite of the moving direction.

**Comment by Devin616** [comment]
i had the same issue, luckily nothing stopped me from stopping, getting out, rotating the train, and reversing that way...

**Comment by 016Nojr** [comment]
It's not working on server running latest version (Railcraft 12.0.0-beta-4). The train only goes forward.

**Comment by liach** [comment]
Looks like I forgot to write a field. Needs more testing though; I am not yet confident
