### ISSUE TITLE
[Suggestions] The future of railcraft

### ISSUE THREAD

**Issue by TimGoll** [Railcraft/Railcraft#1507]
Convert Jaguar asked on Discord what we think about the future of railcraft and I thought this would be an interesting question for a more general audience. Therefore I forwarded this question to reddit. But my posted link got no attention in the discord due to all the messages sent there. 
So here is the link with more than 100 replies. https://www.reddit.com/r/feedthebeast/comments/9mx6ik/1122_railcraft_news/

You can delete this issue if you don't like this

**Comment by liach** [comment]
I failed to see many suggestions besides that one boiler explosion. @Generalcamo Did you see any more suggestions or bug reports? I plan to move them to other new issues.

**Comment by liach** [comment]
Yeah, other than that issue i made, ideas are already in existing issues.
