### ISSUE TITLE
Game crash on dedicated server because of TileManager method reference

### ISSUE THREAD

**Issue by emo64** [Railcraft/Railcraft#1518]
When i place a coke oven structure and try to right click it. The block disappear and throw some error
log here: https://paste.ubuntu.com/p/dQspsdYjnv/

**Comment by liach** [comment]
the erroring method is getcollisionboundingbox. hmm

**Comment by liach** [comment]
hmm, the error is not descriptive at all. remove other coremods (e.g. spongeforge) and report the results

**Comment by emo64** [comment]
It works in singleplayer. So I wonder Is there is a solution for spongeforge?

**Comment by liach** [comment]
hmm, let me check

**Comment by liach** [comment]
i believe it's a coremod error. send me your mod list

**Comment by emo64** [comment]
Mods (43): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Biomes O' Plenty, BuildCraft, BuildCraft Lib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Fast Leaf Decay, Forestry, Immersive Engineering, IndustrialCraft 2, Iron Chest, Just Enough Items, Railcraft, SpongeForge, Thaumcraft, UniDict, Waila, WanionLib

**Comment by liach** [comment]
@emo129  你是自己构建的还是下载发布的包，你这个error没有信息和方法名称不正常啊

**Comment by emo64** [comment]
是自己构建的 2936c7fe81ac8084580744297b06fb81589f2770

**Comment by liach** [comment]
那是四天前了，现在再构建下试试看

**Comment by emo64** [comment]
一样的问题 还是在刷错

**Comment by liach** [comment]
哎，试试看一次移除一半mod，如果有错继续移除，如果有错把被移除的一半放回来继续移除，直到找到冲突mod

**Comment by emo64** [comment]
现在试完了 冲突mod就是spongeforge 那么请问能在以后改善spongeforge的兼容吗

**Comment by liach** [comment]
呵呵，我也不知道为什么安了sponge lambda就炸了

**Comment by liach** [comment]
我把锅提给sponge

**Comment by liach** [comment]
还有 #1519 也是同样原因，静待观察。

**Comment by emo64** [comment]
And there are some broken texture here. Minecart has a transparent texture or totally black steel armor.
@liach 右键箱子车也会有一样的问题，还发现了一些材质的问题，例如列车都是透明的。或者钢头盔和裤子材质是黑色的

![w a cc_4jth2o fw7 vcq66](https://user-images.githubusercontent.com/7891878/47602384-c5f06c80-da10-11e8-928a-8b20dfe6a9d4.png)

![jt3 ag t9g0q6o6a13ehjgt](https://user-images.githubusercontent.com/7891878/47602387-d6084c00-da10-11e8-8a3c-4df5262ad805.jpg)

**Comment by liach** [comment]
矿车透明是万圣节特性，右键的错误发一下。装甲我会研究

**Comment by emo64** [comment]
https://paste.ubuntu.com/p/YZVqZbgWjw/

**Comment by liach** [comment]
@emo129 这个还是上次村民的那个错误

**Comment by emo64** [comment]
是的 挺频发的

**Comment by liach** [comment]
@emo129 我的意思是你发了重复的崩溃报告  :sweat:

**Comment by liach** [comment]
应该在 ab5fa1eef449058f1539604681832ed466305384 中修复了。再更新下试试看，保留SpongeForge

**Comment by emo64** [comment]
还是一样的错误
https://paste.ubuntu.com/p/dWtqk3d8cq/

**Comment by liach** [comment]
降级java有没有用

**Comment by emo64** [comment]
没有用

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5127

**Comment by liach** [comment]
Temporary fix pushed.

**Comment by CovertJaguar** [comment]
Fixed by Forge.
