### ISSUE TITLE
[mc-1.12.2] SpongeForge server crash by villager's pathfinderAI

### ISSUE THREAD

**Issue by emo64** [Railcraft/Railcraft#1519]
Mods (43): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Biomes O' Plenty, BuildCraft, BuildCraft Lib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Fast Leaf Decay, Forestry, Immersive Engineering, IndustrialCraft 2, Iron Chest, Just Enough Items, Railcraft, SpongeForge, Thaumcraft, UniDict, Waila, WanionLib

Spongeforge version: 1.12.2-2768-7.1.2

crash report: 
https://paste.ubuntu.com/p/nKJVR3rmXG/

from commit e0ccc25db05c46e27c5c05b35d9cf764050e4705

**Comment by liach** [comment]
Merging this into #1518
