### ISSUE TITLE
Increase maximum values for fluid cart capacity and fluid loader fill rate

### ISSUE THREAD

**Issue by richardhendricks** [Railcraft/Railcraft#1520]
Hello,
  Gregtech: New Horizons is looking at developing version 3.0 for MC 1.10+, and we would like to encourage players to use rail systems vs just carrying large stacks of fluid cells.  

For this to be effective, we would like to increase the maximum tank cart size to 512 B and the maximum fluid loader fill rate to 256 mB/t. 

Explanation:
In our modpack, players find "underground oil" in a chunk hundreds of blocks from their base and drill it out from beneath the bedrock. These oil pools can be 15,000 - 100,000+ buckets.  Right now players use the jetpacks to carry stacks of large fluid cells to transport this oil home, or magical means to move cells back to their base.   

We would prefer to encourage technological solutions like setting up a rail line.  With the current 64B max tank cart, it is not worth it to setup the rail infrastructure. 512B tank carts would allow us to disable large fluid cells or reduce their stack size significantly. Faster fluid loaders are necessary to load/unload the larger tank carts. Targeting 10 minutes to unload a train with 4x512B tank carts.

Thanks for your consideration.

https://github.com/GTNewHorizons/GTNewHorizons3.0-Core-Mod/issues/3

**Comment by Generalcamo** [comment]
That's more capacity than the metal tanks and the water tanks. I guess an advanced fluid loader could handle higher speeds for modded carts, but what you are asking for the carts would be quite overpowered.

**Comment by liach** [comment]
it's not op at all compared to chest carts.

**Comment by liach** [comment]
(or even fluid cells)

**Comment by Generalcamo** [comment]
Chest carts can't carry fluid cells by default in Railcraft

**Comment by richardhendricks** [comment]
In our modpack, we have supertanks with 4,000, 8k ,16k etc capacities.  So a cart that can move 512B at a time fits well with our design. 

Just to give you an idea, plenty of our players will also build maximum size Railcraft tanks. We do the weird stuff!

![image](https://user-images.githubusercontent.com/1214811/47519614-84669280-d853-11e8-9397-7aeee1161973.png)

This is change to the maximum size, not the default.  We just want to be able to tweak our setting to something useable for our pack.

**Comment by Generalcamo** [comment]
Could you not use our API and add your own cart with a super tank?

**Comment by richardhendricks** [comment]
That's something we can research, for sure. What about increasing the fluid loader/unloader maximum speeds?

**Comment by Generalcamo** [comment]
That's a possibility. Even adding an advanced fluid loader with extra features and a faster speed.

**Comment by richardhendricks** [comment]
Like loading/unloading from any direction? <3

**Comment by CovertJaguar** [comment]
I feel like you are looking at this the wrong way.

Even if we increase the tank cart size to some ludicrous value, I don't see how that incentivizes anyone to change their behavior.

At 500 buckets, you'd fill one of your 4k tanks with only 8 tank carts of fluid, that's ridiculous.

The ultimate outcome of doing this would be that players would still fly their fluids home, but they'd store them in minecarts instead of tanks. =P

The only real way to balance this is to remove the ability to let them carry that much fluid on their person.

At 64 buckets, that still only 12.5 trains to fill a 4k tanks with 5 tank carts per train. If left running in the background this wouldn't take much time at all.

Feel free to keep discussing, but the most I'd approve would be a max increase to 128 buckets, twice the current max.

**Comment by liach** [comment]
I'd suggest decreasing fuel usage of railcraft locomotives. Last time I tried, it takes about 10 coal blocks, or 100 coal, to travel about 1000 blocks on a train with only me (from my base to neptunepink's base on the patron server). A lower value similar to that offered by vanilla (5 blocks/s for 80s, equivalant to 400 blocks/coal), such as 100 blocks per coal, compared to what we have now (10 blocks per coal) would generate an incentive to use train as a cheap mean to transport.

**Comment by richardhendricks** [comment]
@CovertJaguar - Yes, that is exactly our plan.  We will be reducing the stacksize for cells from 64 to 16, and probably removing large cells entirely, or else making them give slowness/root you.

Also, the 4K tanks are the smallest "super" tanks - they go up to 64k (totally appropriate within the pack).  And you're right, a train can easily be expanded by adding carts.  128 buckets per cart would be OK I guess, but I don't understand the hesitation behind raising the max allowed.

The real issue is the load/unload time.  If the fluid loader/unloader maximum could be increased by 5x that would be delicious (or advanced loader/unloaders). Creating quests to teach players how to split carts for two or more load/unload stations is a bit much to ask (even for our hardcore players). 

Thanks for your consideration and work.

**Comment by richardhendricks** [comment]
Also, are there examples of the minecart API?  I spent a while looking at it (I am not a java dev, more algorithms focused), and couldn't figure out heads or tails from it.   Based on my quick look the maximum would limit carts created via the API as well, right? Could we use Reflection within our modpack coremod to update the maximum ourselves?

Thanks again.

**Comment by CovertJaguar** [comment]
Well... you can do anything with a core mod.

I'm just kind of old school when it comes to how I feel things should be balanced, probably for no good reason really. Sure let's crank it up and do something about loaders.

**Comment by richardhendricks** [comment]
Thanks so much!

**Comment by Hakameda** [comment]
Would help our world, exu drum carts =)

**Comment by liach** [comment]
It's not railcraft's job to support an RF mod.

**Comment by liach** [comment]
Honestly, I should say "a random mod" instead. Moreover, Minecraft 1.7.10, the version you play on, is no longer supported @Hakameda, so the cart won't be added by Railcraft (you can ask other interested people to make an addon instead.)

**Comment by Hakameda** [comment]
You make it sound like we wouldn't also play gtnh on 1.12, ATM it's broken. It's almost better to wait for it to update so we can do railworld
