### ISSUE TITLE
Minecart with more health

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1524]
Low health is one of the major issue of minecarts. For example, when you are riding a train through wilderness, skeletons might start shooting at you; sometimes, a bowshot from a skeleton is enough to kill a minecart in the train and thus, break the whole train. I suggest something like a shulker cart to defend the rider.

**Comment by CovertJaguar** [comment]
We could probably just buff the minecart "health" vs everything except players breaking them with empty fists.

**Comment by liach** [comment]
Or reduce damage taken by minecarts when hit by projectiles

**Comment by liach** [comment]
Merging into #1769
