### ISSUE TITLE
Improve performance of Multiblock detection

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1525]
Right now, we check multiblocks every few ticks. Discord user Trinsdar suggested using a tool while I suggest checking when the tile entities are added or removed instead (a set of chunk positions to check).

**Comment by TimGoll** [comment]
I'd recommend a tool, because most players are familiar with this technic from IE and it should be slightly better performance wise

**Comment by CovertJaguar** [comment]
What? Do any of you actually understand how the system works?

It checks once! And then it sits idle waiting for something to change!

It does _not_ check every "few ticks", AKA 256, unless half the structure is unloaded and it can't tell if its valid or not. There might be some room for improvements in this one edge case, but that's it.

Railcraft has _always_ been lauded as having the simplest and most efficient multi-block code.

See:
https://github.com/Railcraft/Railcraft/blob/58439fe90a28fc115fa8a6406b28cc8485f0546c/src/main/java/mods/railcraft/common/blocks/multi/TileMultiBlock.java#L330

**Comment by liach** [comment]
Hmm, if people report lags, we will ask them to use sampler to profile.
