### ISSUE TITLE
Game Crashes When Disabling Resource Module

### ISSUE THREAD

**Issue by Voxel-Friend** [Railcraft/Railcraft#1532]
Using unofficial beta 1 for 1.12.2. Seems to happen also when simply disabling dusts. alternatives exist in my pack to the dusts so recipes are not broken afaik.
Crashlog:
https://gist.github.com/Voxel-Friend/65b730092d3f066941aaa8d66173f94a

**Comment by liach** [comment]
Will make the config fail-safe instead. Moreover, note that once you disable a module, you have to change many related stuff, especially advancements and loot tables (loot tables will yield nothing if one of its entry is in a disabled module)

**Comment by Voxel-Friend** [comment]
Is all that configurable in the config?

**Comment by liach** [comment]
See https://minecraft.gamepedia.com/index.php?title=Loot_table&oldid=1115017#Custom_Maps
The loot tables are changed in vanilla ways. For railcraft, change the `<custom directory>` part to `railcraft` (must be all lowercase). A few are available here at https://github.com/Railcraft/Railcraft/tree/mc-1.12.2/src/main/resources/assets/railcraft/loot_tables/chests . For example, you will refer to the `simple_dungeon.json` with `data/loot_tables/railcraft/chests/simple_dungeon.json`

**Comment by liach** [comment]
For now to stop the crash, remove the dusts from the list of worldspike fuels. I bet you need the void dust for worldspikes to run.

**Comment by liach** [comment]
For the advancements, see https://minecraft.gamepedia.com/index.php?title=Advancements&oldid=1151757#JSON_Format

**Comment by Voxel-Friend** [comment]
Thanks!

**Comment by liach** [comment]
After discussion, we decided to crash with a clearer message instead.

**Comment by CovertJaguar** [comment]
At the very least it needs to print which file and setting failed.

**Comment by liach** [comment]
Well, I just made a mod for that purpose. https://github.com/liachmodded/datapacks/

**Comment by CovertJaguar** [comment]
I kind of figured we'd just hardcode it into the parser call.

**Comment by Wladislav** [comment]
Is this problem fixed? I constantly get these messages. What to do with it?
![server_warn](https://user-images.githubusercontent.com/2454823/51895389-133afc00-23bb-11e9-95ea-81cd3b2733f2.png)

**Comment by CovertJaguar** [comment]
The logging of list parsing is now greatly improved and, as of my cargo blacklist commit a couple weeks ago, no longer crashes on invalid lines. Rather it logs them as an error and ignores them.
