### ISSUE TITLE
Railcraft API not included in classpath while building.

### ISSUE THREAD

**Issue by alwaeles** [Railcraft/Railcraft#1533]
Hi,

The title says a lot. It happens when executing `./gradlew runClient` and in the jar file.

Some debug provided by SamTDS and Mineotopia (see discord):
[crash-2018-11-05_19.10.26-client.txt](https://github.com/Railcraft/Railcraft/files/2550847/crash-2018-11-05_19.10.26-client.txt)
[Gradle Execution](https://gist.github.com/TimGoll/ff501730f6d143f89d7228cc2e57d827)

Thank you,
Axelandre

**Comment by liach** [comment]
Fixed in #1534
