### ISSUE TITLE
[1.12.2] Crash on world load when installed with Immersive Engineering

### ISSUE THREAD

**Issue by YCLiang95** [Railcraft/Railcraft#1536]
full crash report https://pastebin.com/XVNNn5PB

Railcraft version is commit "Minor stuff" 91ee3309c8d7ed1436c4dcad45b1579ee3e4e410 in branch mc-1.12.2, build by myself.
Immersive Engineering 0.12 - 86

Removing Railcraft or IE solve the problem. I have a total of 165 active mods. I was not on a server, just local single player, not open to LAN.

creating new worlds and loading old worlds both cause crashes. 

java.lang.NullPointerException: Exception in server tick loop
    at blusunrize.immersiveengineering.client.ClientProxy.onWorldLoad(ClientProxy.java:1426)

The code that caused the crash in IE is an entity render code.

`for(Object render : ClientUtils.mc().getRenderManager().entityRenderMap.values()) if(RenderMinecart.class.isAssignableFrom(render.getClass()))`

https://github.com/BluSunrize/ImmersiveEngineering/blob/4e3a9e1d73fd47fb80cd523c2bb4b44e85714c17/src/main/java/blusunrize/immersiveengineering/client/ClientProxy.java

btw, tank walls and valves seems to have missing names.

**Comment by liach** [comment]
Caused by https://github.com/Railcraft/Railcraft/commit/05b70b8194bda73265f2e4c675feb54c2032d707#diff-d39248d34cd796c9b4a7abf732d9b1b1R178

**Comment by liach** [comment]
@CovertJaguar Eh, vanilla didn;t broke but immersive engineering did. Fun enough.
