### ISSUE TITLE
Trying to open boiler makes StackOverflowError.

### ISSUE THREAD

**Issue by alwaeles** [Railcraft/Railcraft#1540]
Hello,

I built a steam boiler and when I right clicked it, the game crashed with a StackOverflowError.

I'm using Railcraft Alpha: 12.0.0-alpha-6.

Here's the crash log: [crash-2018-11-09_20.00.25-client.txt](https://github.com/Railcraft/Railcraft/files/2567210/crash-2018-11-09_20.00.25-client.txt)

Thank you,
Axelandre

**Comment by liach** [comment]
Another master block inconsistency.

**Comment by liach** [comment]
I doubt some code was missed in the merge performed by CJ. Will check.

**Comment by liach** [comment]
Uh, this should be included in next update alpha 7. My bad...
