### ISSUE TITLE
Game crashes on placing certain carts.  1.12.2 alpha 6

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1541]
With a new world (tried twice), after placing a single cart (successfully), the game crashes when placing a second cart. So far, this has happened with placing two chest carts (crashed upon placing second chest cart). It happened again after placing a chest cart (didn't crash) and then placed tnt cart (crashed). This will crash the game repeatedly after this until the player moves out of range of the incident. 

More information: this does not crash the server, only the client. 
[crash-2018-11-09_20.38.51-client.txt](https://github.com/Railcraft/Railcraft/files/2568050/crash-2018-11-09_20.38.51-client.txt)

**Comment by Vectrobe** [comment]
I haven't been able to replicate it on my end, is it just with 'vanilla' rails and 'vanilla' carts? in a straight line?

**Comment by liach** [comment]
Good point, we need to start syncing trains to the client.

**Comment by liach** [comment]
This only happens when you place carts on abandoned tracks, right?

**Comment by texaswriter** [comment]
I tested this on the tracks in the Railcraft buildings when it is generated in a vanilla village (are those abandoned?). I did not have crashes when I placed tracks on my created tracks, but I can test that if it will help.

**Comment by Vectrobe** [comment]
oooh does this only occur on vanilla, generated mineshaft tracks?

**Comment by liach** [comment]
no, but abandoned tracks generate in villages.

**Comment by CovertJaguar** [comment]
Actually there is no reason for the client to _ever_ touch trains. I added that exception to help track down such things.

In this specific case, we don't sync NBT data for the cart either, so syncing the train would make no difference.

There is an argument to made that this will negatively impact client simulation vs server simulation and result in weird behavioral artifacts such as stuttering, but there isn't much that can be done about that.

Additionally, the call to random here will result in simulation differences anyway without a major redesign.
