### ISSUE TITLE
1.12.2 server crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [Railcraft/Railcraft#1543]
https://paste.ee/p/Vlvol

**Comment by texaswriter** [comment]
The crash report shows you are using alpha 1, meanwhile alpha 6 is available per the patreon.

**Comment by liach** [comment]
Yeah, this has been fixed in alpha 6 in theory. Btw don't edit the crash report like https://paste.ee/p/Vlvol#s=0&l=2
