### ISSUE TITLE
Train crash with loading Railcraft 1.12.2 A6

### ISSUE THREAD

**Issue by YukaiDragon** [Railcraft/Railcraft#1545]
**Description of the Bug**
Was playing Minecraft and everything was alright, made a few items such as the Coke Oven and the Metal Roller. I already had a Locomotive made also. I went exploring to look for more coal for the oven. Went into a cave for a while and all the sudden the game crashed. When I attempted to reload the save, it would crash immediately after "loading terrain", but the crash log showed no errors. When I removed the Railcraft mod, and loaded the world successfully, then went and added the mod back again. It started working. I was able to play for about 8 hours, before it started to crash before this happened.  

Edit : It just started doing it again, made the Coke Oven, and it started crashing after I exited and tried to reload the game

**To Reproduce**
I couldn't exactly say how to reproduce, but I did have the Coke Oven making coal coke, and I went off exploring, when this started happening. 

**Expected behavior**
The game crashes and then wont reload the save. 

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-6]
 - Forge Version 2784.

**Comment by liach** [comment]
post a crash report.

**Comment by YukaiDragon** [comment]
[crash-2018-11-25_11.34.31-server.txt](https://github.com/Railcraft/Railcraft/files/2614099/crash-2018-11-25_11.34.31-server.txt)

**Comment by YukaiDragon** [comment]
It also did the same thing with the Locomotive, also I did realize I guess it showed that the Coke Oven caused the crash x.x whoops. Water and Coal were in the locomotive, and went to exit the game and it crashed on startup also
[crash-2018-11-26_00.02.21-server.txt](https://github.com/Railcraft/Railcraft/files/2614130/crash-2018-11-26_00.02.21-server.txt)

**Comment by liach** [comment]
Hmm, same as #1540

**Comment by liach** [comment]
The train crash is a different one, though. Still related to trains.

**Comment by texaswriter** [comment]
Not sure if I am having the same issue. Had 4 coke ovens producing creosote/coal coke. Went to go mining, and now the server crashes whenever my client connects. Actually rolled the server back 40 minutes (coke ovens were still producing at that point) and the client still crashes the server upon connection. 
[crash-2018-11-27_23.37.09-server.txt](https://github.com/Railcraft/Railcraft/files/2623084/crash-2018-11-27_23.37.09-server.txt)
[crash-2018-11-27_23.41.01-server.txt](https://github.com/Railcraft/Railcraft/files/2623085/crash-2018-11-27_23.41.01-server.txt)
[crash-2018-11-27_23.48.13-server.txt](https://github.com/Railcraft/Railcraft/files/2623086/crash-2018-11-27_23.48.13-server.txt)
[crash-2018-11-27_23.54.25-server.txt](https://github.com/Railcraft/Railcraft/files/2623087/crash-2018-11-27_23.54.25-server.txt)

**Comment by liach** [comment]
@texaswriter for that one see bug #1540. ask cj for another alpha

**Comment by CovertJaguar** [comment]
I still haven't tracked down the train crashes. But the coke oven one should be fixed.

**Comment by YukaiDragon** [comment]
I put a locomotive into the world and the game loaded fine, even ran the locomotive and exited and it loaded up fine too. Just with a cart and the train.

**Comment by liach** [comment]
Try link 3 carts and kill one of them.

**Comment by CovertJaguar** [comment]
Probably what I need to do is mark Trains for deletion when the cart dies, but actually do the garbage cleanup during the world tick or something.
