### ISSUE TITLE
Alpha 7 - Cargo Cart Item Filter Bug

### ISSUE THREAD

**Issue by Ang3lOfD3ath** [Railcraft/Railcraft#1547]
**Description of the Bug**
1.12.2 RailCraft Alpha 7 Cargo Cart Item Filter Bug

**To Reproduce**
1. Place block/cart '...'
2. Click on '....' try and put in items

**Screenshots & Video**
https://www.youtube.com/watch?v=riARpY80QCo

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-7]
 - Forge version. 14.23.5.2772
 - Possible conflicting mods and their versions. i have none installed jsut railcraft

**Additional context**

**Comment by CovertJaguar** [comment]
@liach test if its been fixed and close if it is.

**Comment by liach** [comment]
Yeah, has been fixed.
