### ISSUE TITLE
Alpha 7 - Signal Surveyor does not recognise Token Signal

### ISSUE THREAD

**Issue by AlexJ6301** [Railcraft/Railcraft#1548]
**Description of the Bug**
Place Token signal next to line.
Right click with Signal Surveyor
Message "Not a valid signal."

**Expected behavior**
Should start to link the Token Signals.

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-7]
 - Forge version: 1.12.2-14.23.5.2784-

**Additional context**
I was going to test that we could now "reset" token signal areas when they get stuck "on".  E.g. a cart enters but never leaves.  Has this been addressed yet, by any chance?

**Comment by CovertJaguar** [comment]
>I was going to test that we could now "reset" token signal areas when they get stuck "on". E.g. a cart enters but never leaves. Has this been addressed yet, by any chance?

No, and there isn't much chance that it ever can be. It would require building a graph of all the tracks in the area and testing each track area individually. Possibly I guess, but very annoying and costly.

Or do you mean something like hitting them with a crowbar to "unstuck" them?

**Comment by AlexJ6301** [comment]
Sorry, I left out the crucial word: **manual** ;-)
There should be a way to manually reset a token ring group back to green in the case where it gets set to red permanently by a disappearing cart.  Otherwise you have to unlink/relink all the token signals back together (which is a pain).  
Doing "something" with a signal surveyor to just one of the signals in the group to reset them to green.

Should I open a separate issue for this?
[I totally understand that an automatic reset is not on the cards, nor would we expect it...]

**Comment by CovertJaguar** [comment]
Yeah, make a separate issue. Should be easy enough to add something.
