### ISSUE TITLE
Cannot pipe water into a Fluid Loader or fill into cart

### ISSUE THREAD

**Issue by instinxx** [Railcraft/Railcraft#1549]
**Description of the Bug**
Unable to pipe water into a fluid loader from any side. I can insert water with a bucket by hand.

cart doesn't load from fluid loader.

**To Reproduce**
attach pipe from water source (In my case 2 different infinite water source blocks.)

**Expected behavior**
Water would flow into loader and quench the thirsty steam engine.

**Screenshots & Video**
Tried using pipes from Cyclic, immersive engineering, Ender IO and Mekenism
![image](https://user-images.githubusercontent.com/1753699/49194495-6956d900-f351-11e8-8fec-9025b01e9bea.png)

**Environment**
Railcraft 12.0.0-alpha-7
 1.12.2
 Unknown at this time. 359 possible other mods.

**Additional context**

**Comment by anar4732** [comment]
I confirm this bug.
i tried immersive engineering.
RC: Alpha 7 Build 24.11.2018

**Comment by liach** [comment]
After long investigation, I am finally able to fix this.

**Comment by Jarrose37** [comment]
> After long investigation, I am finally able to fix this.

What did you do to fix it?

**Comment by liach** [comment]
though the loaders are intended to be unidirectional, it accidemtly faces the opposite side of player facing when placed (like dispenser/piston facing)

**Comment by Jarrose37** [comment]
> though the loaders are intended to be unidirectional, it accidemtly faces the opposite side of player facing when placed (like dispenser/piston facing)

IDK if I should make a new thread but I cant pump water or use water buckets to fill the fluid loader. I've tried mekanism, TE, buildcraft pipes no water goes in from any angle and when I put a water bucket in it just pops out and does not fill the fluid loader. any suggestions?

**Comment by liach** [comment]
set a filter in it.

**Comment by ExDomino** [comment]
Still not working!

**Comment by liach** [comment]
@ExDomino how
