### ISSUE TITLE
Alpha 7 - Stepping on a charge trap causes violent shaking

### ISSUE THREAD

**Issue by instinxx** [Railcraft/Railcraft#1550]
**Description of the Bug**
Stepping on a charge trap causes player to get stuck and the camera starts to violently shake,

**To Reproduce**
1. Place Charge Trap
2. Step on Charge Trap
3. Do the Hustle

**Expected behavior**
Nothing. I expected to be able to walk on it.

**Screenshots & Video**
https://clips.twitch.tv/CulturedKindStorkBleedPurple

**Environment**
Railcraft 12.0.0-alpha-7
forge-1.12.2-14.23.5.2772
Unknown at this time.

**Additional context**

**Comment by CovertJaguar** [comment]
When I tried it, the game crashed. Possibly fixed by 380bb75cf59e40043289e341301084b17dfb1cdd.

**Comment by CovertJaguar** [comment]
Though that looks like bounding box issues.
