### ISSUE TITLE
Alpha 7 - Can't unload Chest-Cart with Item-Unloader

### ISSUE THREAD

**Issue by iridium34** [Railcraft/Railcraft#1551]
**Description of the Bug**
Items inside the chestcart doesn't get unload with itemunloader.
The itemunloader won't emit a redstonesignal for a locking track.

**To Reproduce**
1. Place block/item-unloader
2. Let a chestcart move above it
3. It won't get locked above unloader and no items get unloaded

**Expected behavior**
Chestchart should stop above the unloader, because of the locking track, and get unloaded

**Screenshots** 
![image](https://user-images.githubusercontent.com/4757855/49252722-13536580-f425-11e8-99c9-5545bab7e397.png)

**Environment**
 - Railcraft 12.0.0-alpha-7
 - forge-14.23.5.2772

**Comment by liach** [comment]
Well, the track only locks if it does not receive a redstone signal. Your description is unclear.

**Comment by iridium34** [comment]
i tested a bit more and the problem is not the track. The itemunloader doesn't recognise items inside the cart. It directly emits a redstonesignal if a chestcart is above it, even if there are items inside.

**Comment by liach** [comment]
Try adding a filter for chest carts and change the unloader's mode.

**Comment by Ang3lOfD3ath** [comment]
i have recored some footage of this bug
https://www.youtube.com/watch?v=w-mY-6GFIW0

**Comment by liach** [comment]
The video is not loading.

**Comment by iridium34** [comment]
I did. I put a stack of dirt inside the cart and set the filter with dirt. 
[https://youtu.be/CrY7zAtzAeI](https://youtu.be/CrY7zAtzAeI)

**Comment by texaswriter** [comment]
In alpha 9, both the item unloader and the advanced item unloader are working via the chest cart. Used locking track on top on one or both. unloaded straight away.

**Comment by KillTyrant** [comment]
Can confirm what Texas said. Appears to be working as intended in alpha 9
