### ISSUE TITLE
Alpha 7 - Flux Cart Unplaceable Bug

### ISSUE THREAD

**Issue by Ang3lOfD3ath** [Railcraft/Railcraft#1552]
**Description of the Bug**
1.12.2 RailCraft Alpha 7 Flux Cart [Unplaceable](http://ssl.gstatic.com/dictionary/static/sounds/20160317/unplaceable--_us_1.mp3) bug

**To Reproduce**
1.Try and Place block/cart '...'

3. See error ..... there is none

**Expected behavior**
ummmmm the cart should place..... ;/

**Screenshots & Video**
https://www.youtube.com/watch?v=vw4TjsjjKxg

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-7]
 -Forge version. 14.23.5.2772
 - Possible conflicting mods and their versions. no other mods installed

**Additional context**

**Comment by liach** [comment]
Another aspect of #1545

**Comment by CovertJaguar** [comment]
I have a fix sitting on my computer, but I want to completely redesign how cart speed is calculated instead of just a half ass patch.

**Comment by liach** [comment]
#1545 fixed.
