### ISSUE TITLE
Detector tracks are causing ticks to take very long as carts are going over.

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1556]
**Description of the Bug**
It seems if there are multiple carts on one train network, the server will lag when a cart or train goes over a detector track. 

**To Reproduce**
1) Created simple rail network with one route that leads back to main loop (one main loop and one switched loop leading back to main). 
2) Added detector track to feed redstone signal to redstone torch to  locking track to prevent train crashes. 
3) ran two trains on the main. 
 
**Expected behavior**
Routing is taking place correctly, but it is lagging the server (tick takes ~1-5 seconds when a cart arrives at the detector track)
![2018-12-05_02 09 18](https://user-images.githubusercontent.com/22877053/49499147-dcb98880-f832-11e8-9e97-0405ad75fbc9.png)

**Screenshots & Video**
If applicable, add screenshots and video to help explain your problem.

**Environment**
 - Version [e.g. Railcraft 12.2.0-alpha-7]
 - Forge version. 1.12.2-forge1.12.2-14.23.5.2772
 - 

**Additional context**
When multiple detector tracks were chained (I removed), the watchdog forcibly shutdown the server (tick took longer than 30 seconds)... I just used one detector track and it seems to recover fast enough not to be shut down, but it is still lagging the server.

**Comment by texaswriter** [comment]
I have some crash reports from when I had multiple detector tracks... some of them were crashes after the server was forcibly shutdown. I believe the 01.28.10 was a forcible shutdown and I believe the 01.35.12 was also a forcible shutdown. I think the 1.47.34 and the 1.53.50 were crashes after the forcible shutdown. 

Just to be clear, when I only have one detector track (not multiple chained together), the game doesn't crash nor does it get forcibly shutdown. These are FYI, in case they are useful. 
 
[crash-2018-12-05_01.28.10-server.txt](https://github.com/Railcraft/Railcraft/files/2647826/crash-2018-12-05_01.28.10-server.txt)
[crash-2018-12-05_01.35.12-server.txt](https://github.com/Railcraft/Railcraft/files/2647827/crash-2018-12-05_01.35.12-server.txt)
[crash-2018-12-05_01.47.34-server.txt](https://github.com/Railcraft/Railcraft/files/2647828/crash-2018-12-05_01.47.34-server.txt)
[crash-2018-12-05_01.53.50-server.txt](https://github.com/Railcraft/Railcraft/files/2647829/crash-2018-12-05_01.53.50-server.txt)

**Comment by texaswriter** [comment]
I actually think this is an interaction with the redstone cables I was using... redid this with redstone (vanilla) and am not having any lag whatsoever

Updated picture of with vanilla redstone instead of 
![2018-12-05_02 30 06](https://user-images.githubusercontent.com/22877053/49500208-c06b1b00-f835-11e8-8e92-086a0c01d2eb.png)

**Comment by CovertJaguar** [comment]
Detector tracks are pretty simple.

**Comment by texaswriter** [comment]
Yeah. I recreated something like the original that caused a bug and I seem to be okay. Maybe it was the 5 detector tracks I had back to back that was causing issues for another mod (charset)... i will be looking at the other mods to see what is going on.
