### ISSUE TITLE
Increase void chest item deletion rate

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1558]
**Is your feature request related to a problem? Please describe.**
Void chest only destroys one item in a stack each second. This makes it extremely useless compared to sheer lava burning or cacti. People have avoided lava or cacti for lag, but void chest does not appear to be better.

**Describe the solution you'd like**
Allow void chest to destroy at faster rates based on how full it is.

**Describe alternatives you've considered**
Keep it as it is. Users have complained that this chest is stupid for this weakness.

**Additional context**
None.

**Comment by CovertJaguar** [comment]
I'm fine with making it based on fill percentage. I made it slow originally to possibly give you time to grab anything you mistakenly shift click into the chest.
