### ISSUE TITLE
Question: Empty Lists in Config File

### ISSUE THREAD

**Issue by cpburnz** [Railcraft/Railcraft#1563]
This is probably a trivial question. How exactly to you format an empty list in the *railcraft.cfg*? In the version I'm running, 1.10.2-10.2.0, I want to remove the fuel cost from the world spikes. The config file says,

> if the list is empty, Worldspikes will not require fuel

How do you specify an empty list? Are these just multi-line strings, or proper lists? I'm not familiar with this file format and I can't find any information on it. It looks like a hybrid of JSON and INI, or similar to YAML. The file contains:

```
worldspikes {
    # ...
    fuel {
        # ...
        S:passive <
            railcraft:dust#0=2
            minecraft:ender_pearl=4
            railcraft:dust#6=8
            railcraft:dust#7=12
         >
        # ...
```

**Comment by liach** [comment]
Do so:
```
S:passive <
>
```

On a side note, this cfg format is specified by forge.

**Comment by cpburnz** [comment]
Thanks.
