### ISSUE TITLE
crash on server launch

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1565]
**Description of the Bug**
Server and client was running fine before. Server crashed when starting up next time. See below crash report

[crash-2018-12-12_18.18.38-server.txt]
(https://github.com/Railcraft/Railcraft/files/2674086/crash-2018-12-12_18.18.38-server.txt)

When I restarted the server again, the server crashed when the client connected (see crash report below. 

[crash-2018-12-12_18.25.24-server.txt](https://github.com/Railcraft/Railcraft/files/2674087/crash-2018-12-12_18.25.24-server.txt)

Server restarted and client was able to connect the third time, but most of the trains were gone (locomotives and all carts on main, large rail network). Only 1 cart on its own little section was there and two trains on their own very small network were still there. 

**To Reproduce**
Not sure. I could try getting the six or so trains running on the large network again and see if it crashes. 

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-9]
 - Forge version. 2772
 - Possible conflicting mods and their versions.

**Additional context**

**Comment by liach** [comment]
Gist version: https://gist.github.com/liach/d225061eff1d60a8c4933473298aedfd

**Comment by liach** [comment]
Actually same as #1557
