### ISSUE TITLE
Empty rolling machine recipes in JEI

### ISSUE THREAD

**Issue by LuigiHutch** [Railcraft/Railcraft#1568]
**Description of the Bug**
The JEI Rolling machine plugin shows empty recipes for many things such as Standard rail, Reinforced Rail, Rebar, wire spools and track parts etc. I suspect it might be todo with not having some external material in my instance

**To Reproduce**
1. Open your inventory
2. Look up the uses of the rolling machine
3. Browse the recipes till you see empty ones

**Expected behavior**
No empty recipes to be shown

**Screenshots & Video**
![2018-12-16_21 23 30](https://user-images.githubusercontent.com/9326429/50059001-efa85300-0178-11e9-890c-d60b48c00acf.png)

**Environment**
Versions:
- Railcraft 12.0.0-alpha-9
- jei_1.12.2-4.14.3.237
- forge-1.12.2-14.23.5.2772

**Comment by CovertJaguar** [comment]
Fixed by 307ec2f8ce0cb504e829ca29d9e9171f085fce7a
