### ISSUE TITLE
SIlk touch drops

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1571]
# Heyo # 
```
[05:07:29] [Client thread/ERROR] [railcraft]: Cannot initialize silk touch drops
[05:07:29] [Client thread/ERROR] [railcraft]: java.lang.NoSuchMethodException: net.minecraft.block.Block.getSilkTouchDrop(net.minecraft.block.state.IBlockState)
[05:07:29] [Client thread/ERROR] [railcraft]: java.lang.Class.getDeclaredMethod(Unknown Source)
[05:07:29] [Client thread/ERROR] [railcraft]: mods.railcraft.common.plugins.forge.HarvestPlugin.<clinit>(HarvestPlugin.java:53)
[05:07:29] [Client thread/ERROR] [railcraft]: mods.railcraft.common.items.ItemSteelAxe.initializeDefinition(ItemSteelAxe.java:41)
```
## **To Reproduce** ##
1. Install forge-1.12.2-14.23.5.2796-universal
1. Install railcraft-12.0.0-alpha-9
2. Look in the logs

### **Environment** ###
 - railcraft-12.0.0-alpha-9
 - forge-1.12.2-14.23.5.2796-universal

**Comment by liach** [comment]
This thing is intended for tunnel bores to mine with silk touch enchantment. Should not impact your daily lives by too much in theory.

**Comment by CovertJaguar** [comment]
What is this stuff? I see references to #1314 #1323

https://github.com/Railcraft/Railcraft/blob/fbb2d6d835aaa063e1129907f6b261b10763f948/src/main/java/mods/railcraft/common/plugins/forge/HarvestPlugin.java#L49-L62

Couldn't you do this with an AT?

**Comment by liach** [comment]
Hmm, is `Game.DEVELOPMENT_ENVIRONMENT` initialized incorrectly? This cannot be done with access transformers because this method is protected (overriding methods cannot be all transformed to be public).

**Comment by CovertJaguar** [comment]
I think it looks at the name of Entity.world. I don't know if its current.

**Comment by CovertJaguar** [comment]
You should use [ReflectionHelper](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/relauncher/ReflectionHelper.java). It does most of this for you.

Also 
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/relauncher/FMLLaunchHandler.java#L138-L142

**Comment by liach** [comment]
~The reflection helper does not cache the method or method handle, making it inefficient.~

The reflection helper is deprecated as well. Looking for `Entity.world` is fine because mods can only run under searge name (playing) or mcp name (dev env).

**Comment by liach** [comment]
Ah spotted the fix. Should use `Game.OBFUSCATED` instead

**Comment by liach** [comment]
Uh, made a fix on github.

**Comment by CovertJaguar** [comment]
> The reflection helper is deprecated as well.

Says who?

**Comment by liach** [comment]
Oh, because that class is loaded by another class loader which is not the launch classloader.

**Comment by CovertJaguar** [comment]
I see, it does however appear to have been properly replaced by ObfuscationReflectionHelper. As for the caching issue... do that yourself, you already are. Stop reinventing the wheel.
