### ISSUE TITLE
Crash Report MC 10.2  RC - 10.4.0

### ISSUE THREAD

**Issue by TPC25** [Railcraft/Railcraft#1574]
Downloaded the lastest jar for MC10.2, started it up and got the crash at Forge loading step 2

https://pastebin.com/mmmmrD1T

Edit: I also ran this in it's own profile without any other mods and still got the same crash report, and I am using the latest Forge version 12.18.3.2511

**Comment by liach** [comment]
@covertjaguar did you forget to sign the jar?

**Comment by CovertJaguar** [comment]
Hmm... Maybe the changes I made for Jenkins broke it

**Comment by CovertJaguar** [comment]
10.4.1 posted
