### ISSUE TITLE
HP / LB boiler balancing

### ISSUE THREAD

**Issue by wormzjl** [Railcraft/Railcraft#1575]
So I've made some calculations on the efficiency of RC boilers based on the simulator made by Forecaster.

I have obtained the following results for a full size boiler at maximum temperature:
For LP boiler, 44.44 RF or 13.89 EU per fuel value
For HP boiler, 34.78 RF or 10.86 EU per fuel value
A HP boiler is 2.56 times faster in fuel consumption, but the fuel to power efficiency is roughly 20% lower than LP boiler.

In current modded environment, I wonder if it's necessary to reconsider this balance, since HP boiler will need more time and resource investment, and many players are very sensitive to the term of efficiency.

**Comment by CovertJaguar** [comment]
If this "rebalance" was made, I'd just delete the HP Boiler entirely as it would then be strictly better than the LP Boiler.

This is referred to as tiering. From a gameplay and development standpoint I see tiering as a waste of time and development resources. The user will _always_ build the highest tier they can afford. This is not an interesting choice, and uninteresting choices are, according to my design philosophy, to be removed.

You might argue "it costs more than an equivalent LP Boiler setup", but another part of my design philosophy is that fixed costs of setup are generally meaningless and useless as a means of balancing. It's too easy to get near infinite resources in games for fixed costs to balance anything.

So no, this is not going to change for as long as I'm still around.

I would rather see a single Boiler variant than see one variant being strictly better than the other.
