### ISSUE TITLE
Quarried Stone recipe too weak

### ISSUE THREAD

**Issue by draxxris** [Railcraft/Railcraft#1576]
Crafting Quarried Stone to Quarried Block seems to reduce the available quantity by 1/4. It is a 2x2 (4) to 1 ratio. From the law of conservation of mass, it should produce 4 Quarried Block.

Using railcraft-12.0.0-alpha-9

**Comment by liach** [comment]
Hmm, aren't you supposed to cook them into blocks?

**Comment by draxxris** [comment]
Well mining them doesn't drop the cobble stone variant, so that might actually be a bug too. It drops the smooth stone variant.

**Comment by liach** [comment]
it should drop the regular stone variant. (quarried stone) that's intentional. then you cook in furnace what you pick up after mining

**Comment by draxxris** [comment]
There is no furnace recipe for Quarried Stone.

**Comment by liach** [comment]
should be a bug then.

**Comment by TheDeviantCrafter** [comment]
You can crush quarried stone in a rock crusher, then smelt it. This process has a 1-1 ratio, but requires Railcraft infrastructure. I think it's fair.

**Comment by liach** [comment]
Decided. Reverting to the old recipes.
