### ISSUE TITLE
MFE carts cause other carts/locomotives move away when connected

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1577]
**Description of the Bug**
When trying to connect the MFE cart to a train (or to another cart, rather), it will cause the other carts to move away (like multiple cart lengths away). It will also cause them to move quite a bit. 

It seems to do other things. It seems to cause carts behind it to move away so far (towards the rear) until they are separated from the train (not linked) [at least it appears this way]. It seems to cause itself to move forward (almost merging with the cart in front of it and pushing carts in front of it). 

**To Reproduce**
1. Place MFE cart
2. Place locomotive (or other cart)
3. Use the crowbar to link them together

NOTE for steps to reproduce, I was trying to make a train of two locomotives, 1 MFE cart, and 1 worldspike cart, 

**Expected behavior**
The carts should connect with minimal motion like linking other carts. There is some separation movement that is normal when linking, but usually it is no more than  half a cart length (or less). 

**Screenshots & Video**
If applicable, add screenshots and video to help explain your problem.

**Environment**
 - Version [e.g. Railcraft 12.0.0-alpha-9]
 - Forge version.
 - Possible conflicting mods and their versions.

**Additional context**

**Comment by CovertJaguar** [comment]
How amusing...

**Comment by DiamondSwag** [comment]
I would just like to comment that I have also noticed this bug. The regular BatBox carts function fine, but the MFE cart seems to behave a big "funny".
