### ISSUE TITLE
BootstrapMethodError

### ISSUE THREAD

**Issue by walker-dev** [Railcraft/Railcraft#1578]
**Description of the Bug**
crash on startup see log

**Environment**
 - Version railcraft-12.0.0-beta-1

**Additional context**
[Crash Log Here](https://gist.githubusercontent.com/boosterdev/13122d2c4293e463aa5d6b6f412dfd40/raw/90b1f00b54fc0339a3766a07f2ff1bf3170e5571/gistfile1.txt)

Ignore me for a few days and celebrate chrismas mate :)

**Comment by Onigeshi** [comment]
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.items.ItemFilterBeeGenome.<init>()void/newInvokeSpecial

Install forestry, gendustry or binnies mods.. I don't know from which one of this is this Genome Filter but after installing all these 3 mods it didn't crash anymore..

**Comment by Yzelast** [comment]
looks like installing forestry fix the crash...

**Comment by navaroneee** [comment]
Is forestry needed?

**Comment by liach** [comment]
Looks like we need to add another wrapping supplier to prevent class loading

**Comment by navaroneee** [comment]
Ah ok, fine Merry xmas, and tnks for this gift :D

**Comment by liach** [comment]
2f7415d10423702f3082079aa2c1e33c0dff685a

**Comment by liach** [comment]
Is this fixed in beta 2?

**Comment by walker-dev** [comment]
Yes it is fixed

**Comment by Trinsdar** [comment]
this may have reappeared in beta 4.

**Comment by liach** [comment]
@Trinsdar Log/crash report please.

**Comment by Trinsdar** [comment]
https://paste.dimdev.org/dumebinomi.rb
I might have to test outside my dev instance just to make sure

**Comment by liach** [comment]
aye, cannot see it in china, dunno why. if you can put it on pastebin or gist that is better

**Comment by Trinsdar** [comment]
https://gist.github.com/Trinsdar/e90b133fff842eb0fae921b06e1d7749

**Comment by liach** [comment]
hmm, i cannot find the cause this time. adding a mod prerequisite for this item might be the best solution, i guess.

**Comment by 3TUSK** [comment]
~~Successfully replicated this issue in a decompiled dev environment. All details are present in this crash report: https://paste.ubuntu.com/p/dgfCqBdssp/~~

Edit: this is exactly the reason why we have `deobfCompile`. Use that. Period.

**Comment by liach** [comment]
looks like forge optional interface transformer breaks in dev
