### ISSUE TITLE
1.12.2 Crash 

### ISSUE THREAD

**Issue by AkuzeTR** [Railcraft/Railcraft#1581]
**Crash 1.12.2**

Here is a bin file 

https://pastebin.aquilenet.fr/?21c88e9b2fcea7ed#q6SMGoICnjZclDmBtQAwxjChI49t59Guc4pJQBcPido=

**Comment by Yzelast** [comment]
looks like installing forestry fix the crash...

**Comment by liach** [comment]
Dupe of #1578
