### ISSUE TITLE
1.12.2 missing texture

### ISSUE THREAD

**Issue by Nagyur** [Railcraft/Railcraft#1582]
**Missing texture **
Iron and steel valves has no textures.

**To Reproduce**
1. install mod
2. craft a valve

**Expected behavior**
Has some decent texture on valves. 

**Screenshots & Video**
![railcraft](https://user-images.githubusercontent.com/46134085/50424056-d67d6180-085e-11e9-83a5-d997f9f6ca08.png)

**Environment**
 - Version [e.g. Railcraft 12.0.0-beta-1]
 - forge-1.12.2-14.23.5.2796
- a bunch of other mods

**Comment by liach** [comment]
Seems the tinted cube model has some issues.

**Comment by Nagyur** [comment]
I checked inside the .jar the base texture is there. but i couldn't do anything more than this to fix it. Because Railcraft not referencing textured directly but shade a base one. (as far as i understand)

**Comment by liach** [comment]
Yeah, the texture is fine but the model that binds the texture is not.

**Comment by CovertJaguar** [comment]
I managed to get it to stop tossing errors, but it still fails to load the textures for some reason.

**Comment by liach** [comment]
i got the cause and may push soon.

**Comment by liach** [comment]
This is my bad.

**Comment by liach** [comment]
Done with rendering, though the translation is still a todo.
