### ISSUE TITLE
Firebox crash

### ISSUE THREAD

**Issue by wormzjl** [Railcraft/Railcraft#1583]
**Description of the Bug**
This crash happens whenever I try to place down a solid/fluid fueled firebox
Crashlog:
https://gist.github.com/wormzjl/c40aba893d5fb66d06d2388565a4f83e

**Environment**
 - Version: railcraft-12.0.0-beta-1
 - Forge version. 2796
 - Possible conflicting mods and their versions.

**Comment by liach** [comment]
might just need a check for valid multiblock

**Comment by liach** [comment]
oh, the old logic was totally wrong. i am considering using the pattern in param instead

**Comment by The-Panopticon** [comment]
I just encountered the same issue and upgraded to 12.0.0 beta 4, from beta 3, and am now encountering the issue with Liquid Fireboxes as well, after placing just 3. You may already be aware of this, biut i figured another report couldn't hurt. Here's the latest Crash Report.

https://gist.github.com/Zyd3r/b498d309889330475ba143cd555ff0e0

**Comment by CovertJaguar** [comment]
I'm currently working my way through the multiblocks and migrating them to a new, less coupled, framework. I haven't got to the Boilers yet, working my way through the crafters right now.

The code that is crashing here is in the guts of the stuff that got redesigned, so no point fixing it until I'm ready to do the complete migration of the boilers.

**Comment by The-Panopticon** [comment]
that makes complete sense! I look forward to seeing the results, and I appreciate your hard work!
