### ISSUE TITLE
Elevator rail does not dismount cart

### ISSUE THREAD

**Issue by draxxris** [Railcraft/Railcraft#1586]
Using railcraft-12.0.0-alpha-9

Elevator rail does not seem to dismount from the rail once it gets to the top of the elevator. No configuration of rails at the top seemed to work.

https://www.youtube.com/watch?v=fD4S1QyEvMA

**Comment by liach** [comment]
Hmm, do you use some texture pack

**Comment by draxxris** [comment]
Use:

https://minecraft.curseforge.com/projects/ctm
 
And

https://minecraft.curseforge.com/projects/ctp

**Comment by liach** [comment]
please try with only railcraft and forestry.

**Comment by CovertJaguar** [comment]
Doesn't surprise me much.

**Comment by draxxris** [comment]
Same behavior with only JEI/Forestry/Railcraft installed.

Also tested on 12.0.0-beta-1

**Comment by liach** [comment]
For now, you can add one more elevator track block on top of the elevator column. The top of elevator must be at the same level as the track at top. The described old behavior on the wiki has changed and I will modify that.
