### ISSUE TITLE
Issue with first Blast Furnace

### ISSUE THREAD

**Issue by Calculus-Master** [Railcraft/Railcraft#1588]
Using Railcraft 12.0.0 beta-1 for 1.12.2
(Also using Forestry along with Railcraft, Forge 14.23.5.2796)

After putting 1 iron ingot into the blast furnace, and after it makes steel, the progress arrow remains white, and breaking/replacing a block in the multiblock doesn't fix it immediately
After breaking/replacing, the multiblock will not form until repeating the same process a few times

**Expected behavior**
The progress bar should reset

**Comment by CovertJaguar** [comment]
Fixed by 863fd5b39a40155d672051aa6e76e3cb27341c98
