### ISSUE TITLE
Crash when placing the boiler block on a server

### ISSUE THREAD

**Issue by Marco4413** [Railcraft/Railcraft#1591]
**Description of the Bug**
The world crashed when the boiler block was placed,
can't open the world anymore

**To Reproduce**
1. Place the boiler block
2. The World should crash
3. Try to re-open the world and the game crashes again

**Expected behavior**
The game shouldn't crash

**Crash Log**
https://pastebin.com/v5hzAC0V

**Comment by liach** [comment]
same as #1583
