### ISSUE TITLE
[12.0.0-beta-2] Train Dispenser block cause crash

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#1592]
**Description of the Bug**
If you use Train Dispenser Block to spawn train cart, it will completely crash.

**To Reproduce**
1. Place Train Dispenser Block
2. Open Train Dispenser Block GUI
3. Set Pattern cart & put cart on Buffer
4. Quit Train Dispenser Block GUI & use redstone block to activate.
5. Crashed.

**Environment**
Railcraft 12.0.0-beta-2
Forge 1.12.2-14.23.5.2796

**Additional context**
See the logs here: https://pastebin.com/yLYmJJZq

**Comment by CovertJaguar** [comment]
Strange

**Comment by liach** [comment]
Uh, github forgot to close this.

**Comment by CovertJaguar** [comment]
You have to write either "Fixes #num" or "Closes #num" in the commit message for that to work.

**Comment by liach** [comment]
Should have written `#1592 Fix train dispenser crash` instead.

**Comment by CovertJaguar** [comment]
https://help.github.com/articles/closing-issues-using-keywords/
