### ISSUE TITLE
[Question] What stone types spawn naturally?

### ISSUE THREAD

**Issue by Voxel-Friend** [Railcraft/Railcraft#1593]
I am adding [Ore Stone Variants](https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants) for my ores in my pack and need to know which railcraft stone types (like quarried stone) spawn naturally. Thank you for your continued hard work!

**Comment by liach** [comment]
just quarried and abyssal ones do. on a side note, abbysal ones generate under seas in balls with empty space inside while quarried generate on forest surfaces.

**Comment by Voxel-Friend** [comment]
Ok thanks! Just wanted to make sure!
