### ISSUE TITLE
Crash when trying to place fuel in Worldspike

### ISSUE THREAD

**Issue by Flaksmith** [Railcraft/Railcraft#1594]
**Description of the Bug**
Attempting to insert a single item of any valid fuel type in the fuel slot of any worldspike will cause the game to crash. A crash does not occur when trying to insert two or more items that are stacked. Additionally, a crash won't occur after the worldspike has consumed any amount of fuel.

**To Reproduce**
1. Place any of the 3 worldspikes which consume fuel.
2. Open the GUI and attempt to insert a single piece of fuel (any type) by any means (shift+left-click, right-click drop, left-click drop, etc.)
3. Crash

**Expected behavior**
The fuel to be consumed and the worldspike to start working

**Screenshots & Video**
https://i.imgur.com/wJawYAn.png
Dropping a single piece in the fuel slot here will cause a crash, placing a stack of 2 or more inside by left click and drop, or shift+left clicking will cause normal function. 

https://i.imgur.com/3AvWQyN.png
Once the worldspike has consumed fuel, individual pieces of fuel can be placed in the fuel slot without causing a crash. I have not confirmed if a crash will occur once the timer has run out.

**Environment**
- Minecraft 1.12.2 
- Railcraft 12.0.0-beta-1
- Forge 14.23.5.2796
- IC2 2.8.105-ex112
- Buildcraft 7.99.20
- Forestry 5.8.2.374
- Project Red 4.9.1.92
- Ender Storage 2.4.5.135

**Additional context**
I planned to use these in my modded world instead of the IC2 chunkloaders (which keep sucking power and can't seem to be switched off), but I decided to be safe and test them in a creative world first, really glad I did.

**Comment by liach** [comment]
@Flaksmith Please give me a crash report, or I cannot fix this for you!

**Comment by liach** [comment]
https://gist.github.com/liach/67dace1e45f632fa438d02a98a7c28bc

**Comment by liach** [comment]
The cause is clear: there is an entry in the fuel map that maps an item to `null` float, causing an npe.

**Comment by liach** [comment]
Hmm, I don't know how a null gets there...

**Comment by liach** [comment]
Moreover, after one crash, placing fuel into other worldspike blocks without fuel no longer cause crashes. This may be an initialization issue.

**Comment by WarlordWossman** [comment]
Having related problems in beta 3, trying to get fuel into a worldspike using a hopper:
[crash-2019-01-10_02.34.50-server.txt](https://github.com/Railcraft/Railcraft/files/2743242/crash-2019-01-10_02.34.50-server.txt)

**Comment by liach** [comment]
same fuelmap glitch.
