### ISSUE TITLE
Void chest no longer renders

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1595]
**Description of the Bug**
Void chest texture does not stitch, either as a block or in a minecart.

**To Reproduce**
1. Find void chest in creative inventory
2. Observe a blank item and a void chest cart
3. Put the blank item in hotbar and right click to place it. Observe the bounding box. Right click again to show the inventory of void chest works. Turn on F3 and see that the void chest block does exist.

**Expected behavior**
The void chest should stitch its texture like the metals chest does (metals chest works fine)

**Screenshots & Video**
![2018-12-26_13 11 09](https://user-images.githubusercontent.com/7806504/50457429-44359600-0910-11e9-9e4e-736f7061bd0d.png)
![2018-12-26_13 11 11](https://user-images.githubusercontent.com/7806504/50457430-44359600-0910-11e9-99cd-9a22fbe58244.png)
![2018-12-26_13 11 20](https://user-images.githubusercontent.com/7806504/50457431-44359600-0910-11e9-986d-6c86e93cc341.png)

**Environment**
 - 12.0.0 beta 2 (dev env)
 - Forge version 14.23.5.2779
 - With runtimeOnly mods present

**Additional context**
The metals chest works fine; the void chest cart does not stitch texture to the block as well.

**Comment by CovertJaguar** [comment]
I can't imagine what I would have done to affect rendering.

**Comment by liach** [comment]
Fixed by cj.
