### ISSUE TITLE
Worldspike does not drop fuel on destruction

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1596]
**Description of the Bug**
When a survival mode player destroys a regular worldspike, it does not drop fuels yet in its inventory.

**To Reproduce**
1. Put fuel into a worldspike, e.g. 16 void dusts
2. Observe that the spike consumes one fuel and leaves 15 void dusts
3. Break the block with a diamond pickaxe (survival mode required). The world spike itself will drop; however, the 15 void dust won't.

**Expected behavior**
The 15 unused void dust drops.

**Screenshots & Video**
Computer not good enough to make vid

**Environment**
 - 12.0.0 beta 2 (dev env)
 - Forge version 14.23.5.2779
 - With runtimeOnly mods present

**Additional context**
None.

**Comment by CovertJaguar** [comment]
Hmm... oh... its probably not handled automatically by the super class because it doesn't usually actually implement IInventory.

**Comment by CovertJaguar** [comment]
The tiles were never getting sent the break event. They had already been deleted.
