### ISSUE TITLE
Server crash (null pointer exception related to track kit (locking)

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1597]
**Description of the Bug**
The server crashes out of the blue with a null pointer exception. Says related to locking track kit. 

Before the crash, I received a WALL of red text in the server command line that seems railcraft-related. There was so much that it scrolled my terminal window... whatever was last left is there. 

CRASH REPORT: 
[crash-2018-12-26_16.35.37-server.txt](https://github.com/Railcraft/Railcraft/files/2710969/crash-2018-12-26_16.35.37-server.txt)

SUPPORTING (COPY OF TERMINAL OUTPUT): 
[crash-2018-12-26_16.35.37-server_SUPPORTING.txt](https://github.com/Railcraft/Railcraft/files/2710970/crash-2018-12-26_16.35.37-server_SUPPORTING.txt)

**To Reproduce**
Not sure. 

**Expected behavior**
Not crash

**Screenshots & Video**
If applicable, add screenshots and video to help explain your problem.

**Environment**
 - Version [e.g. Railcraft 12.0.0-beta-2]
 - Forge 2796.
 - Possible conflicting mods and their versions.

**Additional context**

**Comment by liach** [comment]
hmm, locking track crash

**Comment by texaswriter** [comment]
I'm trying to recreate... I have 8 trains in the exact situation. I am watching the area it happened though. i'll let it run up to 10 trains in this situation (the rail network automatically spaces the trains out through the network).

**Comment by texaswriter** [comment]
What happened was that some cart seemed to get disconnected from a train... this was stuck in another entity... i think it caused some feedback to railcraft or other trains... 
I restarted the server (it crashed), then i had another train get stuck there... I stopped the train, and tried to troubleshoot.. there was an invisible cart there. restarted the server again. now I could see the cart. broke it, reset the train that was stuck, and it was fixed... but I don't know what caused the initial lockup (should not have been trains crashing... they were all spaced)

**Comment by texaswriter** [comment]
Another crash. In creative was trying to click on a cart to delete. Sometimes the click goes through to the next block. This click landed on a turnout track, (removing it?) and instantly crashing the server. 
[crash-2018-12-27_01.11.47-server.txt](https://github.com/Railcraft/Railcraft/files/2711744/crash-2018-12-27_01.11.47-server.txt)

**Comment by liach** [comment]
same crash as before.

**Comment by texaswriter** [comment]
Yeah. I am trying to add some context for you, not sure if it helps you troubleshoot. Here is another crash. Was trying to delete a cart. INstantly crashed server. You don't have to read... same as above. 
[crash-2018-12-27_01.25.30-server.txt](https://github.com/Railcraft/Railcraft/files/2711769/crash-2018-12-27_01.25.30-server.txt)

**Comment by liach** [comment]
k, it's null train again
