### ISSUE TITLE
Crash on startup after disabling structures module

### ISSUE THREAD

**Issue by laserlemons** [Railcraft/Railcraft#1601]
**Description of the Bug**
The game crashes on startup after disabling the structures module.
https://pastebin.com/YBCR4zNb

**Environment**
 - Railcraft 12.0.0-beta-2
 - Forge version 2796
 - I also have the whole suite of COFH mods. (Thermal Expansion)

**Comment by liach** [comment]
This has been confirmed by a few other users as well.
https://github.com/Railcraft/Railcraft/blob/5af3e73e576e099d8676e621fae3d7495ab1d2c0/src/main/java/mods/railcraft/common/blocks/detector/BlockDetector.java#L170
Should be replaced by an `isLoaded()` fix.
