### ISSUE TITLE
[1.12.2][Crash] "Ticking block entity" when placing boilers

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Railcraft/Railcraft#1605]
**Description of the Bug**
When i placed some (solid fuel) boilers the game just crashed, the world is completely broken as any attempt at opening it just instantly crash the game again

**Logs & Environment**

[LOG](https://pastebin.com/w9ybfVbm)

**Comment by liach** [comment]
duplicate of #1583

**Comment by ProxyPlayerHD** [comment]
oops sorry. i searched for ticking block entity and didn't find anything

**Comment by liach** [comment]
No worries, I do expect people to report duplicate major bugs.

**Comment by ProxyPlayerHD** [comment]
that's how you know they are major. :)

**Comment by CovertJaguar** [comment]
I'm slowly working my way through the MBS bugs.
