### ISSUE TITLE
[1.12.2] Sponge Forge server crash while using Manual Rolling Machine

### ISSUE THREAD

**Issue by 054545641** [Railcraft/Railcraft#1607]
**Description of the Bug**
Producing (at least) something on Manual Rolling Machine will cause a server crash on SpongeForge Server. And there will be java.lang.IncompatibleClassChangeError in the Crash-report.

**To Reproduce**
1. Place a Manual Rolling Machine anywhere
2. Right click to open GUI of the Manual Rolling Machine
3. Put a Iron Ingot into it
4. Click Track Parts and wait for its completion

**Expected behavior**
A Track Part should be made normally without crash.

**Logs & Environment**
 - Environment:
Forge version 1.12.2-14.23.5.2779
Sponge version 1.12.2-2768-7.1.4
Railcraft version 12.0.0-beta-2
 - Full log: 
[debug.log](https://gist.github.com/054545641/13d7694f12bdfae396b699438bac889a)
[latest.log](https://pastebin.ubuntu.com/p/cj3yzHsrPx/)
 - Crash report (If available): 
[Crash-reports-server.txt](https://pastebin.ubuntu.com/p/zYfdkppZs9/)

**Comment by liach** [comment]
Sponge bug.

**Comment by liach** [comment]
@CovertJaguar Apparently sponge doesn't want our inventory to implement iterable for something other than `Iterable<org.spongepowered.api.item.inventory.Inventory>`. Blame Mumfrey.

**Comment by CovertJaguar** [comment]
They make a change like that and expect it to break nothing? Lol.

Closing due to _Not Railcraft_

**Comment by liach** [comment]
I think I will start working on the sponge compat soon, at least fixing this thing
