### ISSUE TITLE
[1.12.2] Dust of ender pearls

### ISSUE THREAD

**Issue by Draskh** [Railcraft/Railcraft#1609]
The dust of ender pearl that is added by Railcraft is registered in OD as dustEnder. Most mods use dustEnderPearl instead. That causes some incompability with Railcraft. Maybe additional registration can be added or completly changed?

**Comment by liach** [comment]
Please list some mods. Afaik, some mods use `dustEnder`, including not enough potions mod,

**Comment by Draskh** [comment]
-Ender IO
-Applied Energestics 2 (uses both in recipes as alternatives)
-Tech Reborn

**Comment by liach** [comment]
For now use crafttweaker to bypass this restriction.

**Comment by Draskh** [comment]
I registered everything correctly. Then I tried to fix the recipes.
>#Fixing ender pearl dustFertilizer
>recipes.replaceAllOccurences(<ore:dustEnder>, <ore:dustEnderPearl>);
>recipes.replaceAllOccurences(<railcraft:dust:6>, <ore:dustEnderPearl>);

That's lead to a recipe in which void powder is made of three ender dust instead the normal recipe. Don't know how this could happend.

**Comment by liach** [comment]
I guess crafttweaker has some issues with item meta. Cannot help beyond that,

**Comment by Draskh** [comment]
That only effects Railcraft. No other mod though.

**Comment by Draskh** [comment]
> I guess crafttweaker has some issues with item meta. Cannot help beyond that,

That couldn't be a problem with metadata. The recipes uses dustObsidian for instance. It seems that Crafttweaker finds the right recipes and assumes that every ingredient is railcraft:dust:6 instead of just one.

**Comment by CovertJaguar** [comment]
It might be adding ItemDust to the oreTag as a wildcarded ItemStack, matching everything.
