### ISSUE TITLE
[1.12.2] Steam boiler outputs water insted of steam

### ISSUE THREAD

**Issue by PowerAmbroz** [Railcraft/Railcraft#1611]
**Description of the Bug**

The bug appears when I try using Mekanism fluid Pipes, or any other fluid pipe from other mods. At first the Railcraft Steam Boiler outputs water than it changes to steam and back to water. I've tryed all the sites of the multyblock but the problem still appears.

**To Reproduce**

1. Place block/cart '...'
3. See '...'

**Expected behavior**

If it is possible, it would be fine to have a config GUI where you can set where is the water input, the fuel input and the steam output is located.
Eventualy a sort of fix that will detect that the player want's to output steam not water from the boiler.

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by liach** [comment]
Don't use a pipe. Place an empty fluid container block aside and see what happens to that container (e.g. an empty tank from any mod)

**Comment by CovertJaguar** [comment]
Put it next to the Boiler tank blocks as well. The firebox allows access to the water tank.

**Comment by liach** [comment]
The production is right. We just need to set canDrain to false.
