### ISSUE TITLE
[1.12.2] Fueled Boiler and Tank Bug

### ISSUE THREAD

**Issue by Tonton-Juro** [Railcraft/Railcraft#1613]
I want to report you more bug / problem on the latest version of Railcraft:
Config: Java 1.8.0_191 64 bit Forge 14.23.5.2779 (I also tried forge 14.23.5.2796, test done only solo and in creative

first of all the Fluid Fueled Boiler and Solid Fueled Boiler make crash minecraft of they are posed 

then I noticed several problems:
the water tank does not fill with water alone (which should normally be the case).
the iron and steel tanks have the same capacity of storage

the iron, steel and water tank do not display the encrypted capacity (the precise number of bucket).

Log : https://pastebin.com/j2nZ1D45

If need more info do not hesitate to contact me

**Comment by YukariMindGap** [comment]
I can confirm it happen to everyone else not just him.
Running minecraft with no other mods.
Log: https://pastebin.com/0aYTmff3

**Comment by Jarrose37** [comment]
I wonder when it will get fixed

**Comment by Filvandrel** [comment]
Same here. I also get a ticking tile entity crash everytime I place any boiler firebox block.

**Comment by liach** [comment]
See #1611 #1583
