### ISSUE TITLE
[1.12.2] Cascading world generation

### ISSUE THREAD

**Issue by Draskh** [Railcraft/Railcraft#1617]
https://pastebin.com/rDe382GE

I had this all the time spamming my sever console causing players timing out. 

Forge:2076
Railcraft: 12.0.0 Beta 2

**Comment by liach** [comment]
The spam happens, but it does not cause players to time out.

**Comment by CovertJaguar** [comment]
The code has been the same since forever. The only difference is that Forge decided to complain about it instead of ignoring it. It'll get fixed eventually, but crashes and usability bugs come first as this one doesn't have any affect other than a one time tick cost on chunk generation.

**Comment by liach** [comment]
Merging into #1474
