### ISSUE TITLE
Brass recipe does not work when inventory tweaks is loaded

### ISSUE THREAD

**Issue by Trinsdar** [Railcraft/Railcraft#1623]
**Description of the Bug**
If inventory tweaks is loaded brass cannot be crafted from 3 copper ingots and one zinc ingot

**To Reproduce**
1. install inventory tweaks
2. get three copper ingots and one zinc ingot
3. try to craft brass

**Expected behavior**
brass should craft from 3 copper ingots and one zinc ingot

**Screenshots & Video**
![2019-01-06_18 18 37](https://user-images.githubusercontent.com/30245301/50742927-6fa56400-11df-11e9-934a-c53216a109aa.png)

**Logs & Environment**
latest.log: https://paste.dimdev.org/qamoluhafi.md

**Additional context**
Railcraft 12.0.0-beta2
forge14.23.5.2779
inventory tweaks-1.63
Edit: tested with latest alpha version of inventroy tweaks on curseforge and still happens

**Comment by liach** [comment]
My best guesses: 
1. Inventory tweaks coremod tweaked container code and broke recipe identification; 
2. inventory tweaks registers oredict entry `dustZinc` and `dustCopper`, making railcraft assume that there is alternative logical ways to craft brass

Needs digging.

**Comment by liach** [comment]
Ah, got it. it should be cause 2.

https://github.com/Inventory-Tweaks/inventory-tweaks/blob/88fda94ca737c3a93cc1f19b5e57f506e5d9e514/src/main/resources/assets/inventorytweaks/itemtree.xml#L628

**Comment by Kobata** [comment]
So, as far as my side goes:

1. The coremod's arbitrary-ish edits are limited solely to adding new methods that are used for internal things. The only stuff it does that actively edits existing things is the small tweak to prevent registering sort commands while typing, and a few replacements of internal things to hook them up the the added methods.
2. I don't register new ore entries anywhere. The use of the ore dictionary is solely limited to asking for the list of items registered with that entry (and monitoring for new registrations).

Looking at Forge, I do concur it's probably 2 (the 'get entries in the dictionary from a name' method ends up adding that name to the dictionary for... some reason), but while I can sidestep it by adding a similar initial check, I do think that railcraft needs to fix this as well: assuming existence of a key in the dictionary means anything in particular is obviously incorrect.

**Comment by liach** [comment]
imo invtweaks does not need to change. This can be done by railcraft itself.

**Comment by Kobata** [comment]
I'm making it avoid unnecessarily adding the entries just because that's a good thing to do in general anyway. (That code's been there for quite a while so I probably either didn't notice or the non-cluttering version didn't exist at the time)

**Comment by Trinsdar** [comment]
Makes me wonder if I should check other alloy recipes

**Comment by CovertJaguar** [comment]
What is this code even doing? Why doesn't it just register the recipes?

Looking at the history, this looks like a bad merge by @Generalcamo.

Removed here:
https://github.com/Railcraft/Railcraft/commit/4a6527fc83247320e484f1168cd185f27872a4c4

Then readded here:
https://github.com/Railcraft/Railcraft/commit/0201daf855467376f2a70c670f2ec3e7303cfb45

**Comment by Generalcamo** [comment]
Yes I apologise for that. I'll go ahead and fix it.
