### ISSUE TITLE
Game crashes when open JEI coke oven recipes GUI

### ISSUE THREAD

**Issue by samjviana** [Railcraft/Railcraft#1628]
**Description of the Bug**

Game crashes when try to open the coke oven recipes GUI from JEI, even the launcher closes!
Obs. This only happens when the game window is with the height bigger than approximately 750px, the width doesn't seems to affect in nothing.

**To Reproduce**

1. Just click on the "fire" icon on the coke oven, or press "R" to see the recipe of something that is done in the coke oven.

**Logs & Environment**

 - [Full log](https://gist.github.com/Maarsupial/e39ea725b0f187fb82b0caf14b49a8ea) 

 - [Crash report](https://gist.github.com/Maarsupial/be7a556e1eb7c807ce209371a4578249#file-crash-2019-01-08_05-08-08-client-txt)

**Comment by CovertJaguar** [comment]
Are you running custom configs? It seems one of the recipes had no input assigned.

**Comment by CovertJaguar** [comment]
Upon inspection this probably happens if IC2 isn't installed as the ore tag "woodRubber" then has no members defined.

**Comment by TheDeviantCrafter** [comment]
I had a similar crash, and IC2 was not installed.

**Comment by CovertJaguar** [comment]
Yes, the underlying issue is fixed. And I think even made it into Beta-4.
