### ISSUE TITLE
[12.0.0-beta-3][Server] Crash on server launch

### ISSUE THREAD

**Issue by GameBurrow** [Railcraft/Railcraft#1629]
**Description of the Bug**
Railcraft is causing server to crash after update to beta-3 from beta-2.

**To Reproduce**
Start our server after update to Beta 3

**Expected behavior**
Start server without crashing.

**Screenshots & Video**
-

**Logs & Environment**

 - Full log: 
https://gist.github.com/kerts93/1195b4cf93bbe18c75a34f5137ad7b95
 - Crash report (If available): 
https://gist.github.com/kerts93/9359e70718060a93b7fddf7eb9b0b6cc

**Additional context**
Modpack: https://minecraft.curseforge.com/projects/the-society-transportcraft
Broken version: https://cloud.sepaurg.eu/index.php/s/XRQqdMbX6dQTbY5
_This is curse instance source file, we archived it on curse to revert back to previous version_

**Comment by Sixdd6** [comment]
Can confirm, Railcraft is calling renderer on serverside.
Here is the crash report: [linky](https://pastebin.com/p8Mqh6jx)

**Comment by laxadeR** [comment]
Just for the sake of it, tried clean empty server with just railcraft on it, same issue.
[Crash report](https://pastebin.com/N0wxMLkK)

**Comment by liach** [comment]
Hmm, this crash is totally weird. I guess the cause might be in private code.

**Comment by CovertJaguar** [comment]
Closed by 6b105a96d17b9941204a801a1ff217ae1a20b0a1

**Comment by chrizfilmz** [comment]
the bug is not fixed, why did you close this issue? i still have it ass of 10minutes ago

**Comment by GameBurrow** [comment]
@chrizfilmz Fixed in code, which will come to you with next release.
