### ISSUE TITLE
[12.0.0-beta-3]IC2 charge feeder unit 

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1632]
**Description of the Bug**
Can only get it by using the command:
`/give <playername> railcraft:charge_feeder`
Missing texture, instantly disappears after being placed in the world, doesn't show up in creative.

The admin version seems to be fine, it doesn't share any of the problems named above.

**To Reproduce**
I used a clean 1.12.2 install with forge 14.23.5.2784 and railcraft 12.0.0-beta-3 and was only able to get the block the way I named above.

**Expected behavior**
Somewhat similar to the admin charge feeder where you can normally see it in creative and place it in your world.

**Screenshots & Video**
![2019-01-09_03 36 07](https://user-images.githubusercontent.com/16925725/50873673-3298c780-13c1-11e9-8649-f975d8f8a459.png)
![2019-01-09_03 36 30](https://user-images.githubusercontent.com/16925725/50873677-37f61200-13c1-11e9-82b7-5b5850e45d65.png)

**Logs & Environment**
[2019-01-09-1.log.gz](https://github.com/Railcraft/Railcraft/files/2739175/2019-01-09-1.log.gz)

**Comment by WarlordWossman** [comment]
It does work with IC2 installed it seems, so not sure if this would still be considered a bug.
Would like to see a feeder unit that works with GTCE but that's a feature request at this point.

**Comment by CovertJaguar** [comment]
It would probably crash your game if you tried to use it without IC2 installed.

GTCE uses a different energy API and would require its own block.
