### ISSUE TITLE
Can not craft advanced and powered rails

### ISSUE THREAD

**Issue by JosephFoster118** [Railcraft/Railcraft#1634]
**Description of the Bug**
I'm unable to craft the advanced and powered rails in the rolling machine

**To Reproduce**
Place items in recipe listed online into rolling machine

**Expected behavior**
Advanced and powered rails can be crafted

**Screenshots & Video**

![desktop screenshot 2019 01 10 - 06 39 55 14](https://user-images.githubusercontent.com/18226716/50969121-f3db3e00-14a2-11e9-95b7-c7b9cdbeb4ad.png)

![desktop screenshot 2019 01 10 - 06 41 14 60](https://user-images.githubusercontent.com/18226716/50969126-fa69b580-14a2-11e9-9d93-1dcb1b194401.png)

**Logs & Environment**
 - Full log: 

[debug.log](https://github.com/Railcraft/Railcraft/files/2745312/debug.log)
[latest.log](https://github.com/Railcraft/Railcraft/files/2745313/latest.log)

**Additional context**

Additional mods loaded:
[mods_list.txt](https://github.com/Railcraft/Railcraft/files/2745318/mods_list.txt)

**Comment by CovertJaguar** [comment]
I believe those are the old recipes. They have changed.

**Comment by liach** [comment]
Advanced rails are 3 gold ingots on the left column and 3 redstone dusts on right column. 
Electric rails are 3 copper ingots on the left column and 3 more copper ingots on the right column.
Both recipes should have their middle column left blank.

**Comment by liach** [comment]
Hmm, I am curious. This recipe has been changed since the 1.10 port, but people seem to be unaware of this change all along.

**Comment by CovertJaguar** [comment]
Which reinforces my belief that not many people played 1.10.

**Comment by JosephFoster118** [comment]
The wiki is where I went to get the recipes, it still list the old ones.

**Comment by liach** [comment]
Fixed on wiki for now with a short description. http://railcraft.info/wiki/part:rails
