### ISSUE TITLE
Fluid Unloader

### ISSUE THREAD

**Issue by red360** [Railcraft/Railcraft#1644]
**Description of the Bug**
Fluid Unloader only works from above track/fluid cart.
MC 1.12.2
RailCraft  12.0.0-beta-4

**Comment by liach** [comment]
is my pr in beta 4 yet? if not, the explanation is that you looked up when placing the unloader.

**Comment by red360** [comment]
OK yes the Unloader works as expected when placing under track looking down.
Thanks.

**Comment by liach** [comment]
this bug is implemented and will be fixed in the next beta.

**Comment by liach** [comment]
Closing. Will be tracked in #1641 instead.
