### ISSUE TITLE
No textures for steam

### ISSUE THREAD

**Issue by chrizfilmz** [Railcraft/Railcraft#1650]
No textures for steam and related items.

**Comment by liach** [comment]
No screenshot, no evidence.

**Comment by liach** [comment]
A few other "missing texture for steam" cases have happened before as well; most of the time, it is caused by some other mods loaded before Railcraft adding broken steam. You should have filled out the issue template, at least the log part so that I can know what mods you have, etc.

**Comment by liach** [comment]
Steam works and does have texture. 
![2019-01-13_21 17 54](https://user-images.githubusercontent.com/7806504/51097420-bfa09f80-1778-11e9-8153-253ba4847b7a.png)

**Comment by chrizfilmz** [comment]
Sorry for long response this image is from beta-4
<img width="1062" alt="screen shot 2019-01-16 at 19 14 11" src="https://user-images.githubusercontent.com/20757946/51269581-1b5e6900-19c3-11e9-969d-3b46b54de475.png">

**Comment by liach** [comment]
@chrizfilmz Give me your mod list (press F3+C for 8 seconds or more and upload the crash report). One of the mods loaded before Railcraft is adding steam.
