### ISSUE TITLE
Tracks won't detect redstone signal

### ISSUE THREAD

**Issue by anar4732** [Railcraft/Railcraft#1651]
![2019-01-14_04 11 46](https://user-images.githubusercontent.com/10792085/51092611-b9c7b000-17b2-11e9-90e9-d6be7360d007.png)
![2019-01-14_04 11 51](https://user-images.githubusercontent.com/10792085/51092612-b9c7b000-17b2-11e9-98d0-756cab7ff2dc.png)

**Comment by liach** [comment]
Railcraft turnout and wye tracks are only controlled by actuators placed next to the track. You can control switch motor actuator with redstone.

**Comment by liach** [comment]
Will add that information to advancements instead.
