### ISSUE TITLE
[1.12.2] Placing a Void Chest in my inventory causes the game to crash.

### ISSUE THREAD

**Issue by Spearkiller** [Railcraft/Railcraft#1652]
**Description of the Bug**
Title. Any attempts to get a void chest results in the game crashing.

**To Reproduce**
1. Find the void chest in either JEI or the Creative Inventory, or craft one.
2. Click on it, and place it in your inventory.
3. The game will crash.

**Expected behavior**
I expected to be able to obtain and place a void chest to see what they do.

**Logs & Environment**
 - Full log: 
https://pastebin.com/1bPjTBfV
 - Crash report: 
https://pastebin.com/QaU8JAL8

**Comment by liach** [comment]
Will fix together when I apply the advancement ideas suggested on discord.
