### ISSUE TITLE
Steel and iron tank colored valves do not have the correct texture in world

### ISSUE THREAD

**Issue by Trinsdar** [Railcraft/Railcraft#1653]
**Description of the Bug**
When a steel or iron tank valve is placed in world it does shows the default steel and iron textures respectively rather then the correct colored variant.

**To Reproduce**
1. Grab a colored steel or iron tank valve
2. Place it in world
3. Voila

**Expected behavior**
The tank valves show the correct color in world.

**Screenshots & Video**
Look up in the top left corner to see what they really are.
![2019-01-13_20 05 02](https://user-images.githubusercontent.com/30245301/51093228-58cab880-176f-11e9-917f-c9007bb5ab7a.png)
![2019-01-13_20 07 51](https://user-images.githubusercontent.com/30245301/51093230-5ec09980-176f-11e9-8053-efc08743fe0a.png)
![2019-01-13_20 07 53](https://user-images.githubusercontent.com/30245301/51093232-62ecb700-176f-11e9-850e-56fb223265f3.png)
![2019-01-13_20 07 56](https://user-images.githubusercontent.com/30245301/51093236-67b16b00-176f-11e9-93d8-7449d37437b9.png)

**Comment by liach** [comment]
Easy fix. I should move the color check out of the multiblock structure valid block.

**Comment by Trinsdar** [comment]
Update: it does display the correct color when part of a formed multiblock.
