### ISSUE TITLE
Update trackman's backpack to accept track kits

### ISSUE THREAD

**Issue by texaswriter** [Railcraft/Railcraft#1664]
**Is your feature request related to a problem? Please describe.**
This feature request is to update the trackman's backpack to accept track kits since this is the preferred way of modding rails now. 

**Describe the solution you'd like**
Currently, the track kits can't be placed int he trackman's backpack. It would be desired for it to be the default accepted (without custom config)

**Comment by liach** [comment]
hmm, it should be already included in the trackman's backpack. it looks like a bug

**Comment by liach** [comment]
Ah, the track kit handles meta incorrectly for wildcards.
