### ISSUE TITLE
"Transport Mode" for special carts

### ISSUE THREAD

**Issue by 016Nojr** [Railcraft/Railcraft#1666]
It would be cool if special carts, like the track placer or remover or any of them could have a button in their gui that could toggle a "transport mode", what the transport mode would do is disable the cart's functionality and move around like a normal cart.

The transport mode would make the cart move faster because they are locked to move in their working speed.

An alternative solution would be to make the carts move faster when the inventory is empty or they arent working, but I think a button would be the best because a track remover would work all the time.

**Comment by anar4732** [comment]
And the mode changable with activator track

**Comment by liach** [comment]
i strongly disagree with anar4732. if we do add, we should add another kit. moreover, switching mode with kit really has no point as you don't need to automate these special carts for mode switching.

**Comment by CovertJaguar** [comment]
You might be able to create  some crazy contraptions if you could though I suppose.

**Comment by CovertJaguar** [comment]
Closed by e8ce548b5c6af142832dc4fffcbc2fa1e79f7fa2
