### ISSUE TITLE
Saving Trains message in server console, number increases without trains being made

### ISSUE THREAD

**Issue by ranger135xp** [Railcraft/Railcraft#1668]
**Description of the Bug**
Not sure what is going on but without anyone on my server, and no trains are being made by any players yet as RC was recently added, but I noticed the server logs say "21:31:54 Saving 367 Trains..." and the number gets higher and higher seemingly on its own.

**To Reproduce**
Not sure

**Expected behavior**

Saving trains matches the amount of actual RC trains

**Screenshots & Video**

![image](https://user-images.githubusercontent.com/15115164/51434576-16ebb780-1c32-11e9-9bc5-b2761d6e85ba.png)

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

This is a heavily modified FTB Revelation pack for myself and work friends.
Railcraft 12.0.0 beta 4
200+ other mods
Forge 14.23.5.2807

**Comment by liach** [comment]
This would happen if more minecarts are generated in a world. If you have mineshafts, each minecart would make up a train. As a result, the number of trains will increase.

**Comment by ranger135xp** [comment]
well, that number is increasing without moving around the map all but about 16 chunks so I'm not sure how it managed to escalate it's way to 444 trains in one area.

**Comment by liach** [comment]
hmm, try in b5 again

**Comment by CovertJaguar** [comment]
I don't think we have changed anything in the code that would have any affect on this since beta-4.
