### ISSUE TITLE
[Furnace Cart] Can't open furnace gui

### ISSUE THREAD

**Issue by Crosus97** [Railcraft/Railcraft#1670]
**Description of the Bug**
minecraft with furnace cannot clickand open the furnace ui on the last version (railcraft-12.0.0-beta-4)

**To Reproduce**
0.5 im in a minesharf
1. Place minecraft furnace cart
2. right Click on 'minecraft furnace cart'
3. the gui of furnace dont open it 

**Expected behavior**
i try without block in hand and with other tools

**Screenshots & Video**
https://www.youtube.com/watch?v=HtkwXDR4YEk

**Logs & Environment**

**Additional context**
the furnace sems to have another name "entity.cart_furnace.name" when i saw with wayla

**Comment by Crosus97** [comment]
the reverse button does not work either in the locomotive

**Comment by liach** [comment]
First, play vanilla.
https://minecraft.gamepedia.com/Minecart_with_Furnace#Usage Does not say that furnace carts have a gui. It tells you to feed it with coal or charcoal with use button instead, though railcraft enhanced that ability so that furnace carts can accept all fuels.
