### ISSUE TITLE
Make Switch Actuators break faster with crowbar

### ISSUE THREAD

**Issue by 016Nojr** [Railcraft/Railcraft#1671]
I assume this is a bug or just not yet implemented. It takes a long time to break a switch actuator, regardless of the tool, would make sense if a crowbar could break it fast (Tested with a normal switch)

Using version beta-4

**Comment by liach** [comment]
in theory pickaxes can break them faster if i am right. but this should be better harvested by crowbars.

**Comment by 016Nojr** [comment]
Nothing breaks the switches faster, sword, pickaxe, shovel and an empty hand are all the same.

**Comment by liach** [comment]
It should already break fast with iron pickaxes.

**Comment by 016Nojr** [comment]
@liach Doesnt with a diamond pickaxe, but I can try with Iron if it's supposed to be THAT specific

**Comment by liach** [comment]
hmm, will test again. I think there isn't any issue with it in code.

**Comment by CovertJaguar** [comment]
Originally, a lot of blocks where harvestable by both the crowbar and pickaxe, but a change in the Forge code for harvesting made it impossible to assign two tools a single block, which then resulted for a long time in Railcraft blocks being harvested randomly by either a pickaxe or crowbar, but no one was really sure which. So eventually everything was switched to the pickaxe.

**Comment by 016Nojr** [comment]
I thought it would make sense to be a crowbar since the tracks break with a crowbar
