### ISSUE TITLE
Junctions doesnt render electric tracks

### ISSUE THREAD

**Issue by 016Nojr** [Railcraft/Railcraft#1672]
Junctions doesnt render the electric track when it is an electric track as shown in the picture provided.
![2019-01-24_19 34 59](https://user-images.githubusercontent.com/8192699/51700409-5b4ecd00-200f-11e9-9b53-8804c5083312.png)

**Comment by liach** [comment]
hmm, i recall i made a texture fix a while ago. will look into the commit history

**Comment by CovertJaguar** [comment]
This is intentional, and not unusual in the real world. It also saves a us few super tricky texture translations that the shading on the center rail would require.

**Comment by 016Nojr** [comment]
@CovertJaguar Is it possible to make TOP/Waila show that the track is electric so you dont have to break the junction to find out?

**Comment by liach** [comment]
you can try using mag glass or charge meter
