### ISSUE TITLE
Flux transformer accepts rf only on NW side

### ISSUE THREAD

**Issue by Nobody931** [Railcraft/Railcraft#1674]
**Description of the Bug**
The flux transformer accepts rf only on 2 sides of the multiblock. Seen in the screenshot, only the bottom corner of the nord-west side of the multiblock will power the train. I tried EnderIO conduits, Thermal Foundations Fluxfuct and Immersive Engineerings wires. Tried it in 2 different worlds. Using beta-4.

**To Reproduce**
1. flux transformer multiblock and testtrack, put train on track
2. either connect flux transformer with shunting wire or build it beside the track
3. power the flux transformer with rf on either side, NW bottom side should work

**Expected behavior**
Regardless of the side, the flux transfomer should convert rf to charge and power the train/tracks

**Screenshots & Video**
![2019-01-24_21 16 42](https://user-images.githubusercontent.com/47010442/51706577-2a769400-201f-11e9-93a3-df797f7628b0.png)
The train is not moving at the moment

**Comment by liach** [comment]
hmm, will dig into the code.

**Comment by CovertJaguar** [comment]
I assume that only the master is accepting power correctly. The logic conversion should resolve it.

**Comment by liach** [comment]
Fixed in c935eb323d0fef7e2901d04d2f969e7407ab0148
