### ISSUE TITLE
[12.0.0 beta-4] Texture of Tunne boring Machine Bugged

### ISSUE THREAD

**Issue by Crosus97** [Railcraft/Railcraft#1676]
**Description of the Bug**
The texture of tunnel boring machine is not aligned or is bugged

**To Reproduce**

1. Place tunnel boring machine '...'
2. watch the texture [Video]

**Expected behavior**
the texture get drunk and the texture is not aligned

**Screenshots & Video**
https://youtu.be/7FIQbMM9BPk

**Comment by Nobody931** [comment]
I think this is a replica of #1614 and will be fixed in Beta-5 :)

**Comment by Crosus97** [comment]
yep sorry i didnt find it when i search it
