### ISSUE TITLE
Hopper Minecart not picking items

### ISSUE THREAD

**Issue by AzazelHD** [Railcraft/Railcraft#1678]
Hey, I have just installed railcraft, and it changes the behaviour of many things. The most annoying one is that the hopper minecart do not picks blocks on the tracks or 1 block above.

Could you fix this please?¿

I need it to automatize my farms

**Comment by liach** [comment]
will be fixed in beta 5

**Comment by AzazelHD** [comment]
And do you have any idea about when will beta 5 be released?

**Comment by liach** [comment]
cj is working, so guess soon (my guess is late jan or early feb, cannot promise)
