### ISSUE TITLE
Serene Seasons integration

### ISSUE THREAD

**Issue by Freddo3000** [Railcraft/Railcraft#1679]
**Is your feature request related to a problem? Please describe.**
Currently railcraft carts always have the winter texture, despite what biome/season it is.

**Describe the solution you'd like**
Depending on the season and/or biome, cart textures should dynamically change.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/Glitchfiend/SereneSeasons/wiki
Perhaps this could also affect boiler/locomotive heatup time? Though that and more or less this entire issue is mostly a wishlist issue, and effort is better spent elsewhere.

**Comment by CovertJaguar** [comment]
Oh? Tough As Nails got split into two mods? Interesting.

**Comment by CovertJaguar** [comment]
Looks pretty simple, I just need to change how I'm testing if it can snow at a block.
