### ISSUE TITLE
[suggestion] water tank config

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1680]
**Is your feature request related to a problem? Please describe.**
Not really a problem within RC itself but it would massively improve how RC can work together with other mods that need an automatic water supply.

**Describe the solution you'd like**
A config option to multiply the water tank output.

**Describe alternatives you've considered**
A more detailed config would also work so you can set all the values for biomes and rain/snow (de)buffs yourself but I think it would be simpler if you could just scale the existing values up.

**Additional context**
Options for making modpacks. It was always hard to give Railcraft the importance it should have when other mods are installed and configs give you the option to really make it happen.
In my specific example (modpack) water is finite in biomes other than rivers and oceans and the watertank is a cool earlygame alternative. Due to other mods installed you would sometimes need 10 or even more water tanks to fullfill the needs for water and I would like to buff them a little.

The fact that we are getting config options for the multiblock tanks and the chest minecarts already go into that direction and having control over the water tank as well would be very nice!

**Comment by CovertJaguar** [comment]
I reworked the algorithm for water generation as well:
https://github.com/Railcraft/Railcraft/blob/ea0f092266fb4f2af02b9933cb0bdde04391b563/src/main/java/mods/railcraft/common/blocks/logic/WaterGeneratorLogic.java#L26-L65
This code runs every 16 ticks (REFILL_INTERVAL) on every block of the water tank. The old code ran only for the master block with a base rate of 10 mB every 8 ticks. The base rate is now, by default, 4 mB * width * length every 16 ticks and can be adjusted in the config.

Additionally, biomes with temperature values over 1.0 will result in evaporation.

It should also be affected by the seasonal changes of the Serene Seasons mod.
