### ISSUE TITLE
Tunnel bore not working

### ISSUE THREAD

**Issue by pheiix** [Railcraft/Railcraft#1681]
I have trouble using the tunnel bore machine in minecraft 1.12.2, when ever I place it on the tracks it slides slowly forwards or backwards, and if I fill it with gravel, coal, tracks and put on a bore head, it turns 90 degrees and is facing sideways. The bore head is moving, but the machine won't move in the direction of the tracks... Tried placing it down inside a pre dug tunnel (3*3 and deep enough for the machine to be completely inside the tunnel). Also tried placing it out in the open, yet the result is always the same...

Edit: I have several mods installed, so I can't be sure it isn't some other mod that interferes with it, but a quick google search gives at least 1 hit on the issue...

**Comment by liach** [comment]
fixed in code, wait for beta 5
