### ISSUE TITLE
Iron and steel tanks have always 64.000 capacity regardless of size

### ISSUE THREAD

**Issue by krokots** [Railcraft/Railcraft#1682]
**Description of the Bug**
Tank size does not affect its capacity.

**Screenshots & Video**
Tank height 4
https://imgur.com/Gas67Df 
Tank height 5
https://imgur.com/R1omlHZ

**Logs & Environment**
Mod list 
AutoRegLib-1.3-24.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
binnie-mods-1.12.2-2.5.1.186.jar
BiomesOPlenty-1.12.2-7.0.1.2424-universal.jar
buildcraft-7.99.19.jar
Chisel-MC1.12.2-0.2.1.35.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.1.22-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CTM-MC1.12.2-0.3.3.22.jar
dungeonmobs-5.7.0-MC1.12.2.jar
DynamicTrees-1.12.2-0.9.2.jar
DynamicTreesBOP-1.12.2-1.4.1e.jar
energyconverters_1.12.2-1.2.0.10.jar
files.txt
forestry_1.12.2-5.8.2.380.jar
Forgelin-1.8.2.jar
gendustry-1.6.5.8-mc1.12.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
industrialforegoing-1.12.2-1.12.4-228.jar
jeibees-0.9.0.5-mc1.12.2.jar
jei_1.12.2-4.13.1.225.jar
JustEnoughResources-1.12.2-0.8.10.50.jar
list.txt
lista.txt
OptiFine_1.12.2_HD_U_E3.jar
Quark-r1.5-138.jar
**railcraft-12.0.0-beta-4.jar**
RedstoneFlux-1.12-2.1.0.6-universal.jar
tesla-core-lib-1.12.2-1.0.15.jar
ThermalCultivation-1.12.2-0.3.1.8-universal.jar
ThermalDynamics-1.12.2-2.5.3.16-universal.jar
ThermalExpansion-1.12.2-5.5.2.39-universal.jar
ThermalFoundation-1.12.2-2.6.1.22-universal.jar
ThermalInnovation-1.12.2-0.3.1.8-universal.jar

**Comment by liach** [comment]
bug has been reported already. it is just that the capacity shown in gui is totally wrong.

**Comment by JoCat** [comment]
Will it be fixed?

**Comment by liach** [comment]
yes. this is to send tank capacity info correctly to the client. however, my computer is broken so you have to wait a bit.
