### ISSUE TITLE
Zinc does not spawn

### ISSUE THREAD

**Issue by Romz24** [Railcraft/Railcraft#1683]
Version: 12.0.0-beta-4

Zinc is used in the crafting of some items, but it cannot be found. How to fix it or where to find it?

**Comment by CovertJaguar** [comment]
Check if you have a "mine_zinc.cfg" in "<root>/config/railcraft/ore".

Zinc was added later and the default configs are only created once, see the "generateDefaultConfigs" setting in "railcraft.cfg" if it is missing.

**Comment by CovertJaguar** [comment]
I tweaked the generator to pair zinc with lead mines and added a log message when a ore config is loaded.

I doubt this will actually change anything for you if zinc isn't _actually_ generating, rather than simply being unable to find it. It also won't affect already generated ore configs.

**Comment by liach** [comment]
it is generating, but at narrow height ranges.

**Comment by Romz24** [comment]
@liach 

In which biomes and at what height should I look?

**Comment by Romz24** [comment]
@CovertJaguar 

Can you please compile this version for me so that I can check it?

**Comment by liach** [comment]
sorry. i am away now, and will tell you the range when i got to a computer.

**Comment by Romz24** [comment]
UPD: I decided to install the mod "XRay" in order to check the presence of ore in my world. It turns out there is zinc, but it is just in one small area (at least I haven't found more places.) and nowhere else is it. Is this a mistake or should it be?
It seems to me that on servers of such amount of ore there is very little for the players.

https://www.youtube.com/watch?v=2LSvSZNSwII

**Comment by liach** [comment]
It should be at exactly y=30 horizontal plane. It has a very tiny distribution range.

**Comment by CovertJaguar** [comment]
Mines are rare, that's how they spawn.

Also the rich biome thing is currently broken, so its the same for all biomes.

**Comment by liach** [comment]
Should be fixed in 47e09537c4b05a39f6b0b03a46b3efe61a3ac9d8. Rich biome thing should be tracked separately.
