### ISSUE TITLE
Creosote bottle furnace recipe being annoying

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1685]
**Description of the Bug**
The furnace recipes to make creosote bottles from coal and charcoal prevent shift-clicking those fuels into the furnace fuel slot. I guess it makes sense that you can shiftclick them into the top slot since they _can_ be smelted but most of the time (char)coal is used as fuel.
Even if the top slot is filled with other items (cobble for example) (char)coal cannot be shift-clicked to go into the fuel slot.

**To Reproduce**
Test filling a furnace fuel slot with (char)coal, I used crafttweaker to disable the recipe for creosote bottles in the furnace which did in fact restore the old behavior.

**Expected behavior**
Being able to shiftclick (char)coal into the fuel slot of furnaces, it should work even with those recipes enabled.

**Additional context**
It's not gamebreaking by any means and in general minor compared to other bugs, maybe there is a clever way to make a nice workaround to get rid of the annoying behavior introduced by this recipe.

**Comment by liach** [comment]
fyi, this recipe by any means is to bypass coke ovens and is disabled when coke ovens are available.

**Comment by CovertJaguar** [comment]
Shift-Click behavior is controlled by the block, we can adjust it for our blocks, but not for vanilla blocks.

**Comment by WarlordWossman** [comment]
@liach good to know, I am working with the coke oven from gregic additions since they can share walls.

Gonna just disable the recipe then, thanks for looking into it.
