### ISSUE TITLE
Coke Oven Multi-Block spawns enemy creatures.

### ISSUE THREAD

**Issue by shiosakun** [Railcraft/Railcraft#1686]
When I build Coke Ovens, mobs are spawning in the center of it, and I'm talking about any kind of mob. Many of them die instantly suffocated, but others no. In the meanwhile that's kind of anoying. because I can't put any kind of ilumination there because then the oven down't builds. 

Railcraft version: railcraft-12.0.0-beta-4.jar
Forge version 1.12.2-14.23.5.2779

**Comment by CovertJaguar** [comment]
I was pretty sure that mobs couldn't spawn in 1x1 spaces, but oh well, easy fix.

**Comment by liach** [comment]
Hmm, did we handle opaque or mob spawning incorrectly? I recall our delegate blocks allow mob spawns by default.

**Comment by shiosakun** [comment]
> I was pretty sure that mobs couldn't spawn in 1x1 spaces, but oh well, easy fix.

I was sure about that too, but I even saw them spawning

**Comment by Jack-of-a-few-trades** [comment]
I've also seen them spawn inside of tanks, though not as frequently.

**Comment by CovertJaguar** [comment]
It used to be they couldn't spawn on the lower layers of multiblocks, its possible that got lost in the migration.
