### ISSUE TITLE
Tanks not interacting with some fluid conduits [1.10.2]

### ISSUE THREAD

**Issue by Jack-of-a-few-trades** [Railcraft/Railcraft#1687]
**Description of the Bug**
Since Buildcraft decided a port to 1.10.2 is unnecessary, I've had to plug around and find other mods to accomplish fluid/item/energy transport with. Ender IO was the one I settled on, but now that tanks are back in the game, I found that the tanks will not interact with the Ender IO fluid conduits. I thought this might have been an issue with mod compatibility, but when I tried routing fluids into the tanks via IC2 fluid distributors, the issue persisted. 

**To Reproduce**
1. Build a tank. 
2. Try to get things to put fluid in the tank. 
3. Cry.

**Comment by liach** [comment]
you need a tank valve in order to transfer fluid. replace a tank gauge or wall with the valve  input cannot be on the bottom and output cannot be at top.

**Comment by Jack-of-a-few-trades** [comment]
I have a valve for input as the center block at the top of the tank. Still doesn't interact.

**Comment by liach** [comment]
screenshot please.

**Comment by Jack-of-a-few-trades** [comment]
![2019-01-29](https://user-images.githubusercontent.com/32040860/51931372-387f3880-23c2-11e9-81c3-717938f45dcf.png)

![2019-01-29 1](https://user-images.githubusercontent.com/32040860/51931384-3fa64680-23c2-11e9-994c-98553914170a.png)

**Comment by Jack-of-a-few-trades** [comment]
![2019-01-29 2](https://user-images.githubusercontent.com/32040860/51931503-93189480-23c2-11e9-9072-945f8cd89644.png)
And I added another one with just the conduit leading to the valve. It will not connect to the valve.

**Comment by liach** [comment]
hmm, will check. i recall it works in 1.12.2.

**Comment by liach** [comment]
dunno why but enderio is just inconsistent. See #1747
