### ISSUE TITLE
Void chest particles is annoying

### ISSUE THREAD

**Issue by Flammable4444** [Railcraft/Railcraft#1690]
I like using void chest from railcraft, it's way better then void tubes or throwing trash into the lava, but there's one annoyng thing, is that in any room i placed void chest it sometimes randomly makes black particles.

Example:
https://puu.sh/CEGBJ/23e4695178.png

Is there any option to disable this particles? and if not, i suggest you to add it, i'm currently in the middle of, use comfortable void chest and tolerate this particles, or make a void tube, which is worse but at least no particles

**Comment by liach** [comment]
Right. Void chest particles should spawn in a relatively smaller range and with higher precision https://github.com/Railcraft/Railcraft/blob/3c467aedfc3184debc2bdb89416e1f6bc69baa00/src/main/java/mods/railcraft/common/blocks/single/BlockChestVoid.java#L46

**Comment by CovertJaguar** [comment]
I looked at that code the other day... it seemed... odd somehow. The way it picks a random block and generates particles on its face.
