### ISSUE TITLE
Server crash when tick railcraft:boiler_firebox_solid

### ISSUE THREAD

**Issue by AnxQ** [Railcraft/Railcraft#1691]
java.lang.NullPointerException
    at mods.railcraft.common.blocks.multi.TileBoiler.getNumTanks(TileBoiler.java:148)
    at mods.railcraft.common.blocks.multi.TileBoilerFirebox.update(TileBoilerFirebox.java:151)
    at mods.railcraft.common.blocks.multi.TileBoilerFireboxSolid.update(TileBoilerFireboxSolid.java:95)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbc000(World.java:4131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: railcraft:boiler_firebox_solid // mods.railcraft.common.blocks.multi.TileBoilerFireboxSolid
  Block type: ID #325 (tile.railcraft.boiler.firebox.solid // mods.railcraft.common.blocks.multi.BlockBoilerFireboxSolid // railcraft:boiler_firebox_solid)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-50,69,69), Chunk: (at 14,4,5 in -4,4; contains blocks -64,0,64 to -49,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Actual block type: ID #325 (tile.railcraft.boiler.firebox.solid // mods.railcraft.common.blocks.multi.BlockBoilerFireboxSolid // railcraft:boiler_firebox_solid)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {owner:"A",heat:20.0f,pattern:-1b,ownerId:"b76d4ad3-8d01-3150-b333-68cfb4257774",master:0b,inv:[],burnTime:0.0f,x:-50,y:69,tanks:[],currentItemBurnTime:0.0f,z:69,id:"railcraft:boiler_firebox_solid",maxHeat:500.0f}

-- Affected level --
  Level name: 新的世界
  All players: 1 total; [EntityPlayerMP['A'/0, l='新的世界', x=-46.50, y=69.00, z=67.50]]
  Chunk stats: ServerChunkCache: 1090 Drop: 0
  Level seed: -1895430515846058778
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-44,64,68), Chunk: (at 4,4,4 in -3,4; contains blocks -48,0,64 to -33,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 658 game time, 658 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 83215 (now: false), thunder time: 93647 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_144, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3067922744 bytes (2925 MB) / 3892314112 bytes (3712 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2807 Optifine OptiFine_1.12.2_HD_U_E3 11 mods loaded, 11 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID              | Version              | Source                              | Signature                                |
       |:------ |:--------------- |:-------------------- |:----------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft       | 1.12.2               | minecraft.jar                       | None                                     |
       | LCHIJA | mcp             | 9.42                 | minecraft.jar                       | None                                     |
       | LCHIJA | FML             | 8.0.99.99            | forge-1.12.2-14.23.5.2807.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge           | 14.23.5.2807         | forge-1.12.2-14.23.5.2807.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ichunutil       | 7.1.4                | iChunUtil-1.12.2-7.1.4.jar          | None                                     |
       | LCHIJA | ic2             | 2.8.109-ex112        | industrialcraft-2-2.8.109-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | inventorytweaks | 1.64+dev.145.16d98f2 | InventoryTweaks-1.64+dev.145.jar    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | mapwriter       | 2.8.2                | MapWriter-1.12.2-2.8.2.jar          | None                                     |
       | LCHIJA | portalgun       | 7.0.2                | PortalGun-1.12.2-7.0.2.jar          | None                                     |
       | LCHIJA | railcraft       | 12.0.0-beta-4        | railcraft-12.0.0-beta-4.jar         | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | vanillafix      | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar            | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Railcraft (railcraft)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['A'/0, l='新的世界', x=-46.50, y=69.00, z=67.50]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by liach** [comment]
fixed in code, wait for beta 5

已经在代码中修复，下一个版本 beta5就没有这个bug了
