### ISSUE TITLE
Problems while using Worldspike carts

### ISSUE THREAD

**Issue by lsylx** [Railcraft/Railcraft#1692]
**Description of the Bug**

Minecraft Version 1.12.2 on Sponge Server Forge version 14.23.5.2779
I couldn't place Admin Worldspike cart . But standard and personal one can be placed on the tracks
When I try to link the Standard or personal worldspike cart to a Locomotive the server crashs.
**To Reproduce**

(1)Admin Worldspike cart
1.Hold a Admin Worldspike cart then right click on track you will see nothing happend
(2)Crash on linking Locomotive and worldspike cart
1. Place a Locomotive(Whatever the kind it was Steam,Electric.......) and a Standard or personal worldspike cart
2. Use a crowbar to link them
3. You can see a word on screen "Server Closed"

**Expected behavior**

Server closed!!!
**Screenshots & Video**

Unavaliable
**Logs & Environment**

 - Full log(This contains the problem of Unable to place Admin worldspike cart and Crash on linking Locomotive and worldspike cart):  https://pastebin.com/0A1QnCDx
Partial log for Unable to place Admin worldspike cart: https://pastebin.com/VQLtKWWX

 - Crash report (It was the crash report for linking problem): 

 https://pastebin.com/5SVgA4Xj
**Additional context**

None

**Comment by liach** [comment]
we had a partial fix. try beta 5 when it's out

**Comment by liach** [comment]
两个bug一个崩溃rc修了，另一个管理员钉子车我会叫sponge的人修

@faithcaio why did you make abstract lens require inventories to always have slots? this breaks rc admin worldspike cart as it inherits container minecart but does not actually carry any item.

**Comment by Faithcaio** [comment]
Then it should be a `DefaultEmptyLens` instead.

**Comment by StoneLegion** [comment]
Thanks was about to report this. Crashed the second someone put a ender pearl in theirs on the server using Beta 4.

**Comment by WarlordWossman** [comment]
it's probably the same crash stationary worldspikes get atm

**Comment by liach** [comment]
It is a sponge bug. Compare:
https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityMinecartContainer.java#L51

versus:
https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/mixin/core/inventory/MixinInventoryBasic.java#L49-L52

**Comment by liach** [comment]
Fixed on Sponge's side.
