### ISSUE TITLE
MineCraft crash when trying to use boilerfireboxes

### ISSUE THREAD

**Issue by WVMCr** [Railcraft/Railcraft#1693]
**Description of the Bug**
I am using Buildcraft, and when I am placing any of the two fireboxes from RailCraft, the game crash immediately.
When I remove the Buildcraft mod, all is fine. I reported it to BuildCraft first and they asked that I also report it here.

**To Reproduce**
1. By placing a solid fuel firebox from RailCraft, the game crash immediately. Same happens when placing a fluid fueled firebox.

**Expected behavior**
It should not crash.

**Logs & Environment**
[2019-01-31-1.log.gz](https://github.com/Railcraft/Railcraft/files/2820444/2019-01-31-1.log.gz)
[crash-2019-01-31_11.56.44-server.txt](https://github.com/Railcraft/Railcraft/files/2820446/crash-2019-01-31_11.56.44-server.txt)

MineCraft version: 1.12.2
BuildCraft version: 7.99.21
Forge version: 1.12.2-14.23.5.2806

**Comment by WVMCr** [comment]
This submitted log is the first one for 31 January.

**Comment by liach** [comment]
Should be fixed in b5. wait for beta 5.

**Comment by WVMCr** [comment]
Will do, thank you.
