### ISSUE TITLE
Can't craft Rolling Machine

### ISSUE THREAD

**Issue by yakmasta** [Railcraft/Railcraft#1695]
Hi, I can't seem to craft the rolling table (image attached).   I am using version 12.0.0-beta-4 on minecraft 1.12.2.  Has the recipe changed from what is on the wiki? Thanks.
![2019-02-01 2](https://user-images.githubusercontent.com/47264402/52159145-2de8cb80-266e-11e9-8235-69f066c101d1.png)

**Comment by CovertJaguar** [comment]
It uses bronze gears instead of iron ingots.

**Comment by ghost** [comment]
> It uses bronze gears instead of iron ingots.

and how do you craft the bronze gear? hahahaha
