### ISSUE TITLE
1.12.2 Coke Oven + Blast Brick crash

### ISSUE THREAD

**Issue by Pulz-TCP** [Railcraft/Railcraft#1697]
**Description of the Bug**
Placing or breaking a coke oven or blast brick on a server causes a crash in most instances.
With rare occurences where a user can almost build a complete oven before the crashes begin.

**To Reproduce**

Place coal coke brick/attempt to remove the coke brick after a crash

**Logs & Environment**
https://pastebin.com/9pXRN4xc

Possibly a spongeforge issue?
This is for my modpack: https://www.technicpack.net/modpack/tc-redux

Possibly related to #1663 ?

**Comment by Pulz-TCP** [comment]
I'm aware my Sponge is a tad out of date, so I'm going to test this a little more before opening an issue.

**Comment by liach** [comment]
will be fixed in b5. known.

**Comment by Pulz-TCP** [comment]
> will be fixed in b5. known.

Thanks for the information.
