### ISSUE TITLE
Placing Liquid FireBox on World corrupts world and crashes

### ISSUE THREAD

**Issue by chirmac** [Railcraft/Railcraft#1698]
I placed a Liquid FireBox but it crashed my world as soon as it was placed. Can't open up the World anymore.

Here's the report:

[crash-2019-02-03_17.31.10-server.txt](https://github.com/Railcraft/Railcraft/files/2825962/crash-2019-02-03_17.31.10-server.txt)

**Comment by liach** [comment]
will be fixed in b5. already fixed in code.

**Comment by liach** [comment]
more exactly, see #1583
