### ISSUE TITLE
Unnable to connect kinetic pipes or engines to rock crusher

### ISSUE THREAD

**Issue by rzfoxtrot** [Railcraft/Railcraft#1699]
**Description of the Bug**
Unnable to connect kinetic pipes or engines(BC, Forestry) to rock crusher or powered roling machine. Also i cant find  railcraft engines in game. 

**To Reproduce**
1. build rock crusher
2. try to place pipe or engine to give crusher energy
3. no connection 

**Expected behavior**
I exept everything will work)

**Screenshots & Video**

![2019-02-04_13-39-16](https://user-images.githubusercontent.com/46600283/52203649-dc655a00-2882-11e9-9f4f-cbb7e110c983.png)

**Environment**
Minecraft 1.12.2
Forge 14.23.5.2807 
Railcraft railcraft-12.0.0-beta-4

**Comment by liach** [comment]
Working as intended. We need to document that rock crushers use railcraft charge since Series 10 of Railcraft (or Minecraft 1.10.2).
