### ISSUE TITLE
Stone Ties Recipe

### ISSUE THREAD

**Issue by yakmasta** [Railcraft/Railcraft#1700]
What is the recipe for stone ties (12.0.0-beta-4)?  I tried what is on the wiki (3 stone slab, 1 rebar) and it didn't work.  It seems like a few of the recipes have changed; is there a better source to look for recipes or maybe an in game book or something to craft?  Or an option to make the recipes match what is on the wiki?

Thanks

**Comment by liach** [comment]
Try installing just enough items mod.

Moreover, I have posted updated recipes to a chinese wiki, look at there if you don't mind https://www.mcmod.cn/item/707.html

**Comment by yakmasta** [comment]
Awesome, thank you!
