### ISSUE TITLE
Strap Iron Track Speed Boost And/Or Config Option. 

### ISSUE THREAD

**Issue by StoneLegion** [Railcraft/Railcraft#1701]
We tested out the Strap Iron Track Today. We found that it was quite slow in fact you could walk faster then the steam locomotive at full speed runs with it.

It be nice to get a speed boost on the track to say 70% if possible or even better a config option instead. If you do add a config option don't forget to allow it to dynamically adjust the tool tip that says 30% of iron. 

Reason: Making a themed pack that used Railcraft quite a bit. The goal is to allow players to make track early on in the game and be able to slowly start a infrastructure right away. Iron is quite weak on base processing in the pack so you have to work your way up for a while.

**Comment by CovertJaguar** [comment]
The original request for a "slower" track was such:
> Hi! I'm making a dinosaur park and I want to have a very slow moving touring train. Can you implement this somehow?

That said, 0.3 blocks per tick is probably ok still.

**Comment by ExDomino** [comment]
With a config option, everyone can change the speed at their wish.
