### ISSUE TITLE
Seprate Water Tank from factory module.

### ISSUE THREAD

**Issue by StoneLegion** [Railcraft/Railcraft#1702]
**Is your feature request related to a problem? Please describe.**
The water tank is used quite a bit for other things outside of the factory module like filling up your steam train, used in survival packs, etc. 

**Describe the solution you'd like**
Se prate the Water Tank into a new module or some sort of override to allow people to add it back without enabling all the features from modules. 

**Describe alternatives you've considered**
Finding another Mod to do what a mod already has in the pack. 

Thanks

**Comment by liach** [comment]
how about moving to transport module

**Comment by StoneLegion** [comment]
I think that would be a perfect spot for it :)

**Comment by liach** [comment]
@CovertJaguar Please decide.

**Comment by CovertJaguar** [comment]
Go for it!
