### ISSUE TITLE
Brass recipes conflict with those of Thaumcraft 6

### ISSUE THREAD

**Issue by BinxetyBinx** [Railcraft/Railcraft#1706]
Added Railcraft to SkyAdventures mod pack for 1.12.2 because trains between sky islands would be fun. After being added all recipes for anything Brass for Thaumcraft stopped showing up in JEI and only the Railcraft ones appeared (nuggets, ingots, and plates). This includes the base of Alchemical Brass Ingots disappearing. There's not even a way to spawn them in as it just gives Railcraft brass components. 

This makes it impossible to make many things in Thaumcraft as their recipes require the brass plates specifically from that mod and they cannot be substituted (many of the mechanical components including the golems).

I removed Railcraft and everything returned as it was. Readding Railcraft created the same issue again. I did not go in and manually change the item ID's because I'm not personally confident in doing so without messing something up.

I'm also submitting a report to Thaumcraft, but Azinor seems to be taking a break again so I thought it would be more likely to find a resolution here.

Thanks!

Version of SkyAdventures: 1.4.0
Version of Thaumcraft 6: 1.12.2-6.1.BETA26
Version of Railcraft: 12.0.0 beta 4

**Comment by liach** [comment]
That is a bug of thaumcraft instead of Railcraft. I suggest disabling brass plates, ingots, nuggets in railcraft config for a temporary workaround or using CraftTweaker.
