### ISSUE TITLE
Rich biome settings for mines

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1710]
**Description of the Bug**
Rich biome settings for mines don't work.

**To Reproduce**

1. Travel to mesa
2. Look at xray results

**Expected behavior**
Should have more ore and a higher density

**Analysis**
The white black list is broken.

**Additional context**
Left here so we do not forget about this bug.

**Comment by Psion77** [comment]
I can't find any tin ore on my server, even in a mesa biome. I cheated in 2 pieces of tin so I could make a tin divining rod from Random Things, (after finding no tin for 2 weeks) and then spent 3 hours branch mining at Y=50 looking for tin in a mesa, but none was to be found. 

However, I made a creative SSP world, fount a mesa, went down to Y=50, and found tons of tin.  So there might be a difference between behavior on servers and SSP worlds.

**Comment by liach** [comment]
no. the distribution is very random. you should turn on skygen once and observe the difference.
