### ISSUE TITLE
Energy Cart is to slow

### ISSUE THREAD

**Issue by ilhamfu** [Railcraft/Railcraft#1713]
Idk if this intentional, but energy cart is painfully slow. changing the adjustDrag in  configfile didn't change anything

**Comment by CovertJaguar** [comment]
Use beta 5

**Comment by ilhamfu** [comment]
It's Faster, but still slow IMO

**Comment by CovertJaguar** [comment]
Its a balance issue. If its not slow, there will be no reason to use electric tracks.

**Comment by ilhamfu** [comment]
even in single cart setup?
forgive me for being a jerk, but can you add config to adjust the drag of each cart
