### ISSUE TITLE
weird incorrect buffer thing

### ISSUE THREAD

**Issue by freopt** [Railcraft/Railcraft#1714]
**Description of the Bug**
The liquid fueled steam boiler shows weird buffer. 
**To Reproduce**

Make the biggest low pressure steam boiler (may occur with others)
right click water buckets into the tank and watch the buffer be weird.
**Expected behavior**
the buffer to be corrrect

**Screenshots & Video**
https://imgur.com/a/jhbRYyh

**Additional context**
The one probe seems to show the correct buffer. https://imgur.com/a/bX965FA

**Comment by LuigiHutch** [comment]
Duplicate of https://github.com/Railcraft/Railcraft/issues/1567
