### ISSUE TITLE
[Localization] Some Block Names are Unlocalized

### ISSUE THREAD

**Issue by Voxel-Friend** [Railcraft/Railcraft#1715]
**Description of the Bug**
Missing localization for certain blocks. Namely:
- [ ] All Iron and Steel Tank Multiblock Components
- [ ] Light Blue Metal Post
- [ ] Light Gray Metal Post
- [ ] Light Blue Metal Platform
- [ ] Light Gray Metal Platform

Using Railcraft Beta-5

**Screenshots**
![2019-02-13_19 19 55](https://user-images.githubusercontent.com/12395262/52755703-77b5a800-2fc4-11e9-9b33-bb4136c84132.png)
![2019-02-13_19 19 57](https://user-images.githubusercontent.com/12395262/52755704-77b5a800-2fc4-11e9-8749-734b118932df.png)
![2019-02-13_19 20 01](https://user-images.githubusercontent.com/12395262/52755705-77b5a800-2fc4-11e9-8327-2ea00e54af6c.png)
![2019-02-13_19 20 05](https://user-images.githubusercontent.com/12395262/52755706-77b5a800-2fc4-11e9-8a42-dc65e523ac65.png)
![2019-02-13_19 20 15](https://user-images.githubusercontent.com/12395262/52755707-77b5a800-2fc4-11e9-9d9a-32ec834116f8.png)
![2019-02-13_19 20 17](https://user-images.githubusercontent.com/12395262/52755708-77b5a800-2fc4-11e9-9e08-e76da8bc340f.png)
![2019-02-13_19 20 19](https://user-images.githubusercontent.com/12395262/52755709-77b5a800-2fc4-11e9-92a1-a5246f2d7047.png)
![2019-02-13_19 20 21](https://user-images.githubusercontent.com/12395262/52755710-77b5a800-2fc4-11e9-9a83-8b387e2d20fd.png)
![2019-02-13_19 20 23](https://user-images.githubusercontent.com/12395262/52755711-77b5a800-2fc4-11e9-8d38-4a7fc5adfa78.png)

**Comment by liach** [comment]
Thank you for compiling! I realized there is an issue at Railcraft/Railcraft-Localization#346 but did not compile a full list of missing colors.
