### ISSUE TITLE
Track Layer Cart is incapable of retrieving  tracts from adjacent chest carts

### ISSUE THREAD

**Issue by mariojuggernaut22** [Railcraft/Railcraft#1716]
**Description of the Bug**

**To Reproduce**

1. Place block/cart '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by mariojuggernaut22** [comment]
**Description:**
Whenever you connect a Chest Cart to  the track layer cart, it fails to extract the  rail contents of the  box.
**To reproduce:**
Place a track  layer cart and chest cart together, join them  with he crowbar,  fill the chest with the tracks you need to be placed and set the layer to dispense those tracks.

**Comment by liach** [comment]
Might be some issue in the maintenence cart codebase.
