### ISSUE TITLE
Detector Track Kits don't interact with Comparators

### ISSUE THREAD

**Issue by AzazelHD** [Railcraft/Railcraft#1720]
I had a hopper wagon, and when he is above a hopper it does not send any redstone signal to the comparator next to the hopper (it sends a redstone signal of power 1 = not enough to stop the wagon until its hopper is empty).

I don't know why you changed the original code... This mod literally fucked up all the track system in minecraft.

Could you fix this please?

I can't do a recolector because it doesn't work properly. Wagon does not stop over the hopper until it is empty

**Comment by liach** [comment]
Lol comparator outputs for minecarts are passed with detectors. Redstone comparators do not detect minecarts.

**Comment by AzazelHD** [comment]
I mean, the redstone track over the hopper, and the hopper near the comparator...

**Comment by liach** [comment]
Hmm, need to check if this is a design issue of railcraft. try replacing the comparator with a redstone wire and see the output strength.

**Comment by CovertJaguar** [comment]
Some pictures would help.

**Comment by liach** [comment]
hmm, the comparator output does not update with the cart's inventory change.

**Comment by CovertJaguar** [comment]
What is it attached to? The hopper?

**Comment by CovertJaguar** [comment]
The issue here is that Detector TrackKits don't implement the Comparator integration. This is an oversight on our part.
