### ISSUE TITLE
Description of bug

### ISSUE THREAD

**Issue by MilkDudzzz** [Railcraft/Railcraft#1732]
**Description of the Bug**
The liquid fueled boiler can hold unlimited water

**To Reproduce**
1. Create a liquid fueled boiler of maximum size (9 fireboxes, 36 HP boiler tanks)
2. Connect an infinite water source to the base of the boiler. (I used the aqueous accumulator from thermal expansion)

**Expected behavior**
The boiler's water tank says it's limited to holding 4000 mb of water, but instead of capping out at 4000 mb, the boiler filled up past that. there does not seem to be a limit on its capacity

**Screenshots & Video**
![2019-02-18_16 48 27](https://user-images.githubusercontent.com/47763109/52982833-3561e180-339d-11e9-9799-4abc40cd16e6.png)
![2019-02-18_16 48 54](https://user-images.githubusercontent.com/47763109/52982834-3561e180-339d-11e9-9b66-14bfd13eb18d.png)

**Logs & Environment**
Bug does not crash game; no log available

**Additional context**

**Comment by liach** [comment]
See the pinned issue #1567. Thank you!
