### ISSUE TITLE
Blast Furnace (1.12.2 BETA 4)

### ISSUE THREAD

**Issue by Raghalin** [Railcraft/Railcraft#1735]
**Is your feature request related to a problem? Please describe.**
Immersive Engineering (0.12-88) also has Coal Coke.  however the Blast Furnace (in beta4) will only accept the Railcraft Coal Coke.  the IE version of the blast furnace will accept both types of coal coke

**Describe the solution you'd like**
add Immersice Engineering Coal Coke to allowed fuels

I haven't updated to beta5 so I'm hoping this was already solved :P

**Comment by liach** [comment]
Fixed.
