### ISSUE TITLE
Crash when dragon spawns from Dragon Mounts 2

### ISSUE THREAD

**Issue by MorgusVR** [Railcraft/Railcraft#1737]
**Description of the Bug**
Any time a dragon spawns from mod Dragon Mounts 2, it crashes minecraft and that world does not load again til either railcraft or dragon mounts 2 is removed from the mod pack.
Dragon Mounts 2 1.5.3:
https://minecraft.curseforge.com/projects/dm2?gameCategorySlug=mc-mods&projectID=297333

LLibrary 1.7.17
https://minecraft.curseforge.com/projects/llibrary/files

**To Reproduce**
1. Using Railcraft Beta 5
1. Add both DM2 and LLibrary above
2. Spawn Dragon = Instant crash
3. Reload world = Instant crash

**Logs & Environment**
Full last log from loading back into world with spawned dragon
https://www.dropbox.com/s/ifdublclz8je9g9/latest.log

Crash Reports:
Crash when spawned
https://pastebin.com/SCZJD7mE

Crash when tried to load back in
https://pastebin.com/5ttmZyQj

**Comment by liach** [comment]
Did you report to the dragon mounts team? It seems to be them offering an invalid inventory for their dragon.

**Comment by liach** [comment]
I will download that mod and spot the exact issue.

**Comment by CovertJaguar** [comment]
This particular code is very picky that mods follow the exact specification for Capabilties.

In other words, if it reports that it has a Capability, _it must not return null when asked for that Capability_.

**Comment by MorgusVR** [comment]
I did report it to them as well first, any tips for me to pass along to them to try and make them compatible on their side?

**Comment by ghost** [comment]
Hello guys heres my the dragon entity: https://github.com/TheRPGAdventurer/dragonmounts2-1.12.2/blob/1.5.5/src/main/java/com/TheRPGAdventurer/ROTD/server/entity/EntityTameableDragon.java

**Comment by ghost** [comment]
Can you help me with whats going on?

**Comment by ghost** [comment]
ok I fixed the issuem it wass left out when i was copying someones "homework"
