### ISSUE TITLE
Enderio

### ISSUE THREAD

**Issue by Notlucky101** [Railcraft/Railcraft#1743]
Enderio initially is compatible, however when leaving the game completely and leaving the server up and running, when logging back in the conduits disconnect from the coke oven.

**Comment by liach** [comment]
Does the fluid still transfer?

**Comment by Notlucky101** [comment]
when  reconnected yes

**Comment by liach** [comment]
So it is purely an issue with appearance. This is a bug in enderio as enderio manages how its conduit looks.

**Comment by Notlucky101** [comment]
Yeah but it is only when I connect to railcraft coke ovens that the problem occurs. All other mods I use
there is no problem.

**Comment by Ommina** [comment]
I'm confused by the reply.  If you have to manually reconnect it, then fluid does _not_ still transfer when it appears disconnected.  There is an ambiguity here that is important to how @liach will approach the issue.

**Comment by liach** [comment]
Hmm, how about buildcraft pipes or ic2 tanks then? do they still work?

**Comment by msticninja** [comment]
Just FYI, I am running Ender IO conduits on the coke oven in my dedicated server, and have not experienced this. What version of RC and EIO are you running?

**Comment by Notlucky101** [comment]
ok here is the picture what it looks like when I log on the server.

[image: image.png]

and after I reconnect everything.

[image: image.png]

**Comment by liach** [comment]
@notlucky101 you pics are not uploaded. send them again

**Comment by Notlucky101** [comment]
I am running railcraft-12.0.0-beta-5 and EnderIO-1.12.2-5.0.40

**Comment by FlyingThunder** [comment]
EIO item conduits do not connect to the coke oven btw (EIO 5.0.40, RC 12.0.0-beta-5)

**Comment by msticninja** [comment]
@FlyingThunder Umm, what? Here is the item conduit connected to the coke oven with the exact versions you have: 
![2019-02-24_13 47 57](https://user-images.githubusercontent.com/1581853/53304443-dc7dc780-383a-11e9-9698-29016de8d5a2.png)

**Comment by Notlucky101** [comment]
Narrow down the problem. Only occurs when I shut down the server and
restart. I update mods on the server on a regular basis,.
Otherwise leaving the server up and running and logging off on the
client server and re logging on the client is fine. Try restarting your
server and let me know what you think.

**Comment by liach** [comment]
Is your coke oven in spawn chunk or chunkloaded?

**Comment by msticninja** [comment]
Mine still stays connected after server restarts, but we narrowed down something in chat. FlyingThunder  put them on multiple sides of his oven, and only the northern facing conduit stayed connected correctly. Also, placing a block next to it(I'm assuming any block update really) made it show as connected again. My conduit is east facing, and stays connected, but I haven't had time to try other sides yet myself. Also, one of his ovens was not activating the multiblock status on reconnect, the other was fine. The one that kept breaking was sitting on a chunk boundary, and the one that worked normally was built fully within a chunk, no boundaries crossed. Seems like a possible interaction to me.

P.S. The item conduit issue that FT described was not an issue. It was energy conduit, so wasn't supposed to connect.

**Comment by Notlucky101** [comment]
[image: image.png]
the red lines vertically show that the coke ovens on the edge of the chunk
area. The large red lines
shows the chunk loader coverage which is a the default setting of 9 chunks.
The enderio conduits are on the south side
of the coke oven. I will put the enderio conduits all around the coke of
oven and see what happens. I will let you know.

**Comment by liach** [comment]
@Notlucky101 wtf your image broke again. Go on github and upload the image instead. Do not comment when you image is still uploading!

**Comment by Notlucky101** [comment]
ok I post the pics on github, Sorry..

**Comment by liach** [comment]
oh my god, no image still. upload to imgur and link here

**Comment by Notlucky101** [comment]
try this
https://imgur.com/a/PiKuLZN

**Comment by Notlucky101** [comment]
Ok I resetting the server and client with your recommendations and here is
the result
https://i.imgur.com/LNDeohg.png

So I buried on block deep and brought the coke over centre of the chunk
I guess it is a work around for now.

**Comment by liach** [comment]
Moving to #1747

**Comment by CovertJaguar** [comment]
I said this a dozen times, either we aren't properly notifying neighbors when the structure forms with a block update or EnderIO isn't listening for neighbor updates.
