### ISSUE TITLE
Worldspike Ticking entity crash

### ISSUE THREAD

**Issue by MisterInsane** [Railcraft/Railcraft#1744]
I have a worldspike placed in the Deep Dark from Extra Utilities 2. I created a mob grinder and chunkloaded it with a worldspike.

The server crashed a few hours ago with this log: https://pastebin.com/aRQQgQk9

We're running railcraft-12.0.0-beta-4.jar on forge 14.23.5.2808.

Any help would be appreciated.

**Comment by liach** [comment]
Fixed in Railcraft 12.0.0 beta 5 already. Duplicate of #1594
