### ISSUE TITLE
Invalid fluid from other mods break railcraft

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Railcraft/Railcraft#1745]
**Description of the Bug**
The game crashes

**To Reproduce**
Load the pack. Insta crash

**Expected behavior**
The pack loads

**Screenshots & Video**
N/A

**Logs & Environment**
*CrashLog*
https://paste.dimdev.org/abamamiduq.mccrash

*latest.log*
https://paste.dimdev.org/kagavifefe.md

**Additional context**
Have vanilla Fix installed

**Comment by liach** [comment]
Some mod registered a broken fluid, causing a crash.
https://github.com/Railcraft/Railcraft/blob/b7ba6bea1e52ac55792377a1336497c07282ed18/src/main/java/mods/railcraft/client/render/models/resource/FluidModelRenderer.java#L54-L57

Could you please remove half of your mods at a time to see which mod is broken?

**Comment by CrankySupertoonArchive** [comment]
I will but I just deleted my instance

Sent from Mail for Windows 10

**Comment by ZJFishy** [comment]
I have a similar issue, immediately crashing upon launching the game
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)`

**Comment by Ommina** [comment]
@ZJFishy

Sadly, that single line tells us nothing.  Open a new issue, include the full crash report, and the powers that be can determine if it is railcraft bug, or if, like this issue, it is a bug elsewhere that is expressing itself in railcraft code.

**Comment by liach** [comment]
@ZJFishy I marked your comment as off-topic. Next time I will change titles that are too generic. For your case, please create a new issue. https://github.com/Railcraft/Railcraft/issues/new?template=bug_report.md
