### ISSUE TITLE
Pics for you to see.

### ISSUE THREAD

**Issue by Notlucky101** [Railcraft/Railcraft#1747]
![image](https://user-images.githubusercontent.com/42447191/53355325-9cbbec00-38dd-11e9-99a3-38e0302660ea.png)

![image](https://user-images.githubusercontent.com/42447191/53355232-6f6f3e00-38dd-11e9-8ab1-55c0d6154d65.png)

![image](https://user-images.githubusercontent.com/42447191/53355363-b4937000-38dd-11e9-991e-5228cac6f6b3.png)
I did not realise that pics where not showing from here on end I will post here.

**Comment by liach** [comment]
So the fluid ones still connect while the item ones don't?

**Comment by liach** [comment]
Hmm, some people report it works while some others do not. Please create a new issue in case it happens again.

**Comment by FlyingThunder** [comment]
i tested around a little (https://imgur.com/a/zloCsgP) and it seems that the disconnection is random with connections going out on the south being disconnected a lot...
