### ISSUE TITLE
Option to disable "Saving trains" console spam

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Railcraft/Railcraft#1751]
**Is your feature request related to a problem? Please describe.**
Railcraft spams the console whenever it saves the trains. This doesn't cause any noticeable lag and isn't useful to the average player.

**Describe the solution you'd like**
A config option to disable the message from appearing in console. By default, it shouldn't appear in console. This seems like debug information that should only be shown if you explicitly ask for it.

**Describe alternatives you've considered**
A mod like Console Filter could be used, but it's probably not worth the effort.

**Additional context**

**Comment by liach** [comment]
Sure. Will make that log message debug level instead.
