### ISSUE TITLE
9x9 tank multiblock structures don't work

### ISSUE THREAD

**Issue by SullyTheUnusual** [Railcraft/Railcraft#1757]
Trying to build a 9x9 steel tank, and it doesn't seem to be working.  Did the 9x9 size get removed?

**Comment by liach** [comment]
Hmm, will test in game.

**Comment by CovertJaguar** [comment]
I haven't gotten around to refactoring and testing Tanks yet. It's on the todo list.

It should work.

**Comment by Liam-Selleslagh** [comment]
For me the 9X9 tank works but nomatter the size of the tank all of em have a capacity of 64k is this normal?

**Comment by CovertJaguar** [comment]
GUI reports the wrong size, size reporting is fixed in 12.0.0-rc-1.

The server still knows how big the tank really is so you can just ignore it for now.
