### ISSUE TITLE
Tank capacity seems undersized

### ISSUE THREAD

**Issue by SullyTheUnusual** [Railcraft/Railcraft#1758]
I built a 7x7 steel tank which holds 64 buckets.  Instead of spending the 3 1/2 stacks of expensive steel, I can use half a stack of easily obtainable glass blocks to make 4 Buildcraft tanks that hold the same amount.  So is Buildcraft just OP, or are Railcraft tanks a bit undersized?

**Comment by liach** [comment]
#1567

**Comment by liach** [comment]
So what you see (64 buckets) is the capacity of one block because of that bug. The actual volume is 3136 * height buckets.

**Comment by SullyTheUnusual** [comment]
Thanks for the reply.  After posting this I noticed the tank looking full at 64,000, but still taking more liquid.
