### ISSUE TITLE
iron/steel tank doesn't render gasses correctly

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1765]
**Description of the Bug**
Filling gasses into iron/steel tank leads to weird visual glitches (tested with GregTech community edition and Nuclearcraft gasses).

**To Reproduce**
Use any of the gasses from the mods mentioned above and fill them into an iron/steel tank.

**Expected behavior**
Render like "normal" liquids but from top to bottom, visualisation of the input stream should also go up instead of down.

**Screenshots & Video**
![2019-03-07_20 05 44](https://user-images.githubusercontent.com/16925725/53982459-49377280-4115-11e9-8c2a-1fae3122e046.png)
![2019-03-07_20 04 07](https://user-images.githubusercontent.com/16925725/53982460-49377280-4115-11e9-8c1e-2105a4f3c72f.png)

**Logs & Environment**
https://gist.github.com/WarlordWossman/3050fe40fed308de44dc9e4024cbed42

**Additional context**
It's a visual issue and not super important but would be nice if gasses render properly.

**Comment by liach** [comment]
how about railcraft steam?

**Comment by WarlordWossman** [comment]
>how about railcraft steam?

same issue

**Comment by CovertJaguar** [comment]
"Gasses" probably ought to rather than render from top to bottom, have an opacity filter applied based on fullness. Maybe?

**Comment by liach** [comment]
dunno the reason. gas in tank cart renders correctly, which also use our fluid model renderer.

**Comment by liach** [comment]
This is actually also bugged in tank carts. When you fill a tank cart with steam, looking at the steam in tank carts, you can see the bottom sink of the tank cart without the steam cover. That said, The creosote fluid's layer is only visible from the outside (not seen here as replaced by tank texture) while the steam fluid's layer is only visible from the inside (if you look above the fluid in the tank, you can see that the other window has the gaseous fluid texture)
