### ISSUE TITLE
Can't place truck remover

### ISSUE THREAD

**Issue by byalexeykh** [Railcraft/Railcraft#1766]
**Description of the Bug**
Can't place track remover while on server, but can do it in singleplayer. However, there is a problem on the server and on the client.

**To Reproduce**

1. Install railcraft on server
2. Try to place track remover on rails
3. See that you cant do that and check server logs

OR

1. install railcraft 12.0.0-beta-5 and Vanilla Fix on client
2. Go to creative world
3. Try to place track remover and see the error

**Expected behavior**
I expected to be able to place a track remover

**Logs & Environment**
Server: 
https://gist.github.com/byalexeykh/a0e2e1162992e11c8b34ccd526102386
Client: 
https://paste.dimdev.org/awugorufav.mccrash

**Additional context**
You can find errors at the bottom of the log (server)
The error seems to be due to the lack of an interface of track remover.

When clicking on truck remover with right mouse button
![2019-03-09_04 10 21](https://user-images.githubusercontent.com/48031943/54064852-56da1e80-4221-11e9-8197-ed4dc0bce8ee.png)

**Comment by liach** [comment]
The server log error has been fixed in #1663, but the client one is a real issue.

**Comment by liach** [comment]
I'm wrong again. For the server one, update spongeforge to the latest. That crash has been fixed in SpongePowered/SpongeCommon#2186
