### ISSUE TITLE
Allow minecarts be invulnerable from mob damage

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1769]
**Is your feature request related to a problem? Please describe.**
Mobs may kill minecarts via arrows or explosion, causing issues with automation or ride experience.

**Describe the solution you'd like**
Add configuration option to allow minecarts be invulnerable from mob damages.

**Describe alternatives you've considered**
More health may make it harder for players to kill and total invulnerability might not be good for blow ups, etc.

**Additional context**

**Comment by CovertJaguar** [comment]
We probably should just make this the default.
