### ISSUE TITLE
Allow customize default loss rate for electric tracks, wires, etc.

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1772]
**Is your feature request related to a problem? Please describe.**
Some users do not like the gradual charge loss of some of our charge blocks.

**Describe the solution you'd like**
Add configuration to set the default loss rate.

**Describe alternatives you've considered**
Add configuration to disable any loss in the charge network instead of for each different block.

**Additional context**
https://discordapp.com/channels/225184360049934336/225184360049934336/554815280656941056

**Comment by CovertJaguar** [comment]
Ugh... just no, I'm not making a fantasy magic system here. Electricity has losses, lots of losses. I'm open to balance adjustments, and if we add the long range transmission lines, it will elevate most use cases for why people want the losses gone.
