### ISSUE TITLE
read packet data for our tiles sync

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1776]
**Description of the Bug**
https://github.com/Railcraft/Railcraft/blob/1b80ca586c43b69b90562dd999d5d52f06603550/src/main/java/mods/railcraft/common/blocks/TileRailcraft.java#L125
wrap this in schedule on main thread runnable.

**To Reproduce**

Recall that exception on network thread you saw.

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**
Just a reminder, so go back to dev channel in discord

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by liach** [comment]
Actually this is not network thread. It is using charge in client thread.

**Comment by CovertJaguar** [comment]
Sure looked like network thread to me. The exception ofc assumed that if it wasn't the server it was the client as it is not aware of network threads.

If it was pure client thread it should have crashed the game.

**Comment by CovertJaguar** [comment]
I guess it is already a scheduled task, and the debugger claims its the client thread, though I must admit the stack trace lacks any of the normal client start points. Well whatever.

**Comment by liach** [comment]
last i checked, handleupdatetag is sync on client (the net handler has a thread check)
