### ISSUE TITLE
Powered Rolling Machine does not craft on click

### ISSUE THREAD

**Issue by AstralJaeger** [Railcraft/Railcraft#1782]
I can't craft any items using the powered rolling machine, only using the manual rolling machine.
Not sure if its an energy acceptance problem, I tried using IC2, Mekanism and EnderIO power cables.
**To Reproduce**
Minecraft 1.12.2, Railcraft 12.0.0 Beta 5, Enigmatica 2 Modpack, Forge-14.23.5.2781
1. Place block 'Powered Rolling Machine'
2. Put any valid recepie into the machine
3. Click on 'Click to craft' field
4. See that nothing happens

**Expected behavior**
Items start to get produced

**Screenshots & Video**
https://imgur.com/a/1Fv5hLr

**Logs & Environment**

 - Full log: 
    https://pastebin.com/GRzK2YFk

**Comment by bookerthegeek** [comment]
Railcraft uses charge now not any other power source. rtfm.

**Comment by liach** [comment]
We will make charge more accessible in the future.

**Comment by AstralJaeger** [comment]
According to the Wiki here http://railcraft.info/wiki/device:rolling_machine 

> However, the Rolling Machine must be powered via a Redstoneflux compatible energy source. It has > an internal energy buffer of 5000 RF, consumes 5000 RF per operation, and can leave an operation > partially complete. An operation takes 100 Ticks, provided there is enough power. 50RF/t is required > to run the machine continuously. It does not consume source items until an operation has completed.

Any RF source should work. so maybe update the wiki

**Comment by liach** [comment]
When you did not see the manual rolling machine in the wiki and a different gui for the powered one than the one in the wiki, you should have realized it is outdated :sweat:

**Comment by Ommina** [comment]
No.  This is not an appropriate place to blame the user.  Lots of times it is.  This isn't one of them.

If there is an in-game way to learn of the requirement to use RC Charge, I've never seen it.  The wiki says "uses RF".  Unless users are on IRC or following GitHub commits, there simply isn't any way for them to know why the machine isn't working.

Perhaps change the Rolling Machine JEI tooltip to something to the effect of "Consumes Railcraft Charge to craft various metal items"?  Coupled with the existing tooltip on the Flux Transformer, it would at least give players a fighting chance to figure it out on their own.

**Comment by liach** [comment]
Hmm, should railcraft do it in advancements?

**Comment by AstralJaeger** [comment]
Why not do it in a book like may other mods use? As sort of an ingame wiki. And pls, just put a red "obsolote" banner on the wiki. I know I'm on the beta build but please try keep things documented. 
And an outdated GUI on the wiki has not been a reason to update the article until now for most mods.

**Comment by liach** [comment]
we have planned to add a patchouli book in another repo,,so yeah wip

**Comment by CovertJaguar** [comment]
Don't the tooltips document this stuff? If not they should.
