### ISSUE TITLE
Powered Rolling Machine does not accept power from any side

### ISSUE THREAD

**Issue by Solverbolt** [Railcraft/Railcraft#1784]
**Description of the Bug**

Powered Rolling Machine does not accept power from any side, from any power source, BC or otherwise, even when trying to use the producer/consumer set from Energy Converters
**To Reproduce**

1. Place block/cart Build Rolling machine, Place on any side with 
3. See '...'

**Expected behavior**

for it to accept power
**Which modpack it is happening in**

Any of them using any of the last 3 versions of railcraft

**Additional context**

Not even going to expect this to be resolved, as I have noticed that Railcraft and Build Craft staff just try to pass the proverbial "buck" on to others.

**Comment by liach** [comment]
> Not even going to expect this to be resolved, as I have noticed that Railcraft and Build Craft staff just try to pass the proverbial "buck" on to others.

Then why do you even report this bug...
Anyways, thank you for filling out this template. 

Look up ic2 charge feeder and flux transformer; place one ic2 charge feeder or a large transformer right next to the powered rolling machine; supply ic2 eu to the ic2 charge feeder or forge energy/rf to the flux transformer; then the powered rolling machine should receive power and start processing recipes.

**Comment by CovertJaguar** [comment]
You have exceeded the limits of my patience with your trolling. You are wasting our time and efforts on misleading issues. As such you are now banned.

**Comment by DarthPJB** [comment]
And that's what he meant by passing the buck.
