### ISSUE TITLE
[1.12.2] Tracks on tracks

### ISSUE THREAD

**Issue by TheSnowyChickens** [Railcraft/Railcraft#1786]
**Description of the Bug**
The player can place Railcraft tracks on Railcraft tracks, but normal MC tracks are not possible to place on each other, they pop off.

**To Reproduce**
1. Place a track . . 
2. Place a track on the track.

**Expected behavior**
We should not able to place any tracks on other tracks.

**Screenshots**
![2019-03-17_13 50 29](https://user-images.githubusercontent.com/29357962/54491181-a1603880-48bc-11e9-9ab5-8f089b1f845c.png)

![grafik](https://user-images.githubusercontent.com/29357962/54491229-f3a15980-48bc-11e9-8bd5-7f735415c3ef.png)

**Logs & Environment**
(Info: the log is to big for pastebin / hastebin, sry.)
[2019-03-17-6.log](https://github.com/Railcraft/Railcraft/files/2975163/2019-03-17-6.log)

**Additional context**
MC: 1.12.2
Forge: 2821
RC: 12.0.0

Info: This behavior occurs with ONLY Railcraft installed.

Info 2: Some Railcraft rails drops a typical black/purple item/block.

![2019-03-17_14 08 58](https://user-images.githubusercontent.com/29357962/54491375-67903180-48be-11e9-9234-d2f6ae21f3a6.png)
(Placeholder Item, I know)

Edit 2: 
![grafik](https://user-images.githubusercontent.com/29357962/54492756-9233b780-48c9-11e9-82fb-132d6df86f38.png)

**Comment by liach** [comment]
Will test this.

**Comment by CovertJaguar** [comment]
Note that Abandoned Track handles this a little differently.

**Comment by CovertJaguar** [comment]
Cannot duplicate.
