### ISSUE TITLE
water tank issues

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1793]
**Description of the Bug**
1. Cannot obtain water from a water tank by rightclicking it in the world with a fluid container in hand (tested with modded fluid containers as well as vanilla bucket).
2. Can only feed full water buckets into the water tank using a hopper, it will spit it back out instantly if you have another hopper below, if not adding a hopper later on doesn't result in anything (really odd).
3. Empty buckets don't go into the water tank at all.
4. Comparator cannot read from the water tank (not sure if this should work, on the iron tanks it does work when you point the comparator into a valve).

**To Reproduce**
Build up a water tank and test the problems stated above.

**Expected behavior**
1. Can rightclick a water tank (with enough water inside) with any fluid container to obtain water from it.
2. Not sure if you should be able to fill the water tank with water yourself, I would think that it should only be able to fill empty fluid containers and the player doesn't have the option to fill extra water into it.
3. Can feed empty buckets (and other fluid containers) into the water tank by pipes/hoppers/etc and extract the filled ones.
4. Can read from any block of the water tank using a comparator.

**Logs & Environment**
Railcraft 12.0.0 - MC 1.12.2

**Comment by CovertJaguar** [comment]
1 fixed by 1f85df3553844772141f72095f17f0f66ee7fe07

**Comment by CovertJaguar** [comment]
2, 3 fixed by a43e24b964fb4ffb2f321ba238088c8ae6caab80

**Comment by CovertJaguar** [comment]
All fixed
