### ISSUE TITLE
Combining solid and liquid firebox's Crash's server

### ISSUE THREAD

**Issue by Reaperxvii** [Railcraft/Railcraft#1797]
**Description of the Bug**

**To Reproduce**

1. Made a 9x9 boiler box combining solid and liquid, resulted in a server crash and upon rendering crash's server, had to delete railcraft until fixed.

**Expected behavior**

Wiki said you could combine them to use solid and liquid in one boiler.

**Screenshots & Video**

**Logs & Environment**
https://gist.github.com/Reaperxvii/bbb4f01c0622bc25d895921f8d5038bf

**Additional context**

**Comment by CovertJaguar** [comment]
The wiki says that? It was never intended.

I'm not sure I ever actually wrote any specific code for handling/banning this.

I'll look at it when I do the structure migration for the boilers. For now, don't mix them.

If you can't load your world, try disabling the Fireboxes in the railcraft block config. This should force the game to remove them. You can re-enable after they are cleared. Removing the mod entirely is using a nuke where a scalpel is sufficient.
