### ISSUE TITLE
[1.12.2] Fluid textures missing for buckets, GUIs, and tanks

### ISSUE THREAD

**Issue by Codazed** [Railcraft/Railcraft#1799]
**Description of the Bug**
Creosote and Steam textures are missing for buckets, TF florbs, etc., and are also missing textures in GUIs like the ones for the Coke Oven, Steam locomotive, and ME Fluid Terminal. Textures are also missing for the fluids in tanks. I would like to point out that in JEI, the texture for the fluid itself is fine, it's just broken everywhere else. (I am assuming the problem is also happening with steam based on the missing textures for steam bucket, florb, etc in JEI. I haven't put steam in a tank or bucket yet.)

**To Reproduce**
1. Install Railcraft (and JEI for step 3)
2. Put creosote oil (or steam) into a tank.
3. View the bucket items for the fluids in JEI.
4. Smelt coal in a coke oven to produce creosote oil.

**Expected behavior**
The creosote oil or steam textures are visible in all situations.

**Screenshots & Video**
![](https://i.imgur.com/eRJAIuk.jpg)
*The texture for the steam liquid is shown fine in JEI.*

![](https://i.imgur.com/hcYMA1E.jpg) 
*For buckets and TF florbs, the texture for steam is missing.*

![](https://i.imgur.com/M2FuONy.jpg)
*The texture for the creosote liquid is shown fine in JEI.*

![](https://i.imgur.com/84ASe98.jpg)
*For buckets and TF florbs, the texture for creosote is missing.*

![](https://i.imgur.com/t2kj6j2.jpg)
*The texture for creosote is missing in an ME Fluid Terminal*

![](https://i.imgur.com/jtgX6sK.jpg)
*The texture for creosote is missing in tanks.*

![](https://i.imgur.com/Ke6w3k9.jpg)
*The texture for creosote is missing in the coke oven.*

**Logs & Environment**
 - Full log: https://gist.github.com/BaconatorNoVeg/02a293e9f29288518bf3a2d026f90816
 - Mod list: https://gist.github.com/BaconatorNoVeg/78a86d45516680881a8598450304650f

**Additional context**
I've been tolerating this issue since I started the world, but it's started to get annoying. This is why I am just now reporting this. These issues were found in survival which is why I lack screenshots for steam, as I haven't needed it since I no longer have a steam locomotive, but I do remember that the texture for steam was also missing in the GUI for the steam locomotive.

**Comment by liach** [comment]
#1746 It is enderio again! don't blame us as we cannot make enderio remove its fluid registration.

**Comment by Codazed** [comment]
@liach I wasn't really trying to put the blame on anything. I wasn't sure what was causing the issue.

**Comment by Codazed** [comment]
Going to close this since it's technically a duplicate of #1746 and I didn't realize it because of the title of that issue.
