### ISSUE TITLE
Zink Ore

### ISSUE THREAD

**Issue by Zalupa-Konya** [Railcraft/Railcraft#1800]
I can not find zink ore.  Where to find her? I also have no steam engines. this is a bug? 1.12.2

**Comment by Bovive** [comment]
I have also been unable to locate Zinc.

**Comment by LuigiHutch** [comment]
Zinc can be found around Y30 as shown in the config, you will just have to keep looking. Steam Engines have not been ported

**Comment by Bovive** [comment]
After pulling up my world in MCEdit it appears that it is just not loading in older chunks. I enabled retrogen for the zinc, however the Railcraft Retrogen mod on Curseforge is not compatible with 1.12.2.

**Comment by Zalupa-Konya** [comment]
> Zinc can be found around Y30 as shown in the config, you will just have to keep looking. Steam Engines have not been ported

Oh, thanks!

**Comment by et-nik** [comment]
I faced this problem.

Fixed by disabling IC2 Macerator recipes for Ore Dusts in `railcraft.cfg` config.

Find:
```
            # 
            # change to 'ores=false' to disable the IC2 Macerator recipes for Ore Dusts
            # 
            B:ores=true
```

And change `B:ores` to `false` value:

```
            # 
            # change to 'ores=false' to disable the IC2 Macerator recipes for Ore Dusts
            # 
            B:ores=false
```

**Comment by Darkfiend009** [comment]
The above did not fix the issue for me. Still cannot find Zinc anywhere. Enabled retrogen for Zinc too so i could try and spawn it any way possible.

**Comment by ktole1999** [comment]
i do not have this problem with railcraft-12.0.0 in FTB-Revelations

**Comment by charliegc4** [comment]
Mined a 265 x 265 block down to bedrock. No a single block of Zinc! Not on y=30, not anywhere.

--edit: expanded that to 400 x 265. Still nothing.

--edit: my hole is now 400 x 400. Still nothing. I have digital miners also in different biomes, and none of them find Zinc. What is the distribution of Zinc supposed to be? Maybe I could just cheat and give myself x blocks of zinc ore for every 10000 others I mine.

**Comment by sa-shiro** [comment]
Same issue 

After tweaking around a lot I managed to generate zinc but with an very rare amount (0.01% at y30-y40)


Also the world module overrides every world gen (especially CofH World (Thermal Expansion) so you can't disable / enable and tweak ores with cofhWorld or similar mods)

It would be nice, if we could use cofhWorld to manage railcraft ores 

Edit

Removing every ore gen file from /railcraft/ores/ let's cofhWorld control the worlgen **but** zinc as 
"block": "railcraft:ore_metal",
"metadata": 5,
Generates Copper with a green texture and an invalid item texture 


Edit:
**Fixed it with CofhWorld:**
Using the following code structure makes it able to handle CofhWorld to manage any railcraft ore:
```json
....
"block": { "name": "railcraft:ore_metal", "metadata": 5 },
....
```

Note that **metadata** is actually deprecated so you may want to use **properties**:
```json
....
"block":  {
    "name": "railcraft:ore_metal",
    "properties": {
        "variant": "zinc"
        }
    },
....
```

**Comment by CovertJaguar** [comment]
Zinc generates in Lead Mines.
