### ISSUE TITLE
Crafttweaker / Modtweaker support ?

### ISSUE THREAD

**Issue by TheSnowyChickens** [Railcraft/Railcraft#1801]
Hi,
I wanted to disable some Rolling machine recipes, but I found no docu for Craft/Modtweaker. 
(I found only the old minetweaker stuff, but this don't work in the 1.12.2 version)

Could you add support for Craft/Modtweaker ? :)

MC: 1.12.2
Forge: 2823
RC: 1.12.0
CT: 4.1.17
MT: 4.0.17
MTLib: 3.0.6

**Comment by Trinsdar** [comment]
This mod is in the works: https://github.com/Team-AbCiv/RailcraftTweaker

**Comment by TheSnowyChickens** [comment]
Uhh, nice.

Then I close this issue. ^^
