### ISSUE TITLE
2600+ lines of log spam

### ISSUE THREAD

**Issue by Dockter** [Railcraft/Railcraft#1803]
No crash, more of an observation:
https://gist.github.com/Dockter/dfa0c5eb58af879b860f038fbcc4aa4d

Tons of excessive log entries, around 2600 lines, for really no reason. 

Using Forge 1.12.2-2815
Railcraft 12.0.0

Willing to give anymore feedback you need.

**Comment by liach** [comment]
Ah, should have removed this line https://github.com/Railcraft/Railcraft/pull/1777/files#diff-b9922f37203a362f986fcbc4a33dd953R131
sorry.

**Comment by Dockter** [comment]
Thank you.
