### ISSUE TITLE
Water tank missing gui.

### ISSUE THREAD

**Issue by ProsperCraft** [Railcraft/Railcraft#1805]
The gui is missing on the railcraft water tank, there is no visual indication that you correctly formed the tank, and you have no idea if it is gathering water, or how much.  

There was a gui in 1.7.10, is this an intended design change?

**Comment by liach** [comment]
Hmm, the structure might be incorrect. I heard of forming issues; use a magnifying glass to check the structure.

**Comment by ProsperCraft** [comment]
![2019-04-03_23 17 59](https://user-images.githubusercontent.com/4427684/55531250-bed82500-5666-11e9-9266-5a96fbea6574.png)

**Comment by WarlordWossman** [comment]
even with correct structure the GUI is currently missing #1793

**Comment by Xpycteem** [comment]
Same for me , no GUI , but the tank is filling. Have checked it , by placing Fluid Loader/Unloader next to it.

**Comment by ArchitektRadim** [comment]
Same for me.

**Comment by cozyGalvinism** [comment]
You can circumvent it by stepping on the same level as the gauge and then rightclicking it:

Rightclicking the gauge like that works:

![image](https://user-images.githubusercontent.com/1332113/59148359-311f0a00-8a08-11e9-84b3-4f99646a2501.png)

Rightclicking like this doesn't:

![image](https://user-images.githubusercontent.com/1332113/59148365-63306c00-8a08-11e9-93b9-3b06af38a7b4.png)

**Comment by mentimjojo** [comment]
This is indeed a bug, when you destroy one block, and place it back it will go back to normal. But if you open the gui your inventory will also be bugged and you need to relogin (At least on servers, singleplayer i dont know).

**Comment by CovertJaguar** [comment]
Closed by 1f85df3553844772141f72095f17f0f66ee7fe07

Wasn't a bug, it just got intentionally left behind during the Structure logic migration.
