### ISSUE TITLE
Crash when disabling steam and creosote in config.

### ISSUE THREAD

**Issue by ProsperCraft** [Railcraft/Railcraft#1807]
- Crash report (If available): 
https://gist.github.com/ProsperCraft/28321b62193f157bcbca39a4e64c7fb1

**Comment by ProsperCraft** [comment]
Need this fix so we can fix the missing texture issue - https://github.com/GregTechCE/GregTech/issues/706

**Comment by CovertJaguar** [comment]
Closed by a4ecd215645deed12c1c53b5fe869b350c969a6d
