### ISSUE TITLE
Crash when interacting an admin worldspike cart

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1808]
**Description of the Bug**

Crashes the logical server.

**To Reproduce**

Right click on an admin worldspike cart.

**Expected behavior**

??

**Screenshots & Video**

**Logs & Environment**

 - Full log: -

 - Crash report (If available): https://paste.ubuntu.com/p/tWGQXrcTKt/

**Additional context**

**Comment by wanou067** [comment]
I have the same problem, what is the solution ?

**Comment by CovertJaguar** [comment]
I tested this pretty thoroughly, even on the dedicated server.

The crash log indicates that a GUI opened for the Admin cart, but that doesn't happen for me.

Anyway, unless anyone has more information I'm just going to close this.
