### ISSUE TITLE
Nickel ore not generating

### ISSUE THREAD

**Issue by halvors** [Railcraft/Railcraft#1811]
**Description of the Bug**
Nickel ore does not generate at all, i'm unable to find it next to iron. Been looking at level 40 like it says in the config for hours.

**To Reproduce**
1. Go look for nickel ore.
2. And not find anything.

**Expected behavior**
Nickel ore being generated.

**Logs & Environment**
Latest Forge and latest Railcraft release.

**Comment by Dockter** [comment]
I would encourage you to use an xray mod to confirm this.  Random mining doesn't work well for diagnosing this as a possible issue.  Railcraft does vein generation not scatter so this will give you the impression its not working.

**Comment by halvors** [comment]
@Dockter I did. Found no i occurences. I set a breakpoint in the generator in railcraft code, found i vein in 300 chunks totally generated. Seems that nickel is the rarest of all ores.

Isn't it supposed to be more or less as common as iron? Or atleast as common as zinc?

**Comment by MathiasMelk** [comment]
I enabled SkyGen to sample the ores on the sky, and i got a lot of ores, such as zink, but digging exactly below it I still didn't manage to find any, it seams as all railcraft ores are not generating underground

**Comment by halvors** [comment]
I found some zinc after hours of exploration, but no nickel at all.

**Comment by et-nik** [comment]
You should disable IC2 Macerator recipes for Ore Dusts in `railcraft.cfg` config.

Find:
```
            # 
            # change to 'ores=false' to disable the IC2 Macerator recipes for Ore Dusts
            # 
            B:ores=true
```

And change `B:ores` to `false` value:

```
            # 
            # change to 'ores=false' to disable the IC2 Macerator recipes for Ore Dusts
            # 
            B:ores=false
```

**Comment by sa-shiro** [comment]
If you youse Thermal Expansion (CofH World) look here how to fix it:
#1800

**Comment by Alzurana** [comment]
This is not fixing it, it does not provide the ore generation style that Railcraft should have and only scatters the ores randomly. Have the same issue also with cofh installed. In fact I was unable to find any poor ore or normal ore surveying 100 chunks at a time and several times with world edit

In fact: Enabeling the sky generation creates them in the sky but not in the ground
this happens with all mines

**Comment by LuigiHutch** [comment]
Im sure it is generating its just extremly rare as I have found some in my survival world. This is where https://github.com/Railcraft/Railcraft/issues/889 would be really useful but it doesnt look like its coming to fruition any time soon

In the mean time I would recommend using something like the Scannable mod https://www.curseforge.com/minecraft/mc-mods/scannable with a rare ores module: 
![2020-04-15_17 31 44](https://user-images.githubusercontent.com/9326429/79363156-76bd3500-7f3f-11ea-8c15-06aef6aeebb1.png)

**Comment by Alzurana** [comment]
Do you have cofh world in your modpack?
I'm going through my worlds with analytic tools, there really is nothing where the ores are supposed to spawn. Quaried stone as well as geodes do spawn properly. just not any of the ore. Not a single block.

**Comment by LuigiHutch** [comment]
I do not.
My Mod list: 
![Capture](https://user-images.githubusercontent.com/9326429/79364227-f4ce0b80-7f40-11ea-88a5-fac47cf87cdf.PNG)

**Comment by Alzurana** [comment]
I found something:
Changing this config option in the mine_[orename].cfg files:
`    # The generator weight, larger weights generate later. You can use this to sort what order stuff is generated.`

`    [range: 0 ~ 2147483647, default: 100]`

`    I:weight=0`

it's set to 100 and 101 by default, setting it to 0 and 1 respectively does generate the ores as they were meant to generate. I can't say why though.

I suspect that this bug only happens with such insane modpacks as mine which includes 103 mods. Or with a specific mod in there, it seems as if there are conflicts with cofh.

![image](https://user-images.githubusercontent.com/7355313/79366446-7ecfa180-7f4c-11ea-98a9-d38b37194d37.png)

**Comment by CovertJaguar** [comment]
I suppose a conflict is possible. Hmm....

**Comment by simonliu99** [comment]
I can confirm that with stock config files, nickel does not seem to be generating at all. Only after changing generator weight to 0 did I locate nickel. Confirmed lack of nickel generation in previously generated world with x-ray.

I have Railcraft installed with IC2, BC.

**Comment by CovertJaguar** [comment]
> I have Railcraft installed with IC2, BC.

@simonliu99 what about COFH?

**Comment by CovertJaguar** [comment]
The weight should only affect the order in which the ore generators run. There is no way to short cut the ore generation... I can't imagine what could affect this. Aside from some bad faith behavior from some other mod.

**Comment by CovertJaguar** [comment]
I don't know, I changed the defaults to 8 and 9. Let me know if it remains an issue.

**Comment by CovertJaguar** [comment]
Only other thing I can think of is that some mod's generator is throwing an exception that is being caught some where.

**Comment by dmkenza** [comment]
I cant find ores with as well. I use lot of mods with IC2 and Buildcraft.
I use last Railcraft. Still need fix this
