### ISSUE TITLE
Crafting some Infernal Fitted Stone makes the server crashing...

### ISSUE THREAD

**Issue by alwaeles** [Railcraft/Railcraft#1812]
**Description of the Bug**
I was crafting using the player's inventory some Infernal Fitted Stone on a server and the server crashed after shift-clicking on output...

**To Reproduce**
`item = Infernal Fitted Stone`
1. Place Infernal Block in the player's crafting grid (which is 2 * 2 wide),
2. Shift-click on the output (showing `item`) like a mad boy. 😝
3. It should be crashing...

**Expected behavior**
Avoid crashing...

**Logs & Environment**
 - Full log: 
_too long for GitHub gists and it gets splitted and destroyed (the file is 223 KB)..._
 - Crash report: 
[Here's a Gist...](https://gist.github.com/Axelandre42/25c789b88a0a2a6ac436b1baf8627bdc)
 - Versions:
   - Railcraft: **12.0.0**
   - Minecraft Forge: **build 2823**

**Comment by alwaeles** [comment]
**Hint?**
`java.lang.ArrayIndexOutOfBoundsException: 4` should be caused by using the 2 * 2 crafting which is 4 slots: 0, 1, 2 and 3... The 4th slot doesn't exists...

**Comment by liach** [comment]
@Axelandre42 This stacktrace is not a crash related to player but one related to a thermal expansion crafter machine.

**Comment by alwaeles** [comment]
Oh... wait ? I was exactly doing what I described and I got this crash twice... Let me check...

**Comment by alwaeles** [comment]
OK I just found... @liach `ShapedRailcraftRecipe` is not working well with TE's Sequential Fabricator. I'm going to open a new issue cause we got many crashes with that...
