### ISSUE TITLE
CCL Reporting Switch Actuator Rendering Errors

### ISSUE THREAD

**Issue by Ommina** [Railcraft/Railcraft#1814]
**Description of the Bug**

Recently, I've started getting player chat messages from CodeChickenLib that is has caught a rendering exception.

[13:44:33] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] CCL Caught an exception rendering a block. See the log for info.

The switch in question does not render in world when the exception occurs.

**To Reproduce**

It's intermittent, but not infrequent.  I can restart the client, and the switch will render just fine.  Or I can restart the client, and an exception will be thrown with each change of the switch's state.

I've had it affect both the manual and redstone-controlled switch.

The motor where I see the behaviour most frequently is on the south side of a turnout-track kit, electric rail.  However, this is _also_ the motor that is tripped most frequently, as the locomotive is on a small (7x9 block) loop.  The actuator remains powered for 5s at a time, via a capacitor box.

**Expected behavior**
CCL to not be sad and the switch motor to render.

**Logs & Environment**
The exception sent to the client log: https://pastebin.com/XdjNteNG

**Comment by CovertJaguar** [comment]
FoamFix?

See #1806
