### ISSUE TITLE
steam boiler bugging out

### ISSUE THREAD

**Issue by Trixz2018** [Railcraft/Railcraft#1815]
**Description of the Bug**

SP world: when leaving the chunk or world and then returning i found the boiler not formed and when i went to right click the inventory of the boiler ended up in my armor slots and my character become bugged as in items in the inventory was non moveable / non usable and was sprinting and not sprinting over and over again 

only way to fix this is to close out of world and restart it and then break and replace parts of the boiler

no screenshots yet but once it happens again i will take them to show you. and try to record a vid of it. 

logs: 
[2019-04-12-6.log.gz](https://github.com/Railcraft/Railcraft/files/3075627/2019-04-12-6.log.gz)
[latest.log](https://github.com/Railcraft/Railcraft/files/3075629/latest.log)

**Comment by texaswriter** [comment]
This happened to me except with the multi-block tanks instead of steamer.

**Comment by texaswriter** [comment]
FYI. This was happening to me and I noticed that I had built a multi-block tank over two chunks. When I rebuilt the structure in a single chunk the problem went away. You might similarly try this as a workaround.

**Comment by Trixz2018** [comment]
yeah its been happening to all the multi blocks of railcraft, they are very buggy which is why i have had to remove them from being used until there is a fix for them

**Comment by Trixz2018** [comment]
but that shouldnt matter if its in one chuck or 4

**Comment by Trixz2018** [comment]
and i had it happen when i was just trying to form it in one chunk, lost all my armor again and had to restart my client. This is a game breaking bug and i will be removing the multiblocks until further notice

**Comment by Trixz2018** [comment]
ok one issue is when breaking the boiler it keeps its inventory, this should not happen, it should spit out its contents

**Comment by texaswriter** [comment]
It should definitely be fixed, I was just suggesting a workaround in the meantime. It worked for me.

**Comment by Trixz2018** [comment]
i just removed all railcraft multi-blocks, they are just too buggy

**Comment by Aevaris** [comment]
+1 this is happening to me too, even when the chunks are constantly kept loaded by chunkloader. Trying workaround and will comment back.

Edit: Moving each boiler so they don't cross chunks did indeed resolve the problem. Would be a nice thing to fix, as monitoring chunk lines is pretty annoying...

Thanks for the mod and all you guys do!

**Comment by TheNamesKyle** [comment]
I was running into this issue as well (although I didn't realize quite what was happening,) maybe adding a feature that will warn a player if a multi-block structure is being built or was built on multiple chunks?

**Comment by CovertJaguar** [comment]
Will be fixed by Structure migration to Logic Framework (only Boiler remains to be migrated)
