### ISSUE TITLE
Railcraft crashes game with invalid blocks.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Railcraft/Railcraft#1816]
**Description of the Bug**
If you spawn an invalid block (in this case its Galacticraft) such as galacticraftcore:basic_block_core into your inventory the game will crash, this does not happen without railcraft.

**Without Railcraft**

![image](https://user-images.githubusercontent.com/20819543/56133522-98659400-5f5a-11e9-91c0-c4b97388f0aa.png)

**With Railcraft**
 - Full log: 
Unable to upload, for whatever reason.
 - Crash report (If available): 
https://paste.dimdev.org/uzubozavef.mccrash

**Comment by liach** [comment]
Hmm, how can there be a -3 meta? need to ask galaticcraft dev.

**Comment by SlayerTheChikken** [comment]
I spawned it in by accident, that's how I found this issue :P I think it's possible to spawn invalid items with any mod, but I will connect this issue with a Galacticraft issue.
Appreciate the speedy response btw

**Comment by SlayerTheChikken** [comment]
Seems like the galacticraft team fixed the issue on their end, its up to you if you want to close this.
