### ISSUE TITLE
Locomotive linking links control

### ISSUE THREAD

**Issue by sashan13** [Railcraft/Railcraft#1819]
As the title says. Would be nice if all locomotives linked within the same train shared controls. This way we'll be e.g. able to have another locomotive pushing the back of a long train.

**Comment by legoj15** [comment]
You can actually already do this via locomotive control binds, I know I use it for my chain of 4 electric locomotives, you just have to bind a key to speedup, slowdown, power toggle, and reverse/forward toggle

**Comment by sashan13** [comment]
Well, linking them automatically would be a more elegant solution.
Getting them out of "Shutdown" state could be manual tho.
