### ISSUE TITLE
Steam Turbine only outputs power to IC2 power cables

### ISSUE THREAD

**Issue by pjalm** [Railcraft/Railcraft#182]
I have been trying to get the Steam Turbines to work with EnderIO, Buildcraft and a few other type of power cables to collect the energy output but the only ones that work are the IC2 cables which don't seem to work with anything but IC2 devices and machines. The Steam Engines however work fine with all power cables I have tried.

**Comment by Cronosus** [comment]
we have same problem on server with RC 9.12.2.0 .. 
we use only RF-powered mods, and steam turbine is now totally useless, because no way to convert UE to RF.
