### ISSUE TITLE
about ic2 energy carts

### ISSUE THREAD

**Issue by SuperGoddy** [Railcraft/Railcraft#1825]
Dear developer:
I'm an honest player of railcraft, a question has bothered me for a long time: 
Why are ic2 energy carts so heavy? I tryed to attach 8 electricity locomotives to a single MFE cart, and i found it still can't reach the maximum speed. 
Is it a bug or a feature with some other considerations?
I knew electricity locos works nicely on electricity tracks, but i still really want to hear the answer from the developer, if it is a feature, i will then accept it as a rule, if it is a bug, plz fix it. thanks and I'm looking forward to recieve your responses

**Comment by Xpycteem** [comment]
I have opened a thread a long time ago)
https://github.com/Railcraft/Railcraft/issues/752
