### ISSUE TITLE
Issue with Track Parts 

### ISSUE THREAD

**Issue by MrPuggyWins** [Railcraft/Railcraft#1827]
First of all, this mod has been serving me well with other engineering mods, but a bit of an issue has arisen. I can't find the recipe for "Track Parts" in JEI. This is especially odd to me, as I was able to find them in a previous world.
Any ideas? Thanks

**Comment by liach** [comment]
They should be craftable by putting two iron nuggets or one steel nugget into a rolling machine.

**Comment by MrPuggyWins** [comment]
Thanks man, after restarting the game, it works now I guess? Thanks anyways!
