### ISSUE TITLE
Furnace items disappearing

### ISSUE THREAD

**Issue by JJsmabrums** [Railcraft/Railcraft#1828]
**Description of the Bug**
After placing a coke oven and a blast furnace, all of my regular furnaces inventory disappear. each time I open the GUI for either the coke oven or blast furnace then close the gui, and then go back to a regular furnace if I had items in there smelting, they have all disappeared (lost a few stacks of iron and gold), and when you go to put an item in the regular furnace after opening the above guis, it will eat the stack of whatever you are holding and then turn itself off, if you open it again, then there is nothing there, but if you put more items in after this, it works again. 

**To Reproduce**
1 Place furnaces
2 Place iron ore and coal into furnaces
3 place coke oven and blast furnace, open up those, put in some coal. 
4 go back to regular furnace and open it, items should be gone. 
5 place items in furnace again, It should eat whatever you put in and then boot you out of the GUI screen. When you open it again there will be nothing inside. If you put more items in, it works like normal again. 

**Additional context**
I only have buildcraft and railcraft installed on v 1.12.2 minecraft and am playing single player on normal mode. No problems with furnaces until i place both the coke oven and the blasting furnace.

**Comment by BlueCreeper160** [comment]
This only happen with coal and iron?

**Comment by JJsmabrums** [comment]
I lost a stack of 49 gold ore and almost died when it disappeared, I quit minecraft and then opened it back up to see if it just popped into my inventory which happens sometimes if you lose an item, but it wasn't there and the furnace had the flames coming from the front but no fuel and no ore inside. 
I pride myself on not cheating, so this was the only time i have ever inventory edited myself items. broke my heart hahaha. 

I think it happens for any fuel or consumable you put in there. I made a test world and the same thing happened even with newly made furnaces. 
Im not that great at coding but im guessing that the coke oven and blast furnace are somehow using a bit of code or memory that the regular furnace uses and thats whats tripping things up, but honestly I have no idea. 
Im just not going to smelt until I can figure out how to fix the problem.

**Comment by Ommina** [comment]
There is an existing issue of multiblocks not forming under some conditions.  In your case, were the regular (vanilla, I presume) furnaces some distance from the coke oven / blast furnace?

**Comment by JJsmabrums** [comment]
Yes vanilla furnaces, 
They are about 25 blocks away and about 6 blocks below them.

**Comment by JJsmabrums** [comment]
Here is a video of the bug. 
https://www.youtube.com/watch?v=l_iVC6eOe-s&feature=youtu.be
So you can see there is nothing in the coke ovens or the blast furnace. I break my 64 stack of items down to 32 so I dont loose as much, when I put it in its fine, when i put in the coal it boots me out of the gui, and eats my coal and iron.  I quit and reboot to see if that fixes the issue and they pop back into my inventory, but they dont. 
can confirm it happens when I use wood, coal, charcoal, and coke as the fuel source. 
Now that I have lost those items, I can use this furnace and it works like normal until i leave the chunk.

**Comment by tril0byte** [comment]
Seems related: in FTB Revelation 3.2.0, we had an unformed Railcraft coke oven and when using the Magnifying Lens on it, it reported invalid and corrupted the player's inventory, copied items from the right half of the action bar onto the left, and placed some items from the inventory into the equipment slots. The items would appear to return to normal on closing and reopening the inventory, but were still there using the icons of the old items but behavior of the duped ones. It became impossible to tell which items were real. I have a video of this if it helps.

**Comment by CovertJaguar** [comment]
Closed by bc9283ae723dbe080a1b3288aa114b320f0db350
