### ISSUE TITLE
Suggestion: Energy transformer

### ISSUE THREAD

**Issue by BlueCreeper160** [Railcraft/Railcraft#1829]
This will be a solution to make functional machines, I saw in other versions (1.7.10) the use of cables to give energy to the machines, but now we only use batteries, the solution is a block to transform RF, EU, etc. in railcraft energy.

**Comment by Ommina** [comment]
There is an existing Redstone Flux (Forge Energy, if you prefer) transformer.  It's called, not surprisingly, Flux Transformer.

**Comment by bookerthegeek** [comment]
You also can create charge (the new power option in railcraft) with turbines and transfer that with the in mod wire (the name escapes me at the moment)
