### ISSUE TITLE
Cargo Cart uncraftable due to recipe conflict with Chest Cart

### ISSUE THREAD

**Issue by shion-kinos** [Railcraft/Railcraft#1830]
The Cargo Cart is uncraftable in Railcraft 12.0.0 for Minecraft 1.12.2, since the recipe, Trapped Chest + Minecart, seems to be conflicting with the recipe for Chest Cart, which accepts both normal Chest and Trapped Chest.

**Comment by awbuckst11181999** [comment]
Still have this issue

**Comment by Ommina** [comment]
Sadly, the Railcraft project has not seen any (public, at any rate!) development work since mid-March 2019.  At this point, your best bet for solving this is to modify the recipe yourself via CraftTweaker or the like.
