### ISSUE TITLE
Crash when altering RC recipes

### ISSUE THREAD

**Issue by Ushupiuck** [Railcraft/Railcraft#1831]
**Description of the Bug**
The game crashes when trying to search in JEI @Railcraft
**To Reproduce**
After changing recipes via Crafttweaker & reloading your game (close & re-open) the game will crash if you try to @Railcraft in the JEI search bar.
**Expected behavior**
Railcraft items showing up?

 - Crash report (If available): 
https://paste.dimdev.org/cevufojixi.mccrash

**Comment by liach** [comment]
There is no crash report.

**Comment by liach** [comment]
Please upload a crash report again. You failed to upload one when you created this issue.

**Comment by Ushupiuck** [comment]
@liach the crash report has been edited in. Excuse my delay...

**Comment by CovertJaguar** [comment]
Closed because lack of info (dimdev) down.
