### ISSUE TITLE
Crash upon creating new world – incompatibility with ExtraDiscs

### ISSUE THREAD

**Issue by Dimentive** [Railcraft/Railcraft#1833]
I’m creating a custom modpack, but my game crashes when creating a new world with Railcraft installed. Removing Railcraft solves it.

**Crash report:** https://pastebin.com/raw/KeF3ZeXt

The crash report mentions Railcraft in this line:
`at mods.railcraft.common.plugins.forge.LootPlugin.lootLoad(LootPlugin.java:72)`

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **Railcraft:** [12.0.0](https://minecraft.curseforge.com/projects/railcraft/files/2687757) (latest)

**Comment by liach** [comment]
```
at site.geni.ExtraDiscs.ExtraDiscs$Events.addDiscsToDungeonLoot(ExtraDiscs.java:62)
```
Any link to that mod? I need to look into their code to determine whose fault it is.

**Comment by Dimentive** [comment]
[CurseForge.](https://minecraft.curseforge.com/projects/extradiscs)
[Source code.](https://github.com/polgaria/ExtraDiscs)

**Comment by Dimentive** [comment]
* [CurseForge](https://minecraft.curseforge.com/projects/extradiscs)
* [Source code](https://github.com/polgaria/ExtraDiscs)

**Comment by liach** [comment]
https://github.com/polgaria/ExtraDiscs/blob/f59b8d120c6e340cec491f460983ef9ec8e0f127/src/main/java/site/geni/ExtraDiscs/ExtraDiscs.java#L59 Extradiscs should check the namespace as well.
