### ISSUE TITLE
Railcraft insists on brass crafting recipe

### ISSUE THREAD

**Issue by MtnDrew** [Railcraft/Railcraft#1834]
So I have tried Crafttweaker and messing with the configs to get rid of the 1 zinc ingot 3 copper ingot crafting recipe for brass, because I have a IE alloy smelter that will do it instead. But the mod just won't have it for some reason. It will not remove from my game. Bronze did remove itself, perhaps because IE registered it's own way to make it?

**To Reproduce**
1. Install Railcraft. IE and embers are installed as well if that means anything
2. Try to remove the brass handcrafting recipe through Craftweaker/Config means

**Expected behavior**
I'm trying to keep recipes where you smack together metal ingots and they turn into other metals out. So it would be nice to not have it there, since IE's alloy smelter has the capability to make brass and is slightly more believable. 

It's definitely possible to just not use the recipe, but you know how it is.

**Comment by MtnDrew** [comment]
Invar is another issue. Bronze probably would have been had it not removed itself for some reason.

**Comment by CovertJaguar** [comment]
I have moved the alloy recipes to JSON files. If you wish to remove them entirely, you can now do so via a resource pack.
