### ISSUE TITLE
Powered Rolling Machine is crafting the template when items are added

### ISSUE THREAD

**Issue by LyricalLull** [Railcraft/Railcraft#1835]
**Description of the Bug**
The powered rolling machine, when given a template to craft, will begin crafting as soon as any amount of extra material is pumped in despite not clicking "click to craft". This means it cannot be used effectively to automate crafting rails. If this sounds confusing, take a look at the screenshot.

In this example (in the screenshot), the recipe attempts to craft even without enough materials (if you don't count the template as materials). As a result the template is always lost when the recipe has an uneven amount of materials.

**To Reproduce**
1. Open Powered Rolling Machine GUI
2. Insert just the materials for a recipe template (for example, inserting JUST 3 steel for rebar).
3. Add ANY amount of extra material and the template will begin crafting.

**Expected behavior**
The template should never be used up unless you click "click to craft." This makes automation frustrating.

**Screenshots & Video**
https://i.imgur.com/gge1txw.png

**Logs & Environment**

 - Full log: 

 - Crash report (If available):

**Comment by OliverSG400** [comment]
Hello, I met the same issue recently, and I see this ticket is a year old already. Maybe there is any known workaround for that?

**Comment by Codeloquence** [comment]
Hello, I am experiencing this same issue. I am currently running Minecraft version 1.12.2. The powered rolling machine will combine all ingredients it is given and does not leave one in each spot. This has been breaking all my automation chains. I have not been able to find any way around this issue. Any advice or solutions to this would be greatly appreciated :)

**Comment by mkaisercross** [comment]
Having the same issue. It would be good if the rolling machine didn't start running until it had at least 2 of every item in the grid. This way it won't ever consume the template. 

To anyone looking for a workaround if you happen to have enderio installed the impulse hopper can help solve this.
