### ISSUE TITLE
Random client crash from metal chests

### ISSUE THREAD

**Issue by jinkhya** [Railcraft/Railcraft#1836]
**Description of the Bug**

Sometimes a friend's client crashes (not the server) and according to crash-log it's a rendering issue from the metal chests
**To Reproduce**

Not really sure how to reproduce yet.

**Expected behavior**

Well not crash :)

**Screenshots & Video**

**Logs & Environment**
Here's the crashlog :
https://paste.dimdev.org/yuyumunezo.mccrash

**Additional context**

- forge 2815
- railcraft 12.0.0

**Comment by liach** [comment]
Does this happen when removing the chest from the world or adding the chest to the world? Otherwise, it appears that your save is corrupt so that an incorrect chest block entity is located at where an air block is.
