### ISSUE TITLE
Internal Exception error

### ISSUE THREAD

**Issue by Nbgreen** [Railcraft/Railcraft#1838]
**Description of the Bug**
when placing any locomotive players will be disconnected from server
when looking in server console only reason for the disconnect is 
[00:10:58] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Nbgreen lost connection: Disconnected
so I believe this is just a client side error
also player can not log back in till the locomotive is removed
**To Reproduce**
1. place any locomotive
2. done
**Expected behavior**
player to not get kick when placing any locomotive 

**Logs & Environment**

 - client side log https://www.dropbox.com/s/ym1e3vn1g2y3wuh/latest.log?dl=1

 - Crash report (If available): 
game does not crash only kicks player from server

**Comment by liach** [comment]
I only see errors from tinkersjei and packet errors possibly caused by poor network; no evidence locomotives are the cause. Please share a server-side log if possible.

**Comment by Nbgreen** [comment]
sorry for the late response here is the server side logs
https://paste.dimdev.org/imekanusir.md

**Comment by Nbgreen** [comment]
I've done more testing with just railcraft on my sponge bungeecord test server and am still getting the issue  here is the client side log and the server side log from the test.
client log: https://paste.dimdev.org/hudigejufu.md
server log: https://paste.dimdev.org/ehuvuyiruj.md

**Comment by chocheger** [comment]
Any solution? I have the same problem.

**Comment by Nbgreen** [comment]
No never got a fix or a response

**Comment by CovertJaguar** [comment]
Closed because dimdev is dead.
