### ISSUE TITLE
Unable to craft boiler components

### ISSUE THREAD

**Issue by simonliu99** [Railcraft/Railcraft#1839]
**Description of the Bug**

Boiler fireboxes, both solid and liquid, can't be crafted with recipe from wiki involving 4 steel plates, 2 iron bars, 1 bucket, 1 fire charge, and 1 furnace.

**To Reproduce**

I have IC2 and BuildCraft installed on MC 1.12.2 with the latest versions of all respective mods.

**Comment by CovertJaguar** [comment]
The Wiki is probably out of date. Consult JEI.
