### ISSUE TITLE
Spike Maul does not cycle tracks back to standard

### ISSUE THREAD

**Issue by ADDSynth** [Railcraft/Railcraft#1841]
Railcraft version: 12.0.0
Forge version: 14.23.5.2831
Minecraft 1.12.2

**Description of the Bug**
So using the Spike Maul on tracks causes it to switch to a Switch Track, then a Y Track, and then a Junction Track, but then it stays on the Junction Track. It's supposed to switch back to a standard track, or at least that's what I remember from playing the 1.10 versions of Railcraft. The only way of getting the standard track back is by breaking the Junction Track which reverts it to a standard track.

**Comment by ADDSynth** [comment]
I'm pretty sure this is a bug, because, let's say you want to remove a line of track, but the Switch Track doesn't move. You instinctively want to change it back to a standard track rather than remove it.

**Comment by CovertJaguar** [comment]
It's supposed to rotate through the entire list again.... hmm...

**Comment by CovertJaguar** [comment]
Cannot reproduce.

**Comment by leonbaronick** [comment]
Having the same issue. Breaking it just reverts it to the normal track, but it cannot be reverted using the spike maul. Once it is in the junction state, nothing happens by right clicking the track with the spike maul.

**Comment by CovertJaguar** [comment]
What version are you using? This was a problem in one of the earlier beta releases for 1.12.

**Comment by CovertJaguar** [comment]
Also, do sneak hits take it back to normal track? A sneak hit should reverse the order.

**Comment by Ommina** [comment]
I just tried with Forge 14.23.5.2811, JEI 4.15.0.268, and a fresh Railcraft 12.0.0 (just to be sure I didn't rename a beta a year ago and forgot).  Uhm, single player world.  Not a dev environment.

I tried with Electric Track, High Speed Track, Track, Reinforced Track with both Iron and Steel Spike Maul.  I DO see the behaviour described here.  Track will cycle to a four-way junction, then no more.

Nor do I see a difference in sneak and no-sneak.  Both will advance the track to the four-way.  From there, neither will convince the track to change further.

**Comment by leonbaronick** [comment]
The normal release for 1.12, that would be 12.0.0.

It also seems to be working normally in a fresh build of your development branch. Have you maybe already fixed that issue somehow?

**Comment by CovertJaguar** [comment]
Possibly relevant commit: 9b0e52816163268af33e3f730902af323f36cada

**Comment by CovertJaguar** [comment]
Yes, it looks like it was one of the first commits after the 12.0.0 release. That's that mystery solved.
