### ISSUE TITLE
Alloy smith not accepting OreDict items

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Railcraft/Railcraft#1842]
the allow smith that can be found only accepts Railcraft ingots, which i cannot craft because of unidict
![Untitled](https://i.imgur.com/cON3WeH.gif)

to be honest i'm actually not sure if this is an issue with the mod or just vanilla being vanilla and requiring specific items for villager trades. if that ladder one is the case then i'm sorry

**Comment by CovertJaguar** [comment]
I think that is just Minecraft being Minecraft. We don't add that trade.
