### ISSUE TITLE
Elevator Tracks are completely broken

### ISSUE THREAD

**Issue by viniciusgf2** [Railcraft/Railcraft#1844]
The Elevator tracks are creating two perpendicular tracks when you put in the wall instead of one as you can see in the images bellow and because of this you can't create a continuous track and once you reach the top the minecart keeps bouncing stuck forever

To Reproduce
1. Create a straight track line and on the and put a vertical wall
2. On the wall put the elevator track
3. The track will create like two rotated tracks and will not be placed correctly by the bug

Expected behavior:
1. Create a straight track line and on the and put a vertical wall
2. On the wall put the elevator track
3. Track stick to the wall and create only one continuosly track

![bug1](https://user-images.githubusercontent.com/15821908/58650661-aa6e7c80-82e5-11e9-8442-e445fc9d6201.jpg)

![bug2](https://i.imgur.com/WDccZor.gif[/img])

Logs & Environment:
There are no logs, the game don't crash but it simples don´t work as it should work
I´m running the Forge 14.23.5.2838 with OptiFine 1.12.2 HD U E3 with no mods and using the SEUS Renewed 1.0.0 Shader

**Comment by LuigiHutch** [comment]
Now how elevator tracks actually work: 
![2019-05-30_18 44 58](https://user-images.githubusercontent.com/9326429/58652244-08618b00-830b-11e9-9b16-932c92be923e.png)

**Comment by liach** [comment]
In fact, luigihutch's setup isn't totally correct; the elevator needs one more block at top

**Comment by viniciusgf2** [comment]
I ended up putting a cart detector at the top and when the cart is detected a piston pushes the cart on top to the track again
