### ISSUE TITLE
Full-speed electric locomotives explode on exiting HS tracks

### ISSUE THREAD

**Issue by Azenet** [Railcraft/Railcraft#1845]
Hi,

**Description of the Bug**
Using Railcraft 12.0.0, no matter how many powered transition rails are placed, an electric locomotive set to full speed will explode upon exiting the transition section to regular tracks.

**To Reproduce**
1. Place a high-speed electric track long enough for a locomotive to reach full speed, with transition tracks on both ends, going into regular electric tracks.
2. Launch a locomotive at full speed on the track.
3. Locomotive visually slows down on the transition tracks but still explodes when going back to the regular electric tracks.

**Expected behavior**
Locomotive should not explode.

**Screenshots & Video**
Exit section transition: 
![image](https://user-images.githubusercontent.com/770806/58761258-a2f7df00-8542-11e9-9d53-e5f0901d8553.png)

**Comment by Elektron72** [comment]
I have the same issue.

**Comment by Infernalboy95000** [comment]
I found a work-around this issue. This is the "throttle track". Just by placing one that sets the locomotive for one second to third speed, and then, you set it back to full, it doesn't explode again on curves.

![2019-08-24_23 57 31](https://user-images.githubusercontent.com/39791183/63643213-dbcfcc00-c6cb-11e9-9ca4-2b89d7f5ed97.png)

**Comment by Nius** [comment]
I'm having the same problem as of now. I wrote a brief analysis [here](https://www.reddit.com/r/ModdedMinecraft/comments/f7r99u/railcraft_hs_transition_not_working_correctly/). To summarize, the fact that an RF cart can roll out of an HS zone without ever climbing past throttle-2 should shed some light on the problem.

**Comment by Arkandos** [comment]
Having the same issue. Sometimes when slowing down that rapidly carts in a train do merge into eachother however.

**Comment by CovertJaguar** [comment]
Are the transition tracks powered?
