### ISSUE TITLE
[Feature] IronChest typed carts

### ISSUE THREAD

**Issue by NicoNekoDev** [Railcraft/Railcraft#1847]
**Is your feature request related to a problem? Please describe.**
YES! I want IronChest's chests to exists on their cargo variant! Crystal/Diamond/Gold/Iron/(and IC2 related)Silver/Copper Cargo Carts!

**Describe the solution you'd like**
Implement those cargo carts, please!

**Describe alternatives you've considered**
I'd love to make it myself, but ForgeAPI is way over me, and it's hard to understand RailcraftAPI too. I can help, finding and maybe fixing any bugs - newly implemented features (and comits) can make someone understand how this mod works.

**Additional context**
I love this mod for the features it adds, and I love IronChest for the storage upgrade!

PS: if this is not the way I shoud request a feature, sorry! :)

**Comment by LuigiHutch** [comment]
RailCraft does not add iron chest carts. Those come from an addon you have installed.

**Comment by NicoNekoDev** [comment]
Umm apparently there is an addon for this... I never thinked for addons, thanks!
