### ISSUE TITLE
About 'Infinite brush rail machine'

### ISSUE THREAD

**Issue by dzcmingdi** [Railcraft/Railcraft#1849]
**Is your feature request related to a problem? Please describe.**

This is just a suggestion.
Do you learn something about ‘Infinite brush rail machine’？
I'm frustrated that when i start the machine and put rc's rail the game always crush.  

Machine like this image:
![A1B1F2254F5C06591A9FA9AD71F72F65](https://user-images.githubusercontent.com/37565801/59244858-c9a3cd00-8c48-11e9-98d6-d48be610208f.png)

**Comment by liach** [comment]
If the game crashes, please post the crash report.

**Comment by dzcmingdi** [comment]
OK.
[crash-2019-06-11_12.32.20-client.txt](https://github.com/Railcraft/Railcraft/files/3274861/crash-2019-06-11_12.32.20-client.txt)

**Comment by dzcmingdi** [comment]
I think this is caused by other mods . 
i try it again only with railcraft mod and  the result is no crash
