### ISSUE TITLE
Blast furnace GUI arrow not working

### ISSUE THREAD

**Issue by Insane96** [Railcraft/Railcraft#1850]
**Description of the Bug**
Put Iron in a Blast Furnace, fuel is consumed but the progress via the arrow is not shown.

**To Reproduce**
1. Create a Blast Furnace
2. Put iron ingot + coal coke in it
3. Profit! Fuel is consumed but the progress via the arrow is not shown

**Expected behavior**
Arrow showing progress much like vanilal furnaces

**Screenshots & Video**
![2019-06-14_09 54 27](https://user-images.githubusercontent.com/7185104/59493028-8f297280-8e8a-11e9-8bde-12f42d5324d7.png)

**Logs & Environment**
 - Full log: 
https://gist.github.com/Insane96/f2c2ed52ddae0d86adbcf32ca84226ea

**Comment by ghost** [comment]
#1850 It works, you do not have to modify the config, you may not seen it because it is slow.

**Comment by ablazingrace** [comment]
Can confirm it does NOT work. According to JEI it takes 64 seconds to turn 1 iron ingot into 1 steel ingot. Sat here watching it for that time and the progress bar didn't fill at all, however it still processed the iron into steel.
