### ISSUE TITLE
Trading Station does not work

### ISSUE THREAD

**Issue by GinkREAL** [Railcraft/Railcraft#1853]
**Description of the Bug**
Trading station does not work, right clicking it does nothing. 

**To Reproduce**

1. Create new world and fly to village 
2. Place trading station and right click
3. Nothing happens

**Expected behavior**
1. GUI pops up to allow trading

https://gist.github.com/GinkREAL/61d0d2c33202032fad2f68d32cb38edb

The extra logs about missing blocks was because i tried to remove forestry to see if that would fix the problem

**Comment by JulianNelson** [comment]
I am having the same problem.

**Comment by DriesNieman** [comment]
same for me

**Comment by aerojas** [comment]
Confirmed here. Cart version doesn't work either.

**Comment by kyazuki** [comment]
[TileLogic#blockActivated()](https://github.com/Railcraft/Railcraft/blob/c6214373a27b91c31c6552987a8800fbe6b64462/src/main/java/mods/railcraft/common/blocks/TileLogic.java#L110-L116) and [CartBaseLogic#doInteract()](https://github.com/Railcraft/Railcraft/blob/c6214373a27b91c31c6552987a8800fbe6b64462/src/main/java/mods/railcraft/common/carts/CartBaseLogic.java#L78-L86) doesn't call openGuiMethod when interactMethod returns true.
[TradeStationLogic#interact()](https://github.com/Railcraft/Railcraft/blob/c6214373a27b91c31c6552987a8800fbe6b64462/src/main/java/mods/railcraft/common/blocks/logic/TradeStationLogic.java#L106-L113) always return true, so we can't open GUI.

**Comment by CovertJaguar** [comment]
Good catch

**Comment by BloodyRain2k** [comment]
Is that fix going to be implemented and put on Curse?
Because I just found out that it still exists in 12.0.0 on 1.12.2

**Comment by xJon** [comment]
(@BloodyRain2k It is recommended to use the latest Beta release)
