### ISSUE TITLE
railcraft:actuator causing crash with JEI

### ISSUE THREAD

**Issue by joxpUB** [Railcraft/Railcraft#1855]
**Description of the Bug**

JEI is crashing due to a rendering problem with railcraft:actuator
**To Reproduce**

In latest 1.12.2 JEI, type in 'tra' or possibly just 'j'

**Expected behavior**

Expected it not to crash
**Screenshots & Video**

**Logs & Environment**

 - Full log: https://pastebin.com/3ji8Eqtm

 - Crash report (If available):  https://paste.dimdev.org/yojupewawo.mccrash

**Additional context**

**Comment by Ommina** [comment]
See #1806
