### ISSUE TITLE
Missing Blocks?

### ISSUE THREAD

**Issue by RedLoftwing** [Railcraft/Railcraft#1857]
**Description of the Bug**
Unsure if bug or a change. Can not find steam traps in my "NEI" or "Mod Options..." or even gamemode c search. Also can not find lanterns. Potentially more blocks too but have not noticed more yet. 
I do not see any of these blocks listed as removed or what not in the change log, unless im really blind haha

**To Reproduce**
Nothing really. Other than this is a download from curseforge. Not from a modpack.

**Expected behavior**
All mentioned blocks to appear in NEI...etc. 

**Screenshots & Video**
https://imgur.com/a/X5QWUnr or see image below

**Logs & Environment**
N/A

 - Full log: 
N/A

 - Crash report (If available): 
N/A

**Additional context**
![GitHubHelp1](https://user-images.githubusercontent.com/52433734/60476761-af23a900-9c74-11e9-8cfe-2972a41d908a.png)

N/A

**Comment by EntropicPariah** [comment]
I can confirm the missing lanterns bug. Not only do they not show up in JEI but you also cant craft them even if you remember the recipe and I'm on 1.12.2.

**Comment by EntropicPariah** [comment]
I opened up the 12.0.0 Jar file and the files for the lanterns are GONE. They are not present whatsoever. To compare, I opened the jar for 1.7.10 and right there they are. I have no clue why but lanterns are just not in the newest version.

**Comment by Ommina** [comment]
Because they simply have not been ported to 1.12.2.

Will they ever?  No idea.

**Comment by HLEBENTO** [comment]
Hey, I have the same. Only I noticed the problem, because I did not find the arrow roads. If you noticed, they are not in your screenshot. I spent all day and did not understand what the problem was.

**Comment by Tony4t3** [comment]
Seems that the engines are also missing. This makes it so the only source of energy is the steam turbine. Any idea when they will be ported?

**Comment by LuigiHutch** [comment]
https://github.com/Railcraft/Railcraft/issues/1388

**Comment by moscontheroad** [comment]
On 1.12.2, I have the same issue, however I found out while trying to craft / get a wye and switch track which are missing too.

**Comment by Forecaster** [comment]
> On 1.12.2, I have the same issue, however I found out while trying to craft / get a wye and switch track which are missing too.

They are not crafted anymore. Use a spike maul on a track block in an intersection.
