### ISSUE TITLE
Ores not generating

### ISSUE THREAD

**Issue by ghost** [Railcraft/Railcraft#1858]
Railcraft ores are not in the world, accessible from craftive or JEI cheat.

**Comment by FLAPIXCODE** [comment]
In fact, they are, but they are very rare (but in large quantities). But not everything, as it seems to me. I have never found zinc ore.

**Comment by vovchisko** [comment]
Same problem.

**Comment by CovertJaguar** [comment]
Zinc generates in Lead Mines.
