### ISSUE TITLE
Potential bug: Buildcraft energy fuels

### ISSUE THREAD

**Issue by Volumetric-Nanometre** [Railcraft/Railcraft#1861]
When using the buildcraft energy system, the fuels no longer work with the fluid fired boiler. The boilers used to accept the standard "fuel", however with the change to different types of fuel (dense,light, gas), the boiler will not accept and burn any of them. This is on the latest version of FTB Ultimate reloaded and can be reproduced by just building a boiler and attempting to fuel it with one of the 3 fuel types.

**Comment by jasperfirecai2** [comment]
I would love to see the boiler updated to work with these new fuels too

**Comment by CovertJaguar** [comment]
Merged fix.
