### ISSUE TITLE
Iron Tank Not Showing Proper Measurement

### ISSUE THREAD

**Issue by Black110ninja** [Railcraft/Railcraft#1864]
**Description of the Bug**
Whenever I make an Iron tank it doesn't give me the precise amount and says it is empty. 

**To Reproduce**

1. Make an Iron Tank on  FTB: Infinty Evolved 3.1.0
2. Fill with any liquid
3. It will show the that the walls are empty

**Expected behavior**
I expect it to show the amount of it without having to right click it.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/53358494/61988449-5636fe80-afef-11e9-9bc8-a50e8d29f121.png)

**Additional context**

**Comment by Ommina** [comment]
That is (probably) ToP instead of Railcraft.  But given you're using 1.7.10, I would not expect either of them to be updated further.

**Comment by Black110ninja** [comment]
What is ToP?
