### ISSUE TITLE
Battery not working correctly

### ISSUE THREAD

**Issue by siguma0013** [Railcraft/Railcraft#1865]
Battery not working correctly

*Zinc-Carbon Battery
*Zinc-Silver Battery

1. Place "Powered Rolling Machien" & "Zinc-Silver Battery"
2. Make "Steel Plate"
3. Check battery charge amount (195K c)
4. Pick up "Zinc-Silver Battery" using pickaxe
5. Place "Zinc-Silver Battery"
6. Check battery charge amount (200K c)

INFINITE LOOP!

*Nickel-Iron Battery
*Nickel-Zinc Battery

1. Place "Steam Trubine" & "Nickel-Zinc Battery"
2. Operate "Steam Trubine"
3. Wait a little
4. Check battery charge amount (150K c)
5. Pick up "Nickel-Zinc Battery" using pickaxe
6. Place "Nickel-Zinc Battery"
7. Check battery charge amount (0K c)

Is this working correctly ?

---------------------
Forge: 14.23.5.2838
Railcraft: railcraft-12.0.0.jar
Other MOD: Nothing

**Comment by CovertJaguar** [comment]
Batteries don't retain their charge when picked up. So in regards to the Rechargeable Batteries, yes.

However the Disposable Batteries are supposed to break into an expended version. So no, this part is not working correctly.
