### ISSUE TITLE
Steam Oven crashes client with NullPointerException when smelting finishes

### ISSUE THREAD

**Issue by Questwizard** [Railcraft/Railcraft#1866]
**Description of the Bug**
Every time the steam oven goes to play a sound when it finishes an operation, the client crashes with a NullPointerException. There are no errors, warnings, or other messages relating to Railcraft on the server console when the crash happens.

**To Reproduce**
1. Build a Steam Oven(s) as normal.
2 Supply items to smelt (in my case logs, and steam (using TE steam dynamo for this)
3. Wait until the smelting operation finishes.
4. Client crashes with a NullPointerException. With VanillaFix installed, it just throws a toast message with a link to open the crash report instead of closing the game. I tried disabling FoamFix's coremod functionality, as well as removing SoundFilters, and the issue still persisted.

**Expected behavior**
Expected to hear a sound indicating that the smelting operation finished.

**Screenshots & Video**
Screenshot of the setup that's causing the crash:
![2019-07-29_09 07 07](https://user-images.githubusercontent.com/9144975/62064858-a3c78d00-b1e2-11e9-912a-7d6816645c03.png)

**Logs & Environment**
 - Full log: https://gist.github.com/Questwizard/36c44a4949234cb83163627d83820a83 (note: full of spammed crash reports thanks to vanillafix)
 - Crash report (If available): https://gist.github.com/Questwizard/078de056cb2545459b735849377e502e (this is one of many, many hundreds of identical crash reports as one gets generated for every furnace separately, for every smelting operation)

**Additional context**
This is on a dedicated server that I'm hosting myself. The server doesn't show anything at all in the log at the time of the crashes.

**Comment by Questwizard** [comment]
Disabling sounds in the mod config and restarting the client and server causes the errors to go away. I'm guessing it might just be a wrong sound name, or a missing file somewhere.

**Comment by Justen-N** [comment]
related log: [hastebin](https://paste.dimdev.org/jegayesoho.mccrash)
