### ISSUE TITLE
Tunnel bore not working on multiplayer

### ISSUE THREAD

**Issue by Hrtlss** [Railcraft/Railcraft#1867]
When i place tunnel bore on singleplayer everything is fine, everything is working but when i place it on multiplayer it instantly breakes and drops to ground. Everything else from mod that i tested runs perfectly fine on server

**To Reproduce**
1. be on server
2. place tb on thy server

**Expected behavior**
everything except it breaking instantly

**Additional context**
Naaah i think thats it

**Comment by legoj15** [comment]
Duplicate of #1123
