### ISSUE TITLE
Cannot choose aspects in the Switch Actuactor Motor

### ISSUE THREAD

**Issue by alwaeles** [Railcraft/Railcraft#1868]
**Description of the Bug**
Handling issues with the GUI and the Tile Entity... When I interact by any mean with the GUI the aspects flip between Red and all the other ones... Look on the screenshots.

**To Reproduce**
1. Place a Switch Actuator Motor.
2. Open the GUI.
3. Interact in the GUI the way you want.
4. Close the GUI, you can hear the piston noise.
5. Open the GUI and see that all aspect flipped their states.

**Expected behavior**
Being able to select the aspect I want...

**Screenshots & Video**
![2019-07-31_15 04 43](https://user-images.githubusercontent.com/5228298/62422189-ce1bbd80-b6ae-11e9-8b0f-8258d196d6e0.png)
![2019-07-31_15 05 08](https://user-images.githubusercontent.com/5228298/62422190-ce1bbd80-b6ae-11e9-99d4-0f14191810b4.png)
![2019-07-31_15 05 18](https://user-images.githubusercontent.com/5228298/62422191-ceb45400-b6ae-11e9-8615-deafe895a1d6.png)

**Logs & Environment**
 - Full log: *No significant logging*
 - Crash report (If available): *No crash report*

**Additional context**
*None*

**Comment by alwaeles** [comment]
The issue is caused by a mishandling in [src/main/java/mods/railcraft/common/blocks/machine/wayobjects/actuators/TileActuatorMotor.java](https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/blocks/machine/wayobjects/actuators/TileActuatorMotor.java) :

```java
@Override
public void doActionOnAspect(SignalAspect aspect, boolean trigger) {
    switchOnAspects.flip(aspect.ordinal());
}
```
should be
```java
@Override
public void doActionOnAspect(SignalAspect aspect, boolean trigger) {
    switchOnAspects.set(aspect.ordinal(), trigger);
}
```

**Comment by FireBall1725** [comment]
Ran into this issue today as well

**Comment by kanna-shirakawa** [comment]
bug still present in 12.0.0

**Comment by CovertJaguar** [comment]
Wait for 12.1.0
