### ISSUE TITLE
Error on startup with slightly customized FTB Ultimate Reloaded

### ISSUE THREAD

**Issue by CammiePone** [Railcraft/Railcraft#1871]
**Description of the Bug**
When loading the game up, it errors when Railcraft tries to add an IC2 recipe to the game.

**To Reproduce**
1. Add the following mods to the game:

- Tinker's Construct
- PlusTiC
- Tinker's Tool Leveling
- Open Terrain Generator
- Biome Bundle
- Optifine
- Mantle
- Tree Chopper
- Growthcraft
- Pam's Harvestcraft
- Liteloader
- Mine Little Pony (has a modified hdskins.mixin.json file that removes the mixin call for the main menu, as that caused another crash with another unknown mod)

2. Start the game.
3. Have IC2 error and be just as confused as I am as to why it's not working, because your code looks solid to me.

**Expected behavior**
Expected the game to load.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/16853086/62839284-1a8a6e80-bc56-11e9-9a6c-09833ed35d25.png)

**Logs & Environment**
 - Full log: 
https://paste.ee/p/mdknT

**Comment by CovertJaguar** [comment]
I suspect an item is disabled in the configs, not sure which. It's trying to define the recipe for the Energy Loaders.

**Comment by CovertJaguar** [comment]
Added another check... not necessarily the best fix, or even the correct fix, but its something.
