### ISSUE TITLE
Whitescreen after pushing redstone active rail out

### ISSUE THREAD

**Issue by big-lip-bob** [Railcraft/Railcraft#1873]
**Description of the Bug**
Whitescreen after pushing redstone active rail out

**To Reproduce**
Place a series of rails ( in my case 3 renforced)
Apply a kit that can be powered by restone ( in my case boost )
Power by the end the serie of rails
Push out any rail by a piston
Enjoy White screen of death
(Optifine in, but it freezes the game so i doubt its inolved)

**Expected behavior**
Rail get moved, chaos doesn't start
Other rail part unpowers

**Screenshots & Video**
whitewindow.png

**Logs & Environment**
https://paste.dimdev.org/ateluzaxeg.coffeescript
Optifine

**Comment by CovertJaguar** [comment]
Piston's can't push Outfitted Tracks unless you have a mod that allows tile entities to be pushed.

In which case, the result is undefined.

And since dimdev is gone, I have no logs either.

Closing.
