### ISSUE TITLE
steam locomotive not pulling water from tank cart.

### ISSUE THREAD

**Issue by chyper111** [Railcraft/Railcraft#1874]
**Description of the Bug**
the name of this says it all. I cant get the steam locomotive to pull water from the tank cart it's attached to. currently playing 1.12.2 most recent release.

**To Reproduce**

1. Place block/cart '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by liach** [comment]
Add water filter to the tank cart.

**Comment by chyper111** [comment]
What exactly is a water filer sorry im not seeing it in jei

**Comment by chyper111** [comment]
filter

**Comment by liach** [comment]
use a fluid container with water in it (e.g. vanilla water bucket) in the filter slot of the tank cart to set the filter for the tank cart

**Comment by chyper111** [comment]
oh oki thanks that worked
