### ISSUE TITLE
A Error Entity that looks like a minecart

### ISSUE THREAD

**Issue by Paupertatis** [Railcraft/Railcraft#1875]
At first, I must say that I'm not an native speaker, so my grammer might be wrong.
When I right click on the rails, suddenly it summons a minecart.
However, it's not a normal one, it caused my frame rate to drop to 2~3 fps.
The "TOP" mod shows that it's a unkown entity, and it can't be easily erased.
I have to re-enter the world to erase the "minecart".
And my character's location would change when re-entering the world.

**To Reproduce**
1. Placed a rail on the grass.
2. Right clicked on the rail.
3. Saw a minecart shows up and the frame rate drops.

**Comment by liach** [comment]
looks like a client-server desync. Can you test on dedicated servers?

How does the cart look like?
