### ISSUE TITLE
Railcraft v12.0.0 and SpongeForge RC3903

### ISSUE THREAD

**Issue by TheNamesKyle** [Railcraft/Railcraft#1877]
I have been running a server with SpongeForge and Railcraft. No problems but about 10 hours before this issue we created a steel fluid container. Worked fine for a while but now I am having issues with my player losing random items, and duplicating random items. The steel container also doesn't seem to stay working for long.

26.08 23:00:13 [Server] Server thread/WARN [Sponge]: Could not find slot #42 in Container mods.railcraft.common.gui.containers.ContainerTank
26.08 23:00:13 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
26.08 23:00:13 [Server] INFO java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 42, Size: 38
26.08 23:00:13 [Server] INFO 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
26.08 23:00:13 [Server] INFO 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3903]
26.08 23:00:13 [Server] INFO 	at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716) [MinecraftServer.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
26.08 23:00:13 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
26.08 23:00:13 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 42, Size: 38
26.08 23:00:13 [Server] INFO 	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at mods.railcraft.common.gui.containers.RailcraftContainer.func_184996_a(RailcraftContainer.java:118) ~[RailcraftContainer.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
26.08 23:00:13 [Server] INFO 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3903]
26.08 23:00:13 [Server] INFO 	at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540) ~[hv$1.class:?]
26.08 23:00:13 [Server] INFO 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
26.08 23:00:13 [Server] INFO 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
26.08 23:00:13 [Server] INFO 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
26.08 23:00:13 [Server] INFO 	... 7 more

**Comment by TheNamesKyle** [comment]
Still experiencing the same issue without sponge

26.08 23:40:23 [Server] Server thread/FATAL Error executing task
26.08 23:40:23 [Server] INFO java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 44, Size: 38
26.08 23:40:23 [Server] INFO 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at net.minecraft.util.Util.func_181617_a(Util.java:51) [h.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
26.08 23:40:23 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
26.08 23:40:23 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 44, Size: 38
26.08 23:40:23 [Server] INFO 	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at net.minecraft.inventory.Container.func_75139_a(Container.java:223) ~[afr.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1992) ~[pa.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
26.08 23:40:23 [Server] INFO 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
26.08 23:40:23 [Server] INFO 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
26.08 23:40:23 [Server] INFO 	at net.minecraft.util.Util.func_181617_a(Util.java:50) ~[h.class:?]
26.08 23:40:23 [Server] INFO 	... 5 more

**Comment by TheNamesKyle** [comment]
Seems like the steel container is my issue. The server isn't liking it anymore, don't really know why.

**Comment by Ommina** [comment]
While Sponge does add some uncertainty, this is almost certainly #1815.  If you can keep multiblocks within a single chunk, they will work fine.  If they cross chunk boundaries and are loaded in stages (such as would happen if a player is running toward a base) they become erratic, and exhibit the behaviours you are experiencing.

**Comment by TheNamesKyle** [comment]
@ommina Ah, Ok thanks for the info. I'll close this issue and refer back to #1815.
