### ISSUE TITLE
Iron/Steel Tank Valves not interacting properly with Buildcraft gates

### ISSUE THREAD

**Issue by starslab** [Railcraft/Railcraft#188]
I noticed this back in my FTB Unleashed (Minecraft 1.5) world, and I'm also seeing it now on my Direwolf20 1.6.4 world. I know this used to work correctly back in Minecraft 1.4.x

Tank valves no longer properly interact with Buildcraft gates attached to them. Specifically, the "Space for liquid" signal never turns off, and the "Tank is full" signal never turns on. I've noticed this with lava in the past, and have tested just now with water. This issue affects both Steel and Iron tanks.

To reproduce:

Construct an iron tank, and prepare to fill it with a liquid. (I used several Thermal Expansion Aqueous Accumulators connected to a tesseract)
Place a valve on the one-from-bottom row of the tank, and attach a Buildcraft waterproof wooden pipe. Place a Gate in the pipe. Attach something to the pipe that responds to redstone - I used a white lamp from ProjectRed.

Set the gate to "Fluid in tank" and "Redstone Signal". The lamp will be off. Toggle to "Tank is Empty" and the lamp turns on. Toggle to "Tank Full" and it turns off. Toggle to "Space for fluid" and it turns on. This behavior is as expected.

Now start filling the tank

While the tank is neither full nor empty, the following conditions are shown by the gate:
Fluid in Tank - On
Tank Empty - Off
Tank Full - Off
Space for Fluid - On

Again, this behavior is correct and as expected.

The issue arises once the tank is full:

Fluid in Tank - On
Tank Empty - Off
**Tank Full - _Off_**
**Space for Fluid - _On_**

This behavior is incorrect, and makes it impossible to design mechanisms that detect and respond to a tank being full.

**Comment by Aberro** [comment]
Also, conditions like <25, <50< or <75 free space doesn't working with RC tanks.
