### ISSUE TITLE
Placing locomotives cause player disconnect

### ISSUE THREAD

**Issue by denebwang** [Railcraft/Railcraft#1880]
**Description of the Bug**

After placing a locomotive in the world the player get disconnected with" a fatal error has occured,this connection is terminated". 
neither of server or client crashed. Server is spongeforge.
**To Reproduce**

1. Place any locomotive in the world

**Logs & Environment**

 - client log: https://gist.github.com/denebwang/c4c79fed26ca625a91884a8cce46fd36
 - server log: https://pastebin.com/3ep3Yxix

**Additional context**

**Comment by liach** [comment]
看样子你魔改把datamanager玩坏了

**Comment by denebwang** [comment]
> 看样子你魔改把datamanager玩坏了

我这也没改啥啊...

**Comment by denebwang** [comment]
fixed by reinstall railcraft/reset forge config etc.
