### ISSUE TITLE
Crashing with JEI

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Railcraft/Railcraft#1882]
Can't browse stuff in JEI with Railcraft, because it crashes, due to a rendering issue?

https://paste.dimdev.org/eroxerubep.rb

**Comment by Techokami** [comment]
It seems this has to do with rendering the Actuator? You could just blacklist this item in the JEI config.

It should be noted that if the Actuator appears in a toast (like when unlocking recipes), that will *also* crash the game in the same way...

**Comment by CovertJaguar** [comment]
Duplicate of #1806
