### ISSUE TITLE
Mekanism mechanical pipes

### ISSUE THREAD

**Issue by charliegc4** [Railcraft/Railcraft#1883]
**Description of the Bug**
After saving and restarting the game, any Mekanism mechanical pipes used to feed a fluid firebox become disconnected.

**To Reproduce**
1. Build a boiler with fluid firebox.
2. Attach separate Mekanism mechanical pipes to feed fuel and water to the firebox.
3. Works as expected.
4. Save and quit to title.
5. Load saved game.
6. Pipes are disconnected.
 
**Expected behavior**
Expect pipes to remain connected between saves.

**Comment by CovertJaguar** [comment]
If the pipes aren't re-configuring their connections on neighbor changes, nothing I can do from my end.

**Comment by charliegc4** [comment]
The behavior is the same regardless of which mod pipes you use to connect to the boiler. Connect any pipe, restart and the connection is broken. But also after restart, those pipes remain connected to other items, it is just the connection to the boiler that breaks. 

I guess that means it is not a RailCraft issue, right!!!!

**Comment by CovertJaguar** [comment]
Correct. Railcraft multiblocks aren't actually inventories when the chunk first loads. Because of this, pipes can't connect to them until after they validate. At which point the multiblocks tell the pipes, "hey! I changed!".

Some pipes actually listen....
