### ISSUE TITLE
Wiki hopelessly out of date

### ISSUE THREAD

**Issue by charliegc4** [Railcraft/Railcraft#1884]
**Description of the Bug**
The Official Railcraft Wiki is hopelessly out of date.

**To Reproduce**
1. Go to https://railcraft.info/wiki/start
2. Look at entries.
3. Discover they are applicable only to previous versions, contain items no longer available, or don't mention items in the current version. They are often confusing even when they do contain some information.
4. Become frustrated.

**Expected behavior**
The wiki should contain latest information, and if not in depth information, at least something on everything.

**Comment by charliegc4** [comment]
This was closed, but the issue remains unresolved. ;-(

**Comment by liach** [comment]
Well, wiki maintenance is costly and wiki is expected to be always lagging behind code. Don't expect wiki to update with code when updating code is already costly enough

**Comment by charliegc4** [comment]
So if it is costly, and the content is not relevant, what is the purpose of having the wiki in the first place?

**Comment by liach** [comment]
Notice that **no one has an obligation to keep the wiki up-to-date**. Well, the wiki is there so whoever is interested can register an account and edit the wiki.

For actual content, you can just look up recipes on Just Enough Items and most other crucial stuff is in the item tooltips.

**Comment by CovertJaguar** [comment]
Just to be clear, I closed this because it was both obvious and not relevant to this repository.

Not necessarily because the wiki won't get updated.

**Comment by charliegc4** [comment]
You would think that if someone created it, that it implies they have an obligation to maintain it. But if it is too expensive and no one is obliged, why even keep it if all it offers is incorrect information?

Or maybe if it is of historical value, it could mention in the overview what version the wiki applies to.

**Comment by charliegc4** [comment]
BTW, I wouldn't mind updating it myself, as I think this is a great MOD (despite the few issues) and updated documentation would be the icing. The problem I have is where to get the information to create the wiki entries?

**Comment by CovertJaguar** [comment]
I mean, I *could* delete if you think that's more helpful than just leaving it. The info that is there isn't completely useless, but hey, if no one thinks its useful, might as well delete it right?

/sarcasm

I'm no more obligated to update the wiki than I am to update the mod. I don't have the time/motivation to do both anymore. The wiki was written at a time when the mod was somewhat smaller and the minecraft updates significantly less onerous.

It is a wiki, if you think its outdated... then fix it. If you have questions, come over to the discord and ask. Someone will have the answer.

**Comment by charliegc4** [comment]
"if you think its outdated... then fix it" Chicken and egg!! I went to the wiki to find information, it's not there. I would update the wiki, but the information is not available.

"I'm no more obligated to update the wiki than I am to update the mod." Fair enough, but the creator is the one who has the knowledge to provide the information, so if he is not obligated, then no one is. Creating something implies obligation to some extent unless you consider the visnu-brahma-siva trio where the creator has no involvement in maintaining or destruction.

"I could delete if you think that's more helpful than just leaving it." As I said, maybe label it as to what version it applies to. As a historical document, maybe someone will find it useful.

But otherwise, if I have to ask on Discord, what is the purpose of the Wiki?

**Comment by CovertJaguar** [comment]
So the next person doesn't have to ask? I thought that would be obvious...

I'm not going to have a discussion of entitlement here. This conversation is over.
