### ISSUE TITLE
Tank didn't show the gui clicking on the top

### ISSUE THREAD

**Issue by Crosus97** [Railcraft/Railcraft#1885]
**Description of the Bug**
a 9x9x8 tank dont show the gui on the top, the 5x5x4 show the gui at the top
**To Reproduce**
create a tank 9x9x8 and click on the top the gui show a little but then the gui close

**Expected behavior**
the gui will show like the 5x5x4

**Screenshots & Video**
[Youtube Video](https://www.youtube.com/watch?v=byxl1_Wa_lI)

**Logs & Environment**

 - Full log: 
in the client log nothing show

**Additional context**

**Comment by CovertJaguar** [comment]
Possibly fixed by migrating the Tanks to the Logic framework.
