### ISSUE TITLE
Server crash w/ Rolling Machine

### ISSUE THREAD

**Issue by BigCasper** [Railcraft/Railcraft#1887]
Server crashes after loading a Rolling Machine
Error:
java.lang.IndexOutOfBoundsException

Error occured while multiple other mods were present.

Reproducing: Set up a server or a singleplayer-world with this pack:
https://www.curseforge.com/minecraft/modpacks/world-of-factory
 and place any Rolling Machine: it'll then crash.

**Comment by texaswriter** [comment]
Where is the crash report? There would have been a crash report made and saved to a file in the server folder. In fact, it should be in a folder called "crash-reports" within you minecraft server's folder. 

Also, your bug report is missing ALOT of information. I think there is a template that is there automatically for you to fill in more information.

**Comment by BigCasper** [comment]
> Where is the crash report? There would have been a crash report made and saved to a file in the server folder. In fact, it should be in a folder called "crash-reports" within you minecraft server's folder.
> 
> Also, your bug report is missing ALOT of information. I think there is a template that is there automatically for you to fill in more information.

Yup. Totally forgot that one. Is pastebin ok? :https://pastebin.com/5Bpercva
Also: to reproduce: also works on powered rolling machine and singleplayer.
Maybe it's missing some info, but it's literally all I have.

**Comment by BigCasper** [comment]
[latest.log](https://github.com/Railcraft/Railcraft/files/3694294/latest.log)
[crash-2019-10-06_13.49.58-server.txt](https://github.com/Railcraft/Railcraft/files/3694295/crash-2019-10-06_13.49.58-server.txt)
This enough @texaswriter ?

**Comment by CovertJaguar** [comment]
I believe this was fixed by a83db7795f8683a19d050f5d07a2ed24069a6c4b
