### ISSUE TITLE
会有燃油机车吗

### ISSUE THREAD

**Issue by arnoldwxw** [Railcraft/Railcraft#1892]
会有燃油机车吗

**Comment by panda2134** [comment]
Translation: Will there be fuel-burning locomotive?
BTW I wonder why you use Chinese to open the issue, since the maintainer of Railcraft cannot understand that =.=

**Comment by liach** [comment]
此mod差不多死了，有事烧纸吧

**Comment by Forecaster** [comment]
A fuel powered locomotive has been planned for a long time, but requires a bunch of other things to be added as well. CJ has been too busy to work on Railcraft.

Please keep issues to english even if you have to use a translator to do so.
