### ISSUE TITLE
Switches not showing up in latest release version 12.0.0

### ISSUE THREAD

**Issue by NicholasRB** [Railcraft/Railcraft#1894]
**Description of the Bug**
The switches from the mod don't seem to be showing up and aren't craftable either. I'm not sure why though as I have tested this extensively now and with just Railcraft installed too.

**Expected behavior**

**Screenshots & Video**
Through Discord: 
(https://cdn.discordapp.com/attachments/534875577522454528/634742727560396810/unknown.png)
(https://cdn.discordapp.com/attachments/534875577522454528/634747659600789504/unknown.png)

**Comment by liach** [comment]
lol use spike mauls on tracks.

**Comment by liach** [comment]
and since you have discord you should have asked on railcraft discord before opening an issue

**Comment by NicholasRB** [comment]
I'm not in their Discord
