### ISSUE TITLE
Rail Craft / Various Oddities Conflict - Ticking Player Error

### ISSUE THREAD

**Issue by Ado-line** [Railcraft/Railcraft#1895]
I have also posted this on the Various Oddities tracker, please let me know if it is improper etiquette to do so.

**Description of the Bug**
Holding the Lantern from [Various Oddities](https://www.curseforge.com/minecraft/mc-mods/various-oddities) crashes the game.

**To Reproduce**
Hold a Lantern from Various Oddities

**Logs & Environment**
PasteBin for Crash Log: https://pastebin.com/9wCf0Mpd
Versions: VarOdd 5.1 / RailCraft 12.0.0 / Baubles 1.5.2 / Forge 14.23.5.2847

**Comment by liach** [comment]
Railcraft is using vanilla hooks. https://github.com/Railcraft/Railcraft/blob/b7659590775789e573c9f46006be017e9c172258/src/main/java/mods/railcraft/common/util/inventory/InvTools.java#L488

**Comment by Ado-line** [comment]
It is an error with Various Oddities according to that mod's author, and it will be fixed in future versions. Thank you for your quick response!
