### ISSUE TITLE
No Railcraft ores like tin and Copper spawning

### ISSUE THREAD

**Issue by portres** [Railcraft/Railcraft#1896]
With just railcraft and no other hightech mod there is no copper/tin worldgen. Is that normal?
Mods`  
       | State  | ID                    | Version             | Source                                             | Signature                                |
       |:------ |:--------------------- |:------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2              | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                   | 9.42                | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                   | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge                 | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | ivtoolkit             | 1.3.3-1.12          | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4               | minecraft.jar                                      | None                                     |
       | LCHIJA | dsurroundcore         | 3.5.5.0             | minecraft.jar                                      | None                                     |
       | LCHIJA | forgeendertech        | 1.12.2-4.4.24.0     | ForgeEndertech-1.12.2-4.4.24.0-build.0421.jar      | None                                     |
       | LCHIJA | adhooks               | 1.12.2-3.2.2.0      | AdHooks-1.12.2-3.2.2.0-build.0220.jar              | None                                     |
       | LCHIJA | aiimprovements        | 0.0.1.3             | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
       | LCHIJA | craftstudioapi        | 1.0.0               | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | animania              | 1.7.2               | animania-1.12.2-1.7.2.jar                          | None                                     |
       | LCHIJA | mantle                | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | inspirations          | 1.12.2-0.2.8        | Inspirations-1.12.2-0.2.8.jar                      | None                                     |
       | LCHIJA | placebo               | 1.6.0               | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LCHIJA | apotheosis            | 1.10.4              | Apotheosis-1.12.2-1.10.5.jar                       | None                                     |
       | LCHIJA | applecore             | 3.2.0               | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCHIJA | jei                   | 4.15.0.268          | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHIJA | appleskin             | 1.0.9               | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCHIJA | thedragonlib          | 1.12.2-5.3.0        | thedragonlib-1.12.2-5.3.0.jar                      | None                                     |
       | LCHIJA | armorplus             | 1.12.2-11.25.1.62   | armorplus-1.12.2-11.25.1.62.jar                    | None                                     |
       | LCHIJA | aroma1997core         | 2.0.0.2             | Aroma1997Core-1.12.2-2.0.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | aromabackup           | 2.1.1.4             | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | aromabackuprecovery   | 2.1.1.4             | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | quark                 | r1.6-177            | Quark-r1.6-177.jar                                 | None                                     |
       | LCHIJA | autoreglib            | 1.3-32              | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | ichunutil             | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools             | 7.0.1               | BackTools-1.12.2-7.0.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | baubles               | 1.5.2               | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | betterbuilderswands   | 0.11.1              | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCHIJA | bettercaves           | 1.12.2              | bettercaves-1.12.2-1.5.0.jar                       | None                                     |
       | LCHIJA | forgelin              | 1.8.4               | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | betterfoliage         | 2.2.0               | BetterFoliage-MC1.12-2.2.0.jar                     | None                                     |
       | LCHIJA | bibliocraft           | 2.4.5               | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | bibliotheca           | 1.3.6-1.12.2        | bibliotheca-1.3.6-1.12.2.jar                       | None                                     |
       | LCHIJA | blockcraftery         | 1.12.2-1.3.1        | blockcraftery-1.12.2-1.3.1.jar                     | None                                     |
       | LCHIJA | bloodmoon             | 1.5.3               | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | buildinggadgets       | 2.7.3               | BuildingGadgets-2.7.3.jar                          | None                                     |
       | LCHIJA | carbonado             | 1.5.1               | carbonado-1.5.1-mc1.12.x.jar                       | None                                     |
       | LCHIJA | chameleon             | 1.12-4.1.3          | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | ctm                   | MC1.12.2-0.3.3.22   | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCHIJA | chisel                | MC1.12.2-0.2.1.35   | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | LCHIJA | chiselsandbits        | 14.33               | chiselsandbits-14.33.jar                           | None                                     |
       | LCHIJA | clienttweaks          | 3.1.11              | ClientTweaks_1.12.2-3.1.11.jar                     | None                                     |
       | LCHIJA | clumps                | 3.1.2               | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJA | codechickenlib        | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cyclopscore           | 1.5.0               | CyclopsCore-1.12.2-1.5.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | colossalchests        | 1.7.3               | ColossalChests-1.12.2-1.7.3.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | cookiecore            | 2.0.0               | cookiecore-1.12-2.0.0.jar                          | 4bbb70ebe391f24f7704e343108a9b21b44c1b10 |
       | LCHIJA | craftingtweaks        | 8.1.9               | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | LCHIJA | crafttweaker          | 4.1.19              | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJA | ctgui                 | 1.0.0               | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJA | crafttweakerjei       | 2.0.3               | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJA | customizeddungeonloot | 1.0.3               | Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar        | None                                     |
       | LCHIJA | fastbench             | 1.7.2               | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
       | LCHIJA | cyclicmagic           | 1.19.17             | Cyclic-1.12.2-1.19.17.jar                          | None                                     |
       | LCHIJA | ding                  | 1.0.2               | Ding-1.12.2-1.0.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | dungeontactics        | DT-0.16.6           | DungeonTactics-1.12.2-0.16.6.jar                   | None                                     |
       | LCHIJA | csb_ench_table        | 1.1.3               | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
       | LCHIJA | enchdesc              | 1.1.15              | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enderstorage          | 2.4.6.137           | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | exchangers            | 1.12.2-2.8          | Exchangers-1.12.2-2.8.jar                          | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHIJA | shadowmc              | 3.8.0               | ShadowMC-1.12-3.8.0.jar                            | None                                     |
       | LCHIJA | extrarails            | 1.3.0               | ExtraRails-1.12-1.3.0.jar                          | None                                     |
       | LCHIJA | familiarfauna         | 1.0.11              | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
       | LCHIJA | farseek               | 2.3.2               | Farseek-1.12-2.3.2.jar                             | None                                     |
       | LCHIJA | fastfurnace           | 1.3.1               | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCHIJA | fencejumper           | 1.0.5               | fencejumper-1.12-1.0.5.jar                         | None                                     |
       | LCHIJA | foamfix               | 0.10.7-1.12.2       | foamfix-0.10.7-1.12.2.jar                          | None                                     |
       | LCHIJA | friendlyfire          | 1.5.10              | FriendlyFire-1.12.2-1.5.10.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | ftbbackups            | 0.0.0.ftbbackups    | FTBUtilitiesBackups-1.0.0.12.jar                   | None                                     |
       | LCHIJA | futureminecraf        | 1.2.1.1             | FutureVersionsV1.2.1.1.jar                         | None                                     |
       | LCHIJA | galaxite              | 1.1.2               | galaxite-1.1.2-mc1.12.x.jar                        | None                                     |
       | LCHIJA | harvest               | 1.12-1.2.7-20       | Harvest-1.12-1.2.7-20.jar                          | None                                     |
       | LCHIJA | heroicarmory          | 1.1.3               | heroicarmory-1.2.0.jar                             | None                                     |
       | LCHIJA | hopperducts           | 1.5                 | hopperducts-mc1.12-1.5.jar                         | None                                     |
       | LCHIJA | inventorypets         | 2.0.3               | inventorypets-1.12-2.0.3.jar                       | None                                     |
       | LCHIJA | ironchest             | 1.12.2-7.0.67.844   | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | itemfilters           | 1.0.3.12            | ItemFilters-1.0.3.12.jar                           | None                                     |
       | LCHIJA | jeiintegration        | 1.5.1.36            | jeiintegration_1.12.2-1.5.1.36.jar                 | None                                     |
       | LCHIJA | journeymap            | 1.12.2-5.5.5        | journeymap-1.12.2-5.5.5.jar                        | None                                     |
       | LCHIJA | jeresources           | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | keywizard             | 1.12.2-1.7.1        | keywizard-1.12.2-1.7.1.jar                         | None                                     |
       | LCHIJA | kleeslabs             | 5.4.12              | KleeSlabs_1.12.2-5.4.12.jar                        | None                                     |
       | LCHIJA | laggoggles            | FAT-1.12.2-4.8      | LagGoggles-FAT-1.12.2-4.8.jar                      | None                                     |
       | LCHIJA | libraryex             | 1.0.12              | LibraryEx-1.12.2-1.0.12.jar                        | None                                     |
       | LCHIJA | literalascension      | 1.12.2-1.0.2.2      | literalascension-1.12.2-2.0.0.0.jar                | None                                     |
       | LCHIJA | longfallboots         | 1.2.1a              | longfallboots-1.2.1b.jar                           | None                                     |
       | LCHIJA | magicfeather          | @VERSION@           | magicfeather-1.12.1-2.1.0.jar                      | None                                     |
       | LCHIJA | mcjtylib_ng           | 3.5.4               | mcjtylib-1.12-3.5.4.jar                            | None                                     |
       | LCHIJA | memeinabottle         | 2.1.1               | MemeInABottle-1.12.X-2.1.1.jar                     | None                                     |
       | LCHIJA | modnametooltip        | 1.10.1              | modnametooltip_1.12.2-1.10.1.jar                   | None                                     |
       | LCHIJA | moreoverlays          | 1.15.1              | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
       | LCHIJA | morpheus              | 1.12.2-3.5.106      | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | LCHIJA | mousetweaks           | 2.10                | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHIJA | llibrary              | 1.7.19              | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs           | 1.5.4               | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHIJA | multimob              | 1.0.5               | multimob-1.0.5.jar                                 | None                                     |
       | LCHIJA | naturalbabyanimals    | 1.2.0               | naturalbabyanimals-1.2.0-mc1.12.x.jar              | None                                     |
       | LCHIJA | naturescompass        | 1.5.1               | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | LCHIJA | neat                  | 1.4-17              | Neat 1.4-17.jar                                    | None                                     |
       | LCHIJA | netherex              | 2.0.15              | NetherEx-1.12.2-2.0.15.jar                         | None                                     |
       | LCHIJA | netherportalfix       | 5.3.17              | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
       | LCHIJA | recipehandler         | 0.13                | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
       | LCHIJA | norecipebook          | 1.2.1               | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
       | LCHIJA | notenoughwands        | 1.8.1               | notenoughwands-1.12-1.8.1.jar                      | None                                     |
       | LCHIJA | oreexcavation         | 1.4.143             | OreExcavation-1.4.143.jar                          | None                                     |
       | LCHIJA | oeintegration         | 2.3.4               | oeintegration-2.3.4.jar                            | None                                     |
       | LCHIJA | openglider            | @VERSION@           | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
       | LCHIJA | potioncore            | 1.8_for_1.12.2      | PotionCore-1.8_for_1.12.2.jar                      | None                                     |
       | LCHIJA | primitivemobs         | 1.2.3a              | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCHIJA | qualitytools          | 1.0.7_for_1.12.2    | QualityTools-1.0.7_for_1.12.2.jar                  | None                                     |
       | LCHIJA | quarkoddities         | 1                   | QuarkOddities-1.12.2.jar                           | None                                     |
       | LCHIJA | railcraft             | 12.0.0              | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | randomthings          | 4.2.7.3             | RandomThings-MC1.12.2-4.2.7.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | reccomplex            | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHIJA | redstonepaste         | 1.7.5               | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
       | LCHIJA | reptilemod            | 3.8.4               | reptilemod-1.12.2-3.8.4-89.jar                     | None                                     |
       | LCHIJA | additionalstructures  | 2.3.0               | Rex's-Additional-Structures-1.12.x-(v.2.3.0).jar   | None                                     |
       | LCHIJA | roguelike             | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | ropebridge            | 2.0.5               | ropebridge-1.12-2.0.7.jar                          | None                                     |
       | LCHIJA | ruins                 | 17.2                | Ruins-1.12.2.jar                                   | None                                     |
       | LCHIJA | rustic                | 1.1.1               | rustic-1.1.1.jar                                   | None                                     |
       | LCHIJA | signals               | 1.4.1-30            | Signals-1.12.2-1.4.1-30-universal.jar              | None                                     |
       | LCHIJA | snad                  | 1.12.1-1.7.09.16a   | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
       | LCHIJA | soundfilters          | 0.11_for_1.12       | SoundFilters-0.11_for_1.12.jar                     | None                                     |
       | LCHIJA | specialmobs           | 1.0.2_for_mc1.12.2  | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
       | LCHIJA | stepup                | 1.0.2-mc1.10-1.12.2 | StepUp-1.0.2-mc1.10-1.12.jar                       | None                                     |
       | LCHIJA | stg                   | 1.12.2-1.2.3        | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCHIJA | storagedrawers        | 1.12.2-5.4.0        | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
       | LCHIJA | strawgolem            | 1.3                 | strawgolem-1.4.1.jar                               | None                                     |
       | LCHIJA | streams               | 0.4.7               | Streams-1.12-0.4.7.jar                             | None                                     |
       | LCHIJA | telepass              | 1.0                 | TelePass-1.0.jar                                   | None                                     |
       | LCHIJA | theoneprobe           | 1.4.28              | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | LCHIJA | thutcore              | 5.21.0              | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | LCHIJA | thutcore_compat       | 1.0                 | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | LCHIJA | torchmaster           | 1.8.0.79            | torchmaster_1.12.2-1.8.0.79.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | ultimate_unicorn_mod  | 1.5.16              | ultimate_unicorn_mod-1.12.2-1.5.16.jar             | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-SNAPSHOT     | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | vc                    | 5.9.13              | ViesCraft-1.12.2-5.9.13.jar                        | None                                     |
       | LCHIJA | vulcanite             | 1.5.2               | vulcanite-1.5.2-mc1.12.x.jar                       | None                                     |
       | LCHIJA | waystones             | 4.0.72              | Waystones_1.12.2-4.0.72.jar                        | None                                     |
       | LCHIJA | wearablebackpacks     | 3.1.4               | WearableBackpacks-1.12.2-3.1.4.jar                 | None                                     |
       | LCHIJA | wildcrops             | 1.0.1               | WildCrops-1.12-1.0.1.jar                           | None                                     |
       | LCHIJA | wolfarmor             | 2.2.3.6             | wolfarmor-1.12.2-2.2.3.1798-universal.jar          | None                                     |
       | LCHIJA | xpholder              | 2.0.4               | XpHolder-2.0.4-mc1.12.x.jar                        | None                                     |
       | LCHIJA | orelib                | 3.5.2.3             | OreLib-1.12.2-3.5.2.3.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround             | 3.5.5.0             | DynamicSurroundings-1.12.2-3.5.5.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | vt                    | 1.12.2-1.5.5        | VanillaTweaks-1.12.2-1.5.5.jar                     | None                                     |
       | LCHIJA | mysticallib           | 1.12.2-1.3.8        | mysticallib-1.12.2-1.3.8.jar                       | None                                     |`

**Comment by Forecaster** [comment]
Railcraft spawns ore in large mines as seen in [this post](http://www.railcraft.info/railcraft-10-0-0-happy-halloween/).

These mines are huge but rare, meaning you have to search for them and can't just dig anywhere.
