### ISSUE TITLE
Intermittent crash when requesting Railcraft crafting recipes in Refined Storage

### ISSUE THREAD

**Issue by ItsTheKais** [Railcraft/Railcraft#1897]
**Description of the Bug**
After programming a Refined Storage system with crafting recipes from Railcraft, sometimes requesting those recipes causes the game to crash.

**To Reproduce**
1. Program a Crafter with patterns containing shaped crafting recipes from Railcraft
2. Request those things be crafted (might take a few tries; seems more likely to happen if you request something with multiple nested Railcraft recipes; also seems more likely to happen if the request is triggered by an interface with a crafting upgrade than by manually requesting from a grid)
3. May have some other condition? I tried to reproduce this in a creative test world using the same recipes that caused this in my survival world (the one in the crash log was caused by reinforced track or some nested recipe thereof) but could not get the crash to occur there.

**Logs & Environment**
 - Crash report: https://pastebin.com/0x6PGDqH

**Comment by CovertJaguar** [comment]
Closed by 1eb527b49655c157c915c54d5c1e6cfedba4e34a
