### ISSUE TITLE
Transucent Trains

### ISSUE THREAD

**Issue by AstralJaeger** [Railcraft/Railcraft#1898]
**Description of the Bug**
Trains become translucent on a server.

**To Reproduce**
Not really sure, on a slightly modified Enigmatica 2 Expert server with ProjectRed, Railcraft and Wireless Redstone.

**Expected behavior**
Trains not being or ever becoming translucent.

**Screenshots & Video**
https://imgur.com/a/pcJEPSP

**Logs & Environment**
[pastebin server latest.log](https://pastebin.com/YT4pXupU)

**Additional context**
Nothing to add.

**Comment by Forecaster** [comment]
It's a halloween easter egg. They will become normal again after a certain time I can't remember. There's an option to disable this somewhere in the config.

**Comment by AstralJaeger** [comment]
Kinda early for a Haloween easter egg isn't it?
