### ISSUE TITLE
All Carts Entity Glitch

### ISSUE THREAD

**Issue by Multi-Coder-24** [Railcraft/Railcraft#1901]
I am having an issue with all of the carts and locomotives they appear translucent in color

Just A bit of info about the machine this game is running on is
Minecraft: 1.12.2
Forge Version: 1.12.2-14.25.5.2847
OS: Mac os X El Capitan early 2009 with 8GB ram and minecraft is using 6GB
Railcraft Version: 12.0.0

will send screenshots and logs Shortly

**Comment by Multi-Coder-24** [comment]
Link To Latest.log
https://gist.github.com/DDX5/f7de9119915f9c3a8ee5c26335c26a12
Link To debug.log
https://gist.github.com/DDX5/1e143878768c1516059d2023746c46b1

**Comment by liach** [comment]
halloween seasonal feature

**Comment by Multi-Coder-24** [comment]
thanks I had no idea

**Comment by charliegc4** [comment]
> Link To Latest.log
> https://gist.github.com/DDX5/f7de9119915f9c3a8ee5c26335c26a12
> Link To debug.log
> https://gist.github.com/DDX5/1e143878768c1516059d2023746c46b1

Both links give a 404 page not found error.
