### ISSUE TITLE
Crash when attempting to bucket BoP poison

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Railcraft/Railcraft#1902]
**Description of the Bug**

Crash while attempting to bucket BoP poison 
**To Reproduce**

1. Find poison in world
2. NPE when you try to bucket it

**Expected behavior**

A bucket of poison to be produced
**Screenshots & Video**

**Logs & Environment**

 - Full log: 
https://paste.dimdev.org/edejewavuf.mccrash

 - Crash report (If available): 

**Additional context**

This may be BoP's fault, or something in between. As RC's code is first up in the stack trace, I'm letting you guys know. Will be creating an issue on BoP's side as well

**Comment by liach** [comment]
they are returning invalid fluid for their fluid block
