### ISSUE TITLE
with Railcraft buttons stop working

### ISSUE THREAD

**Issue by Ivar418** [Railcraft/Railcraft#1903]
**Description of the Bug**
when i have railcraft installed i cant use button like "R"for guns mod to reload, and "C" for project E to openup crafting table with philopher stone

**To Reproduce**
install my mods ( its a onedrive link) ( https://1drv.ms/u/s!AvA2DBq3tqxzgpkWzkulGq30QiaSeA?e=GBNlbR ) and grab a "rifle" with "advanced ammo (may be basic ammo)" and try to reload with R

**Expected behavior**
to have railcraft working plus all my other mods

forge version: 1.12.2-forge1.12.2-14.23.5.2847

**Logs & Environment**
https://gist.github.com/Ivar418/a4f6d65e69fef9d3b903f84346502099

**Comment by Ommina** [comment]
There are only so many keys available.  If two mods use the same key in the same context, one of them isn't going to work. 

You'll have to reassign the affected keys to something else.

**Comment by Ivar418** [comment]
Okay even tho i do not see railcraft use the R button it worked assigning any other actions that use r to another letter. Thanks for the help

**Comment by charliegc4** [comment]
Thought it was just me, but I had the same issues with RailCraft and TechGuns. Even though the R key is NOT assigned to ANY RailCraft action, it does not reload the gun.

So, is this a coincidence that it is the **R** key, and **R**ailcraft?

**Comment by Ivar418** [comment]
> Thought it was just me, but I had the same issues with RailCraft and TechGuns. Even though the R key is NOT assigned to ANY RailCraft action, it does not reload the gun.
> 
> So, is this a coincidence that it is the **R** key, and **R**ailcraft?

Haha, but no because it also applied to the philophers stone's crafting table. Wich uses C
