### ISSUE TITLE
Placing a steam locomotive on any rail while on a server crashes the client until entity is forcibly removed

### ISSUE THREAD

**Issue by isomeras** [Railcraft/Railcraft#1908]
**Description**: Tested on both SP and MP: while in multiplayer, the moment the steam locomotive entity is created, the client crashes. The moment the client logs in, the client crashes, until the entity is forcibly removed via console commands. This issue does not appear present in single player.

**Reproducibility** See above

**Expected Behaviour** Basic functionality of the things the mod is named after. Trains should go on rails, not destroy the very foundation of consciousness.

**Logs**
https://paste.dimdev.org/vayelofeci.mccrash

**Comment by liach** [comment]
Some other mods is registering invalid entity data manager parameters on basic minecarts.

**Comment by isomeras** [comment]
I'm not sure where you got that from, the bug report is about locomotives. Why would the minecarts, none of which have been spawned on the server, affect this?

**Comment by liach** [comment]
Fyi forestry once had added a data tracker parameter to the basic minecart entity class and broke railcraft. try again with only railcraft in your game; you won;t crash then when you place the locomotive.

**Comment by isomeras** [comment]
I would, but it's on the server that it breaks, not on singleplayer, and i'm not willing to upheave my friends that're playing. I'll try to test some changes on-server tomorrow while nobody's around. Thanks for looking in to it.

**Comment by isomeras** [comment]
I've identified a potential conflict with the Terracart mod's "frictionless" mode. Disabling that mod's frictionless carts has re-enabled standard minecarts. Sorry for the delay on this one: been a hectic few days.

All is working and accounted for. Thanks again for your insight.
