### ISSUE TITLE
embarking track doesn't stop carts

### ISSUE THREAD

**Issue by el-ahrairah** [Railcraft/Railcraft#1911]
RC 10.4.1
Unpowered embarking track does not stop carts.  Powered embarking track works fine.  Also had this problem with RC 10.1.2.  What might I be doing wrong?

Is this the right place to ask such a question?

Minecraft 1.10.2, Forge 12.18.3.2185

**Comment by CovertJaguar** [comment]
Embarking track doesn't and never stopped carts. It just teleports nearby entities into a cart.

If you want a cart to stop, use a Locking Track.
