### ISSUE TITLE
Impossible to install a tunnel boring machine [1.12.2]

### ISSUE THREAD

**Issue by Horusbk** [Railcraft/Railcraft#1913]
Hello,

I have the version **railcraft-12.0.0** of railcraft used on Minecraft 1.12.2.
I encounter a difficulty with the installation of the tunnel boring machine, but, only on the seed _-9363708386013540_

When I put the machine on rails, it appears a fragment of seconds before dropping on the ground.

I tried to turn off all of my other mods, resourcepacks... but the problem remain.

Thanks for your help.

**Comment by PJOKIN** [comment]
I also experimented the same problem, for a moment I thought, as you did, that it was a fact of mod incompatibilities. Thanks for stopping me from becoming crazy 😂. I hope is solved soon.

**Comment by mikkolukas** [comment]
I can tell that there ALSO exist a mod incompatibility with YUNG's Better Caves (at any seed), where same problem occur consistently.

**Comment by mikkolukas** [comment]
You are not crazy. I experience the same error om the same seed - but also on a lot of other seeds.

But I have also experienced instances where it WORKS on that exact seed.

Singleplayer, creative.

**Comment by CovertJaguar** [comment]
Fixed
