### ISSUE TITLE
java.lang.NullPointerException when loading railcraft with forge 14.23.5.2838

### ISSUE THREAD

**Issue by Kondor7001** [Railcraft/Railcraft#1915]
**Description of the Bug**
minecraft 1.12.2 using forge 14.23.5.2838 crashes an reports the following error while loading
 net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.NullPointerException

Please find the crash report below:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  EnderCorePlugin (EnderCore-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/24/20 10:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.NullPointerException
	at mods.railcraft.common.fluids.RailcraftFluids$Def.initBlock(RailcraftFluids.java:96)
	at mods.railcraft.common.fluids.RailcraftFluids$Def.access$500(RailcraftFluids.java:78)
	at mods.railcraft.common.fluids.RailcraftFluids.init(RailcraftFluids.java:130)
	at mods.railcraft.common.fluids.RailcraftFluids.preInitFluids(RailcraftFluids.java:118)
	at mods.railcraft.common.modules.ModuleCore$1.construction(ModuleCore.java:103)
	at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.construction(RailcraftModulePayload.java:71)
	at mods.railcraft.common.modules.RailcraftModuleManager$Stage$1.passToModule(RailcraftModuleManager.java:293)
	at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:250)
	at mods.railcraft.common.modules.RailcraftModuleManager.preInit(RailcraftModuleManager.java:198)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4661590680 bytes (4445 MB) / 6878658560 bytes (6560 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F4 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                           | Version         | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2          | minecraft.jar                                   | None                                     |
	| LCH   | mcp                        | 9.42            | minecraft.jar                                   | None                                     |
	| LCH   | FML                         | 8.0.99.99       | forge-1.12.2-14.23.5.2838.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                        | 14.23.5.2838    | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | opencomputers|core | 1.7.5.192       | minecraft.jar                                   | None                                     |
	| LCH   | actuallyadditions       | 1.12.2-r151     | ActuallyAdditions-1.12.2-r151.jar               | None                                     |
	| LCH   | applecore                 | 3.2.0           | AppleCore-mc1.12.2-3.2.0.jar                    | None                                     |
	| LCH   | architecturecraft       | @VERSION@       | architecturecraft-1.12-3.98.jar                 | None                                     |
	| LCH   | autowalk                  | 1.1             | autowalk-1.12.2-1.0.jar                         | None                                     |
	| LCH   | backpack                 | 3.0.2           | backpack-3.0.2-1.12.2.jar                       | None                                     |
	| LCH   | chameleon                | 1.12-4.1.3      | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCH   | codechickenlib         | 3.2.3.358       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks          | 2.4.2.74        | ChickenChunks-1.12.2-2.4.2.74-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chiselsandbits            | 14.22           | Chisels-and-Bits-Mod-1.12.2.jar                 | None                                     |
	| LCH   | clockhud                    | 1.4.0           | ClockHUD-1.12-1.4.0.jar                         | None                                     |
	| LCH   | redstoneflux               | 2.1.0           | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                     | 4.6.3           | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| LCH   | cofhworld                    | 1.3.1           | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | comforts                      | 1.4.1.2         | comforts-1.12.2-1.4.1.2.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | corail_pillar_extension_chisel    | 4.0.0           | corail_pillar_extension_chisel-4.0.0-1.12.jar   | None                                     |
	| LCH   | jei                             | 4.15.0.292      | jei_1.12.2-4.15.0.292.jar                       | None                                     |
	| LCH   | forestry                     | 5.8.0.311       | Forestry-Mod-1.12.2.jar                         | None                                     |
	| LCH   | corail_pillar_extension_forestry  | 4.0.0           | corail_pillar_extension_forestry-4.0.0-1.12.jar | None                                     |
	| LCH   | extendedrenderer          | v1.0            | coroutil-1.12.1-1.2.32.jar                      | None                                     |
	| LCH   | coroutil                          | 1.12.1-1.2.32   | coroutil-1.12.1-1.2.32.jar                      | None                                     |
	| LCH   | configmod                     | v1.0            | coroutil-1.12.1-1.2.32.jar                      | None                                     |
	| LCH   | cyclicmagic                    | 1.19.18         | Cyclic-1.12.2-1.19.18.jar                       | None                                     |
	| LCH   | movingworld                | 1.12-2.337      | movingworld-1.12-2.337-full.jar                 | None                                     |
	| LCH   | davincisvessels             | @DVESSELSVER@   | Davincis-Vessels-Mod-1.12.2.jar                 | None                                     |
	| LCH   | ptrmodellib                   | 1.0.4           | PTRLib-1.0.4.jar                                | None                                     |
	| LCH   | props                             | 2.6.3           | Decocraft-2.6.3_1.12.2.jar                      | None                                     |
	| LCH   | llibrary                          | 1.7.19          | llibrary-1.7.19-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | dragonmounts              | 1.12.2-1.4.4    | DragonMounts-1.12.2-1.4.4.jar                   | None                                     |
	| LCH   | orelib                            | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                     | 3.6.0.2         | DynamicSurroundings-1.12.2-3.6.0.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | easyretrogen                 | 5.0.1           | EasyRetrogen-1.12.2-5.0.1-universal.jar         | None                                     |
	| LCH   | endercore                      | 1.12.2-0.5.37   | EnderCore-1.12.2.jar                            | None                                     |
	| LCH   | thermalfoundation        | 2.6.3           | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalexpansion          | 5.5.4           | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | enderio                           | 5.0.25          | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LCH   | enderiointegrationtic     | 5.0.25          | Ender-IO-Mod-1.12.2.jar                         | None                                     |	| LCH   | enderiobase                  | 5.0.25          | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LCH   | enderioconduits            | 5.0.25          | Ender-IO-Mod-1.12.2.jar                         | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.0.25          | Ender-IO-Mod-1.12.2.jar       | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.0.25          | Ender-IO-Mod-1.12.2.jar     | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.0.25          | Ender-IO-Mod-1.12.2.jar         | None                                     |
	| LCH   | enderiointegrationforestry        | 5.0.25          | Ender-IO-Mod-1.12.2.jar              | None                                     |
	| LCH   | enderiointegrationticlate         | 5.0.25          | Ender-IO-Mod-1.12.2.jar                | None                                     |
	| LCH   | enderiomachines                   | 5.0.25          | Ender-IO-Mod-1.12.2.jar                    | None                                     |
	| LCH   | enderiopowertools          | 5.0.25          | Ender-IO-Mod-1.12.2.jar                    | None                                     |
	| LCH   | opencomputers              | 1.7.5.192       | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCH   | zerocore                          | 1.12.2-0.1.2.8  | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| LCH   | bigreactors                       | 1.12.2-0.4.5.67 | ExtremeReactors-1.12.2-0.4.5.67.jar             | None                                     |
	| LCH   | cfm                               | 6.3.1           | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCH   | healthhungertweaks     | 3.0.1           | Health-and-Hunger-Tweaks-Mod-1.12.2.jar         | None                                     |
	| LCH   | mts                               | 15.5.0          | Immersive+Vehicles-1.12.2-15.5.0.jar            | None                                     |
	| LCE   | railcraft                         | 12.0.0-beta-5   | railcraft-12.0.0-beta-5.jar                     | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | immersiveengineering   | 0.12-89         | Immersive-Engineering-Mod-1.12.2.jar            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivepetroleum       | 1.1.9           | Immersive-Petroleum-Mod-1.12.2.jar              | None                                     |
	| LC    | trackapi                          | 1.1             | TrackAPI-1.1_1.12.jar                           | None                                     |
	| LC    | immersiverailroading      | 1.4.0           | Immersive-Railroading-Mod-1.12.2.jar            | None                                     |
	| LC    | journeymap                   | 1.12.2-5.5.3    | JourneyMap-1.12.2.jar                           | None                                     || LC    | landlust                          | 1.12.2-0.3.6    | Landlust-Furniture-Mod-1.12.2.jar               | None                                     |
	| LC    | longerdays                | 1.0.4           | longerdays-1.0.4.jar                            | None                                     |
	| LC    | radixcore                  | 1.12.x-2.2.1    | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| LC    | mca                          | 1.12.2-5.3.1    | Minecraft-Comes-Alive-Mod-1.12.2.jar            | None                                     |
	| LC    | modernlamps            | 1.0.3           | ModernLights-1.0.3_1.12.jar                     | None                                     |
	| LC    | mtsofficialpack          | 12.0.0          | MTS_Official_Pack_V12.jar                       | None                                     |
	| LC    | mw                            | 0.4.1           | mw_2.0-0.4.1_mc1.12.2.jar                       | None                                     |
	| LC    | stacksize                   | 1.1             | stacksize-1.12.2-1.0.jar                        | None                                     |
	| LC    | storagedrawers        | 1.12.2-5.4.0    | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
	| LC    | storagedrawersextra    | @VERSION@       | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
	| LC    | thermaldynamics         | 2.5.5           | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | treechopper                 | 1.2.4           | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| LC    | weather2                     | 1.12.1-2.6.12   | weather2-1.12.1-2.6.12.jar                      | None                                     |
	| LC    | corail_pillar                  | 4.2.1           | corail_pillar-4.2.1-1.12.jar                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.12.2.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007' Renderer: 'AMD Radeon (TM) R9 390 Series'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v11.0.zip
	OpenGlVersion: 4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007
	OpenGlRenderer: AMD Radeon (TM) R9 390 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

I understand through some on-line trouble shooting that there may be a resource conflict between minecraft and another mod.  But I am not seeing that in the error report.  It seems to be an issue with java.  Any help would be appreciated, since I can not seem to run minecraft at all with railcraft.

**Comment by CovertJaguar** [comment]
Fairly certain this can only happen if the fluid is disable in the config, but the fluid block is not also disabled.

I will add a safety check to prevent crashing.
