### ISSUE TITLE
crash after updating to the latest version of p455w0rd's Lib

### ISSUE THREAD

**Issue by Twisted-Code** [Railcraft/Railcraft#1916]
**Description of the Bug**
After updating to p455w0rd's Lib version 1.12.2-2.3.159, the latest version which is required for one of his other mods' latest version, it caused this to crash. I'm used to getting crashes when I update mods (especially library mods that a few other mods are likely to depend on. I don't always think to check the dependents on curseforge and it's not always clear what depends on what version), but this time there doesn't appear to be a corresponding update to the dependent (you) subsequent the release of the library version that made it break. I don't know if you're even depending on p455w0rd's Lib in the first place (and if you specifically aren't, please say so since I'm reporting this on both trackers), but could you look into this when you have sometime?

**To Reproduce**

1. update p455w0rd's Lib to latest (or install specifically that version if it isn't already installed)
2. enjoy the beautiful... Minecraft launcher screen

**Expected behavior**
 no crash

**Screenshots & Video**
N/A

**Logs & Environment**

 - Full log (I assume by "fml-server-latest.log" and "fml-client-latest.log", your template actually means debug.log, not latest.log? here's both just in case): 
[latest.log](https://github.com/Railcraft/Railcraft/files/4131761/latest.log)
[debug.log](https://github.com/Railcraft/Railcraft/files/4131762/debug.log)

 - Crash report (If available): 
[crash-2020-01-29_20.43.00-client.txt](https://github.com/Railcraft/Railcraft/files/4131813/crash-2020-01-29_20.43.00-client.txt)

**Additional context**
N/A

**Comment by Twisted-Code** [comment]
I'm 90% certain this is actually not your bug at all. It doesn't crash without p455w0rd's mods, and according to someone on the Railcraft discord, might be caused by one of his mods being incompatible with the new version of his main Lib.
Still need to test to be sure (no time to play around with MC right now. Cramming a college assignment as usual), but if that's the case, I apologize and I'll close this myself :-)

**Comment by CovertJaguar** [comment]
I don't think this is my bug either... will close.

**Comment by Twisted-Code** [comment]
Yeah, sorry. forgot to come back and close this after confirming. my bad
