### ISSUE TITLE
Tank Valve Leaking

### ISSUE THREAD

**Issue by Martin-Seifert** [Railcraft/Railcraft#1918]
**Description of the Bug**

A tank that is full will continue to accept liquids from a valve on the top, which deletes the liquid.
This only happens if there is another valve on the bottom, irrelevant if it is connected or not.

**To Reproduce**

1. Build a tank with a valve on the top and bottom.
2. Fill it with a liquid
3. Connect anything that would fill the tank to the top valve, for example buildcraft pipes.
4. Fill the pipes with liquid
5. See that the pipes will slowly empty and the liquid goes nowhere.

**Expected behavior**
Tanks stops accepting liquid when full.

**Screenshots & Video**
https://youtu.be/dzbqEcSRf4o

**Logs & Environment**
railcraft 12.0.0
forge 14.23.5.2847

**Comment by CovertJaguar** [comment]
This is probably fixed as I removed all the special case tank stacking code.

Though I should probably check that valves will push to another valve. I think I forgot that part.
