### ISSUE TITLE
No switching rail [1.12.2]

### ISSUE THREAD

**Issue by kellixon** [Railcraft/Railcraft#1921]
I can't find these switching rails in 1.12.2. It was not added or it will not be in 1.12.2? Tell me please
![Безымянный](https://user-images.githubusercontent.com/22012731/75613228-46126f00-5b3c-11ea-9707-34e874dc0bf6.jpg)

**Comment by ParapetCloud** [comment]
you need to hit the rail with a spike maul to create the turnout, wye, and junction tracks

**Comment by chyper111** [comment]
parapet's right just get ether spike maul and it will switch to the switcher or the other two.

**Comment by kellixon** [comment]
Yes, of course, thank you **ParapetCloud** and **chyper111**. I've been playing 1.12.2 for almost a year without this rail, and I didn't think of it)
