### ISSUE TITLE
zinc battery texture and block use fail. 1.12.2

### ISSUE THREAD

**Issue by chyper111** [Railcraft/Railcraft#1922]
**Description of the Bug**
 when placing the zinc battery doesn't work and in breaking its texture glitches out.

**To Reproduce**

1. Place block/cart '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by CovertJaguar** [comment]
There are three Zinc battery types. Only one works. This is known.
