### ISSUE TITLE
Tunnel Bore not working everytime

### ISSUE THREAD

**Issue by Hrtlss** [Railcraft/Railcraft#1924]
Okay so i wanted to use this mod like a year ago or so on minecraft server only for the tunnel bore. At the time it didnt work on server so i deleted it. And now recently i started playing modded survival singleplayer and i thought i would give it a try. And the tunnel bore still drops as an item after placing it on tracks. I tried different type of tracks and none of it works... but i noticed something. I tried placing it on the same world using creative or spawning an item. None of it worked... on this world. I created new world and it worked. So from what i observed it only doesnt work if the world was created before adding the mod itself to the game. If thats the case what would i need to do to fix that so it works on my old world. Sorry but im not gonna start a new world just for one mod. Is there some kind of line in the code of the world i need to add so the bore works? Or maybe some command line

**Expected behavior**
I expected the bore to work...

**Additional context**
Im using the most recent version

**Comment by CovertJaguar** [comment]
Fixed
