### ISSUE TITLE
Worldspikes does not accept ore dictionary items

### ISSUE THREAD

**Issue by xJon** [Railcraft/Railcraft#1926]
Is it possible to let the Worldspikes accept `dustEnderPearl` & `dustObsidian`?
Thanks!

**Comment by CovertJaguar** [comment]
Ore tags are already supported.

**Comment by xJon** [comment]
@CovertJaguar I am trying to input an `ore:dustObsidian` item into a Worldspike and it is not working.

**Comment by xJon** [comment]
I think that the default config not using `dustObsidian` and `dustEnderPearl` is what caused my confusion.
