### ISSUE TITLE
Wye Track won't face each other on east-west direction

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#1927]
I would like to do this to my wye tracks. When facing the north-south direction they work fine.
![2020-03-23_15 32 25](https://user-images.githubusercontent.com/23195822/77292875-1b22d180-6d1c-11ea-8bf1-8142bedd3a33.png)

But, when facing east-west, it always turns out like this. I've tried everything but it keeps rearranging.
![2020-03-23_15 24 10](https://user-images.githubusercontent.com/23195822/77292928-3c83bd80-6d1c-11ea-854d-48e9bd9a6384.png)

**Comment by CovertJaguar** [comment]
Switched REQUIRE space (straight tracks connected to each side) around them to function properly.

This is not a bug, but the result of normal vanilla track placement logic. There is no point overriding it because the switching logic REQUIRES the extra space.
