### ISSUE TITLE
Flux Transformer does not display RF content with The One Probe

### ISSUE THREAD

**Issue by Freddo3000** [Railcraft/Railcraft#1929]
**Description of the Bug**

Flux transformer does not display how much RF is stored with The One Probe

**To Reproduce**

1. Form Flux Transformer multiblock
2. Power it with an infinite energy cell
3. Hover cursor over flux transformer and see '0 RF'

**Expected behavior**

It to display RF content

**Screenshots & Video**

![image](https://user-images.githubusercontent.com/14627848/77521821-8f2bb980-6e83-11ea-8a2a-4c75727d4b67.png)

**Logs & Environment**

 - Full log: [latest.log](https://github.com/Railcraft/Railcraft/files/4380024/latest.log)

 - Crash report (If available): N/A

**Additional context**

https://github.com/McJtyMods/TheOneProbe/issues/370

**Comment by janagyjr** [comment]
Probably should open this issue with The One Probe, then.

**Comment by CovertJaguar** [comment]
Not a bug, side effect of implementation. The Flux Transformer has a max storage capacity of Zero. All input is immediately converted to charge.

**Comment by Ommina** [comment]
Would it be worth storing 1RF just so ToP can give that reassuring visual indication of "yeah, it's full"?

Although, I concede that it may merely prompt an issue titled "Flux Transformer Only Holds 1RF".

**Comment by CovertJaguar** [comment]
It would add a bunch of unnecessary code for a such a minor thing. The transformer doesn't even posses an EnergyStorage object.

**Comment by janagyjr** [comment]
Conceptually speaking, transformers are not energy storage devices anyway. A good multimeter would be able to tell you what's being processed by the transformer.

Source: Am a licensed electrician trained in residential, commercial, and industrial electrical work.
