### ISSUE TITLE
Railcraft Causes Crash?

### ISSUE THREAD

**Issue by janagyjr** [Railcraft/Railcraft#1932]
**Description of the Bug**
I'm honestly not sure. I was upgrading JEID but that was causing issues with Phosphor, so I downgraded it and upgraded Advanced Rocketry and now Railcraft is throwing an error.

**To Reproduce**

1. Place block/cart '...'
3. See '...'

Honestly I never get *in-game*.

**Expected behavior**
Modpack to load

**Screenshots & Video**

**Logs & Environment**

 - Full log: No fml-client-latest.log; this is latest.log however: https://gist.github.com/janagyjr/02a4889f01a02a0ab01321172be2a867

 - Crash report (If available): https://gist.github.com/janagyjr/c050d50f1fa4d6b3d4841d42771ab889

**Additional context**

I'm just trying to get my modpack launching again so I can continue play-testing while Phosphor and JEID and Mixinbootstrap fix their crap.

**Comment by liach** [comment]
Hmm, delete the `railcraft` folder in your config folder and try again

**Comment by janagyjr** [comment]
I'll move it out of my config folder to my desktop, deleting it with the custom configs isn't a good option (it is an option, just not a good one).

And it does nothing. The pack won't even load now. 

Seems I'm still having problems with MixinServiceBootStrap
https://gist.github.com/janagyjr/5d7c8dadaee01283d6c749066f83ab10

fml

**Comment by liach** [comment]
This one is not railcraft's fault. You need to find out which mods ship SpongePowered mixin and remove them one by one. If you have spongeforge consider renaming it to `aSpongeForge` so its mixin loads before other mixins and this problem may be avoided

**Comment by janagyjr** [comment]
There are several mods that I'm aware are using Spongepowered Mixin. Phosphor and JEID. I absolutely need the latter, and Phosphor enables me to play w/o using Optifine. This is seemingly related to:
https://github.com/jellysquid3/phosphor/issues/64

Closing this issue, thanks for the help.
