### ISSUE TITLE
Error Russian localization Buildcraft gates on Railcraft machines

### ISSUE THREAD

**Issue by Kageburado** [Railcraft/Railcraft#1934]
I played Railcraft 9.12.2.0 and found errors Russian localization of Buildcraft gates in Railcraft machines. Is it possible to fix it?
![2020-04-01_22 25 36](https://user-images.githubusercontent.com/63039999/78366127-be030780-75c8-11ea-843f-755e1e170117.png)
![2020-04-01_22 25 47](https://user-images.githubusercontent.com/63039999/78366159-c8250600-75c8-11ea-9fc1-0a7d29f38f68.png)
![2020-04-01_22 27 36](https://user-images.githubusercontent.com/63039999/78366185-cf4c1400-75c8-11ea-89cc-1300c1647884.png)
![2020-04-01_22 27 45](https://user-images.githubusercontent.com/63039999/78366224-dbd06c80-75c8-11ea-977c-54d494927658.png)
![2020-04-01_22 27 48](https://user-images.githubusercontent.com/63039999/78366240-e4c13e00-75c8-11ea-9694-8589eab74acd.png)
![2020-04-01_22 27 50](https://user-images.githubusercontent.com/63039999/78366297-f6a2e100-75c8-11ea-8757-aeaad096ae6f.png)
![2020-04-01_22 30 53](https://user-images.githubusercontent.com/63039999/78366380-163a0980-75c9-11ea-8673-40489bbd45b0.png)
![2020-04-01_22 31 00](https://user-images.githubusercontent.com/63039999/78366473-3a95e600-75c9-11ea-8551-66bef953e53d.png)
![2020-04-01_22 31 04](https://user-images.githubusercontent.com/63039999/78366493-41245d80-75c9-11ea-8b4a-70e54e6ff56f.png)
![2020-04-01_22 31 09](https://user-images.githubusercontent.com/63039999/78366522-4a152f00-75c9-11ea-9e29-5394b5df1daa.png)
![2020-04-01_22 31 11](https://user-images.githubusercontent.com/63039999/78366546-526d6a00-75c9-11ea-88d2-1ee6ab74eb09.png)
![2020-04-01_22 33 02](https://user-images.githubusercontent.com/63039999/78366558-57cab480-75c9-11ea-84ef-2190de577463.png)

**Comment by CovertJaguar** [comment]
See railcraft/localization repo.

https://github.com/Railcraft/Railcraft-Localization
