### ISSUE TITLE
[1.12.2] Iron tank breaks when placed across chunk boundires

### ISSUE THREAD

**Issue by RouNNdeL** [Railcraft/Railcraft#1937]
**Description of the Bug**
When an iron fluid tank is placed across chunk boundries it breaks every time player leaves those chunks and comes back. There is a Standard Worldspike right on top of the tank to make sure all those chunks are loaded. Also, as show on the second screenshot clicking on the tank when it is not formated completly breaks the player's inventory, duplicating, removing and placing items in invalid slots, can be fixed be disconnecting and reconnecting (sometimes one of the items gets placed in one of the tank's slots).

**To Reproduce**

1. Build an iron tank across chunk boundries
2. Place a Worldspike
3. Leave the chunks 
4. Come back

**Expected behavior**
The tank should format correctly 

**Screenshots & Video**

Unformated tank. Note: the other 2 are just fine.

![2020-04-13_18 40 24](https://user-images.githubusercontent.com/22538735/79139446-9bd26c00-7db6-11ea-9e0a-f265d32ff98d.png)

Inventory before clicking on the tank:

![2020-04-13_18 28 29](https://user-images.githubusercontent.com/22538735/79139949-7d20a500-7db7-11ea-83ae-1730d3d4edd7.png)

Inventory after clicking on the tank:

![2020-04-13_18 28 32](https://user-images.githubusercontent.com/22538735/79139950-7e51d200-7db7-11ea-95f6-19f7cfd10017.png)

An item "disappearing" into the tank, the tank has to be destroyed and rebuilt in order to retrive the item.

![2020-04-13_18 54 22](https://user-images.githubusercontent.com/22538735/79140386-37b0a780-7db8-11ea-992c-2df349ebf3bf.png)

**Logs & Environment**
Tekxit 3 Modpack v0.971 + Forestry, Gendustry, RFTools and some more minor mods (the tank was breaking before modifying the mod pack)

 - Full log: 
https://gist.github.com/RouNNdeL/36869487ca3f0d4e6c9d2cbdddd5ab45
 - Crash report (If available): 
None

**Additional context**
I'm running a self hosted server. The tanks that do not cross the boundry all work fine. I'm open to any questions and further testing requests to help resolve this issue :)

**Comment by wtr478** [comment]
I am experiencing a similar phenomenon.

figure1.Inventory before clicking on the tank.
![image](https://user-images.githubusercontent.com/68231757/87307041-e7cab380-c553-11ea-8828-111be267b936.png)

figure2.Inventory after clicking on the tank.
![image](https://user-images.githubusercontent.com/68231757/87307073-f1ecb200-c553-11ea-8e11-8c6a29a192fa.png)
Armor is lost... :_(

Also, the tank was full, but when reconnected it is empty.
but, Breaking the glass and reallocate will restore the water.

figure3.Tank before reallocate glass.
![image](https://user-images.githubusercontent.com/68231757/87307382-74757180-c554-11ea-954e-330cf0625d18.png)

figure4.Tank after reallocate glass.
![image](https://user-images.githubusercontent.com/68231757/87307469-a4247980-c554-11ea-96e4-871a03470568.png)

My computer's environment.
![image](https://user-images.githubusercontent.com/68231757/87307581-d6ce7200-c554-11ea-9879-6a4c14f73f98.png)

Installed mods.
  - additionalpipes-6.0.0.8.jar
  - Advanced+Machines-61.0.1.jar
  - Advanced+Solar+Panels-4.3.0.jar
  - buildcraft-all-7.99.24.3.jar
  - ChickenChunks-1.12.2-2.4.2.74-universal.jar
  - ClickManaita-2.0.0.jar
  - CodeChickenLib-1.12.2-3.2.3.358-universal.jar
  - CompactSolars-1.12.2-5.0.18.341-universal.jar
  - CraftingEX_1.12-v1.2.0.jar
  - ElevatorMod-1.12.2-1.3.14.jar
  - EnderCore-1.12.2-0.5.73.jar
  - EnderIO-1.12.2-5.1.52.jar
  - Flan's Mod-1.12.2-5.5.2.jar
  - Forgelin-1.8.4.jar
  - ForgeMultipart-1.12.2-2.6.2.83-universal.jar
  - Gravitation+Suite-3.1.1.jar
  - ImmersiveEngineering-0.12-89.jar
  - industrialcraft-2-2.8.187-ex112.jar
  - InventoryTweaks-1.63.jar
  - ironchest-1.12.2-7.0.72.847.jar
  - jei_1.12.2-4.15.0.291.jar
  - journeymap-1.12.2-5.5.5.jar
  - logisticspipes-0.10.3.40.jar
  - mod_MineAllSMP_v2.6.5.jar
  - MrTJPCore-1.12.2-2.1.4.43-universal.jar
  - NotEnoughItems-1.12.2-2.4.3.245-universal.jar
  - OptiFine_1.12.2_HD_U_F4.jar
  - ProjectE-1.12.2-PE1.4.1.jar
  - ProjectEX-1.2.0.39.jar
  - ProjectRed-1.12.2-4.9.4.120-Base.jar
  - ProjectRed-1.12.2-4.9.4.120-compat.jar
  - ProjectRed-1.12.2-4.9.4.120-fabrication.jar
  - ProjectRed-1.12.2-4.9.4.120-integration.jar
  - ProjectRed-1.12.2-4.9.4.120-lighting.jar
  - ProjectRed-1.12.2-4.9.4.120-mechanical.jar
  - ProjectRed-1.12.2-4.9.4.120-world.jar
  - railcraft-12.0.0.jar
  - RefinedRelocation_1.12.2-4.2.36.jar
  - thutcore-1.12.2-5.21.0.jar
  - thuttech-1.12.2-6.1.6.jar
  - WR-CBE-1.12.2-2.3.2.33-universal.jar
  - XL-Food-Mod-1.12.2-1.9.1.jar
  - [1.12.2]+SecurityCraft+v1.8.18.2.jar
  - [1.12][forge2413]mod_CutAllSMP_v2.5.2.jar
  - [1.12][forge2413]mod_DigAllSMP_v2.3.2.jar
  - [1.12][forge2413]mod_StorageBox_v3.2.0.zip

I am operating on my own server as well as the questioner, so cooperation such as verification is possible.

I hope it will be improved.
Thank you.

**Comment by CovertJaguar** [comment]
Should be fixed by moving to the new logic based structure system (hopefully).
