### ISSUE TITLE
High speed track max speed

### ISSUE THREAD

**Issue by Harchvertelol** [Railcraft/Railcraft#1938]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when speed of my minecart is slow. For mineraft version 1.7.10 for the Railcraft, I used the Railcraft and Traincraft and was able to get a maximum speed of 1000 blocks in 34 seconds (without changing the configs). There is no Traincraft for version 1.12.2, so I, in addition to changing the config, was able to get 1000 blocks in 41 seconds. There is a limit of 1.2 at maximum speed.

**Describe the solution you'd like**
Please, could you change the maximum speed limit? Not 1.2, but, for example, 5.0. Thanks.

**Describe alternatives you've considered**
Set max.speed 1.2. Set max speed 1.3 (this already not working, because we have limit max speed 1.2).

**Additional context**

**Comment by CovertJaguar** [comment]
Cannot be done due to engine limits. You begin to outpace chunk loading.
