### ISSUE TITLE
Cart detectors incorrectly detecting max speed locomotive

### ISSUE THREAD

**Issue by CodedBinary** [Railcraft/Railcraft#1939]
**Description of the Bug**
Cart detector will detect a locomotive travelling at max speed when there is an entire block separating it and the locomotive. Importantly, a locking track may exist there.

**To Reproduce**
1. Place segment of normal tracks
2. (Optional) Place locking track (set to any mode)
3. Place Cart Detector (Any) underneath the rail immediately following the locking track
4. Place steam locomotive on track, fill completely with water and coal blocks
5. Turn locomotive to full speed towards locking track
6. Cart detector will emit redstone even though locking track prevents the locomotive from being adjacent

**Expected behavior**
Cart detector should not emit a redstone signal as the locomotive is never adjacent to it.

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/64187936/80067409-1ce0ee80-8581-11ea-91b0-bbc8a27da8c4.png)

![image](https://user-images.githubusercontent.com/64187936/80067028-70067180-8580-11ea-9377-92c70076849d.png)

**Logs & Environment**
Environment:
Forge version: forge-1.12.2-14.23.5.2847 downloaded from curseforge with SHA-1: 8398503A59F4EBE1EA878498ADF2B32CB9B470C1
Railcraft version: v12.0.0 downloaded from curseforge with SHA-1: EA2085A509B816BB9A3CDD79F2F44175B588737A
Minecraft version: v1.12.2 (singleplayer creative)
Operating System: Windows
Other mods installed: none

Logs:
Uploaded in 2 parts since text size exceeded 512M:
https://pastebin.com/evnkjnbM
https://pastebin.com/hXgyAAhX

**Additional context**
Sometimes on your first placement, this will not occur. However, this reliably occurs every time after the first occurrence, which is within 1-3 attempts at replicating. This issue does not in fact depend on locking tracks, but can ruin a token based system relying on them.

**Comment by CovertJaguar** [comment]
I attempted to reproduce with your setup with various different configurations. I was never once saw the behavior you describe.
