### ISSUE TITLE
The falling block in TFC will destroy the rails with the track  and cause the game to crash

### ISSUE THREAD

**Issue by ShuiShengDaLi** [Railcraft/Railcraft#1941]
Description of the Bug
Forgive my poor English
The falling block in TFC will destroy the rails with the track  and cause the game to crash

To Reproduce
1. Place rails with the track
2. Put a blocks with gravity in TFC on the rail
3. Falling block destroy the rail
4. Game crash

Logs & Environment
logs:https://github.com/ShuiShengDaLi/repository/blob/master/latestlogs
crash-reports:https://github.com/ShuiShengDaLi/repository/blob/master/crash-reports

**Comment by CovertJaguar** [comment]
Closed by eebeb8e1fc0193d231ada2152844a33191ac2a8c
