### ISSUE TITLE
Ticking player caused by having/crafting minestrapp panel

### ISSUE THREAD

**Issue by scotty74864** [Railcraft/Railcraft#1942]
When crafting a wall panel from Minestrappolation (any material) or logging into a world with one in inventory, game crashes.

**To Reproduce**
1. This parts tricky, Ive been using minestrapp for years, and Railcraft for months but this only started happening just last week:
2. Craft a wall panel, put one from JEI in your inventory or log into a world where a panel is in inventory. 

**Expected behavior**
I get a handful of walls for buildings

**Logs & Environment**
<script src="https://gist.github.com/scotty74864/43fbff6bae8c70a102f755cafc978590.js"></script>

**Additional context**
<!--Ive opened a ticket with minestrapp, and been studying the issue myself, but Im lost. Appreciate any help in advance, as I love Railcraft!

Thanks

**Comment by scotty74864** [comment]
Sorry, first timer to using Git.
https://gist.github.com/scotty74864/43fbff6bae8c70a102f755cafc978590

**Comment by CovertJaguar** [comment]
Closed by 18ad20f2aec6414d5f2bc12b72726da0e6aee060
