### ISSUE TITLE
Water Tank Siding not Producing Water no GUI

### ISSUE THREAD

**Issue by shawnbyday** [Railcraft/Railcraft#1943]
**Description of the Bug**
Water tank built properly and not across chunk boundaries. The water tank produces no water and has no GUI.

**To Reproduce**
* Install Forge v14.23.5.2854.
* Add railcraft-12.0.0.jar to mods folder.
* Launch game.
* Build water tank (check to make sure not crossing any chunk boundaries).
* Observe no GUI and no water.

**Expected behavior**
I was expecting it to produce water and have a GUI at this point.

**Screenshots & Video**

**Logs & Environment**

**Additional context**
Interestingly enough if you change to railcraft-12.0.0-beta4.jar then the water tank works fine and has a GUI, however, other things (such as the localization) are broken. In the beta4 version placing a coal boiler multi-block causes a crash so it seems it'd be easier to figure out what was changed from beta4 to beta5 (water tank doesn't work in beta5 either so whatever changed between those release is where the issue likely is - I looked through your commits but those only look to cover the 1.10.x version).

I also tried going back in Forge versions one by one until I hit the point where railcraft was telling me my FML was too old.

**Comment by DrUltraLux** [comment]
Same issue here with the same version. I think the wooden water tank multiblock isn't forming at all in fact.

**Comment by CelestialPhoenix** [comment]
Ran into a similar issue- water tank also appears to have some biome based properties, so it won't collect water in dry biomes.

**Comment by shawnbyday** [comment]
@CelestialPhoenix pretty sure that's intended. At least in the past it was always a thing.

**Comment by CelestialPhoenix** [comment]
Its an intended feature; just that there's no indication for it. If you're unaware (_like I was at the time_) it feels like a bug.

**Comment by CovertJaguar** [comment]
It was a side effect of the fractured nature of the multiblock codebase as the Water Tank and Iron Tanks shared the same GUI originally. But when the Water Tank was updated to the new logic system, it was no longer compatible with the old Tank GUI. In the interest of expediency, the GUI was simply dropped until it could be fixed.

It is now restored.
