### ISSUE TITLE
 train routing (router block) problem 

### ISSUE THREAD

**Issue by gameplays12303** [Railcraft/Railcraft#1945]
i am having a routeing problem / you change it on me or i don't rember 
even your book dose not give me enough info it just tell me "hay do this get that " 
no clue of what's going on 

in 1.7.10  i could put 
"north/east/station_2" on the ticket and leave out "north/east" on the router at the destination 
if this is some new idea which i don't think it is
could you re-implement

in this i could build a train network without lagging out or filling up the routing book with 200 lines 
if this is still possible please let me know i have look all over to see how routing is working and i have yet to get an answer  (because google is more worried about get the money then they are giving me the answer )

**Comment by CovertJaguar** [comment]
I'm pretty sure you've got it backwards.

Think of it like an address: city/road/address

In the train you put the fully qualified address. In the routing tables along the way, you only need to specify most general parts of the address. For example, if a line heads towards 'city', the table only needs city. Once you are in 'city', the routing tables would have 'city/road'. Once you are on the specific road and at your final destination, the last table would have the fully qualified address 'city/road/address'.

This has never changed and has always been the way the system works.
