### ISSUE TITLE
Cannot craft steam turbine parts or create bronze ingots

### ISSUE THREAD

**Issue by PaddlesTheLaddles** [Railcraft/Railcraft#1947]
**Description of the Bug**

**To Reproduce**

1. Place block/cart '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by CovertJaguar** [comment]
I assume recipe conflicts....
