### ISSUE TITLE
Ore generation on other planets (galacticraft4)

### ISSUE THREAD

**Issue by whatisthat-wq** [Railcraft/Railcraft#1948]
Hi there!

I am running a server and recently installed railcraft. Because I had loaded a huge chunk on the overworld, I decide to load railcraft ore onto other planets (e.g. Mars). However, for some reason I cannot load it, or only load copper as default....

Here is the config (galacticraft config for ore generation)

 # Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use optional parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for clump size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults are /COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
	railcraft:ore_metal_nickel
	railcraft:ore_metal_zinc
	railcraft：ore_saltpeter
        railcraft:ore_sulfur
     >

i think i might have got the wrong ID name, so please help with this :(

Thank you very much!

**Comment by CovertJaguar** [comment]
Use NEI with advanced tool tips turned on (F3+Q) to find the correct names/meta.
