### ISSUE TITLE
Throttle track sometimes reversing locomotive. Opposite where arrows point to.

### ISSUE THREAD

**Issue by SamTellings** [Railcraft/Railcraft#1949]
**Description of the Bug**
On version 1.12: Throttle tracks sometimes reverse the direction of the locomotive. The arrows would be pointing north, but the locomotive suddenly switches to reverse direction.

**To Reproduce**
1) make a track line in a square so you have a nice rectangle track
2) put a throttle block (and a detector block to power it) on each side of the track always pointing to one direction so in theory the train should drive circles always in the same direction
3) one specific throttle block will act strange and reverse the locomotive to the opposite direction of the arrows on the throttle track.

**Expected behavior**
The locomotive going to were the arrows point, not reverse.

**Comment by Forecaster** [comment]
This not a bug. The throttle track (previously known as the locomotive track) has never had a direction. Although the previous iteration didn't have arrows on it. Just a bar.

All it does, as always, is set the throttle (or gear more accurately) of the locomotive to a forward or reverse speed. Forward to the track is **always** in the direction of the red dot on the track. But the actual direction is always relative to the locomotive, not the track.

**Comment by SamTellings** [comment]
Hey Forecaster,
Just to be sure I took a [screenshot ](https://imgur.com/a/pIJRHls)with an example.

Wouldn't the second throttle track reverse the locomotive normally? Because here to locomotive just keeps driving in the same direction (relatively speaking).

I'm probably missing something obvious here.

Thanks in advance!

**Comment by Forecaster** [comment]
Both of those tracks do the exact same thing

**Comment by SamTellings** [comment]
Ooh, I get it now. I just need to make sure the arrow is pointing to the dot if I want the same direction, and away from the dot if I want to reverse.

The arrows confused me. But it clicked for me now. Sorry for the trouble!

Thanks for helping me!
