### ISSUE TITLE
Missing Switch Tracks and some other Tracks

### ISSUE THREAD

**Issue by Mr4Jon** [Railcraft/Railcraft#1951]
**Description of the Bug**

There is no way to create an Switch Tracks. I use a standard rail (8 pieces) and a wooden canvas (1 piece).
There are no recipes for creating any Switch Tracks.

**Screenshots & Video**

![image](https://user-images.githubusercontent.com/66223908/83362931-eb3c1e00-a39d-11ea-93cc-92429348d7b0.png)

**Additional context**

![image](https://user-images.githubusercontent.com/66223908/83362947-13c41800-a39e-11ea-8b40-f3c9601fa2cb.png)

**Comment by whatisthat-wq** [comment]
I have the same problem as well......

**Comment by whatisthat-wq** [comment]
I found the solution

Apparently you can craft a spike maul, and right-click on the track to turn it into switch track/junction track.

it is not updated on wiki somehow Xd
