### ISSUE TITLE
Ridiculously easy dupe bug

### ISSUE THREAD

**Issue by aconamos** [Railcraft/Railcraft#1958]
**Description of the Bug**
Easy bug that allows you to quickly dupe any item.

**To Reproduce**
1. You need 2 backpacks.
2. Put one in your hotbar, and one in your inventory.
3. Put whatever you want to dupe in the backpack in the hotbar.
4. Open the hotbar backpack.
5. Using hotkeys, switch the two backpacks.
6. Pull whatever you want out of the backpack gui.
7. Bam! You will have copied the items from one backpack, and put them in the empty one.

**Expected behavior**
Take the items out of the right backpack.

**Screenshots & Video**
Not applicable.

**Logs & Environment**
It doesn't log this behavior.

 - Crash report (If available): 
Not available

**Additional context**
Using one backpack, you open a gui. When you update the contents of that gui and close it, it will essentially update whatever backpack you're holding, allowing you to copy contents of one backpack to another.

**Comment by liach** [comment]
More exactly, the bug is that backpack screen doesn't update when the item updates in slot.

**Comment by aconamos** [comment]
> More exactly, the bug is that backpack screen doesn't update when the item updates in slot.

True, never thought of that.

**Comment by CovertJaguar** [comment]
This is a Forestry bug.
