### ISSUE TITLE
first storage cart hopperlike behavior for tunnel bore

### ISSUE THREAD

**Issue by strivenous** [Railcraft/Railcraft#1960]
**Is your feature request related to a problem? Please describe.**
No, I'm fine with the maintenance travel.

**Describe the solution you'd like**
If the first cart linked to a tunnel bore is a storage cart, it should act as an "hopper" medium for the bore, so that you could put boreheads, track or fuel and as it runs out the bore gets restocked by the storage cart.

**Describe alternatives you've considered**
no other alternatives found

**Additional context**
n/a

**Comment by CovertJaguar** [comment]
It does.
