### ISSUE TITLE
Weird bug with Coke Oven and Iron Tanks

### ISSUE THREAD

**Issue by TsundereMatrix** [Railcraft/Railcraft#1961]
**Description of the Bug**
I encountered this strange bug when I interact with my coke oven or iron tank that has creosote oil in it. The iron tank and coke oven act as if they are incomplete structures. My inventory GUI is then all screwed up and many items are duplicated. I have to close Minecraft several times to make the bug go away but it always comes back eventually.

**To Reproduce**
1. Build Coke Oven and Iron Tank
2. Allow Coke Oven to make coal coke and creosote oil
3. Fill Iron tank with creosote
4. Leave area and come back multiple times

**Expected behavior**
It always happens when I least expect it.

**Screenshots & Video**
![glitch](https://user-images.githubusercontent.com/54121698/87823463-4465f100-c828-11ea-846a-3f4079a49b7e.JPG)
This is what happens with the inventory GUI

**Logs & Environment**
No log available

 - Crash report (If available): 
[crash-2020-04-26_14.10.21-client.txt](https://github.com/Railcraft/Railcraft/files/4939807/crash-2020-04-26_14.10.21-client.txt)
This is my latest crash report which was caused by Minecraft itself. The game doesn't crash when this bug/glitch occurs.

**Additional context**
At first I thought it was caused by Buildcraft. Upon removing Buildcraft from my mod list, the bug continued to occur so I'm assuming its a Railcraft bug because its really only affecting Railcraft items and structures.

**Comment by Ommina** [comment]
Not Buildcraft; it's a fairly known bug with Railcraft multiblocks.  You can mitigate it somewhat by ensuring multiblock builds do not cross chunk boundaries.

**Comment by TsundereMatrix** [comment]
> Not Buildcraft; it's a fairly known bug with Railcraft multiblocks. You can mitigate it somewhat by ensuring multiblock builds do not cross chunk boundaries.

That was definitely my problem. The multiblock builds were on chunk boundaries. I will fix that and hope I won't have any more problems. Thanks!

**Comment by CovertJaguar** [comment]
Possibly fixed by b6c7c4b005ca5545371bbf6138ea4ab10e9e070d
