### ISSUE TITLE
[Locked]

### ISSUE THREAD

**Issue by charliegc4** [Railcraft/Railcraft#1965]
"So the next person doesn't have to ask? I thought that would be obvious..."
_Originally posted by @CovertJaguar in https://github.com/Railcraft/Railcraft/issues/1884#issuecomment-675923974_

It is unclear what is "obvious". Does this mean that you consider it obvious that the wiki does not contain information about the current mod?

**Comment by CovertJaguar** [comment]
You just earned a ban, congratulations.
