### ISSUE TITLE
Furnace cart doesn't use last fuel of a stack

### ISSUE THREAD

**Issue by Trinsdar** [Railcraft/Railcraft#1967]
**Description of the Bug**
if you right click a furnace cart with a fuel item such as coal that only has a stacksize of 1, it will fuel the furnace cart without consuming the coal.

**To Reproduce**

1. Place furnace cart
2. Click on furnace cart with exactly one coal
3. watch it start up without consuming the coal

**Expected behavior**
it should consume the coal

**Screenshots & Video**
https://gfycat.com/decentfatherlyhornet

**Logs & Environment**
N/A

**Additional context**
Noticed in our testing pack for my mod, can try to reproduce it with just rc if you want, but I doubt any other mod is messing with the furnace cart.

**Comment by CovertJaguar** [comment]
Relevant Code:

https://github.com/Railcraft/Railcraft/blob/b7ba6bea1e52ac55792377a1336497c07282ed18/src/main/java/mods/railcraft/common/carts/EntityCartFurnace.java#L90-L106

https://github.com/Railcraft/Railcraft/blob/18ad20f2aec6414d5f2bc12b72726da0e6aee060/src/main/java/mods/railcraft/common/util/inventory/InvTools.java#L184-L191

The only way I can see what you describe happening is if you are in creative mode or if Coal has a container item. Coal does not normally have a container item. That said, I've not tested it in game yet, so maybe something is happening I'm not accounting for.

**Comment by CovertJaguar** [comment]
Of course as soon as I say that, I realize that I never actually set the held item. Returning an Empty item from depleteItem() is not sufficient.
