### ISSUE TITLE
Hi-speed friendly Laser track

### ISSUE THREAD

**Issue by HoasRiveor** [Railcraft/Railcraft#1969]
Since Laser tracks are energy-based I think it would be right to make them not causing explosions when carts are moving to it from H. S. Booster track (activated)

![2020-08-31_18 17 45](https://user-images.githubusercontent.com/70528724/91736434-50c6c300-ebb6-11ea-9053-08a37a01deb7.png)
So carts would go at high speeds on laser track

**Comment by CovertJaguar** [comment]
I'm cool with that idea. 👍

**Comment by CovertJaguar** [comment]
Closed by 2c891a8d95b3eabc850f67ff93e29439333b81be
