### ISSUE TITLE
What does it mean when you die and it says (playername) bought a ticket to the afterlife?

### ISSUE THREAD

**Issue by vinnyg0621** [Railcraft/Railcraft#1970]

**Comment by CovertJaguar** [comment]
That they got hit by a train.

**Comment by vinnyg0621** [comment]
that who got hit by a train?

**Comment by CovertJaguar** [comment]
Trying to be cute will just earn you a ban. 

So, I suggest you either be more clear about what you are trying to ask and why or just drop it.
