### ISSUE TITLE
weird visual bug

### ISSUE THREAD

**Issue by TheXTrunner** [Railcraft/Railcraft#1971]
**Description of the Bug**
something odd appears on top of the boiler's temperature bar

**To Reproduce**
Just leave the boiler go up to 1000 degrees

**Expected behavior**
the bar to just go up to the limit, but then it goes above and with those weird textures

**Screenshots & Video**

https://www.reddit.com/r/feedthebeast/comments/ik5orm/how_to_fix_this_visual_glitch/?utm_medium=android_app&utm_source=share

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by CovertJaguar** [comment]
Check with 12.1.0 series.
