### ISSUE TITLE
Crash Cannot set property PropertyDirection

### ISSUE THREAD

**Issue by Larsz11** [Railcraft/Railcraft#1972]
The game crashes if i hold an block from Future Versions.

crash log: https://pastebin.com/EWrWajS5

**Comment by CovertJaguar** [comment]
Closed by 18ad20f2aec6414d5f2bc12b72726da0e6aee060

**Comment by Larsz11** [comment]
and when can i download the newest version because the last version that i can download still has the problem. 
last downloadable version "railcraft-12.0.0.jar"
