### ISSUE TITLE
Switch track cannot turn left

### ISSUE THREAD

**Issue by Dieter-dotco** [Railcraft/Railcraft#1974]
![2020-09-08](https://user-images.githubusercontent.com/70691272/92433741-87ad6200-f1d0-11ea-9f51-e055713ea529.png)
Whatever how many times I use the Spike Maul, I cannot create a junction that can let the cart to turn left. Do there have any other method to change the turning direction with using switch track component?

**Comment by Trinsdar** [comment]
Have you tried using a crowbar to rotate it?
