### ISSUE TITLE
Force tracks may get broken after world re-open

### ISSUE THREAD

**Issue by Vodulm** [Railcraft/Railcraft#1977]
https://vimeo.com/470350580

[latest.log](https://github.com/Railcraft/Railcraft/files/5418087/latest.log)

[debug.log](https://github.com/Railcraft/Railcraft/files/5418085/debug.log)

**Comment by Vodulm** [comment]
Seems not happening if they have separate Feeder units...

**Comment by CovertJaguar** [comment]
Duplicate of #1988
