### ISSUE TITLE
Weird rendering problems on minecarts and locomotives

### ISSUE THREAD

**Issue by Mick235711** [Railcraft/Railcraft#1979]
**Description of the Bug**

The carts and locomotives (even the original minecart with original tracks) is showed as white pictures, and colors on locomotives vanishes. (see screenshots)

**To Reproduce**

1. Simply start a vanilla 1.12.2 Minecraft and put in the 12.0.0 version of Railcraft (also tested with the latest HEAD, same)
2. Start a new world
3. Put down a track, put a locomotive/cart on the track, and see

**Expected behavior**

Vanilla carts and locomotives should show normally.

**Screenshots & Video**

![2020-10-22_23 21 03](https://user-images.githubusercontent.com/22275534/96893565-6b822d80-14bd-11eb-9706-9b7ba0e3bd1d.png)
![2020-10-22_23 20 41](https://user-images.githubusercontent.com/22275534/96893591-71780e80-14bd-11eb-8fd7-dae37444e600.png)

**Logs & Environment**
macOS 10.15.6, JDK 1.8.265, Minecraft 1.12.2, Railcraft 12.0.0

 - Full log: [debug.log](https://gist.github.com/Mick235711/2247c1109ff974197edd256ed5ce7638), [latest.log](https://gist.github.com/Mick235711/2e4ef35e455e8d56d540b7ae2f80dd9c)

 - Crash report (If available): None

**Additional context**

The test is carried out in completely newly installed 1.12.2 Minecraft with only Railcraft installed. Removing Railcraft and the carts are back to normal.

**Comment by Su5eD** [comment]
> Vanilla carts and locomotives should show normally

Unless it's halloween 🎃

**Comment by Forecaster** [comment]
This is a halloween "event" easter egg. Between certain dates this will happen unless you disable the "holiday effects" or something like that in the Railcraft config file.

**Comment by Mick235711** [comment]
Thanks a lot!
A good setting, though maybe a little scaring for people that don't know. :satisfied:

**Comment by Forecaster** [comment]
That's kind of the idea isn't it

It will go back to normal on its own eventually
