### ISSUE TITLE
Trains look like ghosts

### ISSUE THREAD

**Issue by JamesAragorn** [Railcraft/Railcraft#1980]
**Description of the Bug**
Locomotives and carts look white and transparent--like ghosts.  They seem to work normally though.

**To Reproduce**
I'm not sure how to reproduce it.  It was fine when I logged out of my world a few days ago, and then it was this way when I logged in.  Breaking and replacing them didn't fix it, and neither did logging out and back.

**Expected behavior**
I expected the trains to look the way they're supposed to?

**Screenshots & Video**
Screenshot attached.
![Screen Shot 2020-10-24 at 9 39 01 AM](https://user-images.githubusercontent.com/73394774/97084457-d1190b80-15dc-11eb-9c58-49a929710e31.png)

**Logs & Environment**
[latest.log](https://github.com/Railcraft/Railcraft/files/5433024/latest.log)

**Additional context**
It's late October.  If this glitch turns out to be a Halloween Easter egg, I'm not sure whether to be annoyed, amused, or embarrassed for thinking it's a glitch!

**Comment by Trinsdar** [comment]
I believe it is indeed a holloween easter egg, doesn't seem like a bug to me, cause if it were a glitch it would look far worse

**Comment by forresthopkinsa** [comment]
railcraft/client.cfg `enableGhostTrain=false`

**Comment by CovertJaguar** [comment]
Working as intended!
