### ISSUE TITLE
Iron/Steel tanks multiple issues (alpha 5)

### ISSUE THREAD

**Issue by Flaksmith** [Railcraft/Railcraft#1981]
12.1.0 alpha 5

As you mentioned in the release notes you migrated tanks and other multiblocks to a new framework, so I understood there are still kinks to be worked out. However there are a few glaringly obvious issues that I haven't seen brought up yet so I'll use this report to list the current and any additional bugs I find before the next patch.

- [x] 1. ~Fluids cannot be deposited or extracted from a tank by right clicking on them.** I am fully aware that the new glass blocks do nothing, but even right clicking the wall blocks doesn't work. Doesn't matter if a bucket, cell, or capsule is used.~
Works on valves.

- [x] 2. ~Fluids cannot be deposited in the tank using the gui.** Again, it doesn't matter if it's a bucket, cell, or capsule.~

- [x] 3. ~Also in the gui, fluids can only be extracted via buckets. No other items work.~

- [x] 4. Fluids can be deposited and extracted by the valves, but the flow rate appears to be significantly lower than it used to be.** I noticed this when my tree farm kept clogging up with saplings because the fermenters couldn't empty into the tanks fast enough. Not sure if this is intentional.

- [x] 5. ~Tank glass drops nothing when broken without silk touch.** I honestly can't remember if the old glass dropped when broken with a normal pick, but the new glass doesn't. Not sure if this is intentional.~

**Comment by xXPANAGE28** [comment]
My iron tanks in my world mess up my inventory and bug my game when I right click on any block of said tank. I must restart my save to fix. I cannot access fluids in my tanks as a result.

**Comment by xXPANAGE28** [comment]
> My iron tanks in my world mess up my inventory and bug my game when I right click on any block of said tank. I must restart my save to fix. I cannot access fluids in my tanks as a result.

Update: No liquids present upon world initialization. it seems that a pipette from forestry, when held in hand and right clicked anywhere on the tank will spawn the liquid within the tank and I am allowed to touch to access the tank's UI again. This only worked short term tho.

**Comment by Flaksmith** [comment]
You're playing on an older version than me, those issues have been fixed. The problem in your version is that the tanks bug out when you first load the map if they're on chunk boundaries (and sometimes for no reason). Just break and replace one of the blocks to reset it before you try to open the gui.

**Comment by CovertJaguar** [comment]
I'll check again, but I thought I fixed most of these issues.

1 might require a valve.
5 should be fixed.

**Comment by CovertJaguar** [comment]
Fix fluid containers in GUI.

**Comment by CovertJaguar** [comment]
I cannot find any issue with tank flow rates. I filled and emptied tanks exceptionally quickly.

Closing this issue as complete.
