### ISSUE TITLE
Railcraft Invisible Carts

### ISSUE THREAD

**Issue by Minecraft2p0** [Railcraft/Railcraft#1983]
I have the problem that all trains and minecarts are invisible. Since I suspected a conflict with another mod, I loaded Railcraft on its own. The problem occurs even without a resource package and with all settings to default. I'm using version 12.0.0 with Minecraft 1.12.2 and Forge 14.23.28.54. How do I get the problem resolved?

I would like to attach a picture, but don't know how to do it on this page.

**Comment by Minecraft2p0** [comment]
I found the solution. Was just a setting of the mod. I set enable Ghost Train to false. Thank you anyway.

Very good mod by the way.

**Comment by gatoborrachon** [comment]
yeah, its because is spooky time right now, but i wanted to tell you how to add an image: just drop it in the text box or use imgur.com
