### ISSUE TITLE
Blast Furnace not smelting Iron

### ISSUE THREAD

**Issue by 95Gman** [Railcraft/Railcraft#1989]
Vanilla Iron Ingot with a Railcraft Coal Coke in the Railcraft Blast Furnace consumes the fuel, arrow progress bar does not move nor does it produce steel and slag.

1. Have the iron ingot, coal coke and blast furnace ready.
2. Place coal coke in fuel slot and iron ingot in consume slot.
3. Watch the coal be burnt and the fuel be spent.
4. Observe the issue.

Iron Ingot to be processed into Steel and Slag.

No log to report.

**Comment by Flaksmith** [comment]
it does smelt the iron, the progress bar is broke

**Comment by 95Gman** [comment]
Huh. So it took 2 coal cokes to produce 1 steel. I misunderstood the timing and thought the coal coke burnt for 64 seconds which was enough for 1 steel.
