### ISSUE TITLE
FPS down until only left 1(If there is no installed on the server, it should be disabled)

### ISSUE THREAD

**Issue by Largosaki** [Railcraft/Railcraft#1990]
If Railcraft is not installed on the server

The client will cause severe performance degradation until FPS1
And there is no error report

After repeated experiments, it is believed that the error was caused by the original minecart
The client believes that ordinary mine carts should be replaced with Railcraft mine carts
The server thinks it should be an ordinary minecart

This may cause differences in calculations and repeated pulls

Should it be disabled if there is no corresponding module on the server side?

I have the original and Railcraft mod server group in bungee and got this error,
And produced a clean original world to reproduce this error

For this high-throughput repetitive calculation is a legal act
No error report

**Comment by CovertJaguar** [comment]
Why are you triying to connect with mismatched mods?
