### ISSUE TITLE
[1.12.2] Severe: Leak: ByteBuf.release() was not called before it's garbage-collected. - 5 Records with Railcraft in combination

### ISSUE THREAD

**Issue by Chaoschaot232** [Railcraft/Railcraft#1994]
Not sure what the problem is but it is the first time that I encounter this behavior and after some minutes of playing the beloved "Can't keep up ..." message.

I added the JVM Argument to get more info about the leaks and it states all the time:
`mods.railcraft.common.util.network.PacketTileRequest.readData(PacketTileRequest.java:52)
mods.railcraft.common.util.network.PacketHandler.lambda$readPacket$0(PacketHandler.java:139)`

Here you can take a look into the log (extracted with portainer.io, as I am running MC dockerizied, also the leaks are not stored in the log file on the server, why ever): https://github.com/Chaoschaot232/MC-Serverlogs/blob/main/MC-FTB-Rev_3.4-Severe-Leak-RailCraft

Hope that helps by finding out what maybe causes it.

**Comment by Ommina** [comment]
I believe this was addressed back in August, but has yet to be released.

https://github.com/Railcraft/Railcraft/commit/7956f401136f1cc14c2d1020aed59a130d35a686

(I think.)

**Comment by Chaoschaot232** [comment]
I see, so there are a few pending changes for maybe another 1.12.2 release?
Sounds good and would be great, if so :)
