### ISSUE TITLE
The new version of Buildcraft' fuel can't be added to Railcraft machine

### ISSUE THREAD

**Issue by MyBlueHorizon** [Railcraft/Railcraft#1997]
**Description of the Bug**
The new version of Buildcraft' fuel can't be added to Railcraft machine
It is working in old version.
**Expected behavior**
The new version of Buildcraft' fuel can be added to Railcraft machine.

**Comment by Su5eD** [comment]
This has already been implemented. See commit a2e5e7f for more information
