### ISSUE TITLE
Railcraft tunnel bore breaks on placement.

### ISSUE THREAD

**Issue by KenwoodFox** [Railcraft/Railcraft#1999]
**Description of the Bug**
Whenever I try to place a tunnel bore, it breaks immediately. But no error is logged. Testing on a superflat world seems to work fine, but our dedicated server with the same mods does not. There are other mods installed other than railcraft.

**To Reproduce**
1. Place tunnel bore on stock track.
2. See Attached

**Expected behavior**
The bore should be placed and should not break this easily

**Screenshots & Video**
https://kitsunehosting.net/nextcloud/index.php/s/Syk7TwDwYbfBWZo Video Example

**Logs & Environment**
**Additional context**

**Comment by CovertJaguar** [comment]
Fixed
