### ISSUE TITLE
The Coupler Kit model and recipe are in the Extras module instead of the Train module

### ISSUE THREAD

**Issue by Hate9** [Railcraft/Railcraft#2002]
**Description of the Bug**
If the extras module is toggled off, the recipe for the Coupler Kit is unregistered, and it displays with no model.
EDIT: Apparently it also happens with Signals.
**To Reproduce**
1. Disable Extras module
2. Start the game
3. Look up the Coupler Kit in JEI

**Expected behavior**
The Coupler Kit has a recipe and model/texture, as normal.

**Comment by CovertJaguar** [comment]
Ah... yeah. It shouldn't be that way.

**Comment by CovertJaguar** [comment]
I cannot reproduce the issue.
