### ISSUE TITLE
Odd behavior between water tank siding, coke oven, and fluid loader.

### ISSUE THREAD

**Issue by Fireleaf13** [Railcraft/Railcraft#2003]
If a water tank siding is build against a coke oven and a fluid loader is placed below the coke oven the fluid loader starts collecting water.
![image](https://user-images.githubusercontent.com/43079843/106915582-2d0f2800-66d4-11eb-8ca5-8e014a17f0a5.png)

**Comment by CovertJaguar** [comment]
Hmm... will test in new version. Very strange.
