### ISSUE TITLE
Tunnel bore dropping when I try to place it

### ISSUE THREAD

**Issue by FedeLannes** [Railcraft/Railcraft#2010]
For Some reason when I try to put a tunnel bore, it keeps dropping itself rather than place down and working.
I am in any case using the RAD modpack, with a few dozen mods, so that might be the fault?.
And no, this is not any server of some sorts, this is my own world in singleplayer.
Whatever the case, it should just sit down and I should be able to make the job, but that never happens, it always drops.

![drop train](https://user-images.githubusercontent.com/32713427/112710986-d2a87180-8ea3-11eb-8afe-ca43934b747c.gif)

Here's my report if needed:

https://gist.github.com/CaripijaXXX/f213a7a844d2c2cd88336d8e82cdedd5

If you manage to know what's happening I would like to know, because I know next to noting.
Thanks in advance.

**Comment by maleksware** [comment]
Fixed in #2024.
