### ISSUE TITLE
Tin ore is generating instead of zinc (1.12.2)

### ISSUE THREAD

**Issue by Lejimuz** [Railcraft/Railcraft#2011]
Tin ore is generating where zinc should (and poor tin where poor zinc should)

I played for a long time without finding any zinc, then found out that it only spawns in large deposits, so I downloaded an xray mod because I didn't want to try going even longer without finding it, only to realize that when I got to a zinc mine all the zinc was replaced with tin.

![image](https://user-images.githubusercontent.com/64155224/113268443-fcdfa200-929c-11eb-966a-0bdfdf158725.png)

![image](https://user-images.githubusercontent.com/64155224/113268686-43350100-929d-11eb-8e09-135e3a4ae0e0.png)

**Comment by Ommina** [comment]
I'm simply not understanding here.  How does the x-ray mod determine that a particular vein is _supposed to_ be zinc, instead of tin?

I would expect, and this may be my error, that the mod would only report "what is".  How does it determine that what you found isn't just an intended Tin deposit?

**Comment by gatoborrachon** [comment]
the issue here is that the X-ray mod can't differentiate between same blocks with different metadata (the case of Railcraft's ores).

and there's no fix, the author of that mod said that he will not work on the 1.12 version anymore 

MC Version: 1.12.2 ||| Mod version: 1.5.0 ||| Status: Discontinued

**Comment by gatoborrachon** [comment]
also, i suggest you to not use X-ray mod, it takes the fun away, but you are free to play how you want.
