### ISSUE TITLE
Railcraft ores only spawns in small areas

### ISSUE THREAD

**Issue by Jomosoto** [Railcraft/Railcraft#2012]
**Description of the Bug**
Railcraft ores only spawn in small areas. I looked for a long time for zinc and I looked with x-ray: In a map that is already hugely genrated, there is only a zone of some chunks that has railcraft ores.

**To Reproduce**
1. Start a new World with Railcraft and an x-ray mod.
2. Go in spectator, set the x-ray on zinc or tin.
3. Search in the deep for a long time, and find something like in the photos.

**Expected behavior**
Railcraft ores should be generated balanced all over the map

**Screenshots**
![Railcraft Zinc](https://user-images.githubusercontent.com/40580158/113991816-1c556c80-9853-11eb-8481-f5b80e3024a1.png)
![Railcraft Zinc 2](https://user-images.githubusercontent.com/40580158/113992476-cdf49d80-9853-11eb-9c98-922907426d23.png)

**Logs & Environment**
My logs, I don't know if it can help

Latest:
[latest.log](https://github.com/Railcraft/Railcraft/files/6277123/latest.log)

Debug:
[debug.log](https://github.com/Railcraft/Railcraft/files/6277125/debug.log)

**Comment by Ommina** [comment]
#1953, #1896, and almost certainly others.

**Comment by Jomosoto** [comment]
But isn't it a bit too rare? I searched a very long time in spectator. In survival it should be nearly impossible
