### ISSUE TITLE
FluidModelRenderer block state container churn

### ISSUE THREAD

**Issue by asiekierka** [Railcraft/Railcraft#2015]
**Description of the Bug**

The current FluidModelRenderer implementation creates [an ExtendedBlockState container on every renderFluid call](https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/client/render/models/resource/FluidModelRenderer.java#L86). This is incredibly sub-optimal - creating a new block state container is an expensive operation. To improve the situation, the ExtendedBlockState object should be cached, and the IExtendedBlockState grabbed from the cached ExtendedBlockState.

**Comment by CovertJaguar** [comment]
I don't really understand all the blockstate stuff, but maybe this is the fix you meant? I just made it static final.

**Comment by asiekierka** [comment]
This was a while ago...

I think I would have preferred it to be cached on first call, rather than on static initializer, but I *think* the renderer's static initializer won't be called before Blocks.WATER is initialized. Typically. The former would be safer IMO, but this is roughly what I meant.

Thank you!

**Comment by CovertJaguar** [comment]
Ah, didn't think about that, but it seems to work so I'm going to call it good for now.
