### ISSUE TITLE
Inventory mess when clicking on a Iron Tank Wall

### ISSUE THREAD

**Issue by ExDomino** [Railcraft/Railcraft#2018]
**Description of the Bug**
When you click on a Iron Tank Wall, your inventory is mess, you have items in your armors slots, in your crafting, some items in double, and you have to disconnect and reconnect again to fix the problem.

**To Reproduce**
Create a Iron Tank that is completely functionnal.
Click on every block that is a part of the multiblock structure.
See your inventory completely messed.

**Expected behavior**
Inventory is not messed.

**Screenshots & Video**
Before : https://ibb.co/7xhpKfW
After : https://ibb.co/1Z8CksH

**Logs & Environment**
There is no logs and no crash to submit.

**Additional context**
I posted two screenshots, one before and one after I clicked to the wall.
I'm using the latest version (12.0.0.0) of your mod, on Minecraft 1.12.2.
The Forge version is 2854.
I have Optifined installed client-side but not on the server.

**Comment by Ommina** [comment]
See #1961 (and others).
