### ISSUE TITLE
Very laggy, reports suggest railcraft.

### ISSUE THREAD

**Issue by Morthgal** [Railcraft/Railcraft#2019]
When joining a world, the world is incredibly laggy, a frame every few seconds. Having gone through all reports it appears to be a problem with railcraft, and having dug further into files etc, appears to have something to do with inventories(despite the fact we don't have any blocks or items with inventories in the world, at least to our knowledge). This issue appears to have been reported before and fixed, but the fix never pushed out, nor a quick fix that someone could implement. 

Link to previous report on the issue, as you can see it claims to have been fixed by people who have commented:
https://github.com/Railcraft/Railcraft/issues/1994

You would have to have our modpack and world file to replicate the exact problem, which i can provide if necessary, but the basics are that it is a 1.12.2 world, running Immersive Railroading and Railcraft, with other mods thrown in. The problem has apparently (according to our server manager) been around since the very start, but never seemed to be a problem, until recently.

Log of the issue:
https://pastebin.com/TfzEMx02

I would happily take a quick fix that could be implemented by us, as i understand that the developer(s) 1. have other projects, and 2. are busy with life elsewhere. Thank you for your time.

**Comment by Morthgal** [comment]
Having done some more testing recently, the problem appears to be the signal boxes, as we had recently massively increased the amount we have, causing the problems we had. I still don't know the exact problem with it, but at least it narrows it down to the signal boxes.

**Comment by CovertJaguar** [comment]
I don't know if I fixed this correctly, but I looked at how Forestry handled it and copied that.

I don't really understand the correct method of handling these objects, the ownership chain is obscenely complicated.

Maybe it's fixed though.
