### ISSUE TITLE
 it won't let me put the TBM

### ISSUE THREAD

**Issue by Palomero33** [Railcraft/Railcraft#2021]
sorry for the translator.
When I try to put the TBM on the tracks it won't let me, I put it on it disappears, then the item appears on the ground and every time I try it it doesn't work, I hope you will help me because I need the TBM urgently please.

**Comment by maleksware** [comment]
Possible duplicate of #2010, check it for now.

**Comment by maleksware** [comment]
This bug was fixed in #2024.
