### ISSUE TITLE
Configuration of steam production and consumption

### ISSUE THREAD

**Issue by Tyrrx** [Railcraft/Railcraft#2027]
The amount of steam produced by steam boilers is very hight compared to other mods that also utilize steam. This leads to a very unbalanced situation in a modpack (e.g. FTB Ultimate Reloaded).

I would recommend adding a configuration option where it is possible to change the steam output of a boiler. 
For example by adding an internal steam unit that defines the base production of steam und fuel usage just like it is now but add an output factor that defines the actual steam output. 
As this leads to an incompatibility with the own Railcraft machines that use steam I would also add an steam input factor for these machines. 

There is no alternative solution except for changing the other mods. I will create an issue there too.
My current solution for the problem is disabling the steam module which is not the desired way in my opinion.

**Comment by CovertJaguar** [comment]
I find this uninteresting. It reduces interesting complexity.

Steam to water is 1:160 ratio. In reality, this should be 1:1600. It was reduced by a factor of ten because of engine issues (no pipes that could handle such volumes).

Railcraft was first to bring forth steam. Changing the ratio breaks a lot of things. Would rather go the Ic2 route and rename my steam.

**Comment by Tyrrx** [comment]
Hi, no my idea was to add the possibility to change the production amount in order to achieve mod compatibility. For example by adding a new section to the config file. Not to change the existing ratio.

**Comment by CovertJaguar** [comment]
You mean change the fuel to steam ratio?

**Comment by Tyrrx** [comment]
Yes, but without applying changes to the current settings. That's in my opinion not necessary. Just moving the current hard-coded configurations to a user changeable settings file so that it is possible to chage the fuel to steam ratio. Assuming the ratio is a factor it would also be great beeing able to scale the max fuel input (e.g. to limit the max steam output).

I would have made a PR but I don't have enough time to look at the implementation details at the moment.

**Comment by CovertJaguar** [comment]
I thought I already had boiler multipliers in the config.
