### ISSUE TITLE
Turbine Blade Recipe 

### ISSUE THREAD

**Issue by munkey707** [Railcraft/Railcraft#2028]
**Description of the Bug**
The Turbine Recipe is suppose to be 3 steel Ingots but it said in minecraft i need 3 nickle plates for a blade i only got my first rotor

**To Reproduce**
<!-go to crafting the recipe said it need 3 nickle plates for blade which is nearly impossible to find
1. Place block/cart '...'
3. See '...'

**Expected behavior**
<!-> The recipe to be 3 Steel Ingots

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by CovertJaguar** [comment]
It was changed back in 2018 by Cody. Not sure I would have made the change, but I see nothing particularly wrong with it.

**Comment by CovertJaguar** [comment]
I think I'll add steel plates in addition to nickel and move it to the rolling machine.
