### ISSUE TITLE
All locomotives cause client problems on multiplayer server

### ISSUE THREAD

**Issue by KaelaniRevyruun** [Railcraft/Railcraft#2029]
**Description of the Bug**
Steam locomotive causes client crash loop, electric and creative cause disconnect loop

**To Reproduce**

1. Place block: Electric Rail (in my case)
2. Place Steam/Electric/Perpetuum locomotive
3. A: Steam Locomotive (Crash immediately)
3. B: Electric/Perpetuum Locomotive (Lag placing animation, immediate disconnect)
4. ???
5. Rage because the only way to fix it is to delete all entities on the server unless you know how to filter to a specific mod

**Expected behavior**
Locomotive to place and render on the track block

**Logs & Environment**

 - Full log: https://pastebin.com/D9hnz9iU (Not the entire log file, but file extends back before even trying to place the steam locomotive. Enclosed is /give command to take perpetuum locomotive from NEI to attempt to log back in after running command to delete entities from server via console <aka all relevant clientside information>)
 - Crash report (If available): https://pastebin.com/yf3MsL14

**Additional context**
Not sure if it's cos of specifically the rail block or something else; waila states that the rail block was "state_north" or something like that; either way, the "direction" for the rail was set as north.

**Comment by Ommina** [comment]
This _seems_ to be some sort of interaction with Chococraft.  On which side the error falls I'm really not able to speculate.

I'd try removing Chococraft (on a backup world!) as a test and see what happens.  If that resolves the error, you might see if the Chococraft devs have any ideas, as Railcraft remains pretty much out of steam at the moment.

**Comment by CovertJaguar** [comment]
Chococraft appears to have improperly created a DataSerializer with an improper key and added it to Locomotives?

I'm leaning towards a Chococraft bug.
