### ISSUE TITLE
Track Recipe Uncraftable 

### ISSUE THREAD

**Issue by Erosion139** [Railcraft/Railcraft#2034]
**Description of the Bug**
Tracks are not craftable on Forge 1.12.2-14.23.5.2860 Server (maybe other things too, locomotives are craftable)
Vanilla crafting tables show no recipe result.

Crafting recipe works on the client in a single-player world. The server however does not work. Will check out server exclusive mods installed. 
**To Reproduce**
Create a forge 1.12.2-2860 client and server
load only railcraft
The recipe for the standard track will show in single-player worlds, but will not show in multiplayer.

**Screenshots & Video**
https://youtu.be/h5ZkHAz5K3o

**Logs & Environment**
CLIENT
https://pastebin.ubuntu.com/p/ZjNVWD3cD5/
SERVER
https://pastebin.ubuntu.com/p/KYdbYtdCHH/

**Comment by Ommina** [comment]
This is a mismatch in recipes between the server and the client.  The recipes exist on the client, but not on the server.  Since the server is authoritative in these matters, it wins.

Ensure the recipes in your pack match.

**Comment by Erosion139** [comment]
> This is a mismatch in recipes between the server and the client. The recipes exist on the client, but not on the server. Since the server is authoritative in these matters, it wins.
> 
> Ensure the recipes in your pack match.

Hey could you point me to resources that could help me see what the server recipe is and perhaps be able to change it? I have updated my issue with the forge version, as I am sure this is not expected behavior. I also tested and reproduced the bug on the same modpack but with every other mod deleted. Also just came to mind I could have potentially changed a config in railcraft that changes the recipe. I will check this and get back to you.

**Comment by Erosion139** [comment]
Issue fixed by setting "use alternative track recipe" to false on the server, I had it set to true from an earlier annoyed client. You can find this config in 
Configs>Railcraft>Railcraft.cfg

**Comment by Ommina** [comment]
I'm *pretty sure* that CraftTweeker has a command to display a vanilla recipe, but honestly it's been a long while since I've poked at 1.12.2.

If you have changed a config, though, DO ensure that the config file also matches between server and client.  If you have a module disabled on the server, for example, but not on the client, you can see similar behaviour.

**Comment by Erosion139** [comment]
> Issue fixed by setting "use alternative track recipe" to false on the server, I had it set to true from an earlier annoyed client. You can find this config in Configs>Railcraft>Railcraft.cfg

Closed
