### ISSUE TITLE
the resources module loading error cause crash.

### ISSUE THREAD

**Issue by magcicada** [Railcraft/Railcraft#2039]
**Description of the Bug**
the resources module loading error cause crash.
the game will get crash at loading railcraft modules in stage 2.

this is the discord message: https://discord.com/channels/225184360049934336/225184360049934336/981135769689292800

**Comment by magcicada** [comment]
this is the full log just with jei and railcraft:
[latest.log](https://github.com/Railcraft/Railcraft/files/8804211/latest.log)

**Comment by ALJ323** [comment]
same crash here

**Comment by ArkenorOakshadow** [comment]
Also getting identical crash.

**Comment by Blarnix** [comment]
I am also getting this exact crash.

**Comment by CovertJaguar** [comment]
Fyi, it will not crash on Forge 14.23.5.2847 and earlier. But it should be fixed for next release.

**Comment by magcicada** [comment]
i use the forge version 2847 also get this crash, just look at the above log.

**Comment by CovertJaguar** [comment]
Maybe I meant 2846 and earlier.

Anyway, a fixed version is posted.
