### ISSUE TITLE
Strengthened glass multiblock access

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#2041]
**Description of the Bug**
Can't click strengthened glass to access tank multiblocks.

**To Reproduce**
Form an iron or steel multiblock tank, you can only click on all blocks but the strengthened glass to access the GUI - most likely due to the change in beta 1, I recall being able to click the old tank gauges!

**Expected behavior**
You can access the tank clicking on the glass.

**Logs & Environment**
Using 12.1.0-beta-2

**Comment by CovertJaguar** [comment]
Working as intended. It's just glass. Click a wall or valve.
