### ISSUE TITLE
weird coke oven fluid container behavior

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#2044]
Version: 12.1.0-beta-2

https://www.youtube.com/watch?v=4226N3kZiIE

Seems like the bucket successfully picks up the fluid for a second but puts it back into the coke oven internal tank right after. Not visible in the video but when the bucket gets briefly filled the tank does go down by 1000 mB as expected - issue is just that it returns the fluid right after!

**Comment by CovertJaguar** [comment]
Fixed by 7d6561493ded9c27cc2b3a0b63e65625cc59781e
