### ISSUE TITLE
boiler multiblock forming issue

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#2045]
Version: 12.1.0-beta-2

https://www.youtube.com/watch?v=a4ASJeH1N4w

Seems like a valid structure only forms if the blocks are placed in the right order. There is probably a lot more examples and edge cases but this issue seems to be at least one that's at the bottom of it.

**Comment by CovertJaguar** [comment]
I haven't ever seen this in my own testing.

**Comment by WarlordWossman** [comment]
Might have been fixed by the other commits related to fireboxes (?)

**Comment by WarlordWossman** [comment]
Still happening for me in beta 6, could it be that no block updates get send to the firebox? (just a random guess)
Wonder if another mod is causing this if you cannot reproduce in your dev environment.

**Comment by CovertJaguar** [comment]
What about chunk boundaries?

**Comment by CovertJaguar** [comment]
But yeah, it looks like a block change propagation issue.

**Comment by WarlordWossman** [comment]
> What about chunk boundaries?

Tested with some multiblock configurations that do not cross any chunk borders at all in beta 7 just now.
From what I can tell any boiler multiblock only starts looking for a valid structure when a block of either of the bottom 2 layers is placed. Any boiler tanks placed above other boiler tanks instead of the fireboxes means no multiblock forms even if the structure is valid.

**Comment by CovertJaguar** [comment]
I'll do some more tests when I next get a chance.

**Comment by CovertJaguar** [comment]
Okay, I have confirmed the issue.
