### ISSUE TITLE
Electric locomotive can't be dyed

### ISSUE THREAD

**Issue by ChuChu128** [Railcraft/Railcraft#2056]
**Description of the Bug**
There is no recipe to dye the electric locomotive. Moreover, when you craft it and you place the locomotive in a rail, it appears as double white color when it was yellow and black by default, if you break the locomotive now is pure white forever. I'm using the latest railcraft version (12.1.0-beta-7) but i tried it on the 12.0.0 release and doesn't work too.

**To Reproduce**
1. See the recipe in JEI, the recipe to paint it doesn't exist.
2. Try to do it anyways.
3. Doesn't work although the steam locomotive can be dyed.

**Screenshots**
![image](https://user-images.githubusercontent.com/108199418/175792115-863f321d-6ea8-42b1-a907-e4e9a5c7aebc.png)

**Comment by ChuChu128** [comment]
Ok, forget it, i tried it with only railrcaft installed and it works so its not railcraft fault, i'm sorry.

**Comment by CovertJaguar** [comment]
I wonder what kind of mod interaction could break that...

**Comment by ChuChu128** [comment]
Ok, i was searching and I found that the modpack I'm using (Tekxit 3.14) deletes the electric locomotive recipe and adds another recipe with another type of steel gear, but doing this deletes the paint recipe too so if someone uses tekxit 3.14 only need to go to scripts folder inside the modpack and comment the 2nd line "#recipes.remove(<railcraft:locomotive_electric>);" of "Recipe Fixes.zs". I'm sorry for not seeing this problem before posting an issue here.
