### ISSUE TITLE
[1.12.2] Incompatibility (crash) with Computronics

### ISSUE THREAD

**Issue by xJon** [Railcraft/Railcraft#2064]
**Description of the Bug**
Crash at launch

**To Reproduce**

1. Install [Computronics](https://wiki.vexatos.com/wiki:computronics)
2. Install Railcraft `12.1.0-beta-8`
3. Attempt to launch the game

**Logs & Environment**

 - Crash report (If available): https://pastebin.com/DbhLVwUX

**Comment by Forecaster** [comment]
I believe this is because you are using the wrong version of Computronics. You need a version of Compu for the beta version of railcraft. There is a message with a link to it in the Railcraft discord in the #general channel

**Comment by xJon** [comment]
@Forecaster Thanks for the info! I can't find it unfortunately.

**Comment by Forecaster** [comment]
Hm, the link in the message is broken anyway, and it's not the latest version, I have a more recent one.

If you ping me in the Railcraft discord I'll send you the latest one I have which should solve the issue

**Comment by Forecaster** [comment]
Actually never mind that, it's better to just link it here:

https://towerofawesome.org/files/Computronics-1.12.2-1.6.6.192-rc-beta-5.jar

**Comment by xJon** [comment]
Thank you :)
Would be nice to have it over https://wiki.vexatos.com/wiki:computronics as well if you know who to contact about that!

**Comment by xJon** [comment]
And nevertheless the warnings in chat from the beta version of Railcraft somewhat discouraged me enough to wait for a more stable release.

**Comment by Forecaster** [comment]
That would be Vexatos, but he probably wont want to post a beta version there

**Comment by Lukramancer** [comment]
Nowadays `Computronics-1.12.2-1.6.6.192-rc-beta-5.jar` doesn't work with Railcraft `12.1.0-beta-8`, but `Computronics-1.12.2-1.6.7-railcraft-beta-8.jar` does. I've found this version in [general](https://discord.com/channels/225184360049934336/225184360049934336/1151206083369644127) of official Railcraft's discord guild, thanks to [this message](https://discord.com/channels/225184360049934336/225184360049934336/1261787752437907567).

P.S. I'm posting this message for those who struggle with this incompatibility and found this issue as I did. You can download compatible version from the guild or try to find it on the net.

**Comment by xJon** [comment]
@Lukramancer It was built for Tekkit 2 by poking Vexatos enough, I've also recently asked for the source to be published (https://github.com/Vexatos/Computronics/tree/1.12-railcraft-beta-8) although building from source takes a bit of effort.
