### ISSUE TITLE
Glitched Item

### ISSUE THREAD

**Issue by PLPLUGIN** [Railcraft/Railcraft#2074]
**Description of the Bug**

There are glitched pants that you can get from railman villager (maxed out villager), when you put them on they crash your game when trying to take them off (you need to kill yourself to get them off). They have duplicate enchantments.

I've seen them in tekkit 2 modpack, it might be some mod compatibility issue.

**To Reproduce**

1. Find railman npc
2. Buy some stuff from him until he's max trades lvl
3. Buy glitched pants

**Expected behavior**

1. Finding railman npc
2. Buying some stuff from him until he's max trades lvl
3. Buying not glitched pants

**Screenshots & Video**

![unknown](https://user-images.githubusercontent.com/64206241/187459912-f9590e31-3663-4ac5-919b-6143663b139b.png)

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by Romz24** [comment]
My game does not crash, but residents sell broken pants. It seems that all possible enchantments exist on these pants.

![image](https://user-images.githubusercontent.com/2458113/187626446-2a24de62-08c6-44bf-a57c-7d5537c81007.png)
![image](https://user-images.githubusercontent.com/2458113/187627743-050b25b4-b752-4bbb-9a4a-9a26e644cbe3.png)

**Comment by djdubbs12** [comment]
please fix 
![image](https://user-images.githubusercontent.com/92045860/197404045-8fffc369-6898-4f1e-8964-53928b8a5863.png)

**Comment by xJon** [comment]
@PLPLUGIN Why did you close this issue?

**Comment by Romz24** [comment]
@PLPLUGIN This bug is still present in the mod
