### ISSUE TITLE
Ghost Carts (Is it a feature or a bug?)

### ISSUE THREAD

**Issue by unqmed** [Railcraft/Railcraft#2083]
![2022-10-23_17 01 53](https://user-images.githubusercontent.com/112613035/197377821-8fdf18a7-b41f-437b-a3cd-42b669ed0b7a.png)

(Restart Minecraft with the mod to see if the glitch works because locomotives has been affected by this mod which make sense)

I restarted Minecraft only to see that the carts and locomotives were half 'transparent'. It's weird and strange, I reset Minecraft on October 23. Or it could just be a feature for Halloween which could have freaked players out though.

Can you please fix this bug or have an option to toggle the feature?
Thanks

**Comment by Forecaster** [comment]
There are 10 (closed) issues that come up when you search for "ghost carts". Maybe that's a good place to start.
