### ISSUE TITLE
“Ghost Trains”

### ISSUE THREAD

**Issue by csm550d** [Railcraft/Railcraft#2085]
okay I just found out this is a Halloween Feature, I’ve been bamboozled and I love it.

Hey, I use Railcraft 12.0.0 and my trains look like this. Pic 1 with Shader, Pic 2 without.
![CF0A9692-8CB1-41F3-A156-298DBD5ED0CE](https://user-images.githubusercontent.com/116508353/197404210-c7f4b9b2-cf17-4a91-91bb-6c5a2090e995.jpeg)

![024EB715-5EAC-4AFB-B3F2-9A3FFEEC81F3](https://user-images.githubusercontent.com/116508353/197404201-c7f6dee3-cfc9-4086-985a-c532884ad4d5.jpeg)

They work just fine but the textures are weird - I started to think that other mods might be interfering but just with Optifine installed, this problem occurs.

**Comment by Forecaster** [comment]
There are 11 (closed) issues that come up when you search for "ghost carts". Maybe that's a good place to start.
