### ISSUE TITLE
GTCE Incompatability

### ISSUE THREAD

**Issue by jackisgood99** [Railcraft/Railcraft#2090]
**Description of the bug**
I am unsure if this is due to railcraft or or gregtech but they appear to have issues being installs together i would guess its railcraft because it works fine on the stable build of railcraft

**To Reproduce**
1. install Railcraft 12.1.0-beta-8
2. install Gregtech community edition

**Expected behavior**
crash when finish first mod initialization phase in forge loading window

**Screenshots & Video**
it just closes

**Logs & Environment**
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

**Additional context**
im mostly sure it is gregtech because when its removed everything works unless its an incompatibility with it along with another mod and then railcraft

**Comment by alwaeles** [comment]
This crash is completely unrelated to Railcraft. You've installed enough mods to reach the technical limit of IDs in Minecraft. There's some mods that can raise the limit but it's your own risk.

**Comment by jackisgood99** [comment]
> This crash is completely unrelated to Railcraft. You've installed enough mods to reach the technical limit of IDs in Minecraft. There's some mods that can raise the limit but it's your own risk.

how many more ID's does beta railcraft use then because i can install many other mods then just updating railcraft and dont hit the limit
