### ISSUE TITLE
[1.20.1] Incompatible with Better Furnaces

### ISSUE THREAD

**Issue by FrozenGalaxy** [Railcraft/Railcraft#2116]
See for log: https://github.com/Wilyicaro/BetterFurnacesReforged/issues/152#issuecomment-1945242610

Seems to error out on placing the furnace.

**Comment by FrozenGalaxy** [comment]
Thanks for the fix, you should update the issues link on curseforge i didnt even realise this is the old git repo

**Comment by Edivad99** [comment]
The link is already right
