### ISSUE TITLE
Incomplete vanilla cart replacement

### ISSUE THREAD

**Issue by octarine-noise** [Railcraft/Railcraft#220]
Vanilla minecarts are only replaced with Railcraft ones on chunkload, but not when first placed down in the world. This causes a problem with the tunnel bore and connected chest carts, since the vanilla carts do not transfer items.

Railcraft 9.0.0.0 + Forge 10.12.1.1098

**Comment by kremsy** [comment]
@CovertJaguar i still have this bug in railcraft version 9.5, is there anyway to solve it?

**Comment by CovertJaguar** [comment]
@kremsy does relogging fix it? Does it work with just Railcraft? Does replacing the Cart fix it?

**Comment by kremsy** [comment]
Reloggin fixed it, thank you!!

**Comment by MexWolf** [comment]
still waiting, but now we have cargo cart, but undercutter still can't pull items from it

**Comment by liach** [comment]
that's irrelevant. open a new issue.
