### ISSUE TITLE
Update water tank recipe

### ISSUE THREAD

**Issue by Forecaster** [Railcraft/Railcraft#308]
I suggest replacing the planks in the water tank recipe with creosote blocks and removing the slime ball.

That is all.

(Possibly re-balance the output amount?)

**Comment by Generalcamo** [comment]
This was mentioned over a year ago, but I countered with an actual wooden water pipe:
http://www.blackdiamondnow.net/.a/6a00e5513924e68833019affdb8ac0970b-pi
