### ISSUE TITLE
Investigate Entity AI of Minecart Riding Entities for Issues

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#316]
As demonstrated in the following video, apparently non-player entities riding minecarts can now move the minecart randomly while doing so. They can do this even against the pull of a Locomotive.

https://www.youtube.com/watch?v=qiFSU6qnrag

**Comment by CovertJaguar** [comment]
Well first attempt is only partially successful. I disabled the AI tasks when riding, which works, pigs don't follow carrots anymore. However it doesn't seem to have stopped random wandering and running when hurt.

**Comment by CovertJaguar** [comment]
I don't actually know which code has authority over ridden entity control translation. Kind of hard to fix without knowing that.

**Comment by Ristellise** [comment]
damn should have reimplemented the pigs following carrots... i could have amde a nice minigame :P

**Comment by liach** [comment]
I think you should work on minecart instead of entity ai code.

**Comment by CovertJaguar** [comment]
Nothing I can do unless I can find what is modifying the motion vector.

**Comment by liach** [comment]
Isn't this fixed?

**Comment by CovertJaguar** [comment]
Not completely. Random wandering still causes carts to move.

**Comment by liach** [comment]
@CovertJaguar So what do we do on this?

**Comment by CovertJaguar** [comment]
Nothing, unless you want to dig into the entity movement code.

**Comment by liach** [comment]
The code is in `EntityMinecart#update` block, which we have little control over. Thus, we cannot really fix this.

**Comment by liach** [comment]
By the way https://github.com/MinecraftForge/MinecraftForge/pull/4665 may fix this issue once accepted.

**Comment by liach** [comment]
Now by overriding a method, I think I managed to fix this issue. Will push soon

**Comment by liach** [comment]
It is fixed; a pig can no longer pull a creative locomotive.
