### ISSUE TITLE
Track Relayer and Undercutter Carts dont push/pull items from chest carts

### ISSUE THREAD

**Issue by Gaunt596** [Railcraft/Railcraft#344]
with the Track Relayer, Instead of pulling up the old track and depositing it in the linked chest cart, it spews it all over the place around the cart, and when it runs out of replacement rails, it simply stops replacing them and dosent pull new rails from the linked chest cart. The undercutter has a similar behavior, not placing the cut blocks in the linked chest cart and not pulling replacement blocks from the chest cart when it internal inventory depletes.

**Comment by MexWolf** [comment]
but still relevant
