### ISSUE TITLE
When tanks are filled with gasses, they should fill up as a gas would.

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#412]
Currently, gasses like steam currently fill up a tank like any other liquid would, which is not very realistic. What if they filled tanks up like they fill up tanks in Thermal Expansion and Xycraft? Filling up the entire tank, but just changing the opacity of the texture?

**Comment by CovertJaguar** [comment]
How does one determine something is a gas from the Fluid object?

**Comment by AEnterprise** [comment]
i think it's negative dencity or so

**Comment by Vexatos** [comment]
negative density just means it flows upwards. `isGaseous` checks for gases.

**Comment by CovertJaguar** [comment]
This should be fixed by 0979a0930b76b6881e09cbfc6431df39cf134c77
