### ISSUE TITLE
Add Bronze bore head

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#423]
Even through Tunnel Bore is pre-Wither, but I think that Railcraft had better include Thaumium Bore Head and enchantments.

**Comment by choncho** [comment]
@liach no because Thaumiumcraft is more beginner friendly

**Comment by liach** [comment]
@choncho No, I just think there'll be bore head made of void metal or something else, which can get better enchantment or special usages.

**Comment by MrCalhoun** [comment]
Are there plans to overhaul the tunnel bore? I got some suggestions :)

The bore head should be able enchanted. Maybe unbreaking, efficient and some customs?

**Comment by liach** [comment]
@CovertJaguar How about an invar bore head?

**Comment by bookerthegeek** [comment]
Why not just dynamicaly create birr heads from any material that has an ingot? Set the harvest level to match whatever a pickaxe of the same material would have.

**Comment by liach** [comment]
no... they might be only made of hard materials

**Comment by liach** [comment]
Hmm will consider thaumcraft only later.

**Comment by CovertJaguar** [comment]
Seems like a strange use for Invar. Nickel-Steel probably flakes too much to be useful on Bores (and too expensive) irl. But I suppose we could add one anyway.

**Comment by Generalcamo** [comment]
It was probably suggested due to the occurrence of Invar tools in other mods (Substratum/Foundry and Thermal Expansion come to mind). That said, I feel the difference between the three heads is pronounced as-is.

**Comment by liach** [comment]
@Generalcamo You work on this since you added metals.

**Comment by Generalcamo** [comment]
There are no metals to add currently, until Thaumcraft 6 is released.

**Comment by liach** [comment]
You said you wanted to add invar bores.

**Comment by Generalcamo** [comment]
I never said that. I said they make no sense.

**Comment by Generalcamo** [comment]
After some thought: Bronze Heads might make sense. Would be pretty much the same as Iron but with a different color.

I can do art on Void Metal and Thaumium Heads too while I am at it.

**Comment by liach** [comment]
Bronze may have a lower durability, I think.

**Comment by Generalcamo** [comment]
Definitely not. Bronze is equivalent to iron in strength, actually better in the ways that are relevant here.

**Comment by liach** [comment]
So make them the same. Yay!
