### ISSUE TITLE
Crossing Arms

### ISSUE THREAD

**Issue by kwstoudt** [Railcraft/Railcraft#426]
Just a suggestion for a new feature. It would be cool to have like a crossing arm that goes down (blocking a road) when a train approaches and back up after it has passed.

**Comment by Opiboble** [comment]
Would love this! plenty of walkways cross my tracks and people keep getting killed :/

**Comment by Thorn799** [comment]
I think this is a good idea as well.

**Comment by iceman11a** [comment]
This all ready has been added in a new mod called Fuelcraft. I will be adding this mod to curseforge as seen as they can fix my account

**Comment by CovertJaguar** [comment]
I believe this has been done in a Railcraft compatible manner already in one of the addon mods.
