### ISSUE TITLE
RC config setting breaks NEI

### ISSUE THREAD

**Issue by PitchBright** [Railcraft/Railcraft#440]
Railcraft_1.7.10-9.4.0.0
NotEnoughItems-1.7.10-1.0.3.74-universal
CodeChickenCore-1.7.10-1.0.4.29-universal

NEI Menu won't appear when pressing "O" key… and Recipes won't show when pressing "R" key.

Error on world load seen in Game Output log: http://pastebin.com/v7egXPkK

Problem has been isolated to Railcraft module.cfg… when:
    B:tracks.highspeed=false
or
    B:tracks.wood=false

**Comment by PitchBright** [comment]
This bug still exists, and affects the Search Tab in Creative Mode, even without NEI.

**Comment by CovertJaguar** [comment]
@PitchBright  The bug you describe in the other issue is not the same as the one posted here.

**Comment by PitchBright** [comment]
@CovertJaguar Oh okay. My bad. Thanks for looking into it!
