### ISSUE TITLE
Add Token Signals

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#455]
Token Signals are based on radio token routing.

http://en.wikipedia.org/wiki/Radio_Electronic_Token_Block

> Developments in electronic systems have led to the development of electronic token systems. Trains are able to run over consecutive single-track sections, with the whole operation being controlled from a single central control room. Every train carries a special electronic unit that receives and sends an encrypted block of data which represents the token. The system is designed such that the control centre can only issue one token for any particular section until it is returned. Trains cannot send tokens to each other. This system allows the whole line to operate without any further signalling personnel. The system has operated without major incident.

You define an area covered by a token, and when a Train enters this area it is given a token. So long as something "owns" this token, no other Train can enter the defined area. Leaving the area releases the token.

This concept could be adapted to a new type of Signal Block called a Token Signal. You would be able to pair a collection of Token Signals together to define the boundary of a Token Area. This could allow for simple Grand Junction creation and even work on diagonal Tracks as the system does not rely on active detection of entities.

**Comment by Forecaster** [comment]
I approve! Would definitely be useful to cover intersections and similar with one big area instead of multiple signal blocks, greatly simplifying the logic required!

**Comment by ssotangkur** [comment]
In terms of game mechanics, how would a loco know that it has the token? Would it be more like an interlock/detector box that can power a locking track directly?

**Comment by CovertJaguar** [comment]
Similar to how a Train knows that it's being locked I suppose. Locomotives hook into the Train object to and inspect the list of tracks locking the Train, the same concept could be applied to Tokens. Though I haven't decided yet how to prevent trains from the entering the block, whether you will need a track or if it "just knows".

**Comment by Forecaster** [comment]
I'd say a track. Otherwise the trains might not stop where you want them to, or in some cases you might not want a certain line to stop even if it crosses into the token area.

**Comment by CovertJaguar** [comment]
Why would you put a  Token Signal (the boundary markers) on a line that doesn't obey the token system?

**Comment by Forecaster** [comment]
I dunno, it was just a random thing that popped into my head. My point is that it allows for the most control.

**Comment by ssotangkur** [comment]
To answer CJ's question. It might make sense in situations where you're using overpasses  to direct through traffic and keep the intersection for turning traffic. The overpasses would surround the intersection and the trains waiting to turn would need to queue up outside the overpasses. In this case it would make sense to have the token signals covering just the intersection w/o the overpasses and the locking tracks would remain outside the overpasses. This keeps trains waiting for the intersection from changing the signal aspect of the signal blocks of the overpasses.

**Comment by CovertJaguar** [comment]
Just to clarify, the system would know nothing about random trains entering the area by un-gated tracks. There is no wide area entity detection involved. All the system knows is whether a Train has the token, or the token is free. The Signals merely mark the points where a token is either handed out or retrieved.

**Comment by Forecaster** [comment]
Oh, then I misunderstood the concept completely. I thought you'd mark a square where trains that entered would receive the token...

**Comment by liach** [comment]
fixed!
