### ISSUE TITLE
[Feature Request] Warded Jar Carts

### ISSUE THREAD

**Issue by bculkin2442** [Railcraft/Railcraft#532]
Some kind of cart that could transport thaumcraft essential would be nice.

**Comment by liach** [comment]
hungry chest carts as well

**Comment by bculkin2442** [comment]
That'd be something I'd say would probably go best as some kind of rail that fills carts with inventories. Vacuum rail maybe?

**Comment by liach** [comment]
You can put a lot of cart loaders above the track or advanced loaders beside the track.

**Comment by bculkin2442** [comment]
What I thought you were thinking of was something like a vacuum hopper in a cart. I suppose I may have misunderstood.

**Comment by ssotangkur** [comment]
Could you use a chest cart and fill it with warded jars?

**Comment by bculkin2442** [comment]
You could, but you'd need something to place/break the jars, and that's kind of hard to automate still. Also, it wouldn't look as cool :P

**Comment by ssotangkur** [comment]
Are you thinking along the lines of a tank cart that can hold a single type of essentia? It might be easy to allow essentia to work with tank carts and fluid loaders/unloaders code-wise, but gameplay-wise making the connections to a "suction based network" and being able to hold essentia without quicksilver or making stuff on the arcane worktable seems a bit odd. So to really fit in, you'd want to have a special thaumcraft version of carts, loaders, unloaders.

**Comment by liach** [comment]
killing this because thaumcraft has an unclear future.

**Comment by liach** [comment]
Respawning this since thaumcraft revived in 1.12, although I do not know if warded jars are still here.

**Comment by liach** [comment]
https://www.patreon.com/posts/sad-farewell-23967282

**Comment by Voxel-Friend** [comment]
This should be reopened, as thaumcraft is not dead after all, but rather going to be maintained, refactored, and updated to later MC versions by kinglemming and a team led by him and azanor (keeping creative direction). Same goes for other TC compat.

**Comment by liach** [comment]
At least this is not the case for minecraft 1.12.2, as kinglemming said he will port thaumcraft 6 to mc 1.13.

If you have any proof, please link.

**Comment by Voxel-Friend** [comment]
No you are correct that he will not work too much on 1.12.2, just hoped that these feature requests won't disappear into the void.

**Comment by CovertJaguar** [comment]
Honestly, me and KL have a bit of history and its not great. We'll just have to wait and see for now.

At the very least I'd like to see a better focus on the API than we've seen from Azanor so far.
