### ISSUE TITLE
Anchor GUI accepted fuels display does not reflect config

### ISSUE THREAD

**Issue by leagris** [Railcraft/Railcraft#615]
Anchor GUIs always display `Ender Pearl` ignoring whatever is configured as fuels.

Accepted fuels shall be displayed as configured in `railcraft.cfg`:

``` yaml
S:passive.fuel= minecraft:ender_pearl=12, minecraft:coal#0=4
S:personal.fuel= minecraft:ender_pearl=12, minecraft:coal#0=4
S:world.fuel= minecraft:ender_pearl=12, minecraft:coal#0=4
```

Given there my be several configured fuel types and required quantities:
Item icons followed by name and quantity could timely rotate as with recipe guides from NEI.

**Comment by liach** [comment]
https://github.com/CovertJaguar/Railcraft-Localization/blob/master/assets/railcraft/lang/en_US.lang#L285

Funny right?

**Comment by CovertJaguar** [comment]
If someone wants write the code to make that happen, they are more than welcome to do so.
