### ISSUE TITLE
Jukebox Cart

### ISSUE THREAD

**Issue by supergameplayer** [Railcraft/Railcraft#633]
This is simply a minecart with a jukebox, great for listening to music on the go.

**Comment by Forecaster** [comment]
Minecraft's sound system doesn't allow for this in a nice way. Sounds play at a set position and cannot move.

**Comment by CovertJaguar** [comment]
It "might" be possible. But the only options are ugly hacks (playing single notes at a time) or rewriting the entity sound tracker to support multiple types of sound (track+music). Neither are very appealing to me.

**Comment by liach** [comment]
I think I can try this.

**Comment by CovertJaguar** [comment]
I might be possible these days. MovingSound.java is far more robust than it used to be.

If you figure it out, apply it to whistles too.

I started an attempt with MinecartSound.java in client/utils/sound, but its incomplete.
https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/client/util/sounds/MinecartSound.java

**Comment by liach** [comment]
Yes, I figured out we can play the sound when the cart is spawned (from events)

**Comment by liach** [comment]
Not really from events... The sounds are from packets instead.
