### ISSUE TITLE
[Suggestion] Void Chest cart

### ISSUE THREAD

**Issue by MrCalhoun** [Railcraft/Railcraft#645]
The Void Chest Cart is the latest product from our guys in the Void Tech lab of the Railcraft, Inc.
It has the same functionality as the Void Chest except for one detail: 

It's in a cart!

It's very useful if you are digging long shafts with your Tunnel Bore and you don't need all that ores and stones.
Also it could be the last cart of your Tunnel Bore train. Once your Tunnel Bore's added chests carts are full all the other stuff simply vanishes!
Honestly, who didn't want a portable Void Chest Cart? 

Your coworkers are annoying? Put them in the cart!
You don't like the new pet of your (girl-)friend? Put it in the cart!
You want to put a Void Chest into a Void Chest Cart? Put it in the cart!

(Railcraft, Inc. is not responsible for any missing persons, items and creating wormholes)

The guys from the Void Tech lab announced some new, big and unseen device. But since the announcement the lab simply vanished.

(Recipe: Cart+Void Chest | Wiki article: see above)

**Comment by Vexatos** [comment]
:+1: This actually is a really pretty good idea.

**Comment by liach** [comment]
Metal chest cart...

**Comment by MrCalhoun** [comment]
@liach Please write what you think and don't refer to other suggestions that were declined.
The main reason is that not everybody read 21 site of closed issues/suggestions and 4 of open issues/suggestions. So I did it :)

The reason why I see no problem with that: The void chest is actually a development of CJ.
If he declined that idea he will also lost a nearly finished wiki article :P

**Comment by liach** [comment]
Nope, I think metal chest is so similar to void chest that I related them together. Void chest cart could be a remote trashcan. The metal chest cart is not a rejected idea. It's a quite new one. I support your idea. Sorry.

**Comment by MrCalhoun** [comment]
@liach Maybe that what I wrote was a little bit rude. I'm sorry. I thought that I read an suggestion about the metal chest but I think I misread. I also mixed up the Metal Chest with the Iron Chest addon (https://github.com/CovertJaguar/Railcraft/issues/362).

So I'm sorry. Let's get back to topic about a brand new Void Chest Cart :)

**Comment by liach** [comment]
Aye, although this is extremely easy to implement, we need to wait till multiblocks are back.

**Comment by liach** [comment]
@Generalcamo We should add a filter to the void chest cart.

**Comment by Generalcamo** [comment]
@liach Not unless we add filters to the void chest.

**Comment by liach** [comment]
Add a filter to the void chest and its logic then :smile:

**Comment by liach** [comment]
I am adding the metals chest cart too.

**Comment by liach** [comment]
Both void and metals chest carts are added.
