### ISSUE TITLE
[Suggestion] Colourizable smokers

### ISSUE THREAD

**Issue by marcin212** [Railcraft/Railcraft#656]
How about adding an option to the smokers that would enable changing the smoke color? Like, right-clicking with a dye, or having a dye somewhere in the crafting recipe? Not all smoke is black :)

**Comment by liach** [comment]
@CovertJaguar @Generalcamo I think we can address this right now.

**Comment by Generalcamo** [comment]
I was considering adding a Steamer block which would have different particle effects. Those could be colourable too though I guess.

**Comment by liach** [comment]
@Generalcamo You should move steamer to a separate block. I will work on this.
