### ISSUE TITLE
Locomotive glitching

### ISSUE THREAD

**Issue by tebruuls** [Railcraft/Railcraft#657]
I made a train system on my server and it is working well, mostly. When a train enters a station, a locomotive track puts it in shutdown. Control tracks handle it in the station, but it needs to heat up when it leaves. Sometimes when it starts after hearing up it switches direction. Any way to avoid this or is it a bug?

**Comment by Forecaster** [comment]
It is likely due to minecraft entity glitchyness.

You may want to hold the train for a set time while it heats up, then launch it in the intended direction once it's ready.

**Comment by liach** [comment]
Moved to #1460
