### ISSUE TITLE
Tunnel Bore infinite gravel placement bug

### ISSUE THREAD

**Issue by EntropicPariah** [Railcraft/Railcraft#664]
I encountered a weird bug with the tunnel bore last night as it punched through an abandoned mineshaft. It stopped above a gap and started to drop gravel but somehow it got stuck in a cobweb directly underneath and instead of piling up, passing through or breaking the gravel stayed within the cobweb. I don't know how, but as each new gravel block fell, it overlapped the one stuck in the cobweb and the tunnel bore continued to feed it out until I switched into creative and broke the cobweb.

Wish I'd thought to get a screenshot but all I have is this description.

**Comment by liach** [comment]
It happens when the bore tries to place a gravel above a flower or something like that.

**Comment by liach** [comment]
@CovertJaguar Do we add a max placement number like the detected height? Once it exceeds that it stops placing.

**Comment by CovertJaguar** [comment]
I'd probably just modify the scanning function that determines if its a fillable hole to be aware of these blocks and either block progress or remove the troublesome blocks.

**Comment by liach** [comment]
How about we add a water slot and let it use water to wash first before placing?

**Comment by CovertJaguar** [comment]
That seems needlessly complicated.
