### ISSUE TITLE
BioDiesel support from Immersive Engineering

### ISSUE THREAD

**Issue by danielkanjo** [Railcraft/Railcraft#706]
my question is there is a possible way to feed liquid fueled boiler with biodiesel from immersive engineering ? it would be awesome to be possible :)

**Comment by bakaxyf** [comment]
https://github.com/CovertJaguar/Railcraft/issues/662

**Comment by liach** [comment]
IE bug and it should add requirement to load before Railcraft.

**Comment by CovertJaguar** [comment]
The best way to register it is via the InterModComs on IE's end. But if someone wants to give me some balanced values I don't mind adding it on my end.

**Comment by Vexatos** [comment]
Having @BluSunrize here might be helpful...

**Comment by BluSunrize** [comment]
Yeah, always great to tag me on stuff like that.
Technically, diesel is designed to ignite under high compression in a diesel engine, but sure, if Covert wants to add it, the fluid name is "biodiesel"

**Comment by liach** [comment]
I will just add this to fluid fuel manager.

**Comment by liach** [comment]
@malte0811 How does ie register fluid fuels to other mods?

**Comment by liach** [comment]
Fixed by #1688
