### ISSUE TITLE
Option To Toggle Bottom Valve Auto Extract On and Off

### ISSUE THREAD

**Issue by mikeloeven** [Railcraft/Railcraft#735]
Valves on the bottom of a rail craft tank will push out fluid regardless of the state of conduits attached to them. please add an option to disable this behavior in the tank GUI so that the bottom valves can extracted from on demand but not flood the system. I get it gravity is a thing but generally a valve can be turned on and off  as needed

**Comment by CovertJaguar** [comment]
Valves on lowest side layer have the behavior you desire.

**Comment by mikeloeven** [comment]
I understand this however simply for more granular control over the system it would be nice to see this behavior toggle-able as having the behavior of the valve totally dependent on position provides limitations on how a system can be configured

**Comment by liach** [comment]
@CovertJaguar I do not think this is the case any more

**Comment by liach** [comment]
@Generalcamo Can you test this issue to see if this is still the case?

**Comment by liach** [comment]
This issue itself is not important, but fluid lighter than air is real.
