### ISSUE TITLE
redstone support for rockcrusher

### ISSUE THREAD

**Issue by gitishi** [Railcraft/Railcraft#760]
so you don't have to break the multi-block when u building above it and u don't wanna lose any items in the process

**Comment by liach** [comment]
Just cut the power of the rock crusher. When it does not have any power, it will no longer crush items.

**Comment by gitishi** [comment]
16k rf internal buffer

**Comment by Yopu** [comment]
At current you can use buildcraft gates to pause the work.

**Comment by gitishi** [comment]
yeah that works. I did not know about this "gates.action.pause" function.

**Comment by Generalcamo** [comment]
With the buffer removed, you can now just cut off the cable as originally suggested.
