### ISSUE TITLE
Additional filters

### ISSUE THREAD

**Issue by Acerixx** [Railcraft/Railcraft#761]
Additional filters for the Advanced Item Loader:
- Whitelist/blacklist
- metadata on/off
- nbt on/off
- ore dictionary on/off

Edit. Adv Item Unloader and Cargo Cart too.

**Comment by Landrash** [comment]
A different option would be a loader that exposes the carts inventory as a inventory so you could use any other mods filtering options and item transportations.

**Comment by CovertJaguar** [comment]
I like what @Landrash suggested. It has been brought up before.

**Comment by Generalcamo** [comment]
Mostly implemented by ec9c7c9f3305aa77e2f666b3990a2d9ecfa96fa4

Rest was implemented by b04cec67f3204c5533bdfd236c51163e55a09da5
