### ISSUE TITLE
Rock Crusher damages you even if you're not on top of it, destroys items dropped next to it

### ISSUE THREAD

**Issue by McFrugal** [Railcraft/Railcraft#771]
This is for railcraft_1.7.10-9.8.0.0

Okay, first off, if you stand on a block next to the Rock Crusher so that your eyelevel is above the rock crusher, it will damage you if you simply bump into the thing.  I believe this damage is, or used to be instant death, so this is SOMEWHAT unreasonable.  I'm using it with tfc so it doesn't instantly kill me even if I stand on it.
Secondly, I had an engine attached to the upper layer, on the side.  I broke that engine, and it was destroyed, because I assume the dropped item rubbed up against the corner of the machine.

So, I'm guessing that the hitbox for determining if things are destroyed/damaged is a little too generous, and should be made smaller.  Safe use of the machine should not outright require putting blocks on top of it!

A texture change for the top of the rock crusher would be good too, to serve as a visual warning that there's a pit of grinding teeth in there, not just... flat black.
Or maybe get rid of this mechanic altogether?  It's a machine with a UI, why do things need to drop into it at all?

**Comment by Forecaster** [comment]
It was requested long ago. Why don't you want to put blocks over it? Seems like a minor issue.
