### ISSUE TITLE
Enhancement: Sleeper Cart

### ISSUE THREAD

**Issue by blaklafter** [Railcraft/Railcraft#779]
A minecart, which behaves exactly like the standard minecart (you can ride in it), only when it is night, it qualifies as a bed and it doesn't set your spawn.

**Comment by liach** [comment]
I'd not name it sleeper, for sleeper means railroad ties in British English.

**Comment by liach** [comment]
It turns out that this cart needs a lot of hack, but I've at least done most part of it.

**Comment by liach** [comment]
@CovertJaguar Can you decide how should player sleep and leave the bed?

**Comment by liach** [comment]
Should I use a carpet for the bed, I wonder?

**Comment by liach** [comment]
Will close this one for now as it is already in code.
