### ISSUE TITLE
Things to test for returning stuff

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#780]
This is mostly to serve as a reminder to myself, but if others want to help out that would be awesome too.
- [x] Test [PowerPlugin](https://github.com/Railcraft/Railcraft/blob/liach-1.12.2/src/main/java/mods/railcraft/common/plugins/forge/PowerPlugin.java) to ensure proper redstone behavior, especially with regards to redstone wire.
- [x] Test [HarvestPlugin](https://github.com/Railcraft/Railcraft/blob/liach-1.12.2/src/main/java/mods/railcraft/common/plugins/forge/HarvestPlugin.java) Behavior/Fix Forge Tool code.
- [x] ~Investigate RollingMachine support for IRecipe.getRemainingItems()~ Edit: Use a new interface for rolling machine recipes since rolling machines should not have remaining items, etc.
- [x] Test Loot Code
- [ ] Test Post connections with Signs
- [x] Test inventory management extensively on all three types of Inventories (IInventory, ISidedInventory, and IItemHandler)
- [ ] Investigate ILockableContainer // liach: like items with tags as keys for chests
- [ ] Investigate IInteractionObject
- [ ] Check Stone Lantern textures
- [x] Test Rock Crusher recipes // liach: large works now

Edit: liach's comments and fixed links, checkmarks

**Comment by liach** [comment]
Actually I think that you should just bump to MC 1.9 since forge for 1.9 will come out soon.

**Comment by liach** [comment]
@CovertJaguar Is railcraft going to be 1.11?

**Comment by liach** [comment]
I think harvest and power plugins work fairly well now. Post connections need some test though.

**Comment by liach** [comment]
A few things not tested are not that crucial because they are related to post connections and such. Moving this to the next milestone.

**Comment by CovertJaguar** [comment]
This is mostly outdated, and what is left is known to need work anyway or not really relevant.
