### ISSUE TITLE
[Suggestion] Provide specific tuning to RF generation on steam engines

### ISSUE THREAD

**Issue by DoragonKeiyou** [Railcraft/Railcraft#824]
In the configs, can you add a few lines that help define how much RF/t each of the steam engines can output?  Trying to help balance it against other RF generators from various mods.  Thanks.

**Comment by Generalcamo** [comment]
See #1203, this might be changed and/or closed.

**Comment by liach** [comment]
Just change it to FE for now.

**Comment by CovertJaguar** [comment]
No point in changing to FU if we are just going to remove it all anyway.

**Comment by liach** [comment]
So engines are planned to get removed?

**Comment by Generalcamo** [comment]
This is to be discussed as seen in the checklist in #1203

**Comment by liach** [comment]
@Generalcamo This is not related to #1203 if you change the energy unit, etc.

**Comment by Generalcamo** [comment]
Two options for the engines: Remove or port to MJ. Both of which obsoletes this.
