### ISSUE TITLE
Attempting to complete pairing with an anchor/sentinel which no longer exists does not cause an error

### ISSUE THREAD

**Issue by JLambeth** [Railcraft/Railcraft#847]
This is probably a low priority bug, given that there are two workarounds, but I thought it worth posting anyway (and I didn't see an existing bug report).

Basically, if you're trying to pair an anchor with a sentinel, and you destroy the anchor/sentinel that you BEGAN the pairing process with, you cannot complete or cancel the pairing process. Once this occurs, you cannot begin pairing on a new anchor/sentinel\* (*see workarounds).

In my opinion, if you try to complete pairing on an anchor/sentinel which no longer exists, you should receive an error to the effect of "the pair's origin no longer exists," and pairing should be cancelled allowing you to start the pairing process again. 

Minecraft: 1.7.10
Forge: 10.13.4.1614
Railcraft: 9.12.2

Here's a video:
https://youtu.be/j62CTe4fJUk

Reproduction steps:
1. Place an anchor and a sentinel anywhere in the world
2. While holding a crowbar, right click the sentinel to begin pairing
3. Destroy the sentinel
4. While holding a crowbar, right click the anchor -- normally this would produce some kind of message, but if a sentinel doesn't exist at the sentinel's original set coordinates, nothing happens
5. Create another sentinel (at a different set of coordinates)
6. While holding a crowbar, right click the sentinel to begin pairing -- in this case, you receive no error message, and you have no way\* (see workarounds) to pair the new sentinel with the anchor

Workaround:
- Logout of the server, or end single player game. Log back in, and re-pair; OR
- Place an anchor/sentinel at the original set of coordinates, complete pairing (either by pairing or cancelling) and destroy the anchor/sentinel

**Comment by CovertJaguar** [comment]
Confirmed.

**Comment by liach** [comment]
I will test this in Railcraft 10.2 betas.
