### ISSUE TITLE
Locomotive getting stuck because of Locking Track/Fluid Unloader combo

### ISSUE THREAD

**Issue by craft90** [Railcraft/Railcraft#848]
So I already reported this regarding the vanilla furnace carts but it seems this bug also affects Locomotives. I placed a Locking track onto a Fluid Unloader with the intention of emptying tank carts. The locking Track keeps it in place, fluid unloads and it gives it a boost away. Now for some reason the Locking track also locks the Locomotive in place and I need to give it a manual redstone signal to release it. Sure Locomotives contains liquid but it doesn't seem intended. Nor does the Liquid Unloader receive any liquid. Which means it should give a redstone signal to release the Locomotive but for some reason the Locking track doesn't react.

Maybe I'm doing something wrong? Is there another way to do what I hope to do? Without those Locking tracks tho the tank will just zoom over and releasing just a tiny bit of liquid.

EDIT: Found the issue. The Unloader was set to Hold Until Empty. Changing it to Immediate fixed it.

**Comment by Forecaster** [comment]
Assuming there is no longer an issue with this.
