### ISSUE TITLE
Suggestion: Add a High Speed junction track

### ISSUE THREAD

**Issue by CyanideCarrot** [Railcraft/Railcraft#852]
Here's how it could be useful:
![2016-07-15_12 16 00](https://cloud.githubusercontent.com/assets/14823057/16873562/0d4ecf34-4a8c-11e6-9052-28bee703943b.png)

**Comment by CovertJaguar** [comment]
Usually it's better to make overpasses for High Speed Track.

**Comment by CyanideCarrot** [comment]
That's my current solution, but it's not aesthetically pleasing.

**Comment by Forecaster** [comment]
I agree that there should be a switch track, since there is a Wye track that is completely useless since you can never go over it in HS since you'll always turn. A switch track makes more sense.

**Comment by CovertJaguar** [comment]
@Forecaster you might want to re-read the issue and go look at the creative menu again. ;)

**Comment by Forecaster** [comment]
...
In my defence is 1am and I'm in bed on my phone...

**Comment by liach** [comment]
@bballboy2002 You can dig underground which is aesthetically pleasing and more safe.

**Comment by purpleposeidon** [comment]
> In my defence is 1am and I'm in bed on my phone

Sounds more like a confession than a defense :D

**Comment by CovertJaguar** [comment]
I'll make sure and add this when I get around to rewriting the track system.

**Comment by liach** [comment]
Resolved by 05fda9bbca5235cf29ea7e9b14219ac58867bbcf
