### ISSUE TITLE
Item Held Wrong

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#853]
This is a list of items that need to have their model json tweaked:
- [x] Electric Meter
- [x] Magnifying Glass
- [x] Signal Surveyor
- [x] Signal Tuner
- [x] Stone Carver

**Comment by williewillus** [comment]
should inherit from "item/handheld" instead of "item/item" probably

**Comment by CovertJaguar** [comment]
They do, but most of these would look better perpendicular to the player's line of sight as opposed to parallel like a normal tool.

**Comment by williewillus** [comment]
ah, I see
