### ISSUE TITLE
New Disposal Track features

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#855]
Boni suggested I add something similar: https://twitter.com/bonusboni/status/753678824588644352

So I got to thinking and figured, hey the Disposal Track already does this for entities, no reason we can't make it do it for items too.

So the idea:
- [x] Add a filter slot gui to limit cart types
- [x] Make Disposal Track extract items from carts
- [x] Make Disposal Track spawn extracted items or insert into inventory below track.
- [x] Rename to Dumping Track?

**Comment by Forecaster** [comment]
Not sure if the "insert into inventory" part is needed. We have the unloaders for that, as well as the hopper cart being able to do that on it's own. The rest I approve of though!

**Comment by CovertJaguar** [comment]
It would still be a very "dumb" system without all the bells and whistles of an unloader. No filters (besides cart), no stocking, no locking track integration/interaction, etc...

**Comment by Forecaster** [comment]
Maybe if it's also slower than the normal unloader?

**Comment by CovertJaguar** [comment]
Probably.

**Comment by Vexatos** [comment]
I actually like the name "Disposal Track".

**Comment by Forecaster** [comment]
Disposal track is great 👍

**Comment by MalkContent** [comment]
How about making it dump to a side and vomit all the items in entity form at once. The cart model could tilt in that direction.
People can then build their own systems to deal with the item onslaught. Or garbage.
Also: I don't think it's necessary to have it dump mobs, too.

**Comment by dj3520** [comment]
> vomit all the items in entity form at once

Massive entity count increase, also I've seen items that respond to being dropped.

**Comment by MalkContent** [comment]
So use the unloaders if that's either to taxing or unwanted gameplaywise. I actually like the thought that there's items that can't be handled this way.

**Comment by liach** [comment]
I've implemented all the ideas here. I just need to add a GUI and test.

**Comment by liach** [comment]
This is "no longer implemented" because old code cannot be merged onto the new base any more.

**Comment by CovertJaguar** [comment]
Right so I need to do some git magic it looks like to bring this in.

**Comment by CovertJaguar** [comment]
Closed by 12fedb804fc8fc0acac3e9649f5a546bc6bf4697
