### ISSUE TITLE
Crash on world load appears related to High Speed

### ISSUE THREAD

**Issue by Greys0** [Railcraft/Railcraft#858]
Upon attempting to load into a Creative Superflat world that I was experimenting with High Speed tracks the client crashed. There may have been a Perpetuum Locomotive travelling at High Speed when the game was closed previously.

I use MultiMC 5 v0.4.11-751

[Two Logs](https://gist.github.com/Greys0/cd64f2d05831ff4be722a4ccfcdf0d51)

**Comment by CovertJaguar** [comment]
For what it's worth, this has been fixed in for RC10 already.
