### ISSUE TITLE
Railcraft backpacks

### ISSUE THREAD

**Issue by Chinthor** [Railcraft/Railcraft#859]
According to the Railcraft wikis available, the backpacks that are added when forestry is present can be edited just as the forestry ones can. You can tweak what items can and cannot be placed into them. But my railcraft config folder has nothing about backpacks in it. Just an option to turn the forestry module on or off.

Is this intentional? Will items for these packs always be hard coded by the author? I'd like to make a few tweaks for my server.

Running a 1.7.10 "kitchen sink" server of tech, farming, and exploration. 
Railcraft is at 9.8.0.0; Forestry is at 4.1.1; Forge is at 1614
_note_ tested in single player with latest Railcraft release. 9.12.2.0. and Forestry 4.2.15. Re-generated the configs for both Railcraft and Forestry. Still no "edit backpack" option.

Any thoughts?

**Comment by CovertJaguar** [comment]
Look in the forestry folder? I don't know how Forestry handles the config files.

**Comment by CovertJaguar** [comment]
@mezz poke

**Comment by bookerthegeek** [comment]
They are in  ../config/railcraft/backpack.cfg

It will list all the backpacks.

**Comment by Chinthor** [comment]
Uh. Nope. After the steps listed above, my /config/railcraft contains:
blocks.cfg
items.cfg
modules.cfg
railcraft.cfg

Are you sure that feature works properly in 1.7.10? I'll try another clean build reinstall, but I've deleted and regenerated these configs at each step of the process. No dice.

**Comment by bookerthegeek** [comment]
Oops.... I meant

 .../configs/forestry/backpack.cfg

**Comment by mezz** [comment]
If the config for the Railcraft backpack is not in `/configs/forestry/backpack.cfg` then it is an issue with Forestry. Unfortunately the backpack configs had issues in 1.7.10, if there is a problem it should be fixed in the 1.10+ version.

**Comment by Chinthor** [comment]
Ok. Thanks for that Mezz.  I'll check it out and cross my fingers. I do love me an All-The-Things! server, but pushing even a minority chunk of the mods to 1.10 is going to be nightmare fuel. Appreciate all the help. Laters.
