### ISSUE TITLE
configs for enabling disabling railcraft change to water container: bottle

### ISSUE THREAD

**Issue by usafphoenix** [Railcraft/Railcraft#860]
working on a barren-world-type modpack that was meant to use railcraft coke oven mechanic as part of the progression line. found that railcraft changes the fluid container for a water bottle to only hold 333mb. causes duplication glitches elsewhere. was wondering if there is (already) or can be added a config option to disable the nerf to the water bottle? or if there is minetweaker, modtweaker support for scripting it out of the mod while using the rest of the mod's features?

**Comment by CovertJaguar** [comment]
There does not currently appear to be a config option for that, but I could certainly add one for RC 10.

That probably doesn't help you though, sorry.

**Comment by usafphoenix** [comment]
guessing RC 10 will be for a newer MC? currently doing 1.7.10 work, but could look into making the pack for 1.10, formivore generators and enviromine are essential to the pack too, so it may just have to be delayed a bit. which i suppose is fine. at any rate, thanks for replying and considering it for future releases :)

**Comment by Voxel-Friend** [comment]
@usafphoenix An alt for environmine is Tough as Nails. Doesn't have sanity, air quality or block physics though.
