### ISSUE TITLE
[Railcraft 9.11.0.0 for minecraft 1.7.10] Elevator track problem

### ISSUE THREAD

**Issue by Ramog** [Railcraft/Railcraft#863]
The elevator tracks currently don't deploy you automatically if you power it on the same block as your exit plattform is. I have build a design like [this](http://railcraft.info/wiki/_media/screenshots:rail_elevator_example_2.jpg?w=500&tok=064a8f)

**Comment by liach** [comment]
@Ramog Can you confirm by testing in 9.12.2.0 and adding your own screenshot?

**Comment by liach** [comment]
Confirmed. It is actually intended to be working like the one in the screenshot, but this can be a useful addition.
![2017-03-13_16 52 25](https://cloud.githubusercontent.com/assets/7806504/23879952/acfc4d24-080d-11e7-8f3b-a30cddd4768c.png)

**Comment by CovertJaguar** [comment]
I'm honestly surprised it works at all.

**Comment by Generalcamo** [comment]
Closed this since it was marked "not a bug". If you want this feature to be implemented, please make a separate card.

**Comment by CovertJaguar** [comment]
I'm not actually sure what it is yet. I was going to take a look eventually. The original description sounds like it might be a bug.
