### ISSUE TITLE
[Railcraft 10.0.x] Crash on Client Startup

### ISSUE THREAD

**Issue by MastaC729** [Railcraft/Railcraft#866]
I have been trying to build a version to help test out for a proper release of Railcraft, but I am currently getting the following crash: 

http://pastebin.com/ntPGBmnY

**Comment by CovertJaguar** [comment]
Interesting, well I ended up not using it anyway. It will be removed in the next commit.

**Comment by MastaC729** [comment]
Haha, thanks for the response.
