### ISSUE TITLE
[1.10] Carts can not be pushed

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#875]

**Comment by CovertJaguar** [comment]
Pushed how? With a crowbar?

**Comment by liach** [comment]
Yes you cannot push it with a crowbar

**Comment by liach** [comment]
Seems to be an issue with drags and motions

**Comment by purpleposeidon** [comment]
I haven't tried a crowbar, but the player can not push one with their body.

**Comment by CovertJaguar** [comment]
Body pushing hasn't worked since I made them solid like 3 years ago.

**Comment by liach** [comment]
Well body push works in 1.7 actually. You can push carts just like pushing animals.

**Comment by liach** [comment]
@CovertJaguar Cart pushing is fixed when you try to boost carts right clicking with crowbars now,
