### ISSUE TITLE
[Suggestion] Make vanilla rail unpushable by pistons

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#878]
Such a change could necessarily prevent the duplication of tracks which harms the playing experience, especially on survival servers.

**Comment by CovertJaguar** [comment]
Sorry? I'm afraid I don't understand the issue.

I always thought pushing tracks enabled some interesting things.

**Comment by KnightMiner** [comment]
There are occasional duplication bugs relating to pistons, rails, and I think slime blocks, so he wants you to disable pushing them with pistons to "fix" it.

**Comment by bookerthegeek** [comment]
To many interesting vanilla train mechanics use this feature. It is not RailCrafts job to fix vanilla minecraft dupes.

**Comment by liach** [comment]
But if you try to push such tracks from railcraft, you will find that you cannot push them-tested in rc 9.12.2.0.

**Comment by CovertJaguar** [comment]
That will no longer be true in 1.10.2, all of the Flex track variants will be pushable (no tile entities).
