### ISSUE TITLE
[1.10.2] Carts sometimes forget links

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#882]
No idea why, but I'm consistently getting some carts that forget they are linked after a game restart.

**Comment by liach** [comment]
How?

**Comment by CovertJaguar** [comment]
Links should be stored in the persistent entity NBT data and point at the other entities persistent UUID.

This is all handled in LinkageManager.java.

**Comment by liach** [comment]
I mean how to reproduce it. Does it happen when you leave the chunk it's in?

**Comment by CovertJaguar** [comment]
Restart game, wasn't enough to reload world.

**Comment by liach** [comment]
Could you state the steps to reproduce it more clearly?

**Comment by CovertJaguar** [comment]
Link a bunch of carts, quit the game, start the game, load world, see broken links. That's really all there is to it.

**Comment by liach** [comment]
Can this still be reproduced?

**Comment by TheMrCaveman** [comment]
This is still the case with beta 2!!!! It forgets ALL links when chunk unloads

**Comment by liach** [comment]
Then it looks like a bug of storage of Railcraft NBT tags.

**Comment by Ristellise** [comment]
huh maybe the game does not fully save all when quite save is pressed???

**Comment by AEnterprise** [comment]
are all the entities properly registered in the registries? if not that could cause nbt to not get saved

**Comment by liach** [comment]
In my opinion, this is probably an issue regarding NBT loading because the cart linking state always saves when a link is created or broken.

**Comment by liach** [comment]
For me, I cannot reproduce it. I linked a bunch of carts, walked away, and went back. I saw those carts still linked. Quitting the game does not work either.

**Comment by Ristellise** [comment]
@liach probably when chunks unload? you may need to walk away far enough.

**Comment by liach** [comment]
Like 10000 blocks? Or just 1000 block? I tried to go 700 blocks away and return, and the carts remain linked.

**Comment by Ristellise** [comment]
think like 10000 blocks...

**Comment by liach** [comment]
Will try later. Thanks for your info.

**Comment by xbjfk** [comment]
confirmed

**Comment by liach** [comment]
Does this happen with certain types of minecart or all?

**Comment by liach** [comment]
May this be a dupe of #585?

**Comment by Ruuubi** [comment]
Experienced the same problem in the current version (10.0.1):
https://www.youtube.com/watch?v=NRi82tY2J1A

- Spawn carts and link them
- Exit world
- Reload world
-> Carts unlinked

I tried to reproduce it in a new world. Sometimes it did work as expected, other times it did not.
Tested it at world spawn and 10,000 blocks away. Doesn't matter if I logged out right besides the train or far away. The result was the same. (Tested in singleplayer, no idea about multiplayer).

**Comment by liach** [comment]
@Ruuubi Cannot reproduce it, but I can see some weird behavior in cart physics.
![2017-02-01_18 59 42](https://cloud.githubusercontent.com/assets/7806504/22535631/25ac89ae-e8b1-11e6-9612-00c0a307204d.png)

**Comment by liach** [comment]
Have we come up with a solution?

**Comment by CovertJaguar** [comment]
Haven't looked at it recently.

**Comment by liach** [comment]
Might this relate to the loading of nbt data instead of the stroage of it?

**Comment by liach** [comment]
This issue has been observed several times on the official Railcraft server.

**Comment by liach** [comment]
Side note: https://github.com/CovertJaguar/Railcraft/commit/f51e32dac5ec5e6140bc2e3b6dbb28a75de149f3

**Comment by liach** [comment]
@CovertJaguar Can I mark this as `can't fix`?

**Comment by CovertJaguar** [comment]
No, I have a possible fix in the wild being testing right this moment.

**Comment by liach** [comment]
https://minecraft.curseforge.com/projects/world-utils#title-7
We should try with this mod.

**Comment by liach** [comment]
@CovertJaguar This issue still exists, confirmed on the patron server.

**Comment by CovertJaguar** [comment]
The Shunting Aura should provide the info necessary to fix it.

**Comment by liach** [comment]
Can we try with dormant chunk cache disabled?

**Comment by CovertJaguar** [comment]
Identify the problem first, then start looking for solutions.

**Comment by liach** [comment]
Closing since we haven't reproduced this in a long time (especially on patron server) and some fixes were already pushed.
