### ISSUE TITLE
[1.10.2] Linking chest cart and tunnel bore caused crash

### ISSUE THREAD

**Issue by SeriousCreeper** [Railcraft/Railcraft#885]
Was messing around with the tunnel bore, it was active, digging a wall. Placed a chest card behind it, shift right click chest cart with crowbar, then right clicked the tunnel bore and it crashed. 
Crashes on loading the world now too. 

crash-report: http://pastebin.com/sECxdrum

**Comment by CovertJaguar** [comment]
Right... that would appear to be the newly written and completely untested capability inventory code that I wrote a couple months back when nothing compiled.

So much untested code. T_T

**Comment by SeriousCreeper** [comment]
It's like an easter egg hunt but with bugs \o/
