### ISSUE TITLE
Command block cart will get a name of @ after quitting and joining a save game

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#887]
Before quitting:
![2016-09-09_21 47 54](https://cloud.githubusercontent.com/assets/7806504/18408029/2f204832-76d7-11e6-828f-b4cb433531c1.png)
After rejoining:
![2016-09-09_21 48 01](https://cloud.githubusercontent.com/assets/7806504/18408031/3f1a3bee-76d7-11e6-99cb-38689ddeaf79.png)

**Comment by liach** [comment]
This disregard the command stored in the cart.

**Comment by liach** [comment]
Actually that's a vanilla bug

**Comment by liach** [comment]
Well somehow this happened again in 342d823e53eb8a1ab0f23eb876aec2f30c8328b8. I guess it is related to broken cart replacement.

**Comment by CovertJaguar** [comment]
I was wondering about that.
