### ISSUE TITLE
[1.7.10] Carts aesthetics problem

### ISSUE THREAD

**Issue by KryptonCaptain** [Railcraft/Railcraft#892]
The new models for certain carts (tank and cargo) added at some point in version 9 aren't compatible with things like CartLivery or Immersive Engineering shaders anymore (though neither of those are compatible with each other as is...) - which is a travesty. 
Is there any way a config could be added to use the old models?

And quick question - how much support will 1.7 get in terms of new (dare I say backported) features and bugfixes, now that you are steaming ahead for 1.10?

**Comment by CovertJaguar** [comment]
I'll admit I hadnt thought of that. I don't have plans to do much with 1.7 at this point. The code bases aren't very similar anymore. But I could probably do something about the models for 1.10, if had some idea how those things worked.

**Comment by Forecaster** [comment]
Wait, why/how does IE and that other mid affect railcraft cart rendering?

**Comment by KryptonCaptain** [comment]
If my guess is correct, both mods look at any entity extending the vanilla cart, and then alter the texture of the cart. I'd have to check the exact code for both though.
IE does a texture replacement of the model for its shaders, and Livery applies a second, transparent texture over the top of the model for its patterns. Because I'm assuming the tank/cargo cart uses a different model/entity/whatever, with the lower sides - the mods don't recognise them as valid carts to apply the new textures to.

I might be able to fiddle around with a fork of Livery to see if I can extend its functions to the new cart models and locos. You'll probably have to talk to Blu about IE though

**Comment by CovertJaguar** [comment]
I'm afraid I can't reconcile anything you just said with how cart/entity rendering actually works. Its not like you can just look the model up in a registry. Renderer yes, model no.

**Comment by octarine-noise** [comment]
Cart Livery works by manipulating **RenderManager.entityRenderMap** (Vanilla) or **CartModelManager.modelMinecart** (Railcraft) to replace the cart body model with my own that recognizes the extra properties I add (pattern and colors).

@CovertJaguar I don't have any plans for 1.7.10 either, but I _was_ thinking about picking up the mod for 1.10 again, once Railcraft stabilizes. As long as you keep the rendering of the body and superstructure of the cart separate, I'll be happy. There's always a way to wiggle my own renderer in.

@KryptonCaptain what exactly does IE do with carts?

**Comment by KryptonCaptain** [comment]
I am 100% not an expert, so am very much just guessing.
The IE commit that added cart shaders: https://github.com/BluSunrize/ImmersiveEngineering/commit/64b2e3b566ecb4cf4e7cf5da419b9dae245a9434, seems to look for classes that extend EntityMinecart, then replaces the cart model with its own.

**Comment by KryptonCaptain** [comment]
While we're all on the topic of aesthetics - you can't apply emblems to the perpetuum locomotive

**Comment by CovertJaguar** [comment]
That's odd...considering it uses the same renderer as the Electric Loco...hmm...

**Comment by CovertJaguar** [comment]
@octarine-noise Railcraft Cart rendering has changed very little from 1.7 to 1.10.

**Comment by BluSunrize** [comment]
I designed my shaders to work well with Railcraft's carts. Did something change to affect that? I knew that CartLivery wasn't compatible, because it was very different, but IE should work with RC as long as Livery isn't involved.

**Comment by liach** [comment]
@CovertJaguar Does this still apply?

**Comment by liach** [comment]
See https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/RailcraftHelper.java. Guess we will poke blusunrize or pr to immersiveengineering if we need to.

**Comment by CovertJaguar** [comment]
I'm not sure. This must be that render code that was crashing when you added the spawner cart override. I'd have to look again but I'm pretty sure it won't touch our renderer, which means no cart shaders.

**Comment by liach** [comment]
This is just an issue with cartlivery shader application and ie shader application. given ie works fine now and cartlivery has an unclear future, I hereby close this issue.

**Comment by CovertJaguar** [comment]
I actually fixed this for IE shaders recently.
https://github.com/CovertJaguar/Railcraft/commit/d66833c96d253cbfdbdb9d286ae764f9a69843d6
