### ISSUE TITLE
Railcraft lite

### ISSUE THREAD

**Issue by Globin347** [Railcraft/Railcraft#893]
I don't know whether this is really a good idea or not, but I couldn't help but think of the possibility of creating a sub-mod called railcraft lite. 
as I envision it, it would include the following:

```
the crowbar
a variant of the powered minecart that can be stopped and started 
    (without waiting for it to use up all the fuel.)
```

and that's it. The mod wouldn't even need switch tracks, because vanilla minecraft already has them after a fashion I also expect that railcraft lite would be much easier to update to new versions.

of course, it's up to you to decide whether this is ultimately worth your time or not. I just thought I'd pitch the idea.

-Globin347

**Comment by CovertJaguar** [comment]
Not a bad idea for a mod, but I have no interesting in being the one to make it.
