### ISSUE TITLE
RC stairs and slabs

### ISSUE THREAD

**Issue by lunchboxxx19** [Railcraft/Railcraft#895]
how come (according to MCEdit) stairs and slabs from railcraft (9.12.2.0) are tile entities and not blocks? like they are in vanilla?

**Comment by CovertJaguar** [comment]
Because otherwise I'd need like 400 block ids.

And the slabs can actually have different top materials from the bottom.

**Comment by lunchboxxx19** [comment]
is that a bad thing to have that many ids?

thats actually quite cool about the slabs, i didnt even know that. usually its not possible for slabs to stack like that.

**Comment by CovertJaguar** [comment]
When I added then we only had 256 ids total, including vanilla stuff. It's better today with 4k, but there are mod packs out there that even hit that. 

It's not like it really matters, they don't tick so they have almost zero extra overhead.
