### ISSUE TITLE
[1.7.10] Dupe with Cart Dispenser

### ISSUE THREAD

**Issue by Eufranio** [Railcraft/Railcraft#901]
https://www.youtube.com/watch?v=CYoFOP5OLCI

**Comment by liach** [comment]
Yes another version for 1.7.10 is necessary

**Comment by liach** [comment]
And it should not be major version 10 but 9.

**Comment by liach** [comment]
@Eufranio Cannot reproduce in dev environment. Can you reproduce it in pure forge server or singleplayer?

**Comment by Eufranio** [comment]
Both singleplayer and multiplayer, using latest version from curse.

**Comment by liach** [comment]
So can it replicate any item or just that dragonic evolution chest? Those hoppers are vanilla ones right?

**Comment by Eufranio** [comment]
Yes, they are vanilla ones. It can dupe everything, normal items, NBT-filled items, blocks, etc.

**Comment by liach** [comment]
So is the steps like this below?
1. Place a hopper at top of cart dispenser to input the item stack to the dispenser
2. Give that dispenser a redstone signal
3. The dispenser still has the item in it while it spawns an item on the ground.

Does the size of the item stack matter? Or must you use hoppers to pick up items to dupe?

**Comment by Eufranio** [comment]
Okay, I made some other tests and I realized that the dupe happens only with the Draconic Chest, `3. The dispenser still has the item in it while it spawns an item on the ground.`
The Cart Dispenser should accept only carts, right? Because we can't put items there, only trough cables/hoppers. The solution of the problem is simply block the item insert...

**Comment by liach** [comment]
@Eufranio Can you dupe other items like Chaos shard, dragonic tools? Or try to dupe firestone from Railcraft?

**Comment by liach** [comment]
It is probably because of custom item entities.

**Comment by liach** [comment]
Should change [this line](https://github.com/CovertJaguar/Railcraft/blob/mc-1.7.10/src/main/java/mods/railcraft/common/blocks/machine/gamma/TileDispenserCart.java#L128) from

``` java
EntityItem item = new EntityItem(worldObj, x + rx, y + ry, z + rz, cartStack);
```

 to 

``` java
Entity item = cartStack.getItem().createEntity(wordObj, new EntityItem(worldObj, x + rx, y + ry, z + rz, cartStack), cartStack);
```

**Comment by liach** [comment]
Btw this need to be tested first.

**Comment by Eufranio** [comment]
You are right, I can dupe Firestone, Chaos Shards, Draconic Tools, etc.

**Comment by liach** [comment]
@CovertJaguar Although the fix is found, but I think we need to provide a utility method to better process  item dropping next time. I will work on fixing this later when I am home.

**Comment by CovertJaguar** [comment]
Fixed for 10.0.0

**Comment by Eufranio** [comment]
Can you backport the fix for 1.7.10?

**Comment by liach** [comment]
@Eufranio For now, I suggest you ban cart/train dispenser.

**Comment by Eufranio** [comment]
It's banned since I reported this dupe, but I would like unban it, it's a cool block =/
