### ISSUE TITLE
[1.10.2] Crashes when using Admin Feeder Unit

### ISSUE THREAD

**Issue by l89669** [Railcraft/Railcraft#902]
Crashed for many times. For now I can't join game in that map, once I try to join, the game will crash.

[crash-2016-09-25_03.14.34-server.txt](https://github.com/CovertJaguar/Railcraft/files/491478/crash-2016-09-25_03.14.34-server.txt)
[crash-2016-09-25_03.16.16-server.txt](https://github.com/CovertJaguar/Railcraft/files/491479/crash-2016-09-25_03.16.16-server.txt)
[crash-2016-09-25_03.18.45-server.txt](https://github.com/CovertJaguar/Railcraft/files/491480/crash-2016-09-25_03.18.45-server.txt)
[crash-2016-09-25_03.05.02-server.txt](https://github.com/CovertJaguar/Railcraft/files/491481/crash-2016-09-25_03.05.02-server.txt)

Tested on a windows client, with forge 1.10.2-12.18.1.2074&2094

**Comment by liach** [comment]
`Time: 16-9-25 上午3:14`
Anyways that npe could be fixed through a forwarding list which returns `EnumSet.noneof()` instead of null when it looks up connections.

**Comment by liach** [comment]
By the way did you play the game using gradle to build?

**Comment by l89669** [comment]
Sorry, I'm not an English native speaker so I'm not sure if i understand what you say. Did you mean asking me how did I get the mod jar?
Just git clone and use the instruction commandline in readme.md

**Comment by liach** [comment]
> `Time: 16-9-25 上午3:14`

呵呵我把这个拿出来就是问你怎么玩Railcraft的

**Comment by l89669** [comment]
为什么Railcraft接坑的是中国人。完全意外

**Comment by liach** [comment]
我又没有接坑，你国内居然开vpn编译玩Railcraft才叫惊奇。我只是做点贡献而已

**Comment by l89669** [comment]
国内不用vpn了现在，求修复BUG

**Comment by liach** [comment]
#904 开了pr了

**Comment by l89669** [comment]
thx :D

**Comment by liach** [comment]
@l89669 话说你有mcbbs帐号吗

**Comment by l89669** [comment]
有的，6级

**Comment by liach** [comment]
主要是要个链接加个好友，我mcbbs号就是用户名，因为你这样编译mod玩的人不多啊

**Comment by l89669** [comment]
主要是因为没发布，只能编译
我还以为你要我号有用，233
