### ISSUE TITLE
Locomotive GUI Interaction not working [Alpha 23]

### ISSUE THREAD

**Issue by Ra1nmak3r91** [Railcraft/Railcraft#903]
I am still able to load the locomotive with loaders and start the train with locomotive tracks. However, the actual GUI buttons do not respond.

**Comment by liach** [comment]
I believe it is not yet implemented.

**Comment by Ra1nmak3r91** [comment]
My apologies then. Closing out then.

**Comment by CovertJaguar** [comment]
Uh I thought it was working.

**Comment by Ra1nmak3r91** [comment]
Just spent an hour trying to confirm it's not a mod interaction issue. (Used a barebones modpack I threw together.) None of the buttons nor inventory slots will do anything. The only interaction I was able to do was right click a water can from forestry on the steam locomotive and the water will show up in the trains water meter.
