### ISSUE TITLE
[1.10] abandoned track places too liberally

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#909]
```
----
##  *---
########
```

Placing a track at the \* causes the thing to break.

**Comment by CovertJaguar** [comment]
Maybe I'm misunderstanding, but I cannot duplicate:
![2016-10-25_02 20 14](https://cloud.githubusercontent.com/assets/1521970/19680198/a5bf18e2-9a59-11e6-86b3-cdd2c75f2585.png)
![2016-10-25_02 20 16](https://cloud.githubusercontent.com/assets/1521970/19680199/a5c30f38-9a59-11e6-9cdf-59b88606e3db.png)

**Comment by purpleposeidon** [comment]
Ah... well, it's the block update that is the problem.
![2016-10-25_14 12 39](https://cloud.githubusercontent.com/assets/150333/19704674/6d1f27b6-9abd-11e6-9891-82b5aeb0e324.png)
![2016-10-25_14 12 42](https://cloud.githubusercontent.com/assets/150333/19704680/7069893e-9abd-11e6-848e-45f4ea7b9da4.png)
![2016-10-25_14 12 47](https://cloud.githubusercontent.com/assets/150333/19704685/73757110-9abd-11e6-8081-02d98f2aaeea.png)

**Comment by CovertJaguar** [comment]
Oh...hmmm

**Comment by CovertJaguar** [comment]
It appears that ascending track requires that it is placed against a block with a solid top face.
