### ISSUE TITLE
[1.10.2] Railcraft doesn't like Terraqueous mod

### ISSUE THREAD

**Issue by mcdodge34** [Railcraft/Railcraft#916]
Ok, I've tried adding Railcraft to my modpack (based off Avant 3 modpack used by FTOG crew) and it seems to cause a problem with a mod in the pack called Terraqueous (https://minecraft.curseforge.com/projects/terraqueous) here's the link to the crashlog, I'm just reporting to help you out here

http://pastebin.com/5azgmSS0

**Comment by CovertJaguar** [comment]
That looks like an error in terraqueous that RC triggered, I can add some error handling to prevent crashing.

**Comment by mcdodge34** [comment]
Cool, should I notify the terraqueous author for it, if I find his github

**Comment by CovertJaguar** [comment]
He should probably at least take a look at it.
