### ISSUE TITLE
IC2 EU storage carts dont actually render the IC2 EU storage blocks 

### ISSUE THREAD

**Issue by LuigiHutch** [Railcraft/Railcraft#917]
Railcraft_1.10.2-10.0.0-beta-2
Forge-1.10.2-12.18.1.2095

IC2 EU storage carts dont actually render the IC2 EU storage blocks so they actually look like normal minecart:
![2016-10-07_01 15 18](https://cloud.githubusercontent.com/assets/9326429/19175107/fc4680b0-8c2b-11e6-9f96-82c017c0701a.png)

They do however still function properly

Thanks,
- LuigiHutch

**Comment by liach** [comment]
Is IC2 needed for normal render?

**Comment by CovertJaguar** [comment]
Yes, it works by passing the IC2 blocks to the normal cart content block renderer. Or at least I think it does.

**Comment by liach** [comment]
Why are not they disabled when ic2 is not loaded?

**Comment by bookerthegeek** [comment]
How did you craft them without ic2 installed?

**Comment by Ristellise** [comment]
creativr mode imo or JEI.

**Comment by bookerthegeek** [comment]
So not broken, but maybe a good idea not to register them if IC2 API is not installed.

**Comment by CovertJaguar** [comment]
Hmm,... Not sure why they are.

**Comment by liach** [comment]
Merged into #993
