### ISSUE TITLE
[Railcraft 10.0.0-beta-2] Crash when resources or factory modules are disabled.

### ISSUE THREAD

**Issue by laserlemons** [Railcraft/Railcraft#918]
I don't know whether this is intentional or not.

**Comment by CovertJaguar** [comment]
Crash log?

**Comment by laserlemons** [comment]
http://pastebin.com/jySCY25V
This is with all modules set to false. It will only start up if I have both resources and factory set to true.

**Comment by CovertJaguar** [comment]
If there were other crashes, I'll need more crash logs. This one only affected the Resources module.

**Comment by laserlemons** [comment]
http://pastebin.com/LshTxtTt
This is with all modules except resources disabled.
