### ISSUE TITLE
carts : track replacer, undercutter and layer issue

### ISSUE THREAD

**Issue by Ristellise** [Railcraft/Railcraft#920]
they qll have the red small light at the top. it used to flash red but now just vanishes. track replacer does not pull the track from a cart attached to it.
@Forecaster has more notes about it. i also posted it on discord.
(ps it is late here and i need some sleep so this issue is kinda very plain.)

**Comment by CovertJaguar** [comment]
Oh right,  forgot to fix that. Didn't know inv interaction was broken though.
