### ISSUE TITLE
Cannot place any outfitted rails.

### ISSUE THREAD

**Issue by brisingraerowing** [Railcraft/Railcraft#921]
For some reason, I cannot place any outfitted rails on any blocks. The rail is placed, then promptly vanishes.

WAILA briefly flashes with info on the rail, but all I can make out is 'Invalid'.

What could be causing this? It is a little annoying.

Otherwise everything looks good!

Note that these are from the creative inventory. I haven't tried crafting them yet.

**Comment by CovertJaguar** [comment]
I can't recall if I tested that. Can you use theTrack Kits directly on placed flex track? I know that works in my dev env.

**Comment by RealGrep** [comment]
I noticed that too. However, that's if I pull the track directly from JEI in cheat mode, or whatnot. If I make the track with a track kit and the track in my crafting grid, I can then place it without it disappearing.

**Comment by brisingraerowing** [comment]
I'll have to try the track kit/crafting. I just was able to get MC back up after fixing a crash in BuildingBricks and getting a fix for TConstruct.

**Comment by brisingraerowing** [comment]
The track kits work, although WAILA says 'Iron Invalid Track' as the name of the item (the In Game Wiki mod states 'X Track Kit', where X is the type of track kit.

**Comment by CovertJaguar** [comment]
What item? Track Kit are generally not supposed to be use to craft tracks, they are used ON tracks in the world.

**Comment by CovertJaguar** [comment]
So the server thinks you are holding a minecart, the client a track, and I have no idea why...

**Comment by liach** [comment]
Are outfitted tracks supposed to be placed with item stacks?

**Comment by brisingraerowing** [comment]
Item. Block. Whatever.

**Comment by QuibblingAsh42** [comment]
I'm not having the exact same problem...when I place an outfitted rail, it's visible and works correctly, but WAILA shows "Invalid Iron Track" for all of them.  I have Extra Rails installed, too, and those show correctly.

**Comment by liach** [comment]
It should be What Am I Looking At handling those tracks with extended states incorrectly.

**Comment by CovertJaguar** [comment]
Open a new issue.
