### ISSUE TITLE
[1.10.2-beta-2]  Log spam with BlockDrops JEI Plugin

### ISSUE THREAD

**Issue by Crazy-KSK** [Railcraft/Railcraft#922]
Loading the game with the three mods below causes the message below to be logged ~2.280.000 times
`[Client thread/WARN] [railcraft/blockdrops]: Rail Tile was invalid when harvesting rail`

Forge 12.18.1.2095
[BlockDrops-1.10.2-1.0.11](https://minecraft.curseforge.com/projects/block-drops-jei-addon)
jei_1.10.2-3.12.5.303
Railcraft_1.10.2-10.0.0-beta-2

**Comment by CovertJaguar** [comment]
That smells like a bug in BlockDrops, that particular code path shouldn't normally be possible. Outfitted Tracks need a valid world context and tile entity to create drops.

I can remove the spam though.
