### ISSUE TITLE
Wiki seems to be gone

### ISSUE THREAD

**Issue by brisingraerowing** [Railcraft/Railcraft#923]
EDIT: Dammit, Firefox! No auto posting!

The wiki seems to be gone, and Firefox states that the server returns 500.

(I don't have a forum account, so posting this here)

**Comment by CovertJaguar** [comment]
Bluehost screwed up the PHP version or something on the server, I'm not entirely sure how to fix it.

**Comment by brisingraerowing** [comment]
Go figure. That's always a PITA.

**Comment by AEnterprise** [comment]
depends on what they did exactly and the wiki software and versions, most likely the host upgraded the php processor but the wiki is made for an older version and doesn't work with the new

**Comment by CovertJaguar** [comment]
The specific errors seems to be caused by older php versions. `__DIR__` is missing. The PHP version config option seems to have zero affect: [root]/php.ini

The wiki is dokuwiki, updated to the latest version.

```
[04-Oct-2016 20:24:17] PHP Warning:  require_once(__DIR__/composer/autoload_real.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory in /home2/railcraf/public_html/wiki/vendor/autoload.php on line 5
[04-Oct-2016 20:24:17] PHP Fatal error:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/usr/lib64/php:/usr/share/pear') in /home2/railcraf/public_html/wiki/vendor/autoload.php on line 5

```

**Comment by AEnterprise** [comment]
ok `__DIR__` is indeed something added in php 5.4.0 so you will eighter need to downgrade docuwiki then to a version that works with whatever php version your host is running or ask their support (or sometimes you can do this in your cpanel) to change the php version to 5.4.0+

**Comment by CovertJaguar** [comment]
yes, there are options in cpanel, they seem to do nothing that I can tell.

**Comment by AEnterprise** [comment]
hmm looking at the slog snippet you posted it does look like it recognizes the magic constant, can you check that the file `public_html/wiki/vendor/autoload.php` exists?

**Comment by CovertJaguar** [comment]
It does.

**Comment by AEnterprise** [comment]
a quick google shows me that it can only heapen then if your php version is to old, i think the only option here is to contact the support of your webhosting. the magic constant was introduced in 5.4 and that has reach EOL over a year ago, your hosting should upgrade or you should consider changing i guess

**Comment by CovertJaguar** [comment]
According to cpanel, they are running 5.4.24. According to the config, 5.4 or 5.6.

**Comment by CovertJaguar** [comment]
Possibly relevant: "If you choose to use PHP 5.4, you'll want to make sure your crons use "/usr/php/54/usr/bin/php" instead, as otherwise it will use PHP 5.2."

**Comment by AEnterprise** [comment]
all i find indicates that that cpanel is incorrect, can you make a php file with as content `<?php phpinfo(); ?>`that should give a page full of info where you can see the php engine version and alot more (remove again after you are done, it's a security risk if they know that)

**Comment by CovertJaguar** [comment]
oh...I fixed it... just had to add the below lines to the .htaccess file:

```
# Use PHP5.4 as default
        AddHandler application/x-httpd-php54 .php
```
