### ISSUE TITLE
[10.0.0-beta-2] Railcraft block textures are all white with Optifine installed

### ISSUE THREAD

**Issue by laserlemons** [Railcraft/Railcraft#924]
I know mod authors hate bug reports that include Optifine, but none of the other mods I've played with have this problem.
![2016-10-07_16 12 44](https://cloud.githubusercontent.com/assets/6501298/19207907/74841a60-8ca9-11e6-841d-6050f0ada39f.png)

**Comment by CovertJaguar** [comment]
Looks like Optifine broke custom texture loading once again.

**Comment by liach** [comment]
Is it caused by Optifine's bad handling of complex textures? Once it broke textures in MC 1.7.10

**Comment by CovertJaguar** [comment]
It broke this basically -> https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/client/util/textures/TextureAtlasSheet.java

**Comment by liach** [comment]
Do manipulators use sheet textures? I think they do and their texture is all right as shown in the screenshot.

Edit: Only the flux manipulator and some type of loader is correct.

**Comment by CovertJaguar** [comment]
Most do, but the Fluid and RF ones don't. Which is what allowed me to narrow down the fault.

**Comment by brisingraerowing** [comment]
I toyed with Optifine in 1.8 a bit, but decided against is as it broke pretty much everything at one point or another. It was (and is) rather finicky to use and causes way too many issues to be of much help with anything. My FPS actually went DOWN with it installed.

**Comment by laserlemons** [comment]
Really? This is the first time I've had any issues with it in modded Minecraft since 1.6.4. It's pretty much essential to half the people on my server to keep their FPS at 60. I have a fairly beefy computer so I don't have any framerate problems but I do get frequent lag spikes, which Optifine also fixes for me.

**Comment by Ristellise** [comment]
tip : DO NOT set fps to unlimited. set it to ~ 70 80  is good enough.

**Comment by sp614x** [comment]
What is the texture atlas unstitching and how should it work?

**Comment by sp614x** [comment]
Looking at [this](https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/client/util/textures/TextureAtlasSheet.java#L56) and [this](https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/client/util/textures/TextureAtlasSheet.java#L61), manipulating the private list of loaded sprites via reflection is a recipe for disaster.

**Comment by sp614x** [comment]
This may be the problem:

```
        Map<String, TextureAtlasSprite> mapRegisteredSprites = ObfuscationReflectionHelper.getPrivateValue(TextureMap.class, textureMap, 5);
```

The reflection helper is getting the wrong field - mapRegisteredSprites is index 4, mapUploadedSprites is index 5. 

```
public class TextureMap extends AbstractTexture implements ITickableTextureObject
{
    private static final Logger LOGGER = LogManager.getLogger();
    public static final ResourceLocation LOCATION_MISSING_TEXTURE = new ResourceLocation("missingno");
    public static final ResourceLocation LOCATION_BLOCKS_TEXTURE = new ResourceLocation("textures/atlas/blocks.png");
    private final List<TextureAtlasSprite> listAnimatedSprites;
    private final Map<String, TextureAtlasSprite> mapRegisteredSprites;
    private final Map<String, TextureAtlasSprite> mapUploadedSprites;
    private final String basePath;
    private final ITextureMapPopulator iconCreator;
    private int mipmapLevels;
    private final TextureAtlasSprite missingImage;
```

This is the default source as decompiled by MCP for 1.10.2, OptiFine is not making any changes in the field ordering.

**Comment by sp614x** [comment]
Looks like it's a Forge's fault - it is inserting one [new field](https://github.com/MinecraftForge/MinecraftForge/blob/f08f3c11053d414b57d03192dd72fcbfaef100f7/patches/minecraft/net/minecraft/client/renderer/texture/TextureMap.java.patch#L7) at the beginning of TextureMap and shifting the rest of the fields.

**Comment by sp614x** [comment]
Reflection is the wrong way to register new sprites, because it can lead to all sorts of hard to find bugs.
Forge provides a method [TextureMap.setTextureEntry(String name, TextureAtlasSprite entry)](https://github.com/MinecraftForge/MinecraftForge/blob/f08f3c11053d414b57d03192dd72fcbfaef100f7/patches/minecraft/net/minecraft/client/renderer/texture/TextureMap.java.patch#L200) to do exactly this. And OptiFine extends it so it can work properly with AA and AF.

**Comment by liach** [comment]
Since forge inserted a new field, the reflection index is correct. I agree to use `TextureMap.setTextureEntry(String name, TextureAtlasSprite entry)` though.

**Comment by CovertJaguar** [comment]
Ah, I didn't see that.

**Comment by liach** [comment]
@CovertJaguar Should I open a pull to forge to allow setting of an entry if the set one is missing?

**Comment by liach** [comment]
@sp614x `TextureMap.setTextureEntry(String name, TextureAtlasSprite entry)` does not work for Railcraft actually, since it does not allow overrides. Railcraft calls this method only after the blocks using `TextureAtlasSheet` is registered.

**Comment by IvanTC95** [comment]
Any way to fix it manually?

**Comment by liach** [comment]
Unfortunately not, unless you code a coremod.

**Comment by sp614x** [comment]
Why the double sprite registration?
Can you register the sprites only once (at the end?) with the correct parameters?

**Comment by liach** [comment]
@sp614x The way it works is like this: Railcraft registers block first and then register those custom icons. When those blocks get registered, they put entries in the TextureMap, rejecting Railcraft from adding correct entries.

**Comment by sp614x** [comment]
Fixed field ordering in OptiFine to match Forge.
However it would be nice if Railcraft uses an official way to re-register sprites instead of manipulating private fields via reflection.

**Comment by liach** [comment]
Thanks. I have opened a pull to forge to avoid use of reflection in the future.
