### ISSUE TITLE
[Idea] Messenger track kit

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#926]
Messenger track kit would be a track kit which tells some message to the player riding on the cart when a cart carrying the player passes by. They can be disabled via redstone signal (or enabled by that). This would be somewhat useful. 

The track might somewhat be controlled by a routing table, checking conditions for the messages.

This feature may be very helpful to designs of train stations.

**Comment by CovertJaguar** [comment]
Oh, that's not a bad idea. I can see the uses for it.

**Comment by Ristellise** [comment]
i am aupporting this idea too. seems pretty neat. :)

**Comment by dj3520** [comment]
"Now to your left is the first desert temple discovered on the server..."
heh

**Comment by vico93** [comment]
Maybe we can use `/tellraw` [syntax](http://minecraft.gamepedia.com/Commands#tellraw) in there.

**Comment by brisingraerowing** [comment]
I like this idea as well.

**Comment by Ristellise** [comment]
i wpuld also wound like a  broadcaster track. does the same but in a radius... good to know that trajn is arriving or when crossing a road block.

**Comment by liach** [comment]
@Joshwoo70 Or add a mode to the track kit, like lockdown tracks.

**Comment by CyanideCarrot** [comment]
another feature to add to this, maybe allow it to play an audio file (placed in world save) though this may be a little too complicated

**Comment by liach** [comment]
@bballboy2002 This needs a custom resource pack if the audio is from the server.

**Comment by dj3520** [comment]
>This needs a custom resource pack if the audio is from the server.

Not entirely. (Research Computronics tape drives.) But I feel like a chat message would be sufficient.

**Comment by liach** [comment]
It is possible to send packets also, but is way more costly.

**Comment by dj3520** [comment]
Personally I don't think it fits the theme. And it's probably not worth it to code (I wouldn't know since I don't even know Java.) Something neat I suppose but a chat message would work well enough.

**Comment by CyanideCarrot** [comment]
I just came up with a better idea for it: text-to-speech. It's what I really wanted to do with the audio files anyways and might be easier to code.

**Comment by liach** [comment]
I don't know if Java supports it

**Comment by HoldYourWaffle** [comment]
@liach you vould reference the google translate api

**Comment by liach** [comment]
Probably custom text components
