### ISSUE TITLE
Repost request

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#928]
Hi @CovertJaguar!
As the title says, I am gonna repost Railcraft mod to [a Chinese forum called MCBBS](http://www.mcbbs.net/).

What will I do:
Include the link to http://railcraft.info and http://headlamp-games.com;
Include the link to [curse page](https://minecraft.curseforge.com/projects/railcraft);
Include the link to [this repository](https://github.com/CovertJaguar/Railcraft);
Include the link to [the Chinese discord channel](https://discordapp.com/channels/225184360049934336/233791812005789697);
I will always clarify that you are the origin author. (I'll write down your name, and GitHub link)
I will not host files on other websites for download but always direct to curse forge download.

Questions:
Do I need to provide the link to Patreon?
May I say that I am a contributor to the code of Railcraft?
May I include the version number of test versions in the post but not releasing them?

@3TUSK may be able to clarify more.

**Comment by CovertJaguar** [comment]
Fine with me if you just linking to me files.

As for the questions:
1. It would be nice if you did.
2. Sure, but for your own sanity you might want to make it clear that you are not a maintainer, only a contributor/bugfixer. No need for you to get unreasonable requests from people for changes that only I can approve. ;)
3. Sure, they are no secret.

**Comment by 3TUSK** [comment]
Well, I am surprised that you said you will post a link to a Chinese discord channel...

**Comment by CovertJaguar** [comment]
I made him a channel on the Railcraft discord server. He might mean that.

**Comment by liach** [comment]
By the way, all the Railcraft reposting threads that include a 1.7.10 version on that forum host Railcraft files on other websites for download. Should that be somewhat prohibited?

**Comment by 3TUSK** [comment]
Isn't that something stated in the license?

**Comment by 3TUSK** [comment]
Just double checked the license, and yes Railcraft can only be redistributed as part of Modpack unless an explicit permission is provided.

@liach if you are in China: how's the speed of downloading something from curseforge recently?

(Time to re-consider my panel on btm16.2... I didn't elaborated the situation very well...)
(Too tired to edit commet on cellphone.)

**Comment by liach** [comment]
If you go to project page it is very slow to load w/o a VPN, probably because of some sort of plugins; but it is pretty fast if you directly link to the file for download.

**Comment by 3TUSK** [comment]
Which part of China you are in? Afaik the speed varies on different area.

**Comment by liach** [comment]
In general the speed is pretty much the same except in some seditious region like Sinkiang
