### ISSUE TITLE
Pokecube Problem

### ISSUE THREAD

**Issue by Sargefan767** [Railcraft/Railcraft#929]
Hi im having a problem with your mod 
http://imgur.com/a/fO5yl
as you can see in that photo railcraft 1.10.2 and its having issues with pokecube revival i was wondering
if you could add compatibility for the two mods?

**Comment by CovertJaguar** [comment]
What the...? Is that supposed to be a basic minecart?

**Comment by Ristellise** [comment]
it looks like. seems like pokecube is SOMEHOW overriding textures.

**Comment by AEnterprise** [comment]
looks like eighter railcraft or pokecube are doing things when textures are stitched but isn't checking what is being stitched

**Comment by CovertJaguar** [comment]
I don't think entity textures are even stitched, more likely it's a texture binding issue.

**Comment by AEnterprise** [comment]
stiched or bound, principle is the same, one of the involved mods isn't performing an input check on an event, i've seen this before

**Comment by CovertJaguar** [comment]
This might be fixed in 10.0.0.

**Comment by liach** [comment]
@Sargefan767 Does this still happen?

**Comment by liach** [comment]
I will test this.

**Comment by liach** [comment]
Lol I cannot even open a world with pokecube in my dev env! Don't think we are ever going to support it if it is so naughty.
