### ISSUE TITLE
[1.10.2] worldgen incomplete or bugged?

### ISSUE THREAD

**Issue by croftyraider** [Railcraft/Railcraft#931]
Using beta-2 ran around in creative looking for worldgen as I'm integrating railcraft into an existing world and wanted to prevent ore duplication. I did see some quarried stone and the villager house, but that's it. None of the "poor" ores whatever those are, nor could I find any abyssal geode's.

I did make one change to the configs - disabled poor tin because I already have two tins in my home made pack.

**Comment by CovertJaguar** [comment]
Just to verify, you are familiar with how Poor Ores spawn? They are not uniform, they form clouds in localized regions. That said I haven't test them myself yet to see if they actually work.

This is the second report of Geodes not spawning though.

**Comment by CovertJaguar** [comment]
I can confirm that at least Poor Lead does spawn.

**Comment by liach** [comment]
This can be checked by a hack mod which looks for blocks IMO.

**Comment by croftyraider** [comment]
Wasn't aware of how the poor ores spawned as I haven't played railcraft in quite awhile. I did spend a fair amount of time hunting though trying to assay how the ores were generating. Poor luck I suppose :)
