### ISSUE TITLE
[10.0.0-beta-2] Crash on start if Factory module is disabled

### ISSUE THREAD

**Issue by vico93** [Railcraft/Railcraft#932]
Hi!

As stated in title, i'm using 10.0.0-beta-2 (latest file from curse) right now, and if i set `railcraft:factory` to `false` in modules.cfg i get [this crash](https://gist.github.com/vpontin/0352ff43eb9c6ab58a8fe4358b63ac06).

**Comment by CovertJaguar** [comment]
Duplicate of #918
