### ISSUE TITLE
Requested Feature

### ISSUE THREAD

**Issue by Tyrantin** [Railcraft/Railcraft#933]
Would like to see the ability to have redstone signal added to the fluid dispenser.
Would also like to see the ability to color all of the carts for routing purposes.
Redstone signal  on: stops fluid from going into a tank cart 
redstone signal off: Allows for fluid transfer

Purpose is for Track automation 

TyRao
Vermilion Modded Servers

**Comment by CovertJaguar** [comment]
BuildCraft gates can already do this.

And there is an Addon for painting Carts called Cart Livery.
