### ISSUE TITLE
(1.10.2) Creosote bottle duplication bug

### ISSUE THREAD

**Issue by Silvrus** [Railcraft/Railcraft#934]
Railcraft version 10.0.0-beta-2 for MC 1.10.2
Immersive Engineering version 0.10-44 for MC 1.10.2

Not sure which mod is causing the issue, but pulling the creosote from IE coke ovens out produces RC creosote bottles (IE doesn't appear to have a bottle item), then when using those bottles to create IE Treated Planks, the bottles aren't used but instead return 64 bottles. 

Edit: Checked with single bottle, works as intended, but with multiple bottles such as a stack of 16, 64 are returned instead.

**Comment by CovertJaguar** [comment]
Also b77e8bcc18ac560b3d05e0c066864adc9b7961ab

**Comment by DnTheMn** [comment]
alrighty nice to see it already getting worked on / patched thanks

**Comment by CovertJaguar** [comment]
It should be in Beta-4 I believe. Let me know if you continue to have issues.

**Comment by RiverC** [comment]
@CovertJaguar I'm running 10.0.0 and IE 0.10-48 and I get "undefined" texture for creosote with no ability to draw creosote from coke ovens in IE. I noticed some odd things when I upgraded from the latest forge build 2099 to 2118 - it seems to have affected my ability to draw fluids out of Tcon smeltery drains too.

**Comment by CovertJaguar** [comment]
Please open a new issue.
