### ISSUE TITLE
[10.0.0-beta-2] Tunnel Bore sometimes go wrong direction

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#936]
As I metioned in Discord Chat, Tunnel Bore moving in reverse direction, that's happen when I put tracks to the North, its go South, so as East and West. And the end of track, it will turn left or right
![2016-10-12_22 59 19](https://cloud.githubusercontent.com/assets/11695493/19317958/f0c283ca-90d0-11e6-9a01-c907a315ca54.png)

**Comment by CovertJaguar** [comment]
Are you sure you are describing this correctly? I can only get it to happen when facing west, all other directions are fine.

**Comment by ccgfok** [comment]
A gif file is a description for this bug.
https://gfycat.com/RewardingSleepyEchidna

**Comment by CovertJaguar** [comment]
Yep, that's West like I said. Anyway, should be fixed.
