### ISSUE TITLE
[10.0.0-beta-2] Embarking track may make Minecraft "not responding"

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#937]
When Embarking Track was powered by redstone, the Minecart will teleport to entities instead of load entities into Carts, after that the entities has "not responding"; it also make Minecraft "not responding" when I was trying to quit Minecraft.
![2016-10-10_17 11 23](https://cloud.githubusercontent.com/assets/11695493/19318294/568bfe56-90d2-11e6-87c7-affc7c4cea9e.png)
![2016-10-10_17 11 31](https://cloud.githubusercontent.com/assets/11695493/19318298/5a2dddea-90d2-11e6-8f54-a1f105d65133.png)

**Comment by CovertJaguar** [comment]
Well....that's moderately amusing.

**Comment by liach** [comment]
:trollface:
