### ISSUE TITLE
[Suggestion] Enhanced spawner minecart

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#939]
Possible additions:
1. Use spawn egg to set the spawned entity;
2. Custom cart item for spawner minecart;
3. Possibly use it in world gen referenced in #889

**Comment by liach** [comment]
Can anyone add a tag or have some comment?

**Comment by Forecaster** [comment]
No, only the repo owner and collaborators can add tags. Not sure what you mean by "have some comment"

**Comment by liach** [comment]
Like [enhancement] tags. Do you have any opinion on this?

**Comment by Forecaster** [comment]
You can put tags in the title, it's fine.

**Comment by CovertJaguar** [comment]
_points out that @Forecaster can add tags_

**Comment by liach** [comment]
@CovertJaguar I think it is not hard to implement this for me, but it is really a pain in the butt for me to draw a texture for the cart item. (vanilla does not have an item for spawner minecart)

**Comment by CovertJaguar** [comment]
Ah, yeah. If you want to work on it, just use a placeholder and I can make a better one later.

**Comment by liach** [comment]
It came a bit late (after 2 years), but here it comes.

**Comment by liach** [comment]
#1522 merged
