### ISSUE TITLE
Routing Table, Golden Ticket edits don't propagate to server

### ISSUE THREAD

**Issue by mconwa01** [Railcraft/Railcraft#944]
Editing one of these will appear to take effect on the client, but the change will be lost when the item is dropped on the ground, put in a Routing Detector, etc.

**Comment by mconwa01** [comment]
(Looks like you're probably aware of this, based on the comment in PacketCurrentItemNBT.java.)

**Comment by CovertJaguar** [comment]
Uh.. Right... My todo comments... Forgot about those...
