### ISSUE TITLE
[10.0.0-beta-3] Player sits too high in minecart.

### ISSUE THREAD

**Issue by laserlemons** [Railcraft/Railcraft#946]
Vanilla:
![2016-10-15_18 10 44](https://cloud.githubusercontent.com/assets/6501298/19414474/22d68c1a-9303-11e6-9817-306d128b91c4.png)

With Railcraft:
![2016-10-15_18 10 06](https://cloud.githubusercontent.com/assets/6501298/19414475/25b547dc-9303-11e6-9de9-01ab11eed1b8.png)

**Comment by Ristellise** [comment]
when you move does it fix itself?

**Comment by laserlemons** [comment]
Nope, it's done that since I've started playing the 1.10 version, even while moving.

**Comment by Ristellise** [comment]
huh... strange... earlier versions i tested when it moves it fixies itself. looks too me like a hitbox issue. do you know how to bring uo the hitboxes and take a picture of it? it should be somewhere around the F3 + Q instructions.

**Comment by laserlemons** [comment]
Looks like the minecart hitbox is also too high?
![2016-10-15_18 22 09](https://cloud.githubusercontent.com/assets/6501298/19414526/57c60364-9304-11e6-926d-fbb44b1814f3.png)

**Comment by Ristellise** [comment]
hmm looks like so... paging @covertjaguar .

**Comment by CovertJaguar** [comment]
Known, and I've been told the same problem exists to some extent in vanilla.

What is also known that it does not affect the Tunnel Bore for whatever reason and that it's only the client that is reporting the wrong position. Additionally, it is only wrong while the cart is on tracks and it fixes itself eventually.

What is not known is why. I spent a couple hours the other day poking at things with no results before deciding I had better things to do.

**Comment by laserlemons** [comment]
I noticed it only happens when the cart is on a track. Maybe it's colliding wrong with the track block? It seems like the height is consistent with that of a slab.

**Comment by CovertJaguar** [comment]
Could have something to do with me giving carts a solid collision box I suppose.

**Comment by liach** [comment]
Confirmed by @Joshwoo70 to be a hitbox issue.

**Comment by liach** [comment]
I once could reproduce this issue, but it eventually disappeared without code change.

**Comment by CovertJaguar** [comment]
Dunno what you are talking about, I see it every time I load a world in my dev environment.

**Comment by Ristellise** [comment]
How to reproduce : https://youtu.be/FJ74K2YWBIs

Using the railcraft patron pack with the latest tag : 1.13

**Comment by liach** [comment]
The last video really helps. Guess it might be related to cart items. @Joshwoo70 How is cart dispenser?

**Comment by liach** [comment]
lol my guess is right
