### ISSUE TITLE
[10.0.0-beta-3] dispensers can't place minecarts on rails

### ISSUE THREAD

**Issue by 4rz0** [Railcraft/Railcraft#948]
The vanilla mechanic of placing carts on rails with dispensers doesn't work with Railcraft installed.
The carts are just plopped out as if there was no rail in front of the dispenser.
I tested with all rail-types and all available carts.

Forge used is recommended (2099).

**Comment by CovertJaguar** [comment]
This is intentional though it could be revisited.

**Comment by 4rz0** [comment]
I actually didn't know about the RC cart and train dispenser (yes, shame on me), so this point is kind of irrelevant.
Feel free to deal with the issue depending on how you want backwards-compatibility to vanilla mechanics ;D

**Comment by CovertJaguar** [comment]
Mostly it was just because I couldn't be bothered to register a dispenser handler for every one of my carts.

**Comment by liach** [comment]
Well dispenser should absolutely be removed. Railcraft edits vanilla behaviors, that's all.

**Comment by Ristellise** [comment]
"Well dispenser should absolutely be removed. Railcraft edits vanilla behaviors, that's all."
wrong. arrows and spawn egges dispence usjg dispensers.

**Comment by liach** [comment]
What is `usjg`?

**Comment by Ristellise** [comment]
and to add on, any mod that removes any vanilla stuff is instantly frowned upon.

**Comment by liach** [comment]
@Joshwoo70 Railcraft also modifies vanilla behavior of minecart with command block and enderman.

**Comment by CovertJaguar** [comment]
I somehow feel you guys are missing the visible and oft complained about change, track recipes.
