### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by brisingraerowing** [Railcraft/Railcraft#950]
I cannot access your website for some reason. What happened?

**Comment by Forecaster** [comment]
Don't know. I unfortunately do not have access. @CovertJaguar will have to check when he returns.

**Comment by AEnterprise** [comment]
seems like a problem with the webhost, it's completely refusing the http connection so the VM running it all is misconfigured

**Comment by CovertJaguar** [comment]
Again? Third time this month.

**Comment by bookerthegeek** [comment]
Why not put it on github?

**Comment by liach** [comment]
@CovertJaguar You can find some useful information at http://headlamp-games.com/ for some reason headlamp games always provide more information than railcraft.info.

**Comment by LizzyTrickster** [comment]
@liach looks like it's just a poor mirror/cache of railcraft.info for me... ![IMG](https://www.theender.net/shx/zion/chrome_2016-10-17_22-12-21.png)

**Comment by CovertJaguar** [comment]
Should be back up soon if it isn't already.

Customer service got it all sorted out right quickly (even if they did charge me $24 for an account upgrade).

**Comment by bookerthegeek** [comment]
Ouch.

Can I ask why an external site vs gitpages?

**Comment by Forecaster** [comment]
Site is back online at http://www.railcraft.info/
