### ISSUE TITLE
Track Relayer Cart Pulls Wrong Items From Chest Cart

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#952]
Description:
When using the track relayer with a linked chest cart, the track relayer pulls the first item from the chest cart instead of the current "replacement" track.

For example, if you're replacing tracks with reinforced tracks, the operation will work until the first slot opens up in the chest cart. Then it starts filling up with regular tracks, which are then pulled into the relayer.

Steps to reproduce:
1. Build a train. (I used: Perpetuum locomotive - chest cart -track relayer)
2. Build a long track out of regular rails
3. Tell the relayer to replace regular rails with reinforced rails
4. Place a stack of reinforce rails in the second slot of the chest cart
5. Run the train

Tested With:
RailCraft: 1.10.2-10.0.0-beta-3
Forge: 1.10.2-12.18.2.2099

**Comment by nrllewellyn** [comment]
Note to anyone else having this issue: A temporary work-around is to fill around 1/2 the chest cart slots at the END of the inventory with single tracks of the type you're removing. This will cause the tracks to stack at the back of the inventory first.

**Comment by nrllewellyn** [comment]
This may be related to #920

**Comment by CovertJaguar** [comment]
Either the inventory code is broken or it needs tweaking for the new track paradigm.

**Comment by CovertJaguar** [comment]
Hmm...whatever it is isn't obvious. Debugger inspect will be required.
