### ISSUE TITLE
Redstone Condition Incorrect on RF Loader

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#953]
Description:
The "complete" redstone condition for the RF loader should be "when cart is full", but instead it's "Process until cart is empty".

Tested With:
RailCraft: 1.10.2-10.0.0-beta-3
Forge: 1.10.2-12.18.2.2099

**Comment by nrllewellyn** [comment]
Related: The redstone output seems to flicker, event when set to the "complete" state. It's almost like it cycles off and back on every time that the cart has RF added.

**Comment by CovertJaguar** [comment]
It doesn't have the new buttons that item loader has yet does it? I forget if I finished that update.

**Comment by nrllewellyn** [comment]
It has the same button (options like "Complete", "Immediate", etc.), but the option for "Complete" is "when unloaded" instead of "when loaded".

Also, the redstone behavior is really odd. It doesn't seem to matter which option you choose--it always behaves the same, and it it outputs either 1-tick or 0-tick "off" pulses. (I suspect that it's a weird zero-tick pulse, since redstone torch not gates never cycle when connected.)

**Comment by nrllewellyn** [comment]
~~Another oddity: If you set the loader to any setting besides "manual", then put a cart in front of it, and then change it to "manual", the redstone signal continues outputting. (Albeit with the strange blinking on-and-off effect.)~~

Edit: Manual mode seems to be ignored entirely.
