### ISSUE TITLE
Strengthened Glass Recipe Bug

### ISSUE THREAD

**Issue by chazwarp923** [Railcraft/Railcraft#954]
Railcraft Beta 3The recipe for the various different colors of strengthened glass produces colors of glass of the wrong color. It appears to be the producing the polar opposite color on the 16 different meta datas spectrum. So instead of producing white glass it produces black. You're probably looping over the meta data the wrong way round somewhere, or vanilla went and changed something on you.

**Comment by CovertJaguar** [comment]
Colors...bleg....
