### ISSUE TITLE
Add railcraft retrogen support

### ISSUE THREAD

**Issue by aemondis** [Railcraft/Railcraft#955]
I have yet to find an explanation, but geodes have simply failed to spawn anywhere in our world despite every configuration option necessary being enabled. The ores and quarried stone have generated as per normal, but not abyssal stone. Even doing a search for any blocks through worldedit has revealed not a single stone anywhere.

I had hoped to perform a retrogen using CPW11's simplyretrogen, but there is no IWorldGenerator entry for Railcraft that I can see. I can't seem to get geodes to generate even moving into new chunks that have never previously generated either.

**Comment by CovertJaguar** [comment]
Geodes are broken in beta-2, fixed in beta-3.
