### ISSUE TITLE
Spectral chestcarts

### ISSUE THREAD

**Issue by PegBeard** [Railcraft/Railcraft#956]
Not sure if this is a bug, feature, or something else, but vanilla 'Minecart with Chest's are ghostly and spectral. I did have a look around, but I couldn't find anything about this, so I wasn't sure if it was intentional, but is there a way to disable it?

I mean, it seems like a cool feature, if you are wearing the Trackman's Goggles you can see where nearby carts are (behind walls and such), but (see screenshots below) this is happening with carts in abandoned mineshafts and ones I have placed even in a new world with no items.

![2016-10-21_04 27 39](https://cloud.githubusercontent.com/assets/17724810/19585733/d1ea7404-9746-11e6-95a1-c0b2ef3db116.png)
![2016-10-21_04 27 49](https://cloud.githubusercontent.com/assets/17724810/19585734/d1ebed16-9746-11e6-8694-a854fa9fe92f.png)

**Comment by CovertJaguar** [comment]
There is an old story on the rails. Especially near old abandoned lines. Sometimes they say you can still hear whistles blowing or if you especially lucky or unlucky, you might see an old Steam Engine puffing down the line, but the train will not be from this realm, but from another and not quite present in our world... they call this the Ghost Train...

**Comment by CovertJaguar** [comment]
On a more serious note, disabling the Seasonal Module will turn this off.

**Comment by PegBeard** [comment]
Ohhhh. So it's the Samhain event. Super. :D

**Comment by brisingraerowing** [comment]
I was wondering about that. Interesting.

**Comment by CovertJaguar** [comment]
For what its worth, at the time it didn't occur to me that you'd be able to see them through miles of dirt.

**Comment by nrllewellyn** [comment]
ROFL I was so confused about this. I was just coming to report it as well. :-P

**Comment by MauveCloud** [comment]
I was bothered about this as well (mainly the long-distance x-ray effect - if it was short-range or only when wearing the goggles, I wouldn't mind it so much).  I'm especially confused that disabling the Seasonal Module worked to eliminate the effect when disabling the entire Railcraft mod did not.

Edit: the "spectral" effect of the cart being semi-transparent when viewed directly goes away if I disable the whole Railcraft mod, but the outline that can be seen through obstacles persists, as seen in the attachment.
![2016-10-24_08 26 59](https://cloud.githubusercontent.com/assets/8942955/19652010/0389f3b6-99c4-11e6-9dee-496d6d918438.png)

**Comment by CovertJaguar** [comment]
I've replaced it with a custom effect that no longer can be seen through walls and can be disabled client side for the next release.

**Comment by liach** [comment]
@CovertJaguar The ghost carts do not show their custom names above them when they are named. Is it intentional?

**Comment by CovertJaguar** [comment]
Yes.

**Comment by liach** [comment]
Since the glowing effect has been removed, I will close this one.

**Comment by ninjatayler10-ctrl** [comment]
how to get this
