### ISSUE TITLE
[1.10.2] Machines not Loading 10.0.0.0-beta-4

### ISSUE THREAD

**Issue by Wulfbayne** [Railcraft/Railcraft#960]
Currently experiencing an issue in 1.10.2 with all objects that are designated as "Machine" (machine_alpha etc) are not loading/registering even though the config files have them listed as enabled. I have not been able to track anything in the console logs indicating there was a problem loading the machines. All but the "Iron Plate" recipe have fallen back to workable crafting recipes elsewhere. The "Iron Plate" recipe uses the same pattern in a crafting table as an "Iron Trap Door".

**Comment by CovertJaguar** [comment]
The machines will return in 10.2.0.
