### ISSUE TITLE
[RC 10.0 Beta 4] No mcmod.info file found

### ISSUE THREAD

**Issue by evieluvsrainbows** [Railcraft/Railcraft#961]
In the latest version of Railcraft for 1.10, no mcmod.info is being detected. Was wondering if this could be resolved. Screenshot attached below.

![image](https://cloud.githubusercontent.com/assets/1617100/19625069/8ea6bf00-98cb-11e6-8e09-7ce278f09056.png)

**Comment by liach** [comment]
:trollface:
But there seems to be one: https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/resources/mcmod.info

**Comment by CovertJaguar** [comment]
Yeah, no idea why it didn't make it into the jar, I'll need to check the build.gradle

**Comment by AEnterprise** [comment]
most likely it made it into the jar but forge doesn't recognize it: it still has the modid with capital R while railraft has a lowercase modid

**Comment by CovertJaguar** [comment]
Yep, that was it!

**Comment by CovertJaguar** [comment]
Also...can anyone point me at some documentation for this config button?

**Comment by AEnterprise** [comment]
can't find the documentation online (if there ever was any) but you can take a look at other mods that use it like JEI, you'll need to declare a factory in your mod annotation iirc from when i did it my mods.

there is an example on the new configs though: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/test/java/net/minecraftforge/debug/ConfigTest.java

**Comment by CovertJaguar** [comment]
I think I have it figured out.
