### ISSUE TITLE
[Suggestion] Random cart ideas

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#962]
Random suggestions I came up with while testing the current beta:
1. Trash cart with filter (e.g. automatically delete cobblestone that's produced by the tunnel bore)
2. Larger chest carts (could be done as a compatability module that works with Iron Chests mod)
3. Lighting cart (auto-place torches along corridors)
4. Sponge cart and/or bore attachment--automatically removes liquids. My tunnel bores run into water and get stuck CONSTANTLY!
5. Other-mod cart compatibility (e.g. Botania mana carts can't link up with trains right now) (not sure if this is possible)
6. Vaccuum cart--picks up items in a larger radius than hopper minecarts
7. Some way of running tunnel bores indefinitely. Perhaps a way for an engine to link up to the train, drop off inventory, and then detatch and return to a base?

**Comment by nrllewellyn** [comment]
One more:
8. An upgraded tunnel bore that can make ceilings. (e.g. when tunneling under an ocean, so that the roof doesn't collapse and flood the tunnel)

**Comment by CovertJaguar** [comment]
1. Can't make things too easy, I'd be willing to add a Void Cart, but only if it eats everything, not just Cobblestone. The Tunnel Bore isn't a mining machine after all.
2. Nope, bigger trains over bigger carts
3. I'll probably make the bore do this at some point or something, maybe a cart is a better idea
4. Too magicky
5. So long as they extend EntityMinecart, this should already work. If they don't there isn't much I can do.
6. Can we get some numbers on range and such of Hopper and proposed cart?
7. This already works, attach a locomotive to the back of Bore train, when the Bore stops, the Locomotive will be activated and it will pull the Bore back to the start of the line.
8. This is planned.

**Comment by nrllewellyn** [comment]
1. Makes sense. This is a lot easier to solve, given your answer for 7. :-)
2. Fair enough. One other thought though: Perhaps cargo carts (or something similar) could have a larger inventory locked to a single item? You take the trade-off of a single item to slightly larger storage... just a thought.
3. Either works :-) I like the cart idea only because I can run it back through if it runs out of torches. Might make sense to add it to both, honestly.
4. I would argue that sponges are now a core item Minecraft, so sponge + furnace = vanilla water clearing. But that's one of those lines that's totally your call as author. :-) 
5. Hrm. I'll put something up in the Botania bug tracker then.
6. It wouldn't have to be much. Looks like the existing hopper cart is limited to ~0.5 blocks from either side of rail. Something like 1 or 2 blocks on either side of the rail would allow for rails to be spaced further apart when building things like farms.
7. HOW DID I NOT KNOW THIS??? (Thanks for the info!)
8. Cool!

**Comment by Forecaster** [comment]
7 is not a well documented feature :P

It'll pull the bore back as well though, so you'll probably want to set up a little station at the start of the tunnel that unloads the bore train, voids things you don't want with void chests, transfers the things you want to a different train and then turns the locomotive off so the bore can continue digging the tunnel

**Comment by liach** [comment]
In my opinion, sponge cart is cool.

**Comment by Forecaster** [comment]
Also #649

**Comment by CovertJaguar** [comment]
The problem with liquids is that they will wipe out the rails long before any cart has a chance to suck up the water. And I mean, what if its an ocean? What then?

**Comment by Ristellise** [comment]
"The problem with liquids is that they will wipe out the rails long before any cart has a chance to suck up the water. And I mean, what if its an ocean? What then?"
if we remove the rails and let the minecart drop to the bottom from the sea floor... let it still work.

**Comment by Ristellise** [comment]
also sponge cart should use more sponges and make it more expensive si it will be more useful.

**Comment by nrllewellyn** [comment]
@CovertJaguar  Hrm... That's a good point. I envisioned the sponge being combined with the tunnel bore ceiling building mechanic, so the tunnel would be sealed upon completion. Perhaps it would make sense as another part of the bore? Plus, now that you mention it, I'd be concerned with performance of a sponge cart outside the scope of a tunnel bore (all those water/lighting updates for water being removed and flowing back in would be expensive).

I hate to invoke the ghost of Steve's Carts, but perhaps some type of modular tunnel bore (or a tunnel bore that you can link additional "helper carts" onto) would make sense. (e.g. Tunnel bore + ceiling builder module cart + sponge module cart = under ocean tunnel bore) That way you can add new things as needed and the tunnel bore's GUI doesn't become a mess. (Plus, if those carts only add effects to the bore it reduces the magicy-ness off it--they're just features of the bore.)

**Comment by nrllewellyn** [comment]
Also, further comment on the "vaccuum cart" idea--having it be able to dump into attached chest carts (i.e. how the tunnel bore works) would be really cool.

**Comment by abculatter2** [comment]
As a solution to water washing away rails, what about making it so reinforced rails don't get washed away?

**Comment by CovertJaguar** [comment]
Its tied to the block Material, which is tricky to change. I'd have to provide a custom material, but that would be inconsistent because I don't modify vanilla tracks currently and I'm not sure easy it would be to change an existing block's Material. It's probably possible via reflection but yeah...

**Comment by nrllewellyn** [comment]
Honestly, if you really wanted underwater tracks, I feel like an upgrade for the tunnel bore to build enclosed underwater tunnels (or possibly a mutliblock that drains water out when completed) would better fit the "not magical" requirement. (Otherwise, you'd need to actively repel the water as the train moves through.)

Although I should point out: Anything that's designed to build underwater tunnels should include the option for glass ceilings and walls--it's way too cool to not do. ;-)

**Comment by Generalcamo** [comment]
This is just a catchall for several other issues. See #645 #649
