### ISSUE TITLE
Items Can Be Shift + Clicked into "Filters" Section

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#963]
With the proper setup, items can be transferred into the "Filters" section of a loader, causing them to disappear.

Steps to reproduce:
1. Place a loader
2. Set single gravel in the filter
3. Shift + click several stacks of gravel into the loader

Behavior seen:
Varies depending on how you perform the test, but usually one of the stacks of gravel disappears and the number of gravel in the filter increments.

Note: This may be a compatibility bug with Inventory Tweaks

Relevant versions:
Railcraft_1.10.2-10.0.0-beta-4
InventoryTweaks-1.61-58
forge 1.10.2-12.18.2.2105

**Comment by CovertJaguar** [comment]
Please attempt to reproduce without Inventory Tweaks.

If it an issue with Inventory Tweaks, I'm not sure how fixable it is from my end.

**Comment by CovertJaguar** [comment]
Looks like Inventory Tweaks has something of an API that could be used to fix this. Its a bit annoying though. Not entirely sure how to get into dev environment. Assuming IT is the problem.

**Comment by nrllewellyn** [comment]
Bug is repeatable without inventory tweaks installed.

EDIT: Bug is repeatable with ONLY RailCraft installed.
