### ISSUE TITLE
Electric locomotive not charging up

### ISSUE THREAD

**Issue by PsikoBlock** [Railcraft/Railcraft#964]
Charging an electric locomotive does not work at all. I tried using the Admin and the IC2 Feeder Unit.
![2016-10-24_22 16 40](https://cloud.githubusercontent.com/assets/3758175/19664313/15a9aa1a-9a40-11e6-9340-48a035631212.png)
![2016-10-24_22 16 38](https://cloud.githubusercontent.com/assets/3758175/19664329/2020d45a-9a40-11e6-94a7-48b093a36b6f.png)
(Linux 4.4.6-gentoo, Java 8u102)

**Comment by CovertJaguar** [comment]
First, get a Charge Meter. Second, you need a redstone torch next to the feeder.

**Comment by PsikoBlock** [comment]
Redstone signal was my problem. Thanks!
