### ISSUE TITLE
Sneak-using a crowbar on a lever sets it to invalid rotations, client-side.

### ISSUE THREAD

**Issue by purpleposeidon** [Railcraft/Railcraft#965]
[minor]

**Comment by CovertJaguar** [comment]
I just call the rotateBlock() method, any issues with the resulting rotation would belong to Forge.

**Comment by CovertJaguar** [comment]
There! Now it will rotate to invalid positions on both client and server!

**Comment by liach** [comment]
> Now it will rotate to **invalid** positions on both client and server!

Uh what?!

**Comment by CovertJaguar** [comment]
The Forge code for rotating levers rotates it into invalid positions.
