### ISSUE TITLE
[Suggestion] Large-Scale Coke Ovening

### ISSUE THREAD

**Issue by abculatter2** [Railcraft/Railcraft#968]
Many people like spamming coke ovens for large-scale energy production. While this, in and of itself, isn't too big  an issue, from what I understand such large set-ups tend to cause a decent amount of lag for servers, and it would be nice either way to have a better way for scaling up production of coke ovens. Here are a few ideas I had for this;
1. A steam coke oven, which consumes steam to process 9 coke oven recipes at once, working more or less exactly like the regular steam oven with the exception of taking the same amount of time to process as a normal coke oven takes to do one process.
2. Add coal dust and wood pulp/chips, made by processing their respective items in a rock crusher. These, when sent through a coke oven, produce the dust versions of coal coke or charcoal, and are processed MUCH faster. (4x? 8x? 9x?) They also produce less creosote per item, however. (200mb per wood block and 400mb per coal?)
   As a tangent to this, ideally this would also come with adding the ability to burn charcoal dust and coke dust in furnaces and blast furnaces. There might also be some other uses for all these new items as well?
3. You could also add the ability to 'upgrade' a coke oven by applying a raw firestone to it somehow. (right-click?) This would speed up the oven (2x faster? 4x?) but also cause it to occasionally create fire in the area immediately adjacent to it. If it increases the speed by quite a lot, you could also make it delete an item in its inventory every once in awhile.

**Comment by Vexatos** [comment]
1. How would steam help coking coal? It would mainly just make the process not work at all since coking has to happen with no air and water in the chamber.
2. Actually, coking dusts is not really better than coking lumps of coal. It definitely isn't any faster.

**Comment by abculatter2** [comment]
Why do people keep going straight for the 'realism' argument? This is a GAME, I really feel that suggestions should be judged on gameplay value rather then some arbitrary determination of 'realism'...

**Comment by Vexatos** [comment]
This is a game, yet Railcraft still is a mod which is, for the most part, at least _logical_. It just makes no sense for steam to increase coking speed. Coking itself is dry and air-free heating/burning of coal. If you add steam to it you aren't coking it.

**Comment by abculatter2** [comment]
Why are you assuming that the steam is in the actual burning box? It could just as easily be simply used as a heating element.
Also, the Steam Oven literally does this exact same thing, but it is capable of smelting iron, literally the stuff it's made of, as well as melting stone, and all kinds of other things. With steam. It's even already capable of burning wood into charcoal.  So it still maintains internal consistency.

Steam, in this mod, seems to simply be an abstracted notion of a hot gas/energy medium. Therefore, it can do stuff that real-world steam can't.

**Comment by Vexatos** [comment]
Using steam as a heating element, once again, makes no sense. All it might do would be heating it up faster, but that doesn't really matter, coking just requires the temperature to stay high for a while, the speed at which the coal reaches that temperature is mostly irrelevant; for the steam oven, that heating speed is what allows heating more things at a time.

**Comment by CovertJaguar** [comment]
The farthest I'm probably willing to go is doubling the length of the oven and allowing it to cook 3x the input at once. (internal space scales faster than surface area)

**Comment by abculatter2** [comment]
Fair enough
