### ISSUE TITLE
Detectors don't respond to crowbar properly

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#969]
Detectors change direction when right-clicked with a crowbar, but this doesn't actually change the direction of the redstone output.

Relevant versions:
Railcraft_1.10.2-10.0.0-beta-4
InventoryTweaks-1.61-58
forge 1.10.2-12.18.2.2105

**Comment by CovertJaguar** [comment]
Oh heh, I didn't test that part.
