### ISSUE TITLE
High-speed tracks have higher drag than normal tracks

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#970]
After a lot of testing, I've found that the drag for tracks seems to differ from what I would expect:
- Reinforced tracks are faster than regular tracks, which are faster than HS tracks
- Loaded chest carts have VERY high drag on HS tracks
- Transition tracks seem to have little or no effect on HS tracks (basically the same effect as boosters)

Tested with 9 boosters for each track type.

(This may be working as intended if there's been a change to how H.S. tracks work since the last time I used them.)

Relevant versions:
Railcraft_1.10.2-10.0.0-beta-4
InventoryTweaks-1.61-58
forge 1.10.2-12.18.2.2105

**Comment by CovertJaguar** [comment]
Hmm...I'm not sure what change could have caused that. I'll need to do some testing apparently.

**Comment by CovertJaguar** [comment]
So the drag on loaded chest carts is a vanilla feature, it should apply to all tracks. Drag and speed are two different things. You can have higher speed and higher drag at the same time, drag is just the rate at which your speed decays.

I can confirm that HS tracks aren't kicking trains into HS.

**Comment by CovertJaguar** [comment]
Moving issue to #973
