### ISSUE TITLE
Crafted booster tracks don't power booster tracks made with booster kit

### ISSUE THREAD

**Issue by nrllewellyn** [Railcraft/Railcraft#971]
Booster tracks made via the crafting recipe do not pass redstone power on to tracks made by adding a booster kit to regular tracks.

Relevant versions:
Railcraft_1.10.2-10.0.0-beta-4
InventoryTweaks-1.61-58
forge 1.10.2-12.18.2.2105

**Comment by CovertJaguar** [comment]
Yeah...not going to fix this. That code is already insanely complicated, it doesn't need to be even more complex.

**Comment by nrllewellyn** [comment]
Cool. Just figured I'd point it out :-)
