### ISSUE TITLE
High Speed Tracks

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#973]
- [ ] Test explosions (known to not work when colliding with other carts) - Moved to #1279
- [x] Test drag...might be weird, not verified
- [x] Investigate ticking carts twice instead of boosting speed

**Comment by liach** [comment]
@CovertJaguar For carts like anchor, will ticking more than once cause unintended side effects?

**Comment by CovertJaguar** [comment]
Good question. The anchor and locomotives will probably use fuel twice as fast.

**Comment by liach** [comment]
Do we make some sort of pseudo ticking?

**Comment by liach** [comment]
Cart colliding does not make explosions yes. Carts don't explode when going up a slope, is that intended?

**Comment by CovertJaguar** [comment]
Yes carts colliding when moving opposite direction explodes.

Why would they explode on a slope? They have never exploded on a slope. Yes its intentional.

**Comment by liach** [comment]
So now we just need to add explosion for cart collision. Drag will be tested later, I guess.

**Comment by CovertJaguar** [comment]
"Add" is probably the wrong term. There is code in MinecartHooks for it already. The question is why its not working.

**Comment by liach** [comment]
Hmm explosion sometimes works. We should change the check to checking absolute velocity between two carts.

**Comment by CovertJaguar** [comment]
That sounds suspiciously like the old method I used to check abrupt changes in velocity, like when hitting a wall. Unfortunately, the motion vector is not so well behaved and likes to change randomly at times. Which resulted in random explosions.

**Comment by liach** [comment]
As I've seen, drag is handled in a method now. We have no access to drag information, unfortunately.

**Comment by liach** [comment]
I doubt the explosion part is the same as #1279 - faults of the vanilla system, because when two carts go on opposite directions, they collide normally.
For the drag part, it looks fine. We can override the methods as we need.
