### ISSUE TITLE
Carts disconnecting from Loco

### ISSUE THREAD

**Issue by Suterusu1337** [Railcraft/Railcraft#975]
Unsure if this is a modded cart issue or not, but this is the second time in several hours the carts have disconnected.  The train was Loco : Tank Cart : Diamond : Iron.  It disconnected between tank and Diamond cart.

http://i.imgur.com/4PYl9Le.jpg

Edit:
RC version 9.12.2.0
Forge: 10.13.4.1566

**Comment by CovertJaguar** [comment]
Duplicate of #882

**Comment by Suterusu1337** [comment]
#882 references 1.10.2 and game restarts, this is not in the same version nor dealing with game restarts, is it still the same issue?

Edit, I am on 1.7.10

**Comment by liach** [comment]
I think this bug actually presents on both versions, but is more observable on Minecraft 1.10.2.

**Comment by CovertJaguar** [comment]
Oh, I didn't notice that...hmm...
