### ISSUE TITLE
Carts not and invetory rendering

### ISSUE THREAD

**Issue by SuperUserDone** [Railcraft/Railcraft#977]
When I place carts on tracks they do not render and they show up white. Also in the creative tab the textures for certain items show up as either grey or invisible. I do use Optifine and if there is a setting that I missed please let me know.

Edit:Is there a way to disable Halloween event?

**Comment by CovertJaguar** [comment]
Hey, thanks for the report.
1. It's the Halloween Event.
2. Don't use Optifine or go bug them to fix their custom texture loader support (again).
