### ISSUE TITLE
Disabling subblocks doesn't work.

### ISSUE THREAD

**Issue by GirafiStudios** [Railcraft/Railcraft#980]
Disabling subblocks in blocks.cfg does apparently not quite work. 
For example trying to disable a specific ore, will not actually remove it.

Railcraft version: 10.0.0-beta-4

**Comment by CovertJaguar** [comment]
If you want to remove something that already exists in the world, you need to disable the entire block. Disabling the sub-blocks will only remove their recipe entries and world generators, preventing you from accessing them in survival, but leaving any existing ones in the world.
