### ISSUE TITLE
Add Recipe to upgrade High Speed Track to HS Electric Track

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#982]
See title, and investigate other possible upgrade/recycling paths.

**Comment by Ristellise** [comment]
idea:
- use the kit system for all the 4 variants.
- when you want to replace a track, use the kit to replace the track. however there is a disadvantage that you will not get back the original track.
- Edit: the kits are easy to craft. same recipe as the other kits but with their variants.
- edit2: track replacer cart are allowed to use kits to replace the tracks.

**Comment by CovertJaguar** [comment]
The code is not easily co-opted for that, it would need to be a new item. Neptunepink suggested making Rails upgrade items, the problem is the cost disparity.

**Comment by abculatter2** [comment]
You could always up the amount of rails you get from the rails recipe.

**Comment by CyanideCarrot** [comment]
You could try something like this and similar for normal -> electric and maybe 
reinforced -> reinforced electric
![screen shot 2016-12-10 at 9 23 51 am](https://cloud.githubusercontent.com/assets/14823057/21072435/6ee7da5e-beba-11e6-9ff1-12309db72dc3.png)

**Comment by liach** [comment]
@CovertJaguar I suggest making rails consumable like tools, each is good for 16 blocks of track. It should be able to upgrade both iron and hs track types.

**Comment by CovertJaguar** [comment]
I guess that works, not really compatible with the track relayer though.
