### ISSUE TITLE
[10.0.0] Config files are empty

### ISSUE THREAD

**Issue by csdivad** [Railcraft/Railcraft#984]
With 10.0.0 release version of Railcraft the config files are empty after creation (with the exception of modules.cfg).
This wasn't a problem with 10.0.0-beta-4.

[FML log](https://gist.github.com/csdivad/c3efdf0e17738746aaef5a07026654c2)

**Comment by GirafiStudios** [comment]
Can confirm. Although it still reads the configs previously generated correctly.

**Comment by liach** [comment]
related to 8b1a453929ef0b18dcae3a920be95548c87c5fae?

**Comment by CovertJaguar** [comment]
Oh dear...

**Comment by CovertJaguar** [comment]
Oh...I removed the save() called to their own function then forgot to call it...
