### ISSUE TITLE
[1.7.10/1.10.2] Signal Block Relay Box Tuning

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#986]
Signal Block Relay Box could not be right-clicked with a Signal Tuner. Now we could no longer pair Signal Block Relay Boxes with Distant Signals!

**Comment by CovertJaguar** [comment]
You need a Controller Box next to it now I believe. This was done to reign in the utility of the Relay Box a bit as people were preferring it in all cases.
