### ISSUE TITLE
Under Cutter Cart Crashing Server

### ISSUE THREAD

**Issue by taluseve** [Railcraft/Railcraft#988]
[crash-2016-11-01_18.35.30-server.txt](https://github.com/CovertJaguar/Railcraft/files/565243/crash-2016-11-01_18.35.30-server.txt)
When trying to add materials to the under cutter cart . my server crashes

**Comment by CovertJaguar** [comment]
Try using a standard Forge install, instead of a custom modified jar?

**Comment by Ristellise** [comment]
how do you know it is a modified jar?

**Comment by taluseve** [comment]
Only thing custom about forge is the name. I use mc mcprohosting for my
server and that is the only way to get java 8 to run with them

**Comment by liach** [comment]
@CovertJaguar This is a Railcraft bug. It calls a method that is only available on the client. 

Btw I suggest the usage of [Minecraft Dev Idea Plugin](https://github.com/minecraft-dev) to prevent future issues on Side handling.

**Comment by CovertJaguar** [comment]
Oh? I hadn't seen that before. interesting.
