### ISSUE TITLE
Launch track on high speed rail crashes server

### ISSUE THREAD

**Issue by snurre0** [Railcraft/Railcraft#995]
Hi,
Thank you for making this mod for 1.10, love it! :)

So, I was playing around with railcraft in creative, and the server suddenly crashed.
Managed to reproduce it by going full speed in a cart at high speed tracks, and then run into a launch track, like this:
![2016-11-06_08 06 38](https://cloud.githubusercontent.com/assets/12727805/20035970/7f8c975e-a3f9-11e6-8099-546041afe966.png)
![2016-11-06_08 06 53](https://cloud.githubusercontent.com/assets/12727805/20035972/8da9e8f0-a3f9-11e6-94fb-c4f721342bba.png)

When passing over the launch track, the server crashes.

I don't know what logs you want, but I've attached all the server logs, and a copy-paste from server controle.

[console-log.txt](https://github.com/CovertJaguar/Railcraft/files/573691/console-log.txt)
[crash-2016-11-06_08.06.56-server.txt](https://github.com/CovertJaguar/Railcraft/files/573692/crash-2016-11-06_08.06.56-server.txt)
[fml-server-latest.log.txt](https://github.com/CovertJaguar/Railcraft/files/573693/fml-server-latest.log.txt)
[latest.log.txt](https://github.com/CovertJaguar/Railcraft/files/573694/latest.log.txt)

Edit: Forgot the version numbers of everything:
MC 1.10.2
Forge: 12.18.2.2114
Railcraft: 10.0.0

No other mods.

(Btw, all my carts are transparent, thats the ghost-thing right? Does it end at some point?)

Best regards,
Morten

**Comment by Forecaster** [comment]
#956 Yes.
