### ISSUE TITLE
Feature Request: Safety pressure "pop off" valve

### ISSUE THREAD

**Issue by dj3520** [Railcraft/Railcraft#997]
Early on in my experience with steam boilers I found out making sure that steam always has a place to go is pretty important if you enjoy the surrounding area being kept intact. But with my usage varying due to simply generating power when I have storage available, it was common that my boiler would heat completely up and then suddenly I don't need any steam anymore. That caused me to start making these regularly:
![image](https://cloud.githubusercontent.com/assets/8284194/20037355/0ebc1840-a3ec-11e6-87ac-12c762751745.png)

It's a makeshift safety valve. If the boiler were to fill completely with steam, the steam trap on top would start venting, avoiding dangerous pressure and explosion. I was wondering if you'd consider it worth it to make a smaller, single block "safety valve" that would act the same, venting steam only if a boiler is full. As for a recipe, I was thinking a manual steam trap on top, redstone in the middle, and iron on bottom in a vertical stack, like shown.
![image](https://cloud.githubusercontent.com/assets/8284194/20037461/5c9e41a4-a3ed-11e6-930b-869c814568b8.png)

The iron would be forced up by pressure into the redstone, triggering the trap. Though really it's final form is up to you. I'm nearly providing my thoughts.

**Comment by Forecaster** [comment]
Boilers don't explode when they fill up with stream. They only explode if the water tank is empty and you then put water in while it is above 300 degrees.

**Comment by abculatter2** [comment]
Yeah... The only thing you'll loose when the tank overflows is energy.

**Comment by dj3520** [comment]
Huh, could of sworn they did. Well consider this irrelevant then.
