### ISSUE TITLE
[Suggestion] Shipping Pallets

### ISSUE THREAD

**Issue by abculatter2** [Railcraft/Railcraft#999]
Shipping pallets would be crafted using wooden ties, and could be used to store certain items more efficiently. You can use a crafting table to pack the items into and take them out of a pallet, or for use in trains you can use an advanced item loader. I figured there could be a mode/checkbox added to the advanced item loader/unloader that makes it so that the loader will only put items into a cart if it has pallets in a special inventory slot, or if it is an unloader it will unpack any pallets and shove them out as normal items.

More specifically, I figured a decent way of handling this would be to have palletized cobblestone to take, let's say, 4 cobblestone, and unpacking it would give back everything used to make it. Palletized items would stack to the same amount their items do. (or just to 64)
Also, while I don't particularly care what the shipping pallet recipe is, I figured that it would be a good thing to have them be cheap enough that it's not unreasonable to simply throw them away after being used, as this would mirror the real-life situation for shipping pallets. I figured 3 pallets per tie would be a good number.

**Comment by Forecaster** [comment]
Do you mean something like the Artifice boxes? (http://i.imgur.com/XCsgVLP.png)

**Comment by abculatter2** [comment]
Yes, though I was thinking something a bit simpler. More similar to Forestry's crates.

**Comment by Forecaster** [comment]
How are forestry crates simpler? IIRC they require a machine to make and package things, and only work on specific items.

**Comment by abculatter2** [comment]
With the exception of requiring a machine to pack/unpack, I would consider that simpler.
Also, I personally kinda like the idea of it only being usable on specific things, rather then being able to store absolutely everything. It makes it less usable outside of more efficient train automation, which is my primary intention with this suggestion. It's up to you how you want to implement it, though.
Another thing that could be done that I wouldn't mind is to make it so that it will only accept items with the exact same data, so that way it's still useful for store lots of one type of items, but can't be used as a backpack-type item.
